@extends('layouts.app')
@section('title','Access Control | UNIFCO Platform')
@section('heading','Access Control')
@section('content')
<style>.ac-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px;margin-bottom:12px}.ac-hero h1{margin:0 0 5px;font-size:22px}.ac-hero p{margin:0;color:#dce5f2;font-size:10px}.ac-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ac-panel{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:15px}.ac-panel.wide{grid-column:1/-1}.ac-panel h3{margin:0 0 10px;font-size:13px;color:#132137}.ac-list{display:grid;gap:6px;max-height:330px;overflow:auto}.ac-row{display:flex;justify-content:space-between;gap:9px;padding:9px;background:#f7f9fc;border-radius:8px;font-size:10px}.ac-row small{display:block;color:#7a889b;margin-top:3px}.ac-form{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.ac-form label{font-size:9px;color:#66758a}.ac-form .wide{grid-column:1/-1}@media(max-width:800px){.ac-grid{grid-template-columns:1fr}.ac-panel.wide{grid-column:auto}.ac-form{grid-template-columns:1fr}.ac-form .wide{grid-column:auto}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="ac-hero"><h1>Access Control</h1><p>Master Roles → Permissions → Scopes → Exceptional overrides. Approval authority remains separate from system authority.</p></section>
<div class="ac-grid"><section class="ac-panel"><h3>Master Roles</h3><div class="ac-list">@foreach($roles as $role)<div class="ac-row"><span><b>{{ $role->code }}</b><small>{{ $role->name_ar ?: $role->name_en }} · {{ $role->users_count }} users · {{ $role->is_active?'ACTIVE':'INACTIVE' }}</small></span><span style="display:flex;gap:5px;align-items:center"><span class="pill">{{ $role->grants_business_authority?'BUSINESS':'SYSTEM' }}</span>@if(!$role->is_system_role)<form method="POST" action="{{ route('admin.access-control.roles.status',$role) }}">@csrf<input type="hidden" name="is_active" value="{{ $role->is_active?0:1 }}"><input type="hidden" name="reason" value="Administrator changed role availability"><button class="btn secondary">{{ $role->is_active?'Deactivate':'Activate' }}</button></form>@endif</span></div>@endforeach</div><form class="ac-form" method="POST" action="{{ route('admin.access-control.roles.store') }}">@csrf<label>Role Code<input name="code" required></label><label>Name EN<input name="name_en" required></label><label>Name AR<input name="name_ar"></label><label class="wide">Description<input name="description"></label><label><input type="checkbox" name="grants_business_authority" value="1"> Business authority role</label><label><input type="checkbox" name="requires_approval" value="1"> Sensitive changes</label><button class="btn">Create Role</button></form></section>
<section class="ac-panel"><h3>Scopes</h3><div class="ac-list">@foreach($scopes as $scope)<div class="ac-row"><span><b>{{ $scope->scope_type }}</b><small>{{ $scope->name }} · {{ $scope->scope_id ?? 'All resources' }}</small></span><span style="display:flex;gap:5px;align-items:center"><span class="pill">{{ $scope->is_active?'ACTIVE':'INACTIVE' }}</span><form method="POST" action="{{ route('admin.access-control.scopes.status',$scope) }}">@csrf<input type="hidden" name="is_active" value="{{ $scope->is_active?0:1 }}"><input type="hidden" name="reason" value="Administrator changed scope availability"><button class="btn secondary">{{ $scope->is_active?'Deactivate':'Activate' }}</button></form></span></div>@endforeach</div><form class="ac-form" method="POST" action="{{ route('admin.access-control.scopes.store') }}">@csrf<label>Type<select name="scope_type">@foreach(\App\Models\AccessScope::TYPES as $type)<option>{{ $type }}</option>@endforeach</select></label><label>Resource ID<input type="number" name="scope_id"></label><label>Name<input name="name" required></label><label>Reason<input name="reason" required></label><button class="btn">Create Scope</button></form></section>
<section class="ac-panel"><h3>Approval Authorities</h3><div class="ac-list">@forelse($authorities as $authority)<div class="ac-row"><span><b>{{ $authority->approval_type }}</b><small>Role #{{ $authority->role_id }} · Level {{ $authority->level }} · Scope #{{ $authority->access_scope_id ?: 'GLOBAL' }} · {{ $authority->is_active?'ACTIVE':'INACTIVE' }}</small></span><span style="display:flex;gap:5px;align-items:center"><span class="pill">{{ $authority->amount_limit ?: 'No limit' }}</span><form method="POST" action="{{ route('admin.access-control.authorities.status',$authority) }}">@csrf<input type="hidden" name="is_active" value="{{ $authority->is_active?0:1 }}"><input type="hidden" name="reason" value="Administrator changed authority availability"><button class="btn secondary">{{ $authority->is_active?'Deactivate':'Activate' }}</button></form></span></div>@empty<div class="muted">No authorities configured.</div>@endforelse</div><form class="ac-form" method="POST" action="{{ route('admin.access-control.authorities.store') }}">@csrf<label>Approval Type<input name="approval_type" required></label><label>Role<select name="role_id">@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->code }}</option>@endforeach</select></label><label>Level<input type="number" min="1" name="level" value="1"></label><label>Scope<select name="access_scope_id"><option value="">Global</option>@foreach($scopes as $scope)<option value="{{ $scope->id }}">{{ $scope->scope_type }} · {{ $scope->name }}</option>@endforeach</select></label><label>Amount Limit<input type="number" min="0" step=".01" name="amount_limit"></label><label>Reason<input name="reason" required></label><button class="btn">Configure Authority</button></form></section>
</div>
@endsection
