@extends('layouts.app')
@section('title',($asset->exists?'Edit':'Register').' Asset · UNIFCO')
@section('heading',$asset->exists?'Edit Asset Master':'Register New Asset')
@section('content')
<style>.asset-form{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.asset-form label{font-size:11px;font-weight:700}.asset-form .wide{grid-column:1/-1}.section-title{grid-column:1/-1;color:#071f4d;font-size:13px;font-weight:900;padding-top:8px;border-top:1px solid #edf1f5;margin-top:5px}.template-note{grid-column:1/-1;background:#f0f5fb;border:1px solid #dce7f3;border-radius:9px;padding:11px;font-size:10px;color:#455b76}.template-note strong{color:#071f4d}.required-specs{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.required-specs span{background:#fff;border:1px solid #dce5ef;padding:4px 6px;border-radius:6px;font-size:9px}@media(max-width:900px){.asset-form{grid-template-columns:1fr 1fr}}@media(max-width:600px){.asset-form{grid-template-columns:1fr}}</style>
<div class="page-head"><div><h2 style="margin:0">{{ $asset->exists?'Asset Master Data':'Register Asset' }}</h2><p class="muted">The asset belongs to the customer and site. Contract coverage is assigned separately in Asset 360.</p></div><a class="btn secondary" href="{{ route('eam.assets.index') }}">Back to Asset Register</a></div>
@if($errors->any())<div class="error" style="margin-top:12px">{{ $errors->first() }}</div>@endif
<div class="card" style="margin-top:14px"><form method="POST" action="{{ $asset->exists?route('eam.assets.update',$asset):route('eam.assets.store') }}">@csrf @if($asset->exists)@method('PUT')@endif<div class="asset-form">
<div class="section-title">Ownership & Hierarchy</div>
<label>Customer<select name="customer_id" id="customer-select" required><option value="">Select customer</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(old('customer_id',$asset->customer_id)==$c->id)>{{ $c->customer_code }} · {{ $c->name }}</option>@endforeach</select></label>
<label>Customer Site<select name="customer_site_id" id="site-select"><option value="">No site selected</option>@foreach($sites as $s)<option value="{{ $s->id }}" data-customer="{{ $s->customer_id }}" @selected(old('customer_site_id',$asset->customer_site_id)==$s->id)>{{ $s->site_code }} · {{ $s->name }}</option>@endforeach</select></label>
<label>Parent Asset<select name="parent_asset_id" id="parent-select"><option value="">Top-level asset</option>@foreach($parents as $p)<option value="{{ $p->id }}" data-customer="{{ $p->customer_id }}" @selected(old('parent_asset_id',$asset->parent_asset_id)==$p->id)>{{ $p->asset_code }} · {{ $p->name }}</option>@endforeach</select></label>
<label>Asset Code<input name="asset_code" value="{{ old('asset_code',$asset->asset_code) }}" required placeholder="WIT-RYD-ELE-GEN-0001"></label>
<div class="section-title">UNIFCO Asset Category Template</div>
<label>Asset Template<select name="asset_category_template_id" id="template-select"><option value="">Custom / Other Asset</option>@foreach($templates as $t)<option value="{{ $t['id'] }}" @selected(old('asset_category_template_id',$asset->asset_category_template_id)==$t['id'])>{{ $t['system_group'] }} · {{ $t['name'] }}</option>@endforeach</select></label>
<label>Asset Name<input name="name" value="{{ old('name',$asset->name) }}" required></label>
<label>Category<input id="category-input" name="asset_category" value="{{ old('asset_category',$asset->asset_category) }}" placeholder="Auto from template or custom"></label>
<label>Subcategory<input name="asset_subcategory" value="{{ old('asset_subcategory',$asset->asset_subcategory) }}"></label>
<label>Criticality<select name="criticality" id="criticality-select">@foreach(['CRITICAL','HIGH','MEDIUM','LOW'] as $s)<option @selected(old('criticality',$asset->criticality ?: 'MEDIUM')===$s)>{{ $s }}</option>@endforeach</select></label>
<div class="template-note" id="template-note"><strong>Select a UNIFCO template</strong> to apply the recommended criticality, useful life, and required technical specification set. Specifications are completed in Asset 360 after registration.<div class="required-specs" id="required-specs"></div></div>
<div class="section-title">Technical Identity</div>
<label>Manufacturer<input name="manufacturer" value="{{ old('manufacturer',$asset->manufacturer) }}"></label><label>Model<input name="model_no" value="{{ old('model_no',$asset->model_no) }}"></label><label>Serial Number<input name="serial_no" value="{{ old('serial_no',$asset->serial_no) }}"></label><label>Supplier<input name="supplier_name" value="{{ old('supplier_name',$asset->supplier_name) }}"></label><label>Installer<input name="installer_name" value="{{ old('installer_name',$asset->installer_name) }}"></label>
<div class="section-title">Lifecycle & Operating Condition</div>
<label>Lifecycle Status<select name="lifecycle_status">@foreach(['DRAFT','INSTALLED','COMMISSIONED','ACTIVE','INACTIVE','RETIRED','DISPOSED'] as $s)<option @selected(old('lifecycle_status',$asset->lifecycle_status ?: 'ACTIVE')===$s)>{{ $s }}</option>@endforeach</select></label>
<label>Operational Status<select name="operational_status">@foreach(['RUNNING','STANDBY','STOPPED','UNDER_MAINTENANCE','BREAKDOWN','ISOLATED','OUT_OF_SERVICE'] as $s)<option @selected(old('operational_status',$asset->operational_status ?: 'RUNNING')===$s)>{{ $s }}</option>@endforeach</select></label>
<label>Manufacture Date<input type="date" name="manufacture_date" value="{{ old('manufacture_date',optional($asset->manufacture_date)->format('Y-m-d')) }}"></label><label>Installation Date<input type="date" name="installation_date" value="{{ old('installation_date',optional($asset->installation_date)->format('Y-m-d')) }}"></label><label>Commission Date<input type="date" name="commission_date" value="{{ old('commission_date',optional($asset->commission_date)->format('Y-m-d')) }}"></label><label>Warranty Expiry<input type="date" name="warranty_expiry" value="{{ old('warranty_expiry',optional($asset->warranty_expiry)->format('Y-m-d')) }}"></label><label>Useful Life (months)<input id="useful-life-input" type="number" min="1" name="useful_life_months" value="{{ old('useful_life_months',$asset->useful_life_months) }}"></label><label>Expected Replacement<input type="date" name="expected_replacement_date" value="{{ old('expected_replacement_date',optional($asset->expected_replacement_date)->format('Y-m-d')) }}"></label>
<div class="section-title">Financial Lifecycle</div>
<label>Acquisition Cost<input type="number" step="0.01" min="0" name="acquisition_cost" value="{{ old('acquisition_cost',$asset->acquisition_cost) }}"></label><label>Replacement Value<input type="number" step="0.01" min="0" name="replacement_value" value="{{ old('replacement_value',$asset->replacement_value) }}"></label>
</div><button class="btn" style="margin-top:14px">{{ $asset->exists?'Save Asset Master':'Register Asset & Start Verification' }}</button></form></div>
<script>
(function(){
 const templates=@json($templates);
 const byId=Object.fromEntries(templates.map(t=>[String(t.id),t]));
 const template=document.getElementById('template-select'),category=document.getElementById('category-input'),criticality=document.getElementById('criticality-select'),life=document.getElementById('useful-life-input'),specs=document.getElementById('required-specs');
 function applyTemplate(force){const t=byId[template.value];specs.innerHTML='';if(!t)return;if(force||!category.value)category.value=t.name;if(force||!criticality.value)criticality.value=t.criticality;if((force||!life.value)&&t.useful_life_months)life.value=t.useful_life_months;t.fields.filter(f=>f.required).forEach(f=>{const s=document.createElement('span');s.textContent=f.label+(f.unit?' ('+f.unit+')':'');specs.appendChild(s)});}
 template.addEventListener('change',()=>applyTemplate(true));applyTemplate(false);
 const customer=document.getElementById('customer-select');
 function filterOwned(select){Array.from(select.options).forEach((o,i)=>{if(i===0)return;const match=!customer.value||o.dataset.customer===customer.value;o.hidden=!match;if(!match&&o.selected)select.value='';});}
 customer.addEventListener('change',()=>{filterOwned(document.getElementById('site-select'));filterOwned(document.getElementById('parent-select'));});filterOwned(document.getElementById('site-select'));filterOwned(document.getElementById('parent-select'));
})();
</script>
@endsection
