@extends('layouts.app')
@section('title','Asset Master · UNIFCO')
@section('heading','Enterprise Asset Management')
@section('content')
<style>
.asset-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:22px;margin-bottom:16px}.asset-hero h2{margin:0 0 5px}.asset-hero p{margin:0;color:#c9d8e9;font-size:12px}.asset-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.asset-filters{display:flex;gap:9px;flex-wrap:wrap;align-items:end;margin-bottom:14px}.asset-filters label{font-size:10px;min-width:180px}.asset-filters select{width:100%}.crit{font-size:9px;padding:4px 7px;border-radius:999px;background:#eef3fa}.crit.CRITICAL{background:#fde8ec;color:#b30f2b}.crit.HIGH{background:#fff2df;color:#9b5b00}.op{font-size:9px;padding:4px 7px;border-radius:6px;background:#eaf7ef;color:#176a43}.op.BREAKDOWN,.op.OUT_OF_SERVICE{background:#fdebed;color:#b42239}.op.UNDER_MAINTENANCE{background:#fff4df;color:#9b5b00}.row-actions{display:flex;gap:6px;flex-wrap:wrap}
</style>
<div class="asset-hero"><h2>Asset Master & Lifecycle Register</h2><p>Customer → Site → Asset → Contract Coverage → Maintenance → Work Orders → Spare Parts → Cost → Lifecycle</p><div class="asset-actions"><a class="btn" href="{{ route('eam.assets.create') }}">+ Register New Asset</a></div></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="card"><form class="asset-filters" method="GET"><label>Customer<select name="customer_id"><option value="">All customers</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(request('customer_id')==$c->id)>{{ $c->customer_code }} · {{ $c->name }}</option>@endforeach</select></label><label>Operational Status<select name="operational_status"><option value="">All statuses</option>@foreach(['RUNNING','STANDBY','STOPPED','UNDER_MAINTENANCE','BREAKDOWN','ISOLATED','OUT_OF_SERVICE'] as $s)<option @selected(request('operational_status')===$s)>{{ $s }}</option>@endforeach</select></label><button class="btn secondary">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Asset</th><th>Customer / Site</th><th>Category</th><th>Manufacturer</th><th>Criticality</th><th>Lifecycle</th><th>Operational</th><th>Meter</th><th>Verification</th><th></th></tr></thead><tbody>@forelse($assets as $a)<tr><td><strong>{{ $a->asset_code }}</strong><br><small>{{ $a->name }}</small></td><td>{{ $a->customer?->name ?: '—' }}<br><small>{{ $a->site?->name ?: $a->location_code ?: '—' }}</small></td><td>{{ $a->asset_category ?: '—' }}<br><small>{{ $a->asset_subcategory ?: '' }}</small></td><td>{{ $a->manufacturer ?: '—' }}<br><small>{{ $a->model_no ?: '' }}</small></td><td><span class="crit {{ $a->criticality }}">{{ $a->criticality ?: 'MEDIUM' }}</span></td><td>{{ $a->lifecycle_status ?: 'ACTIVE' }}</td><td><span class="op {{ $a->operational_status }}">{{ $a->operational_status ?: 'RUNNING' }}</span></td><td>{{ number_format((float)$a->meter_value,2) }}</td><td>{{ $a->verification_status ?: 'DRAFT' }}</td><td><div class="row-actions"><a class="btn secondary" href="{{ route('eam.assets.show',$a) }}">Asset 360</a><a class="btn secondary" href="{{ route('eam.assets.meters.show',$a) }}">Meters</a><a class="btn secondary" href="{{ route('eam.assets.spare-parts.show',$a) }}">Spare Parts</a></div></td></tr>@empty<tr><td colspan="10">No assets found.</td></tr>@endforelse</tbody></table></div></div>{{ $assets->links() }}
@endsection
