@extends('layouts.app')
@section('title',$asset->asset_code.' · Meter Readings · UNIFCO')
@section('heading','Asset Meter Readings')
@section('content')
<style>.meter-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:22px;margin-bottom:14px}.meter-hero h2{margin:0 0 4px}.meter-hero p{margin:0;color:#cbd9e9;font-size:11px}.meter-grid{display:grid;grid-template-columns:360px 1fr;gap:14px}.current{font-size:34px;font-weight:900;color:#071f4d}.plan{padding:10px;border:1px solid #e2e8ef;border-radius:9px;margin-top:8px}.plan strong{display:block;font-size:11px}.plan small{color:#708095}.reading-form{display:grid;gap:9px}.reading-form label{font-size:10px;font-weight:700}.reading-form input,.reading-form textarea{width:100%}@media(max-width:800px){.meter-grid{grid-template-columns:1fr}}</style>
<div class="meter-hero"><h2>{{ $asset->asset_code }} · {{ $asset->name }}</h2><p>{{ $asset->customer?->name }} · {{ $asset->site?->name ?: 'No site assigned' }} · Meter-based maintenance tracking</p></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="meter-grid"><section class="card"><h3>Current Meter</h3><div class="current">{{ number_format((float)$asset->meter_value,2) }}</div><p class="muted">Current accumulated reading</p><form class="reading-form" method="POST" action="{{ route('eam.assets.meter-readings.store',$asset) }}">@csrf<label>New Reading<input type="number" step="any" min="0" name="reading" value="{{ old('reading') }}" required></label><label>Reading Date<input type="date" name="reading_date" value="{{ old('reading_date',now()->format('Y-m-d')) }}" required></label><label>Notes<textarea name="notes">{{ old('notes') }}</textarea></label><button class="btn">Record Reading</button></form><div style="margin-top:15px"><a class="btn secondary" href="{{ route('eam.assets.show',$asset) }}">Back to Asset 360</a></div></section><section><div class="card"><h3>Meter-Based Maintenance Plans</h3>@forelse($meterPlans as $plan)<div class="plan"><strong>{{ $plan->plan_no }} · {{ $plan->name }}</strong><small>Next trigger: {{ number_format((float)$plan->next_due_meter,2) }} · Interval: {{ $plan->frequency_value }} · {{ $plan->priority }}</small></div>@empty<p class="muted">No active meter-based maintenance plans for this asset.</p>@endforelse</div><div class="card" style="margin-top:14px"><h3>Reading History</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Reading</th><th>Recorded By</th><th>Notes</th></tr></thead><tbody>@forelse($readings as $r)<tr><td>{{ $r->reading_date }}</td><td><strong>{{ number_format((float)$r->reading,2) }}</strong></td><td>{{ $r->recorded_by_name ?: 'System' }}</td><td>{{ $r->notes ?: '—' }}</td></tr>@empty<tr><td colspan="4">No meter readings recorded yet.</td></tr>@endforelse</tbody></table></div></div></section></div>
@endsection
