@extends('layouts.app')
@section('title',$asset->asset_code.' · Reliability · UNIFCO')
@section('heading','Asset Reliability')
@section('content')
@php($fmt=function($m){if($m===null)return '—';if($m>=1440)return round($m/1440,1).' d';if($m>=60)return round($m/60,1).' h';return round($m,1).' min';})
<style>.rel-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:22px}.rel-hero h2{margin:0 0 4px}.rel-hero p{margin:0;color:#cbd9ea;font-size:11px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:11px;padding:13px}.kpi b{display:block;font-size:21px;color:#071f4d}.kpi span{font-size:9px;color:#748297}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.box{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:17px}.sev{font-size:9px;font-weight:800}.sev.CRITICAL,.sev.HIGH{color:#b31c36}.cost{font-weight:800;color:#071f4d}@media(max-width:900px){.kpis{grid-template-columns:repeat(2,1fr)}.grid2{grid-template-columns:1fr}}@media(max-width:550px){.kpis{grid-template-columns:1fr}}</style>
<div class="rel-hero"><h2>{{ $asset->asset_code }} · {{ $asset->name }}</h2><p>{{ $asset->customer?->name }} · {{ $asset->site?->name ?: 'No site' }} · Reliability, failures, downtime and lifecycle maintenance cost</p><div style="margin-top:10px"><a class="btn secondary" href="{{ route('eam.assets.show',$asset) }}">Asset 360</a> <a class="btn secondary" href="{{ route('maintenance.work-orders.index') }}">Work Orders</a></div></div>
<section class="kpis"><div class="kpi"><b>{{ $fmt($metrics['mtbf']) }}</b><span>MTBF</span></div><div class="kpi"><b>{{ $fmt($metrics['mttr']) }}</b><span>MTTR</span></div><div class="kpi"><b>{{ $metrics['failureCount'] }}</b><span>Failure Events</span></div><div class="kpi"><b>{{ $fmt($metrics['totalDowntime']) }}</b><span>Total Downtime</span></div><div class="kpi"><b>{{ $metrics['pmCompliance'] }}%</b><span>PM Completion</span></div><div class="kpi"><b>{{ number_format($metrics['totalMaintenanceCost'],2) }}</b><span>Total Maintenance Cost SAR</span></div><div class="kpi"><b>{{ number_format($metrics['preventiveCost'],2) }}</b><span>Preventive Cost SAR</span></div><div class="kpi"><b>{{ number_format($metrics['correctiveCost'],2) }}</b><span>Corrective Cost SAR</span></div></section>
<div class="grid2"><section class="box"><h3>Failure History</h3><div class="table-wrap"><table><thead><tr><th>Failure</th><th>Severity</th><th>Failed</th><th>Restored</th><th>Downtime</th><th>Root Cause</th></tr></thead><tbody>@forelse($failures as $f)<tr><td><strong>{{ $f->failure_code ?: '—' }}</strong><br><small>{{ $f->failure_mode }}</small></td><td><span class="sev {{ $f->severity }}">{{ $f->severity }}</span></td><td>{{ $f->failed_at }}</td><td>{{ $f->restored_at ?: 'Open' }}</td><td>{{ $fmt($f->downtime_minutes) }}</td><td>{{ $f->root_cause ?: '—' }}</td></tr>@empty<tr><td colspan="6">No failures recorded.</td></tr>@endforelse</tbody></table></div></section><section class="box"><h3>Maintenance Cost History</h3><div class="table-wrap"><table><thead><tr><th>WO</th><th>Type</th><th>Status</th><th>Labor</th><th>Materials</th><th>Total</th></tr></thead><tbody>@forelse($workOrders as $wo)<tr><td><a href="{{ route('maintenance.work-orders.show',$wo->id) }}">{{ $wo->work_order_no }}</a></td><td>{{ $wo->maintenance_type }}</td><td>{{ $wo->status }}</td><td>{{ number_format((float)$wo->labor_cost,2) }}</td><td>{{ number_format((float)$wo->material_cost,2) }}</td><td class="cost">{{ number_format((float)$wo->total_cost,2) }}</td></tr>@empty<tr><td colspan="6">No maintenance history.</td></tr>@endforelse</tbody></table></div></section></div>
@endsection
