<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PublicCurrentSparePartsQuoteFinalPresentation
{
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);
        if (! $request->routeIs('public.request-service') || ! method_exists($response, 'getContent') || ! method_exists($response, 'setContent')) return $response;
        $html = (string) $response->getContent();
        if (! str_contains($html, "workspace.id='uf-request-workspace'") || str_contains($html, 'id="unifco-new-spare-parts-script-v1"')) return $response;

        $style = <<<'HTML'
<style id="unifco-new-spare-parts-style-v1">
body.uf-new-spare-parts-mode .uf-details-pane{border-color:#cfdff0!important;padding:16px!important}body.uf-new-spare-parts-mode .uf-details-pane .uf-pane-head{margin-bottom:10px!important}body.uf-new-spare-parts-mode .uf-details-pane .uf-pane-copy b{font-size:20px!important}
.uf-new-spare-note{display:flex;align-items:center;gap:8px;padding:7px 10px;margin-bottom:9px;border:1px solid #cfe2f4;border-radius:7px;background:#eef7ff;color:#426783;font-size:8.5px;font-weight:700}.uf-new-spare-note i{width:18px;height:18px;border:1px solid #4284c8;border-radius:50%;display:grid;place-items:center;color:#176dca;font-style:normal;font-weight:900;flex:0 0 auto}
.uf-new-spare-list{display:grid;gap:8px}.uf-new-spare-part{border:1px solid #cddff0;border-radius:9px;background:#fff;overflow:hidden}.uf-new-spare-part-head{min-height:35px;padding:6px 9px;background:#edf6ff;display:flex;align-items:center;justify-content:space-between;gap:8px;color:#092d61;font-size:10px;font-weight:900}.uf-new-spare-part-head span{display:flex;align-items:center;gap:7px}.uf-new-spare-collapse{width:20px;height:20px;padding:0;border:0;border-radius:50%;background:#1769c2;color:#fff;font:900 16px/1 Arial;cursor:pointer}.uf-new-spare-delete{width:27px;height:25px;padding:0;border:1px solid #f2aab4;border-radius:6px;background:#fff4f5;color:#d51f35;font-size:14px;cursor:pointer}.uf-new-spare-part-body{padding:9px 10px 10px}.uf-new-spare-part.collapsed .uf-new-spare-part-body{display:none}.uf-new-spare-part.collapsed .uf-new-spare-collapse{transform:rotate(45deg)}
.uf-new-spare-description{position:relative;margin-bottom:8px}.uf-new-spare-description label,.uf-new-spare-field label{display:block;margin-bottom:4px;color:#0a2f63;font-size:8.7px;font-weight:900}.uf-new-spare-description textarea{width:100%;height:56px!important;min-height:56px!important;max-height:110px!important;padding:8px 10px 17px!important;font-size:9px!important;resize:vertical}.uf-new-spare-counter{position:absolute;left:8px;bottom:5px;color:#7890aa;font-size:7px;font-weight:700;direction:ltr}
.uf-new-spare-grid{display:grid;grid-template-columns:1.35fr 1.15fr .58fr .85fr;gap:7px;align-items:end}.uf-new-spare-field input,.uf-new-spare-field select{width:100%;height:34px!important;min-height:34px!important;padding:4px 7px!important;font-size:8.5px!important}.uf-new-spare-spec-toggle{display:inline-flex;align-items:center;gap:5px;margin-top:7px;padding:0;border:0;background:transparent;color:#1769c2;font:800 8.5px Cairo,Tahoma,sans-serif;cursor:pointer}.uf-new-spare-spec-toggle i{width:17px;height:17px;border:1px solid #428bd4;border-radius:50%;display:grid;place-items:center;font-style:normal;font-size:13px}.uf-new-spare-spec{display:none;margin-top:7px}.uf-new-spare-spec.show{display:block}.uf-new-spare-spec textarea{height:52px!important;min-height:52px!important;font-size:9px!important}
.uf-new-spare-add{width:100%;min-height:35px;margin-top:8px;border:1px dashed #bcd4ea;border-radius:8px;background:#fff;color:#1769c2;font:900 9px Cairo,Tahoma,sans-serif;cursor:pointer}.uf-new-spare-add span{display:inline-grid;place-items:center;width:18px;height:18px;margin-inline-start:5px;border-radius:50%;background:#1769c2;color:#fff;font:900 14px Arial}.uf-new-spare-hidden{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}
.uf-part-attachments{margin-top:8px;padding-top:8px;border-top:1px solid #e5edf6}.uf-part-attachments-title{margin-bottom:6px;color:#0a2f63;font-size:9px;font-weight:900}.uf-part-attachment-row{display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"meta actions" "preview preview";align-items:center;gap:6px 8px;min-height:42px;padding:6px 8px;margin-top:5px;border:1px dashed #cbdced;border-radius:8px;background:#fbfdff}.uf-part-attachment-meta{grid-area:meta;display:flex;align-items:center;gap:6px;min-width:0;color:#0b2d5f;font-size:8.5px;font-weight:900}.uf-part-attachment-count{width:22px;height:22px;border-radius:50%;background:#eaf2fb;color:#5d7591;display:grid;place-items:center;font-size:7.5px}.uf-part-attachment-count.has-files{background:#176dca;color:#fff}.uf-part-attachment-actions{grid-area:actions;display:flex;gap:5px;direction:ltr}.uf-part-file-btn{width:32px;height:30px;padding:0;border:0;border-radius:7px;color:#fff;display:grid;place-items:center;font-size:15px;cursor:pointer}.uf-part-file-btn.camera{background:#071f4d}.uf-part-file-btn.device{background:#1976d2}.uf-part-file-input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}.uf-part-file-previews{grid-area:preview;display:none;gap:7px;flex-wrap:wrap;padding-top:6px;border-top:1px solid #edf3f9}.uf-part-attachment-row.has-files .uf-part-file-previews{display:flex}.uf-part-preview{width:52px;height:52px;border:1px solid #cddbea;border-radius:8px;position:relative;background:#fff}.uf-part-preview img{width:100%;height:100%;object-fit:cover;border-radius:7px}.uf-part-preview button{position:absolute;top:-6px;left:-6px;width:18px;height:18px;padding:0;border:2px solid #fff;border-radius:50%;background:#d93646;color:#fff;font:900 12px/1 Arial;display:grid;place-items:center}
body.uf-new-spare-parts-mode .uf-attach-title{display:flex!important;align-items:center!important;gap:7px!important;margin:12px 0 7px!important;padding-top:8px!important;border-top:1px solid #e3ebf4!important;font-size:11px!important}body.uf-new-spare-parts-mode #uf-upload-rows{gap:6px!important}body.uf-new-spare-parts-mode #uf-upload-rows .uf-upload-row{min-height:46px!important;padding:7px 9px!important}body.uf-new-spare-parts-mode #uf-upload-rows .uf-upload-row:nth-child(-n+2){display:none!important}
@media(max-width:760px){.uf-new-spare-grid{grid-template-columns:1fr 1fr}.uf-new-spare-description textarea{font-size:16px!important}.uf-new-spare-field input,.uf-new-spare-field select{font-size:16px!important;height:42px!important}.uf-new-spare-part-body{padding:9px}.uf-new-spare-note{font-size:9px}}@media(max-width:440px){.uf-new-spare-grid{grid-template-columns:1fr}.uf-new-spare-part-head{font-size:11px}}
</style>
HTML;

        $script = <<<'HTML'
<script id="unifco-new-spare-parts-script-v1">
(()=>{
 const $=id=>document.getElementById(id),form=$('maintenance-form'),newPanel=$('new-customer-panel'),service=$('service-type'),subtype=$('service-subtype'),workspace=$('uf-request-workspace');
 if(!form||!newPanel||!service||!subtype||!workspace)return;
 let active=false,restoring=false,nextId=1,parts=[];
 const en=()=>document.documentElement.lang==='en';
 const copy=()=>en()?{title:'Spare Parts Details & Attachments',help:'Specify the required parts, quantities, or specifications',note:'You can add more than one part. Describe each part clearly; adding the part number and equipment nameplate helps us identify it accurately.',part:'Part',description:'Part or requirement description',descriptionHint:'Example: A replacement part for the shown component, or a spare part required for the equipment...',name:'Part name (if known)',nameHint:'Example: air filter',number:'Part No. (optional)',numberHint:'Example: 12345678',qty:'Required quantity',condition:'Required part',genuine:'Genuine part',approved:'Approved alternative',either:'Best available',specs:'Add specifications (optional)',specsHint:'Dimensions, material, manufacturer, compatibility, or any other specifications...',add:'Add another spare part',remove:'Remove part',attachments:'Attachments',partPhoto:'Photo of the required part or component',platePhoto:'Equipment nameplate photo',report:'Previous report (if available)',video:'Add a video',required:'Please add a clear description for every spare part.'}:{title:'تفاصيل قطع الغيار والمرفقات',help:'حدد القطع والكميات أو المواصفات المطلوبة',note:'يمكنك إضافة أكثر من قطعة غيار. اكتب وصفاً واضحاً لكل قطعة، ويفضل إضافة رقم القطعة وصورة لوحة بيانات المعدة لتحديدها بدقة.',part:'القطعة رقم',description:'وصف القطعة أو الاحتياج',descriptionHint:'مثال: احتياج فلتر للمعدة / احتياج قطعة بديلة للجزء الظاهر في الصورة...',name:'اسم القطعة إن عُرف',nameHint:'مثال: فلتر زيت',number:'رقم القطعة (Part No.)',numberHint:'مثال: 12345678',qty:'الكمية المطلوبة',condition:'القطعة المطلوبة',genuine:'قطعة أصلية',approved:'بديل معتمد',either:'الأنسب المتاح',specs:'إضافة مواصفات (اختياري)',specsHint:'الأبعاد، الخامة، الشركة المصنعة، التوافق أو أي مواصفات أخرى...',add:'إضافة قطعة غيار أخرى',remove:'حذف القطعة',attachments:'المرفقات',partPhoto:'صور القطعة أو الجزء المطلوب',platePhoto:'صورة لوحة بيانات المعدة',report:'تقرير سابق إن وجد',video:'إضافة مقطع فيديو',required:'يرجى إضافة وصف واضح لكل قطعة غيار.'};
 const target=()=>newPanel.classList.contains('show')&&service.value==='quotation'&&subtype.value==='parts';
 const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const blankPart=()=>({id:nextId++,description:'',name:'',number:'',qty:1,condition:copy().genuine,specs:'',partFiles:[],plateFiles:[]});
 const readParts=()=>{document.querySelectorAll('.uf-new-spare-part').forEach(card=>{const p=parts.find(x=>String(x.id)===card.dataset.partId);if(!p)return;p.description=card.querySelector('[data-part-description]')?.value||'';p.name=card.querySelector('[data-part-name]')?.value||'';p.number=card.querySelector('[data-part-number]')?.value||'';p.qty=card.querySelector('[data-part-qty]')?.value||'1';p.condition=card.querySelector('[data-part-condition]')?.value||'';p.specs=card.querySelector('[data-part-specs]')?.value||''})};
 const serialize=()=>{readParts();const c=copy(),details=$('uf-new-spare-details');if(!details)return;const lines=[en()?'[Requested spare parts]':'[قطع الغيار المطلوبة]'];parts.forEach((p,i)=>{lines.push(`${i+1}. ${c.description}: ${p.description.trim()||'—'}`);if(p.name.trim())lines.push(`   ${c.name}: ${p.name.trim()}`);if(p.number.trim())lines.push(`   ${c.number}: ${p.number.trim()}`);lines.push(`   ${c.qty}: ${p.qty||1}`);lines.push(`   ${c.condition}: ${p.condition||c.genuine}`);if(p.specs.trim())lines.push(`   ${c.specs}: ${p.specs.trim()}`);if(p.partFiles?.length)lines.push(`   ${c.partPhoto}: ${p.partFiles.map(f=>f.name).join(', ')}`);if(p.plateFiles?.length)lines.push(`   ${c.platePhoto}: ${p.plateFiles.map(f=>f.name).join(', ')}`)});details.value=lines.join('\n')};
 const attachmentRow=(p,kind,label)=>`<div class="uf-part-attachment-row" data-part-file-row="${kind}"><div class="uf-part-attachment-meta"><span>${escape(label)}</span><span class="uf-part-attachment-count">0</span></div><div class="uf-part-attachment-actions"><button type="button" class="uf-part-file-btn camera" data-file-action="camera" aria-label="Camera">▣</button><button type="button" class="uf-part-file-btn device" data-file-action="device" aria-label="Upload">↑</button></div><input class="uf-part-file-input" type="file" accept="image/*" multiple name="${kind==='part'?'problem_photos[]':'equipment_photos[]'}"><div class="uf-part-file-previews"></div></div>`;
 const partMarkup=(p,index)=>{const c=copy();return `<article class="uf-new-spare-part" data-part-id="${p.id}"><div class="uf-new-spare-part-head"><span><button type="button" class="uf-new-spare-collapse" aria-label="${escape(c.part)}">−</button>${escape(c.part)} (${index+1})</span><button type="button" class="uf-new-spare-delete" title="${escape(c.remove)}" aria-label="${escape(c.remove)}">⌫</button></div><div class="uf-new-spare-part-body"><div class="uf-new-spare-description"><label>${escape(c.description)} <span class="req">*</span></label><textarea data-part-description maxlength="500" required placeholder="${escape(c.descriptionHint)}">${escape(p.description)}</textarea><span class="uf-new-spare-counter">${(p.description||'').length}/500</span></div><div class="uf-new-spare-grid"><div class="uf-new-spare-field"><label>${escape(c.name)}</label><input data-part-name value="${escape(p.name)}" placeholder="${escape(c.nameHint)}"></div><div class="uf-new-spare-field"><label>${escape(c.number)}</label><input data-part-number value="${escape(p.number)}" placeholder="${escape(c.numberHint)}" dir="ltr"></div><div class="uf-new-spare-field"><label>${escape(c.qty)}</label><input data-part-qty type="number" min="1" max="999" value="${escape(p.qty||1)}"></div><div class="uf-new-spare-field"><label>${escape(c.condition)}</label><select data-part-condition><option ${p.condition===c.genuine?'selected':''}>${escape(c.genuine)}</option><option ${p.condition===c.approved?'selected':''}>${escape(c.approved)}</option><option ${p.condition===c.either?'selected':''}>${escape(c.either)}</option></select></div></div><button type="button" class="uf-new-spare-spec-toggle"><i>+</i>${escape(c.specs)}</button><div class="uf-new-spare-spec ${p.specs?'show':''}"><textarea data-part-specs maxlength="700" placeholder="${escape(c.specsHint)}">${escape(p.specs)}</textarea></div><div class="uf-part-attachments"><div class="uf-part-attachments-title">${escape(c.attachments)}</div>${attachmentRow(p,'part',c.partPhoto)}${attachmentRow(p,'plate',c.platePhoto)}</div></div></article>`};
 const setFiles=(input,files)=>{if(typeof DataTransfer==='undefined')return;const dt=new DataTransfer();files.forEach(f=>dt.items.add(f));input.files=dt.files};
 const renderFileRow=(row,p,kind)=>{const files=kind==='part'?p.partFiles:p.plateFiles,input=row.querySelector('.uf-part-file-input'),preview=row.querySelector('.uf-part-file-previews'),count=row.querySelector('.uf-part-attachment-count');setFiles(input,files);preview.innerHTML='';count.textContent=files.length;count.classList.toggle('has-files',files.length>0);row.classList.toggle('has-files',files.length>0);files.forEach((file,index)=>{const item=document.createElement('div');item.className='uf-part-preview';const img=document.createElement('img'),url=URL.createObjectURL(file);img.src=url;img.onload=()=>URL.revokeObjectURL(url);const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.addEventListener('click',()=>{files.splice(index,1);renderFileRow(row,p,kind);serialize()});item.append(img,remove);preview.appendChild(item)})};
 const bind=()=>{const fields=$('uf-detail-fields');if(!fields)return;fields.querySelectorAll('.uf-new-spare-part').forEach(card=>{const p=parts.find(x=>String(x.id)===card.dataset.partId);card.querySelectorAll('input:not([type=file]),select,textarea').forEach(el=>el.addEventListener('input',()=>{const counter=el.matches('[data-part-description]')?card.querySelector('.uf-new-spare-counter'):null;if(counter)counter.textContent=`${el.value.length}/500`;serialize()}));card.querySelectorAll('[data-part-file-row]').forEach(row=>{const kind=row.dataset.partFileRow,input=row.querySelector('.uf-part-file-input');renderFileRow(row,p,kind);row.querySelector('[data-file-action="camera"]')?.addEventListener('click',()=>{input.setAttribute('capture','environment');input.click()});row.querySelector('[data-file-action="device"]')?.addEventListener('click',()=>{input.removeAttribute('capture');input.click()});input.addEventListener('change',()=>{const targetFiles=kind==='part'?p.partFiles:p.plateFiles;const seen=new Set(targetFiles.map(f=>`${f.name}|${f.size}|${f.lastModified}`));[...(input.files||[])].forEach(f=>{const key=`${f.name}|${f.size}|${f.lastModified}`;if(!seen.has(key)&&targetFiles.length<2){seen.add(key);targetFiles.push(f)}});renderFileRow(row,p,kind);serialize()})});card.querySelector('.uf-new-spare-collapse')?.addEventListener('click',()=>card.classList.toggle('collapsed'));card.querySelector('.uf-new-spare-spec-toggle')?.addEventListener('click',()=>card.querySelector('.uf-new-spare-spec')?.classList.toggle('show'));card.querySelector('.uf-new-spare-delete')?.addEventListener('click',()=>{readParts();parts=parts.filter(x=>String(x.id)!==card.dataset.partId);if(!parts.length)parts.push(blankPart());renderParts()})});$('uf-new-spare-add')?.addEventListener('click',()=>{readParts();parts.push(blankPart());renderParts();document.querySelector('.uf-new-spare-part:last-of-type')?.scrollIntoView({behavior:'smooth',block:'center'})});serialize()};
 const renderParts=()=>{const c=copy(),fields=$('uf-detail-fields');if(!fields)return;if(!parts.length)parts=[blankPart()];fields.innerHTML=`<div class="uf-new-spare-note"><i>i</i><span>${escape(c.note)}</span></div><div class="uf-new-spare-list">${parts.map(partMarkup).join('')}</div><button type="button" class="uf-new-spare-add" id="uf-new-spare-add">${escape(c.add)} <span>+</span></button><textarea class="uf-new-spare-hidden" id="uf-new-spare-details" name="details" aria-hidden="true"></textarea>`;bind()};
 const labelAttachments=()=>{const c=copy(),rows=[...document.querySelectorAll('#uf-upload-rows .uf-upload-row')];rows.forEach((row,i)=>{const label=row.querySelector('.uf-attachment-meta b,b'),value=i===2?c.report:(i===3?c.video:null);if(label&&value)label.textContent=value});const title=document.querySelector('.uf-details-pane .uf-attach-title');if(title)title.textContent=c.attachments};
 const enter=()=>{const c=copy(),fields=$('uf-detail-fields');if(!fields)return;active=true;document.body.classList.add('uf-new-spare-parts-mode');$('uf-detail-heading').textContent=c.title;$('uf-detail-help').textContent=c.help;renderParts();setTimeout(labelAttachments,0)};
 const leave=()=>{if(!active)return;active=false;document.body.classList.remove('uf-new-spare-parts-mode');if(restoring)return;restoring=true;subtype.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>{restoring=false},20)};
 const sync=()=>{if(restoring)return;if(target()){if(!active)enter();else{labelAttachments();serialize()}}else leave()};
 document.querySelectorAll('[data-customer-kind]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(sync,10)));service.addEventListener('change',()=>setTimeout(sync,10));subtype.addEventListener('change',()=>setTimeout(sync,10));
 form.addEventListener('submit',e=>{if(!target())return;serialize();const invalid=parts.some(p=>!p.description.trim());if(invalid){e.preventDefault();e.stopImmediatePropagation();alert(copy().required);document.querySelector('[data-part-description]:invalid')?.focus()}},true);sync();
})();
</script>
HTML;
        $html = str_replace('</head>', $style.'</head>', $html);
        $html = str_replace('</body>', $script.'</body>', $html);
        $response->setContent($html);
        return $response;
    }
}
