<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PublicFinalUnifiedAttachmentsPresentation
{
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        if (! $request->routeIs('public.current-maintenance') || ! method_exists($response, 'getContent') || ! method_exists($response, 'setContent')) {
            return $response;
        }

        $html = (string) $response->getContent();
        if (! str_contains($html, 'id="uf-upload-rows"')) {
            return $response;
        }

        $style = <<<'HTML'
<style id="unifco-final-unified-attachments-v1">
#uf-upload-rows{display:grid!important;gap:8px!important}
#uf-files-summary,.uf-inline-previews,.uf-preview-groups,.uf-preview-summary-title{display:none!important}
#uf-upload-rows .uf-upload-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;grid-template-areas:"meta actions" "preview preview" "error error"!important;align-items:center!important;gap:8px 10px!important;width:100%!important;min-height:52px!important;padding:8px 10px!important;margin:0!important;border:1px dashed #cbdced!important;border-radius:9px!important;background:#fff!important;box-sizing:border-box!important;overflow:visible!important}
#uf-upload-rows .uf-attachment-meta{grid-area:meta!important;display:flex!important;align-items:center!important;gap:7px!important;min-width:0!important;direction:rtl!important}
#uf-upload-rows .uf-attachment-meta>b{display:flex!important;align-items:center!important;gap:5px!important;margin:0!important;color:#0b2d5f!important;font-size:9.5px!important;font-weight:900!important;line-height:1.45!important}
#uf-upload-rows .uf-file-count{position:static!important;display:inline-grid!important;place-items:center!important;width:24px!important;min-width:24px!important;height:24px!important;border-radius:50%!important;background:#eaf2fb!important;color:#5d7591!important;font-size:8px!important;font-weight:900!important;margin:0!important}
#uf-upload-rows .uf-file-count.has-files{background:#176dca!important;color:#fff!important}
#uf-upload-rows .uf-row-limit{display:inline-flex!important;align-items:center!important;height:21px!important;padding:0 7px!important;border-radius:999px!important;background:#f1f6fc!important;color:#667e98!important;font-size:7.3px!important;font-weight:800!important;white-space:nowrap!important}
#uf-upload-rows .uf-compact-actions{grid-area:actions!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:6px!important;direction:ltr!important}
#uf-upload-rows .uf-upload-btn{position:static!important;width:34px!important;min-width:34px!important;max-width:34px!important;height:32px!important;min-height:32px!important;padding:0!important;margin:0!important;border-radius:7px!important;display:inline-grid!important;place-items:center!important;font-size:0!important;line-height:0!important;overflow:hidden!important;box-shadow:none!important;transform:none!important}
#uf-upload-rows .uf-upload-btn.camera{background:#071f4d!important;border:1px solid #071f4d!important;color:#fff!important}
#uf-upload-rows .uf-upload-btn.device{background:#1976d2!important;border:1px solid #1976d2!important;color:#fff!important}
#uf-upload-rows .uf-upload-btn svg{width:16px!important;height:16px!important;display:block!important;fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#uf-upload-rows .uf-upload-btn span{display:none!important}
#uf-upload-rows .uf-upload-input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;clip-path:inset(50%)!important}
#uf-upload-rows .uf-final-preview-strip{grid-area:preview!important;grid-column:1/-1!important;display:none!important;align-items:center!important;justify-content:flex-start!important;gap:8px!important;flex-wrap:wrap!important;width:100%!important;padding:9px 0 1px!important;margin:0!important;border-top:1px solid #edf3f9!important;direction:rtl!important}
#uf-upload-rows .uf-upload-row.has-final-previews .uf-final-preview-strip{display:flex!important}
#uf-upload-rows .uf-final-preview{width:62px!important;height:62px!important;flex:0 0 62px!important;border:1px solid #cddbea!important;border-radius:8px!important;background:#f7faff!important;position:relative!important;display:grid!important;place-items:center!important;overflow:visible!important;color:#176dca!important}
#uf-upload-rows .uf-final-preview-media{width:100%!important;height:100%!important;border:0!important;padding:0!important;margin:0!important;border-radius:7px!important;background:transparent!important;overflow:hidden!important;display:grid!important;place-items:center!important;cursor:pointer!important}
#uf-upload-rows .uf-final-preview img,#uf-upload-rows .uf-final-preview video{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:7px!important;display:block!important}
#uf-upload-rows .uf-final-doc{width:100%!important;height:100%!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important;padding:5px!important;box-sizing:border-box!important;overflow:hidden!important}
#uf-upload-rows .uf-final-doc svg{width:21px!important;height:21px!important;fill:none!important;stroke:currentColor!important;stroke-width:1.8!important}
#uf-upload-rows .uf-final-doc span{width:100%!important;font-size:6.5px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;text-align:center!important}
#uf-upload-rows .uf-final-remove{position:absolute!important;top:-6px!important;left:-6px!important;width:19px!important;height:19px!important;border:2px solid #fff!important;border-radius:50%!important;background:#d93646!important;color:#fff!important;display:grid!important;place-items:center!important;padding:0!important;font:900 13px/1 Arial!important;cursor:pointer!important;z-index:6!important;box-shadow:0 2px 5px rgba(7,31,77,.2)!important}
#uf-upload-rows .uf-row-error{grid-area:error!important;grid-column:1/-1!important;display:none!important;color:#c51f33!important;background:#fff5f6!important;border:1px solid #ffd6db!important;border-radius:6px!important;padding:5px 7px!important;font-size:8px!important;font-weight:800!important}.uf-row-error.show{display:block!important}
.uf-final-viewer{position:fixed!important;inset:0!important;z-index:999999!important;display:none!important;align-items:center!important;justify-content:center!important;background:rgba(5,18,42,.84)!important;padding:18px!important}.uf-final-viewer.show{display:flex!important}.uf-final-viewer-card{position:relative!important;width:min(920px,94vw)!important;height:min(700px,88vh)!important;background:#fff!important;border-radius:12px!important;overflow:hidden!important;box-shadow:0 24px 80px rgba(0,0,0,.35)!important}.uf-final-viewer-close{position:absolute!important;left:10px!important;top:10px!important;z-index:3!important;width:32px!important;height:32px!important;border:0!important;border-radius:50%!important;background:#071f4d!important;color:#fff!important;font:900 20px/1 Arial!important;cursor:pointer!important}.uf-final-viewer-title{position:absolute!important;right:14px!important;top:13px!important;left:54px!important;color:#08295d!important;font:800 10px Cairo!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;text-align:right!important}.uf-final-viewer-body{width:100%!important;height:100%!important;padding:48px 16px 16px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#f7f9fc!important;box-sizing:border-box!important}.uf-final-viewer-body img,.uf-final-viewer-body video{max-width:100%!important;max-height:100%!important;object-fit:contain!important;border-radius:7px!important}.uf-final-viewer-body iframe{width:100%!important;height:100%!important;border:0!important;background:#fff!important}
@media(max-width:650px){#uf-upload-rows .uf-upload-row{grid-template-columns:minmax(0,1fr) auto!important;padding:8px!important}#uf-upload-rows .uf-row-limit{display:none!important}#uf-upload-rows .uf-upload-btn{width:32px!important;min-width:32px!important;max-width:32px!important;height:30px!important;min-height:30px!important}#uf-upload-rows .uf-final-preview{width:56px!important;height:56px!important;flex-basis:56px!important}}
</style>
HTML;

        $script = <<<'HTML'
<script id="unifco-final-unified-attachments-script-v1">
(()=>{
  const cameraSvg='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8h3l1.5-2h7L17 8h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2Z"/><circle cx="12" cy="14" r="3.5"/></svg>';
  const uploadSvg='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4M7 9l5-5 5 5M5 20h14"/></svg>';
  const videoSvg='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3z"/></svg>';
  const docSvg='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h8l4 4v14H7z"/><path d="M15 3v5h5M10 12h6M10 16h6"/></svg>';
  const states=new WeakMap(); let viewerUrl=null;
  const root=()=>document.getElementById('uf-upload-rows');
  const sig=f=>[f.name,f.size,f.lastModified,f.type].join('|');
  const unique=files=>{const seen=new Set();return files.filter(f=>{const k=sig(f);if(seen.has(k))return false;seen.add(k);return true;});};
  const setFiles=(input,files)=>{if(!input||typeof DataTransfer==='undefined')return false;const dt=new DataTransfer();files.forEach(f=>dt.items.add(f));input.files=dt.files;return true;};
  const inputs=row=>[...row.querySelectorAll('input[type=file]')].filter(i=>i.dataset.ufVideo!=='1'&&i.dataset.ufArchived!=='1');
  const state=row=>{if(!states.has(row))states.set(row,{files:unique(inputs(row).flatMap(i=>[...(i.files||[])]))});return states.get(row);};
  const showError=(row,msg='')=>{let box=row.querySelector('.uf-row-error');if(!box){box=document.createElement('div');box.className='uf-row-error';row.appendChild(box);}box.textContent=msg;box.classList.toggle('show',!!msg);if(msg)setTimeout(()=>{if(box.textContent===msg)box.classList.remove('show');},3800);};
  const sync=(row)=>{const list=inputs(row),s=state(row);if(!list.length)return;setFiles(list[0],s.files);list.slice(1).forEach(i=>setFiles(i,[]));row.querySelectorAll('input[data-uf-archived="1"]').forEach(i=>i.remove());};
  const viewer=()=>{let v=document.getElementById('uf-final-viewer');if(v)return v;v=document.createElement('div');v.id='uf-final-viewer';v.className='uf-final-viewer';v.innerHTML='<div class="uf-final-viewer-card"><button type="button" class="uf-final-viewer-close">×</button><div class="uf-final-viewer-title"></div><div class="uf-final-viewer-body"></div></div>';document.body.appendChild(v);const close=()=>{v.classList.remove('show');v.querySelector('.uf-final-viewer-body').innerHTML='';if(viewerUrl){URL.revokeObjectURL(viewerUrl);viewerUrl=null;}};v.querySelector('.uf-final-viewer-close').onclick=close;v.onclick=e=>{if(e.target===v)close()};return v;};
  const open=file=>{const v=viewer(),body=v.querySelector('.uf-final-viewer-body'),title=v.querySelector('.uf-final-viewer-title');if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl=URL.createObjectURL(file);title.textContent=file.name||'معاينة المرفق';body.innerHTML='';if((file.type||'').startsWith('image/')){const img=document.createElement('img');img.src=viewerUrl;body.appendChild(img)}else if((file.type||'').startsWith('video/')){const vid=document.createElement('video');vid.src=viewerUrl;vid.controls=true;vid.playsInline=true;body.appendChild(vid)}else if(file.type==='application/pdf'||/\.pdf$/i.test(file.name||'')){const f=document.createElement('iframe');f.src=viewerUrl;body.appendChild(f)}else{const a=document.createElement('a');a.href=viewerUrl;a.target='_blank';a.textContent=file.name||'فتح الملف';body.appendChild(a)}v.classList.add('show');};
  const render=row=>{if(row.id==='uf-video-upload-row')return;const s=state(row);let strip=row.querySelector('.uf-final-preview-strip');if(!strip){strip=document.createElement('div');strip.className='uf-final-preview-strip';row.appendChild(strip)}strip.querySelectorAll('[data-final-url]').forEach(el=>{try{URL.revokeObjectURL(el.dataset.finalUrl)}catch(_){}});strip.innerHTML='';const badge=row.querySelector('.uf-file-count');if(badge){badge.textContent=String(s.files.length);badge.classList.toggle('has-files',s.files.length>0)}row.classList.toggle('has-final-previews',s.files.length>0);s.files.forEach((file,index)=>{const item=document.createElement('div');item.className='uf-final-preview';const media=document.createElement('button');media.type='button';media.className='uf-final-preview-media';if((file.type||'').startsWith('image/')){const u=URL.createObjectURL(file);item.dataset.finalUrl=u;const img=document.createElement('img');img.src=u;media.appendChild(img)}else{const d=document.createElement('span');d.className='uf-final-doc';d.innerHTML=docSvg+'<span></span>';d.querySelector('span').textContent=file.name||'ملف';media.appendChild(d)}media.onclick=()=>open(file);const rem=document.createElement('button');rem.type='button';rem.className='uf-final-remove';rem.textContent='×';rem.onclick=e=>{e.preventDefault();e.stopPropagation();s.files.splice(index,1);sync(row);render(row)};item.append(media,rem);strip.appendChild(item)});};
  const decorate=row=>{if(!row||row.id==='uf-video-upload-row')return;row.querySelectorAll('.uf-inline-previews,.uf-compact-preview-strip').forEach(x=>x.remove());let label=row.querySelector('b,.uf-attachment-label'),meta=row.querySelector('.uf-attachment-meta'),badge=row.querySelector('.uf-file-count');if(!meta){meta=document.createElement('div');meta.className='uf-attachment-meta';if(label)meta.appendChild(label);if(badge)meta.appendChild(badge);const lim=document.createElement('span');lim.className='uf-row-limit';lim.textContent='الحد الأقصى: 2';meta.appendChild(lim);row.prepend(meta)}else if(!meta.querySelector('.uf-row-limit')){const lim=document.createElement('span');lim.className='uf-row-limit';lim.textContent='الحد الأقصى: 2';meta.appendChild(lim)}if(!badge){badge=document.createElement('span');badge.className='uf-file-count';badge.textContent='0';meta.insertBefore(badge,meta.querySelector('.uf-row-limit'))}let actions=row.querySelector('.uf-compact-actions');if(!actions){actions=document.createElement('div');actions.className='uf-compact-actions';row.querySelectorAll('.uf-upload-btn').forEach(b=>actions.appendChild(b));row.appendChild(actions)}actions.querySelectorAll('.uf-upload-btn').forEach(btn=>{const cam=btn.classList.contains('camera');btn.innerHTML=cam?cameraSvg:uploadSvg;btn.title=cam?'التقاط صورة':'رفع من الجهاز'});inputs(row).forEach(i=>{i.multiple=true;i.removeAttribute('data-uf-polish-change');i.dataset.ufFinalBound='1'});sync(row);render(row);};
  const absorb=(row,input)=>{const s=state(row),picked=[...(input.files||[])];const merged=unique([...s.files,...picked]);if(merged.length>2){s.files=merged.slice(0,2);showError(row,'الحد الأقصى مرفقان فقط لهذا البند. تم رفض أي مرفق إضافي.')}else{s.files=merged;showError(row,'')}sync(row);render(row);};
  const ensureVideo=()=>{const r=root();if(!r||document.getElementById('uf-video-upload-row'))return;const row=document.createElement('div');row.id='uf-video-upload-row';row.className='uf-upload-row';row.innerHTML='<div class="uf-attachment-meta"><b>إضافة مقطع فيديو</b><span class="uf-file-count">0</span><span class="uf-row-limit">فيديو واحد · 15 ثانية</span></div><div class="uf-compact-actions"><button type="button" class="uf-upload-btn camera" id="uf-final-video-camera">'+videoSvg+'</button><button type="button" class="uf-upload-btn device" id="uf-final-video-device">'+uploadSvg+'</button></div><input id="uf-final-video-input" class="uf-upload-input" data-uf-video="1" type="file" name="request_video" accept="video/mp4,video/quicktime,video/webm,video/x-m4v"><div class="uf-final-preview-strip"></div><div class="uf-row-error"></div>';r.appendChild(row);const input=row.querySelector('#uf-final-video-input');row.querySelector('#uf-final-video-camera').onclick=()=>{input.setAttribute('capture','environment');input.click()};row.querySelector('#uf-final-video-device').onclick=()=>{input.removeAttribute('capture');input.click()};};
  const videoChange=(input,row)=>{const f=input.files?.[0];if(!f)return;if(!(f.type||'').startsWith('video/')){input.value='';showError(row,'يرجى اختيار ملف فيديو فقط.');return}const probe=document.createElement('video'),u=URL.createObjectURL(f);probe.preload='metadata';probe.src=u;probe.onloadedmetadata=()=>{const dur=Number(probe.duration||0);URL.revokeObjectURL(u);if(!dur||dur>15.25){input.value='';showError(row,'مدة الفيديو يجب ألا تتجاوز 15 ثانية.');return}const strip=row.querySelector('.uf-final-preview-strip');strip.innerHTML='';const item=document.createElement('div');item.className='uf-final-preview';const media=document.createElement('button');media.type='button';media.className='uf-final-preview-media';const url=URL.createObjectURL(f);item.dataset.finalUrl=url;const vid=document.createElement('video');vid.src=url;vid.muted=true;vid.playsInline=true;media.appendChild(vid);media.onclick=()=>open(f);const rem=document.createElement('button');rem.type='button';rem.className='uf-final-remove';rem.textContent='×';rem.onclick=e=>{e.preventDefault();e.stopPropagation();URL.revokeObjectURL(url);input.value='';strip.innerHTML='';row.classList.remove('has-final-previews');const b=row.querySelector('.uf-file-count');b.textContent='0';b.classList.remove('has-files')};item.append(media,rem);strip.appendChild(item);row.classList.add('has-final-previews');const b=row.querySelector('.uf-file-count');b.textContent='1';b.classList.add('has-files');showError(row,'')};probe.onerror=()=>{URL.revokeObjectURL(u);input.value='';showError(row,'تعذر قراءة مدة الفيديو.')};};
  const init=()=>{const r=root();if(!r)return false;r.querySelectorAll('.uf-upload-row').forEach(decorate);ensureVideo();return true};
  document.addEventListener('click',e=>{const btn=e.target.closest?.('#uf-upload-rows .uf-upload-row:not(#uf-video-upload-row) .uf-upload-btn');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();const row=btn.closest('.uf-upload-row'),list=inputs(row);if(!list.length)return;const cam=btn.classList.contains('camera');const input=cam?(list.find(i=>i.hasAttribute('capture'))||list[0]):(list.find(i=>!i.hasAttribute('capture'))||list[list.length-1]);if(cam)input.setAttribute('capture','environment');else input.removeAttribute('capture');input.click()},true);
  document.addEventListener('change',e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=='file'||!input.closest('#uf-upload-rows'))return;e.stopImmediatePropagation();const row=input.closest('.uf-upload-row');if(input.dataset.ufVideo==='1'){videoChange(input,row);return}absorb(row,input)},true);
  const start=()=>{if(!init())return false;const r=root();new MutationObserver(()=>{r.querySelectorAll('.uf-upload-row').forEach(decorate);ensureVideo()}).observe(r,{childList:true,subtree:true});return true};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(!start()){let n=0,t=setInterval(()=>{if(start()||++n>50)clearInterval(t)},80)}});else if(!start()){let n=0,t=setInterval(()=>{if(start()||++n>50)clearInterval(t)},80)}
})();
</script>
HTML;

        $html = str_replace('</head>', $style.'</head>', $html);
        $html = str_replace('</body>', $script.'</body>', $html);
        $response->setContent($html);

        return $response;
    }
}
