@extends('layouts.app')
@section('title',$asset->asset_code.' · Custody & Transfers')
@section('heading','Asset Custody & Transfers')
@section('content')
<style>.card{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:16px;margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.form input,.form select,.form textarea{padding:8px;border:1px solid #d7e0eb;border-radius:6px}.wide{grid-column:1/-1}.btn{border:0;border-radius:7px;background:#06275c;color:#fff;padding:8px 10px;font-weight:800}.row{padding:9px 0;border-bottom:1px solid #edf1f5;font-size:12px}.notice{background:#e9f7ef;color:#176940;padding:10px;border-radius:8px;margin-bottom:12px}@media(max-width:700px){.grid,.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="card">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<div class="card"><a href="{{ route('asset-master.show',$asset) }}">← Asset 360</a><h2>{{ $asset->asset_code }} · {{ $asset->name }}</h2><div>{{ $asset->lifecycle_status }} · {{ $asset->verification_status }}</div></div>
<div class="grid">
<section class="card"><h3>Assign Custody</h3><form class="form" method="POST" action="{{ route('asset-master.custody.assign',$asset) }}">@csrf<select name="custodian_user_id"><option value="">Employee / user (optional)</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input name="custodian_name" placeholder="External custodian name"><input name="department" placeholder="Department"><input name="branch" placeholder="Branch"><textarea class="wide" name="notes" placeholder="Handover notes"></textarea><button class="btn wide">Assign Custody</button></form></section>
<section class="card"><h3>Request Transfer</h3><form class="form" method="POST" action="{{ route('asset-master.transfers.request',$asset) }}">@csrf<select name="custodian_user_id"><option value="">New employee / user</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input name="custodian_name" placeholder="New custodian name"><input name="department" placeholder="New department"><input name="branch" placeholder="New branch"><input class="wide" name="reason" required placeholder="Transfer reason"><textarea class="wide" name="notes" placeholder="Request notes"></textarea><button class="btn wide">Submit for Approval</button></form></section>
<section class="card"><h3>Custody History</h3>@forelse($custodies as $custody)<div class="row"><b>{{ $custody->status }}</b> · {{ $custody->custodian?->name ?: $custody->custodian_name ?: $custody->department }} · {{ $custody->assigned_at?->format('Y-m-d H:i') }}@if($custody->status==='ACTIVE')<form method="POST" action="{{ route('asset-master.custody.return',[$asset,$custody]) }}" style="margin-top:6px">@csrf<input name="notes" placeholder="Return notes"><button class="btn">Return Custody</button></form>@endif</div>@empty<div>No custody records.</div>@endforelse</section>
<section class="card"><h3>Transfer Approvals</h3>@forelse($transfers as $transfer)<div class="row"><b>{{ $transfer->status }}</b> · {{ $transfer->reason }} · {{ $transfer->requested_at?->format('Y-m-d H:i') }}@if($canApprove && $transfer->status==='PENDING_APPROVAL')<form method="POST" action="{{ route('asset-master.transfers.review',[$asset,$transfer]) }}" style="margin-top:6px">@csrf<input name="notes" placeholder="Checker notes"><button class="btn" name="decision" value="APPROVE">Approve</button><button class="btn" name="decision" value="REJECT">Reject</button></form>@endif</div>@empty<div>No transfer requests.</div>@endforelse</section>
</div>
@endsection
