@extends('layouts.app')
@section('title','Asset Master · UNIFCO')
@section('heading','Professional Asset Master')
@section('content')
<style>.am-grid{display:grid;grid-template-columns:1fr 1.4fr;gap:14px}.box{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:16px}.box h3{margin:0 0 12px;color:#071f4d;font-size:14px}.form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.field{display:grid;gap:4px;font-size:9px;font-weight:800;color:#506079}.field input,.field select,.field textarea{padding:8px;border:1px solid #d7e0eb;border-radius:7px;font-size:10px;background:#fff}.field textarea{min-height:72px}.wide{grid-column:1/-1}.btn{border:0;border-radius:7px;background:#06275c;color:#fff;padding:9px 11px;font-weight:850;font-size:9px;cursor:pointer}.asset{border:1px solid #e7ebf1;border-radius:10px;padding:11px;margin-bottom:8px;display:flex;justify-content:space-between;gap:12px}.asset b{font-size:11px;color:#0b2857}.asset small{display:block;color:#77859a;font-size:9px;margin-top:3px}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf3fb;color:#285f99;font-size:8px;font-weight:850}.score{font-size:18px;font-weight:900;color:#0b2857}.notice{background:#e9f7ef;color:#176940;padding:10px 12px;border-radius:8px;margin-bottom:12px;font-size:10px}.errors{background:#fff0f0;color:#962f2f;padding:10px 12px;border-radius:8px;margin-bottom:12px;font-size:10px}@media(max-width:1000px){.am-grid{grid-template-columns:1fr}}@media(max-width:600px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors">@foreach($errors->all() as $e)<div>{{ $e }}</div>@endforeach</div>@endif
<div class="am-grid">
<section class="box"><h3>Register Customer Asset</h3><form class="form" method="POST" action="{{ route('asset-master.store') }}">@csrf
<div class="field"><label>Customer</label><select name="customer_id" required><option value="">Select</option>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->customer_code }} · {{ $c->name }}</option>@endforeach</select></div>
<div class="field"><label>Site</label><select name="customer_site_id" required><option value="">Select</option>@foreach($sites as $s)<option value="{{ $s->id }}">{{ $s->site_code ?? '' }} {{ $s->name }}</option>@endforeach</select></div>
<div class="field"><label>Asset Name</label><input name="name" required placeholder="Transformer TR-01"></div><div class="field"><label>Customer Asset Code</label><input name="customer_asset_code"></div>
<div class="field"><label>Category</label><input name="asset_category" required placeholder="Electrical"></div><div class="field"><label>Asset Type</label><input name="asset_type" required placeholder="Distribution Transformer"></div>
<div class="field"><label>Subcategory</label><input name="asset_subcategory"></div><div class="field"><label>Specification Template</label><select name="asset_category_template_id"><option value="">None</option>@foreach($templates as $t)<option value="{{ $t->id }}">{{ $t->category }} → {{ $t->asset_type }}</option>@endforeach</select></div>
<div class="field"><label>Manufacturer</label><input name="manufacturer"></div><div class="field"><label>Model</label><input name="model_no"></div><div class="field"><label>Serial Number</label><input name="serial_no"></div><div class="field"><label>Criticality</label><select name="criticality" required>@foreach($criticalities as $v)<option>{{ $v }}</option>@endforeach</select></div>
<div class="field"><label>Ownership</label><select name="ownership_type" required>@foreach($ownershipTypes as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="field"><label>Maintenance Strategy</label><select name="maintenance_strategy"><option value="">Not set</option>@foreach($strategies as $v)<option>{{ $v }}</option>@endforeach</select></div>
<div class="field"><label>Building</label><input name="building"></div><div class="field"><label>Floor</label><input name="floor"></div><div class="field"><label>Zone / Area</label><input name="zone"></div><div class="field"><label>Room</label><input name="room"></div><div class="field wide"><label>Physical Location</label><input name="physical_location" placeholder="Electrical Room 01, Basement"></div>
<div class="field"><label>Installation Date</label><input type="date" name="installation_date"></div><div class="field"><label>Commissioning Date</label><input type="date" name="commission_date"></div><div class="field"><label>Warranty Start</label><input type="date" name="warranty_start"></div><div class="field"><label>Warranty End</label><input type="date" name="warranty_expiry"></div><div class="field wide"><label>Warranty Provider</label><input name="warranty_provider"></div>
<div class="field wide"><label>Technical Specifications (JSON)</label><textarea name="technical_specifications" placeholder='{"rated_power_kva":1000,"primary_voltage":"13.8kV","secondary_voltage":"400V"}'></textarea></div>
<div class="wide"><button class="btn">Create Pending Verification Asset</button></div></form></section>
<section class="box"><h3>Asset Registry</h3>@forelse($assets as $asset)<div class="asset"><div><span class="pill">{{ $asset->asset_code }}</span><b style="display:block;margin-top:6px"><a href="{{ route('asset-master.show',$asset) }}">{{ $asset->name }}</a></b><small>{{ $asset->customer?->name ?: 'No customer' }} · {{ $asset->site?->name ?: 'No site' }}{{ $asset->location?' · '.$asset->location->name:'' }}</small><small>{{ $asset->asset_category }} → {{ $asset->asset_type ?: $asset->asset_subcategory ?: '-' }} · {{ $asset->manufacturer ?: '-' }} {{ $asset->model_no ?: '' }}</small><small>{{ $asset->lifecycle_status ?: $asset->status }} · {{ $asset->verification_status ?: 'PENDING' }} · Commissioning {{ str_replace('_',' ',$asset->commissioning_status ?? 'NOT_STARTED') }}</small></div><div style="text-align:right"><div class="score">{{ $asset->data_completeness_score ?? 0 }}%</div><small>complete</small></div></div>@empty<div style="font-size:10px;color:#77859a">No customer assets registered.</div>@endforelse</section>
</div>
@if($canVerify)<div class="am-grid" style="margin-top:14px"><section class="box"><h3>Location Hierarchy Node</h3><form class="form" method="POST" action="{{ route('asset-master.locations.store') }}">@csrf<div class="field"><label>Customer</label><select name="customer_id" required>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="field"><label>Site</label><select name="customer_site_id" required>@foreach($sites as $s)<option value="{{ $s->id }}">{{ $s->site_code }} · {{ $s->name }}</option>@endforeach</select></div><div class="field"><label>Location Type</label><select name="location_type"><option>SITE</option><option>BUILDING</option><option>FLOOR</option><option>ZONE</option><option>ROOM</option><option>AREA</option></select></div><div class="field"><label>Code</label><input name="code" required placeholder="BLD-A / EL-RM-01"></div><div class="field wide"><label>Name</label><input name="name" required placeholder="Main Building / Electrical Room 01"></div><div class="field wide"><label>Description</label><input name="description"></div><div class="wide"><button class="btn">Create Location Node</button></div></form><p style="font-size:9px;color:#77859a">Parent/child nesting is supported by the API workflow; site ownership is always validated before the node is accepted.</p></section><section class="box"><h3>Asset Specification Template</h3><form class="form" method="POST" action="{{ route('asset-master.templates.store') }}">@csrf<div class="field"><label>Category</label><input name="category" required></div><div class="field"><label>Asset Type</label><input name="asset_type" required></div><div class="field wide"><label>Template Name</label><input name="name" required></div><div class="field wide"><label>Specification Schema (JSON)</label><textarea name="specification_schema" placeholder='{"rated_power_kva":{"label":"Rated Power kVA","type":"number"}}'></textarea></div><div class="wide"><button class="btn">Save Template</button></div></form></section></div>@endif
@endsection
