@extends('layouts.app')
@section('title',$asset->asset_code.' · Maintenance Intelligence')
@section('heading','Asset Maintenance Intelligence')
@section('content')
<style>.mi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:15px}.card h3{margin:0 0 10px;font-size:12px;color:#08295b}.metric{font-size:26px;font-weight:950;color:#08295b}.muted{font-size:9px;color:#748298;line-height:1.6}.row{padding:8px 0;border-bottom:1px solid #edf1f5;font-size:9px}.pill{display:inline-flex;padding:4px 8px;border-radius:999px;background:#edf3fb;color:#285f99;font-size:8px;font-weight:850}.form{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.form input{padding:7px;border:1px solid #d7e0eb;border-radius:6px;font-size:9px}.btn{border:0;border-radius:7px;background:#06275c;color:#fff;padding:8px 10px;font-size:9px;font-weight:850}.notice{background:#e9f7ef;color:#176940;padding:10px;border-radius:8px;margin-bottom:12px;font-size:10px}@media(max-width:1000px){.mi-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.mi-grid{grid-template-columns:1fr}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div style="margin-bottom:12px"><a href="{{ route('asset-master.show',$asset) }}">← Asset 360</a> · <b>{{ $asset->asset_code }} · {{ $asset->name }}</b></div>
<div class="mi-grid">
<section class="card"><h3>Health Score</h3><div class="metric">{{ $snapshot['score'] }}/100</div><span class="pill">{{ $snapshot['band'] }}</span><div class="muted">Calculated from failures, downtime, overdue PM, age and lifecycle state.</div></section>
<section class="card"><h3>Reliability</h3><div class="metric">{{ $snapshot['failureCount'] }}</div><div class="muted">Failures recorded<br>MTBF: {{ $snapshot['mtbf']===null?'-':$snapshot['mtbf'].' h' }}<br>MTTR: {{ $snapshot['mttr']===null?'-':$snapshot['mttr'].' min' }}</div></section>
<section class="card"><h3>Downtime & PM</h3><div class="metric">{{ $snapshot['downtime'] }}</div><div class="muted">Downtime minutes<br>Overdue PM: {{ $snapshot['overdue'] }}<br>Next due: {{ $snapshot['nextDue'] ?: '-' }}</div></section>
<section class="card"><h3>Lifecycle Outlook</h3><div class="metric">{{ $snapshot['remaining']===null?'-':$snapshot['remaining'] }}</div><div class="muted">Remaining life months<br>Recommendation: {{ str_replace('_',' ',$snapshot['replacement']) }}<br>Meter: {{ $asset->meter_value }}</div></section>
<section class="card"><h3>Meter Readings</h3><form class="form" method="POST" action="{{ route('asset-master.intelligence.meter',$asset) }}">@csrf<input type="number" step="0.0001" min="0" name="reading" placeholder="Reading" required><input type="date" name="reading_date" value="{{ now()->toDateString() }}" required><input name="notes" placeholder="Notes"><button class="btn">Record</button></form>@forelse($readings as $r)<div class="row"><b>{{ $r->reading }}</b> · {{ $r->reading_date?->format('Y-m-d') }} @if($r->notes)· {{ $r->notes }}@endif</div>@empty<div class="muted">No readings yet.</div>@endforelse</section>
<section class="card"><h3>Maintenance Plans</h3>@forelse($plans as $p)<div class="row"><b>{{ $p->plan_no }} · {{ $p->name }}</b><br>Next date {{ $p->next_due_date ?: '-' }} · Next meter {{ $p->next_due_meter ?: '-' }} · {{ $p->maintenance_strategy ?? 'PREVENTIVE' }}</div>@empty<div class="muted">No active maintenance plans.</div>@endforelse</section>
<section class="card"><h3>Failure History</h3>@forelse($failures as $f)<div class="row"><b>{{ $f->failure_mode ?: $f->failure_code ?: 'Failure' }}</b><br>{{ $f->failed_at }} · {{ $f->severity }} · {{ $f->downtime_minutes }} min @if($f->failure_cause)<br>{{ $f->failure_cause }}@endif</div>@empty<div class="muted">No failure records.</div>@endforelse</section>
<section class="card"><h3>Health Recalculation</h3><div class="muted">Persisted health: {{ $asset->health_score ?? '-' }} / {{ $asset->health_band ?: '-' }}<br>Last calculated: {{ $asset->last_health_calculated_at?->format('Y-m-d H:i') ?: '-' }}</div><form method="POST" action="{{ route('asset-master.intelligence.recalculate',$asset) }}" style="margin-top:10px">@csrf<button class="btn">Recalculate Health</button></form></section>
</div>
@endsection
