@extends('layouts.app')
@section('title','Immutable Audit Trail | UNIFCO Platform')
@section('heading','Immutable Audit Trail')
@section('content')
@include('admin.system.operations-styles')
<style>.audit-integrity{display:flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid #ffffff22;border-radius:999px;background:#ffffff10;font-size:9px;font-weight:850;white-space:nowrap}.audit-integrity:before{content:'';width:7px;height:7px;border-radius:50%;background:#41d18b}.audit-hash{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:8px;color:#52627a}.audit-changes summary{cursor:pointer;color:#1e315b;font-weight:800;font-size:9px}.audit-changes pre{max-width:520px;white-space:pre-wrap;word-break:break-word;background:#f7f9fc;border:1px solid #e6ebf1;border-radius:8px;padding:9px;font-size:8px;color:#46566f}</style>
<section class="ops-hero"><div><small>GOVERNANCE & FORENSICS</small><h1>Immutable Audit Trail</h1><p>Append-only system and business history. Entries are read-only and cannot be edited or deleted from the administrative interface.</p></div><span class="audit-integrity">APPEND-ONLY</span></section>
<section class="ops-card"><div class="ops-section-head"><div><h3>Audit Explorer</h3><p>Search by module, actor, object, time range, network source or correlation identifier.</p></div><span class="ops-badge">Read only</span></div><form class="ops-filter" method="GET"><label>Module<select name="module"><option value="">All Modules</option>@foreach($modules as $module)<option @selected(request('module')===$module)>{{ $module }}</option>@endforeach</select></label><label>Action<input name="action" value="{{ request('action') }}" placeholder="Action"></label><label>Actor<select name="user_id"><option value="">All Actors</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user_id')===(string)$user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select></label><label>IP Address<input name="ip" value="{{ request('ip') }}" placeholder="IP"></label><label>Object Type<input name="entity_type" value="{{ request('entity_type') }}" placeholder="Object Type"></label><label>Object ID<input name="entity_id" value="{{ request('entity_id') }}" placeholder="Object ID"></label><label>From<input type="date" name="from" value="{{ request('from') }}"></label><label>To<input type="date" name="to" value="{{ request('to') }}"></label><label>Correlation ID<input name="correlation_id" value="{{ request('correlation_id') }}" placeholder="Correlation ID"></label><button class="btn">Apply Filters</button></form>
<table class="ops-table"><thead><tr><th>ID</th><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>IP / Session</th><th>Integrity / Changes</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>#{{ $log->id }}</td><td>{{ $log->created_at }}</td><td><b>{{ $users->firstWhere('id',$log->user_id)?->name ?: 'SYSTEM' }}</b></td><td><b>{{ $log->action }}</b>@if($log->reason)<small>{{ $log->reason }}</small>@endif</td><td>{{ $log->entity_type }}<small>#{{ $log->entity_id }}</small></td><td>{{ $log->ip_address ?: '—' }}<small>{{ $log->session_id ?: '—' }}</small></td><td><span class="audit-hash">{{ $log->entry_hash?substr($log->entry_hash,0,14).'…':'Legacy entry' }}</span>@if($log->before_state||$log->after_state)<details class="audit-changes" style="margin-top:6px"><summary>View change set</summary><pre>Before: {{ $log->before_state ?: '{}' }}
After: {{ $log->after_state ?: '{}' }}</pre></details>@endif</td></tr>@empty<tr><td colspan="7" class="ops-empty">No audit entries match the selected filters.</td></tr>@endforelse</tbody></table>{{ $logs->links() }}</section>
@endsection
