@php
$home = [
    'lang' => 'en',
    'dir' => 'ltr',
    'nav' => ['Home', 'About', 'Services', 'Industries', 'How We Work', 'Projects', 'Contact'],
    'language' => 'AR',
    'login' => 'Client Login',
    'request' => 'Request Service',
    'hero_eyebrow' => 'ONE FACILITY SHOP',
    'hero_title' => 'One partner for every facility need',
    'hero_text' => 'Integrated facility operations, maintenance and technical services with specialist teams and digital visibility that keep your business running efficiently.',
    'explore' => 'Explore Our Services',
    'hero_proofs' => [['◴', 'Operations Support', '24/7'], ['▣', 'Preventive', '& Corrective'], ['↗', 'Digital Tracking', '& Clear Reports']],
    'capabilities' => [
        ['▥', 'Facility Management', 'Integrated facility operations'],
        ['⚙', 'MEP & Technical Services', 'Mechanical and electrical works'],
        ['◇', 'Preventive Maintenance', 'Planned maintenance programs'],
        ['▤', 'Digital Client Portal', 'A connected service platform'],
    ],
    'about_kicker' => 'ABOUT US',
    'about_title' => 'Your integrated facility management partner',
    'about_text' => 'UNIFCO delivers integrated facility operations, maintenance and asset management through specialist teams, structured processes and digital visibility that improve readiness, reduce failures and strengthen performance.',
    'about_points' => [
        ['◎', 'Central Management', 'For assets and maintenance'], ['♙', 'One Team', 'For multiple services'],
        ['↗', 'Routine Tracking', 'With transparent reports'], ['◈', 'Tailored Solutions', 'For every facility'],
    ],
    'about_button' => 'Discover UNIFCO',
    'stats' => [['+','Sites Served'], ['+','Assets Managed'], ['98%','SLA Compliance'], ['24/7','Operations Support']],
    'services_kicker' => 'OUR SERVICES',
    'services_title' => 'Integrated solutions under one roof',
    'services_text' => 'From daily facility management to specialized technical operations',
    'services' => [
        ['01', '/images/home/facility-power.svg?v=20260823-13', 'Facility Management', 'Daily facility operations, asset oversight and coordinated support services.'],
        ['02', '/images/unifco-hero-workers-v7.jpg?v=20260823-13', 'Preventive & Corrective Maintenance', 'Planned programs and responsive repairs that sustain operations.'],
        ['03', '/images/home/hero-electrical.svg?v=20260823-13', 'MEP Services', 'Mechanical, electrical and plumbing systems maintenance and operations.'],
        ['04', '/images/home/ats.svg?v=20260823-13', 'HVAC Systems', 'Inspection and maintenance for efficient cooling and ventilation.'],
        ['05', '/images/home/generator.svg?v=20260823-13', 'Electrical & Power Systems', 'Electrical infrastructure, generators and backup power solutions.'],
        ['06', '/images/home/ups.svg?v=20260823-13', 'Asset Management', 'Complete asset lifecycle, maintenance, warranty and technical history.'],
    ],
    'more' => 'Learn more',
    'all_services' => 'View All Services',
    'process_kicker' => 'HOW WE WORK',
    'process_title' => 'A clear process from start to finish',
    'process' => [
        ['01', 'Assessment', 'Understand the site, assets, risks and service requirements.'],
        ['02', 'Planning', 'Build the work plan, schedule, resources and service levels.'],
        ['03', 'Execution', 'Deliver the work and document readings, results and findings.'],
        ['04', 'Follow-up & Improvement', 'Report performance and continuously improve operations.'],
    ],
    'industries_title' => 'Industries we serve',
    'industries' => [
        ['/images/home/sector-commercial.svg?v=20260823-13', 'Commercial Buildings'],
        ['/images/home/sector-warehouse.svg?v=20260823-13', 'Offices'],
        ['/images/home/sector-healthcare.svg?v=20260823-13', 'Residential Communities'],
        ['/images/home/sector-industrial.svg?v=20260823-13', 'Warehouses & Factories'],
        ['/images/home/sector-datacenter.svg?v=20260823-13', 'Critical Facilities'],
        ['/images/home/sector-education.svg?v=20260823-13', 'Hospitality'],
        ['/images/home/sector-government.svg?v=20260823-13', 'Government'],
    ],
    'all_industries' => 'View All Industries',
    'maintenance_title' => 'From reactive maintenance to planned operations',
    'maintenance_text' => 'UNIFCO reduces emergency failures by planning, documenting and improving maintenance before problems interrupt your operation.',
    'maintenance_checks' => ['Preventive plans', 'Routine inspections', 'History and spare parts', 'Efficiency programs', 'Work order documentation', 'Continuous improvement'],
    'maintenance_button' => 'Explore Maintenance Services',
    'portal_title' => 'Manage every service in one place',
    'portal_text' => 'A connected client portal that makes every facility service easy to monitor.',
    'portal_checks' => ['Contract tracking', 'Asset management', 'Maintenance requests', 'Reports and payments', 'Upcoming maintenance', 'SLA performance'],
    'portal_button' => 'Client Portal Login',
    'why_title' => 'Why UNIFCO?',
    'why' => [
        ['◎', 'Integrated Solutions', 'All services and assets in one platform'],
        ['▤', 'Clear Reporting', 'Accurate reports that build visibility and trust'],
        ['◴', 'Fast Response', 'Structured handling for failures and emergencies'],
        ['♙', 'Qualified Teams', 'Experienced engineers and skilled technicians'],
        ['⚙', 'Smart Prevention', 'Maintenance plans focused on avoiding failures'],
        ['◉', 'One Experience', 'A complete solution from one accountable partner'],
    ],
    'projects_title' => 'Our work in action',
    'projects_button' => 'View All Projects',
    'emergency_title' => 'Need urgent support?',
    'emergency_text' => 'If a failure is affecting operations, send an emergency maintenance request for immediate routing.',
    'emergency_button' => 'Emergency Maintenance',
    'final_title' => 'Your facility deserves better management',
    'final_text' => 'Let UNIFCO manage operations and maintenance while you focus on your business.',
    'quote' => 'Request a Quote',
    'contact' => 'Talk to Us',
    'footer_about' => 'Integrated facility management, operations and technical maintenance through one connected service experience.',
    'company' => 'Company',
    'services_label' => 'Services',
    'contact_label' => 'Contact',
];
@endphp
@include('public.partials.home-reference-layout', ['home' => $home])
