@php
$home = [
    'lang' => 'en',
    'dir' => 'ltr',
    'nav' => ['Home', 'About', 'Services', 'Industries', 'How We Work', 'Projects', 'Contact'],
    'language' => 'AR',
    'login' => 'Sign In',
    'request' => 'Request Service',
    'hero_eyebrow' => 'ONE FACILITY SHOP',
    'hero_title' => 'One partner for every facility need',
    'hero_text' => 'Integrated electrical power, maintenance, facility and asset management services delivered by specialist teams with digital visibility that keeps operations running efficiently.',
    'explore' => 'Explore Our Services',
    'hero_proofs' => [['clock', 'Operations Support', '24/7'], ['shield', 'Preventive', '& Corrective'], ['chart', 'Digital Tracking', '& Clear Reports']],
    'capabilities' => [
        ['settings', 'Electrical Power Systems', 'Transformers · UPS · Generators · MV'],
        ['shield', 'Maintenance Services', 'Preventive · Corrective · Emergency'],
        ['building', 'Facility & MEP Services', 'Facility operations and technical services'],
        ['monitor', 'Asset & Digital Management', 'Asset lifecycle and digital visibility'],
    ],
    'about_kicker' => 'ABOUT US',
    'about_title' => 'Your integrated electrical and facility services partner',
    'about_text' => 'UNIFCO provides specialist electrical power, preventive and corrective maintenance, testing, maintenance contracts, MEP, HVAC, facility management and asset management services through qualified technical teams, structured operations and digital visibility.',
    'about_points' => [
        ['target', 'Central Management', 'For assets and maintenance'], ['team', 'One Team', 'For multiple services'],
        ['report', 'Routine Tracking', 'With transparent reports'], ['layers', 'Tailored Solutions', 'For every facility'],
    ],
    'about_button' => 'Discover UNIFCO',
    'stats' => [['+','Sites Served'], ['+','Assets Managed'], ['98%','SLA Compliance'], ['24/7','Operations Support']],
    'services_kicker' => 'OUR SERVICES',
    'services_title' => 'Electrical, maintenance and facility services under one roof',
    'services_text' => 'From critical power and specialist maintenance to facility and asset management',
    'services' => [
        ['01', '/images/home/transformer.svg', 'Transformers', 'Inspection, maintenance and operation of electrical transformers to improve reliability and performance.'],
        ['02', '/images/home/ups.svg', 'UPS Systems', 'Supply, inspection and maintenance of UPS and uninterrupted power systems for critical loads.'],
        ['03', '/images/home/generator.svg', 'Generators', 'Generator maintenance, testing and operation for reliable standby power continuity.'],
        ['04', '/images/home/mv-switchgear.svg', 'MV Systems', 'Medium-voltage systems, switchgear, protection, testing and commissioning services.'],
        ['05', '/images/home/service-preventive.svg', 'Preventive Maintenance', 'Planned preventive maintenance programs that reduce failures and improve asset readiness.'],
        ['06', '/images/home/service-corrective.svg', 'Corrective / Emergency Maintenance', 'Responsive corrective and emergency maintenance to restore operation quickly and safely.'],
        ['07', '/images/home/service-inspection.svg', 'Inspection & Testing', 'Electrical equipment and system inspection, testing and clear technical reporting.'],
        ['08', '/images/home/service-contracts.svg', 'Maintenance Contracts', 'Structured maintenance contracts with service levels, schedules, tracking and reporting.'],
        ['09', '/images/home/service-industrial-electrical.svg', 'Industrial / Commercial Electrical Services', 'Specialist electrical services for industrial plants, commercial buildings and operating sites.'],
        ['10', '/images/home/service-asset-management.svg', 'Asset Management', 'Complete asset lifecycle, maintenance history, warranty and technical record management.'],
        ['11', '/images/home/service-hvac.svg', 'HVAC Systems', 'Inspection, maintenance and operation of HVAC systems to improve efficiency and reliability.'],
        ['12', '/images/home/service-mep.svg', 'MEP Services', 'Mechanical, electrical and plumbing systems maintenance and operations for buildings and facilities.'],
        ['13', '/images/home/service-facility-management.svg', 'Facility Management', 'Integrated facility operations, daily services, asset oversight and contractor performance management.'],
    ],
    'more' => 'Learn more',
    'all_services' => 'View All Services',
    'process_kicker' => 'HOW WE WORK',
    'process_title' => 'A clear process from start to finish',
    'process' => [
        ['01', 'Assessment', 'Understand the site, assets, risks and service requirements.'],
        ['02', 'Planning', 'Build the work plan, schedule, resources and service levels.'],
        ['03', 'Execution', 'Deliver the work and document readings, results and findings.'],
        ['04', 'Follow-up & Improvement', 'Report performance and continuously improve operations.'],
    ],
    'industries_title' => 'Industries we serve',
    'industries' => [
        ['/images/home/industry-photo-v14-00.webp', 'Commercial Buildings'],
        ['/images/home/industry-photo-v14-01.webp', 'Offices'],
        ['/images/home/industry-photo-v14-02.webp', 'Healthcare Facilities'],
        ['/images/home/industry-photo-v14-03.webp', 'Warehouses & Logistics'],
        ['/images/home/industry-photo-v14-04.webp', 'Industrial Facilities'],
        ['/images/home/industry-photo-v14-05.webp', 'Hospitality'],
        ['/images/home/industry-photo-v14-06.webp', 'Government'],
    ],
    'all_industries' => 'View All Industries',
    'maintenance_title' => 'From reactive maintenance to planned operations',
    'maintenance_text' => 'UNIFCO reduces emergency failures by planning, documenting and improving maintenance before problems interrupt your operation.',
    'maintenance_checks' => ['Preventive plans', 'Routine inspections', 'History and spare parts', 'Efficiency programs', 'Work order documentation', 'Continuous improvement'],
    'maintenance_button' => 'Explore Maintenance Services',
    'portal_title' => 'Manage every service in one place',
    'portal_text' => 'A connected client portal that makes every facility service easy to monitor.',
    'portal_checks' => ['Contract tracking', 'Asset management', 'Maintenance requests', 'Reports and payments', 'Upcoming maintenance', 'SLA performance'],
    'portal_button' => 'Client Portal Login',
    'why_title' => 'Why UNIFCO?',
    'why' => [
        ['layers', 'Integrated Solutions', 'All services and assets in one platform'],
        ['report', 'Clear Reporting', 'Accurate reports that build visibility and trust'],
        ['clock', 'Fast Response', 'Structured handling for failures and emergencies'],
        ['team', 'Qualified Teams', 'Experienced engineers and skilled technicians'],
        ['settings', 'Smart Prevention', 'Maintenance plans focused on avoiding failures'],
        ['target', 'One Experience', 'A complete solution from one accountable partner'],
    ],
    'projects_title' => 'Our work in action',
    'projects_button' => 'View All Projects',
    'emergency_title' => 'Need urgent support?',
    'emergency_text' => 'If a failure is affecting operations, send an emergency maintenance request for immediate routing.',
    'emergency_button' => 'Emergency Maintenance',
    'emergency_contact' => '24/7 operations support · Send your urgent request directly',
    'final_title' => 'Your facility deserves better management',
    'final_text' => 'Let UNIFCO manage operations and maintenance while you focus on your business.',
    'quote' => 'Request a Quote',
    'contact' => 'Talk to Us',
    'footer_about' => 'Integrated electrical power, maintenance, facility and asset management through one connected service experience.',
    'company' => 'Company',
    'services_label' => 'Services',
    'contact_label' => 'Contact',
    'footer_contact' => ['24/7 operations support', 'Service requests and urgent response', 'Saudi Arabia'],
];
@endphp
@include('public.partials.home-reference-layout', ['home' => $home])
