<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#132137">
<title>UNIFCO | مؤسسة وحدة المرافق للمقاولات</title>
<style>
:root{font-family:Tahoma,Arial,sans-serif;--navy:#1e315b;--dark:#132137;--red:#ce122d;--light:#f7f9fc;--muted:#68758a;--line:#e4e9f1;--surface:#fff;--shadow:0 18px 45px rgba(19,33,55,.09)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--dark);background:#fff}a{text-decoration:none;color:inherit}img{max-width:100%}.wrap{width:min(1240px,92%);margin:auto}
.top{background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:50;backdrop-filter:blur(12px)}.nav{display:flex;align-items:center;gap:18px;min-height:82px}.logo{width:122px;height:64px;object-fit:contain;margin-left:auto}.nav-links{display:flex;align-items:center;gap:18px}.nav-link{font-size:14px;font-weight:700;color:#47566d}.nav-link:hover{color:var(--red)}.nav-actions{display:flex;align-items:center;gap:8px}.btn{display:inline-flex;justify-content:center;align-items:center;min-height:44px;padding:11px 17px;border-radius:10px;background:var(--navy);color:#fff;font-weight:800;border:1px solid transparent;transition:.18s ease}.btn:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(30,49,91,.16)}.btn.red{background:var(--red)}.btn.light{background:#fff;color:var(--navy);border-color:#dce3ec}.menu-toggle{display:none;border:0;background:var(--navy);color:#fff;width:44px;height:44px;border-radius:10px;font-size:22px;cursor:pointer}
.mobile-menu{display:none;padding:0 0 14px}.mobile-menu.open{display:grid;gap:8px}.mobile-menu a{padding:12px 14px;background:#f7f9fc;border-radius:9px;font-weight:700;color:var(--navy)}
.hero{position:relative;overflow:hidden;padding:86px 0 64px;background:radial-gradient(circle at 10% 10%,rgba(206,18,45,.08),transparent 28%),linear-gradient(135deg,#fff 0%,#f8fafc 62%,#eef3f9 100%)}.hero:after{content:"";position:absolute;left:-120px;bottom:-160px;width:360px;height:360px;border-radius:50%;background:rgba(30,49,91,.06)}.hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1.15fr .85fr;gap:58px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--red);font-size:13px;font-weight:900;letter-spacing:.05em}.eyebrow:before{content:"";width:34px;height:3px;border-radius:999px;background:var(--red)}.hero h1{font-size:clamp(38px,4.8vw,62px);line-height:1.2;color:var(--navy);margin:16px 0 18px;letter-spacing:-.02em}.hero p,.lead{color:#5e6d82;line-height:1.95}.hero p{font-size:18px;max-width:720px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:26px}.hero-visual{background:#fff;border:1px solid rgba(30,49,91,.08);border-radius:28px;padding:28px;box-shadow:var(--shadow);position:relative}.hero-logo{width:100%;height:330px;object-fit:contain}.visual-badge{position:absolute;right:18px;bottom:18px;background:var(--dark);color:#fff;padding:10px 13px;border-radius:12px;font-size:12px;font-weight:800;box-shadow:0 10px 24px rgba(19,33,55,.2)}
.trust-strip{position:relative;z-index:2;margin-top:-18px}.trust-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;background:#fff;border:1px solid var(--line);border-radius:18px;padding:12px;box-shadow:0 16px 35px rgba(19,33,55,.08)}.trust-item{padding:14px 16px;border-left:1px solid #edf1f6}.trust-item:last-child{border-left:0}.trust-item strong{display:block;color:var(--navy);font-size:17px;margin-bottom:5px}.trust-item span{color:var(--muted);font-size:12px;line-height:1.6}
.section{padding:74px 0}.section-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:28px}.section-head>div{max-width:780px}.kicker{color:var(--red);font-size:13px;font-weight:900;margin-bottom:8px}h2{color:var(--navy);font-size:clamp(28px,3vw,38px);margin:0 0 12px}.alt{background:var(--light)}.about-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:stretch}.about-panel{background:linear-gradient(145deg,var(--dark),var(--navy));color:#fff;border-radius:20px;padding:26px;display:grid;gap:14px}.about-panel strong{font-size:26px}.about-panel p{margin:0;color:#d8e0eb;line-height:1.8}.about-points{display:grid;grid-template-columns:1fr 1fr;gap:12px}.point{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px}.point b{display:block;color:var(--navy);margin-bottom:6px}.point span{font-size:13px;color:var(--muted);line-height:1.7}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:24px;border:1px solid var(--line);border-radius:16px;background:#fff;transition:.18s ease}.card:hover{transform:translateY(-3px);box-shadow:0 14px 30px rgba(19,33,55,.08);border-color:#d6deea}.service-no{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border-radius:10px;background:#eef3fa;color:var(--navy);font-weight:900;margin-bottom:14px}.card b{color:var(--navy);display:block;margin-bottom:8px;font-size:17px}.card p{color:#68758a;line-height:1.75;margin:0}
.process{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.step{position:relative;background:#fff;border:1px solid var(--line);border-radius:15px;padding:20px}.step-num{display:inline-flex;width:34px;height:34px;border-radius:50%;align-items:center;justify-content:center;background:var(--red);color:#fff;font-weight:900;margin-bottom:12px}.step b{display:block;color:var(--navy);margin-bottom:6px}.step p{margin:0;color:var(--muted);font-size:13px;line-height:1.7}
.cta{padding:38px;border-radius:22px;background:linear-gradient(135deg,var(--dark),var(--navy));color:#fff;display:flex;justify-content:space-between;align-items:center;gap:26px;box-shadow:0 18px 40px rgba(19,33,55,.18)}.cta h2{color:#fff}.cta p{color:#d6dfeb;max-width:720px;line-height:1.8}.footer{background:#0f1a2b;color:#cbd5e1;padding:32px 0}.foot{display:flex;justify-content:space-between;gap:18px;align-items:center}.foot-brand{display:flex;align-items:center;gap:14px}.foot-logo{width:82px;height:48px;object-fit:contain;background:#fff;border-radius:8px;padding:5px}.foot small{display:block;color:#8ea0b8;margin-top:4px}
@media(max-width:1050px){.nav-links{display:none}.menu-toggle{display:inline-flex;align-items:center;justify-content:center}.hero-grid,.about-grid{grid-template-columns:1fr}.hero-visual{max-width:680px;margin:auto;width:100%}.trust-grid{grid-template-columns:repeat(2,1fr)}.trust-item{border-left:0}.cards{grid-template-columns:repeat(2,1fr)}.process{grid-template-columns:repeat(2,1fr)}}
@media(max-width:720px){.wrap{width:min(94%,680px)}.nav{min-height:70px;gap:10px}.logo{width:100px;height:52px}.nav-actions .btn:not(.red){display:none}.nav-actions .btn{padding:9px 12px;font-size:12px;min-height:40px}.hero{padding:54px 0 44px}.hero-grid{gap:30px}.hero h1{font-size:36px}.hero p{font-size:16px}.hero-visual{padding:18px;border-radius:20px}.hero-logo{height:230px}.visual-badge{position:static;margin-top:10px;text-align:center}.trust-strip{margin-top:0;padding-top:14px}.trust-grid{grid-template-columns:1fr 1fr}.section{padding:54px 0}.section-head{align-items:flex-start;flex-direction:column}.about-points,.cards,.process{grid-template-columns:1fr}.cta{padding:26px;align-items:flex-start;flex-direction:column}.cta .actions,.cta .btn{width:100%}.foot{align-items:flex-start;flex-direction:column}}
@media(max-width:460px){.nav-actions .btn.red{display:none}.hero h1{font-size:31px}.actions{display:grid;grid-template-columns:1fr}.actions .btn{width:100%}.trust-grid{grid-template-columns:1fr}.trust-item{text-align:center}.hero-logo{height:190px}.foot-brand{align-items:flex-start}.section{padding:46px 0}.card,.point,.step{padding:17px}}
</style>
</head>
<body>
<header class="top">
  <div class="wrap nav">
    <img class="logo" src="{{ route('brand.logo') }}" alt="UNIFCO">
    <nav class="nav-links" aria-label="التنقل الرئيسي"><a class="nav-link" href="#about">عن الشركة</a><a class="nav-link" href="#services">خدماتنا</a><a class="nav-link" href="#process">كيف نعمل</a></nav>
    <div class="nav-actions"><a class="btn red" href="{{ route('public.quote') }}">طلب عرض سعر</a><a class="btn" href="{{ route('public.emergency') }}">صيانة طارئة</a><a class="btn light" href="{{ route('login') }}">تسجيل الدخول</a></div>
    <button class="menu-toggle" id="menu-toggle" aria-label="فتح القائمة" aria-expanded="false">☰</button>
  </div>
  <div class="wrap mobile-menu" id="mobile-menu"><a href="#about">عن الشركة</a><a href="#services">خدماتنا</a><a href="#process">كيف نعمل</a><a href="{{ route('public.quote') }}">طلب عرض سعر</a><a href="{{ route('public.emergency') }}">صيانة طارئة</a><a href="{{ route('login') }}">تسجيل الدخول</a></div>
</header>
<main>
<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">UNIFCO · ONE FACILITY SHOP</div><h1>حلول متكاملة للمرافق والمشاريع والتشغيل والصيانة</h1><p>مؤسسة وحدة المرافق للمقاولات تقدم إدارة المرافق المتكاملة والمشاريع الكهربائية والميكانيكية وأعمال التشغيل والصيانة، مع خبرة في المولدات الكهربائية ولوحات التحويل ATS والاختبارات والتشغيل.</p><div class="actions"><a class="btn red" href="{{ route('public.quote') }}">اطلب عرض سعر</a><a class="btn" href="{{ route('public.emergency') }}">طلب صيانة طارئة</a><a class="btn light" href="#services">استعرض الخدمات</a></div></div><div class="hero-visual"><img class="hero-logo" src="{{ route('brand.logo') }}" alt="شعار UNIFCO"><div class="visual-badge">Integrated Facilities · MEP · Power Systems</div></div></div></section>
<section class="trust-strip"><div class="wrap"><div class="trust-grid"><div class="trust-item"><strong>إدارة مرافق متكاملة</strong><span>تشغيل وصيانة الأنظمة والمرافق تحت مظلة واحدة.</span></div><div class="trust-item"><strong>MEP Projects</strong><span>أعمال كهربائية وميكانيكية واختبارات وتشغيل.</span></div><div class="trust-item"><strong>مولدات وATS</strong><span>حلول الطاقة الاحتياطية والتشغيل والصيانة.</span></div><div class="trust-item"><strong>استجابة للطوارئ</strong><span>مسار مباشر لاستقبال طلبات الصيانة العاجلة.</span></div></div></div></section>
<section id="about" class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">عن UNIFCO</div><h2>شريك تشغيلي وهندسي للمرافق</h2><p class="lead">نخدم الجهات والمنشآت عبر تنفيذ وإدارة الأعمال الكهربائية والميكانيكية والتشغيل والصيانة وفق متطلبات الجودة والمواصفات الفنية والممارسات الهندسية المعتمدة.</p></div></div><div class="about-grid"><div class="about-panel"><strong>One Facility Shop</strong><p>واجهة موحدة لخدمات المرافق والصيانة والمشاريع الفنية، من استقبال الطلب وحتى التنفيذ والمتابعة.</p><p>نركز على الجاهزية، وضوح دورة العمل، وسرعة الوصول للخدمة المناسبة.</p></div><div class="about-points"><div class="point"><b>صيانة وقائية</b><span>خطط دورية تساعد على تقليل الأعطال ورفع الجاهزية.</span></div><div class="point"><b>صيانة تصحيحية</b><span>معالجة الأعطال وإعادة الأنظمة إلى الخدمة بكفاءة.</span></div><div class="point"><b>اختبارات وتشغيل</b><span>تحقق فني قبل التسليم والتشغيل الفعلي للأنظمة.</span></div><div class="point"><b>متابعة رقمية</b><span>طلبات وعروض أسعار وخدمات طارئة عبر المنصة.</span></div></div></div></div></section>
<section id="services" class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">خدماتنا</div><h2>تغطية متكاملة للأعمال الفنية والتشغيلية</h2><p class="lead">خدمات مصممة لدعم دورة حياة المرفق من التنفيذ الأولي وحتى التشغيل والصيانة المستمرة.</p></div></div><div class="cards"><div class="card"><span class="service-no">01</span><b>إدارة المرافق المتكاملة</b><p>تشغيل وصيانة المرافق والأنظمة المرتبطة بها.</p></div><div class="card"><span class="service-no">02</span><b>المشاريع الكهربائية والميكانيكية</b><p>تنفيذ الأعمال والتركيبات والاختبارات والتشغيل.</p></div><div class="card"><span class="service-no">03</span><b>المولدات الكهربائية وATS</b><p>تشغيل وصيانة وإصلاح أنظمة الطاقة الاحتياطية ولوحات التحويل.</p></div><div class="card"><span class="service-no">04</span><b>الصيانة الوقائية</b><p>برامج صيانة دورية للحفاظ على الجاهزية.</p></div><div class="card"><span class="service-no">05</span><b>الصيانة التصحيحية والطوارئ</b><p>معالجة الأعطال واستعادة التشغيل بأسرع مسار ممكن.</p></div><div class="card"><span class="service-no">06</span><b>الاختبارات والتشغيل النهائي</b><p>التحقق من أداء الأنظمة قبل التسليم والتشغيل.</p></div></div></div></section>
<section id="process" class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">كيف نعمل</div><h2>من الطلب إلى التنفيذ في مسار واضح</h2></div></div><div class="process"><div class="step"><span class="step-num">1</span><b>أرسل الطلب</b><p>اختر عرض سعر أو صيانة طارئة وشارك تفاصيل الاحتياج.</p></div><div class="step"><span class="step-num">2</span><b>مراجعة فنية</b><p>يتم تصنيف الطلب وتحديد نوع الخدمة والمسار المناسب.</p></div><div class="step"><span class="step-num">3</span><b>التنفيذ والمتابعة</b><p>تتم متابعة التنفيذ وحالة الطلب ضمن دورة العمل التشغيلية.</p></div><div class="step"><span class="step-num">4</span><b>إغلاق موثق</b><p>توثيق النتائج والمرفقات والتقارير حسب نوع الخدمة.</p></div></div></div></section>
<section class="section"><div class="wrap"><div class="cta"><div><h2>هل لديك مشروع أو عطل طارئ؟</h2><p>أرسل طلبك بدون تسجيل. في النهاية نطلب فقط البريد الإلكتروني، الجوال، اسم الشركة والسجل التجاري.</p></div><div class="actions"><a class="btn red" href="{{ route('public.quote') }}">طلب عرض سعر</a><a class="btn light" href="{{ route('public.emergency') }}">صيانة طارئة</a></div></div></div></section>
</main>
<footer class="footer"><div class="wrap foot"><div class="foot-brand"><img class="foot-logo" src="{{ route('brand.logo') }}" alt="UNIFCO"><div>UNIFCO · مؤسسة وحدة المرافق للمقاولات<small>C.R 1010823937 · One Facility Shop</small></div></div><a href="{{ route('login') }}">بوابة الدخول</a></div></footer>
<script>(function(){const b=document.getElementById('menu-toggle'),m=document.getElementById('mobile-menu');if(!b||!m)return;b.addEventListener('click',()=>{const open=m.classList.toggle('open');b.setAttribute('aria-expanded',open?'true':'false');b.textContent=open?'×':'☰'});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('open');b.setAttribute('aria-expanded','false');b.textContent='☰'}));})();</script>
</body></html>
