<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>UNIFCO | مؤسسة وحدة المرافق للمقاولات</title>
<style>
:root{font-family:Tahoma,Arial,sans-serif;--navy:#1e315b;--dark:#132137;--red:#ce122d;--light:#f8f9fb;--muted:#68758a}*{box-sizing:border-box}body{margin:0;color:var(--dark)}a{text-decoration:none;color:inherit}.wrap{width:min(1160px,92%);margin:auto}.top{background:#fff;border-bottom:1px solid #e8ecf2;position:sticky;top:0;z-index:10}.nav{display:flex;align-items:center;gap:20px;min-height:76px}.logo{width:112px;height:58px;object-fit:contain;margin-left:auto}.nav a{font-size:14px}.btn{padding:11px 17px;border-radius:9px;background:var(--navy);color:#fff;font-weight:700}.btn.red{background:var(--red)}.hero{padding:72px 0;background:linear-gradient(135deg,#fff,#f8f9fb)}.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:45px;align-items:center}.hero h1{font-size:46px;line-height:1.3;color:var(--navy);margin:10px 0 18px}.hero p,.lead{color:#5f6c80;line-height:1.9}.hero-logo{width:100%;height:370px;object-fit:contain}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.section{padding:64px 0}.alt{background:var(--light)}h2{color:var(--navy);font-size:32px;margin:0 0 12px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:28px}.card{padding:22px;border:1px solid #e3e8ef;border-radius:14px;background:#fff}.card b{color:var(--navy);display:block;margin-bottom:8px}.card p{color:#68758a;line-height:1.7;margin:0}.cta{padding:34px;border-radius:18px;background:var(--dark);color:#fff;display:flex;justify-content:space-between;align-items:center;gap:20px}.cta p{color:#cbd5e1}.footer{background:#0f1a2b;color:#cbd5e1;padding:28px 0}.foot{display:flex;justify-content:space-between;gap:16px;align-items:center}@media(max-width:850px){.nav a:not(.btn){display:none}.hero-grid,.cards{grid-template-columns:1fr}.hero h1{font-size:34px}.hero-logo{height:250px}.cta,.foot{flex-direction:column;align-items:flex-start}}
</style>
</head>
<body>
<header class="top"><div class="wrap nav"><img class="logo" src="{{ route('brand.logo') }}" alt="UNIFCO"><a href="#about">عن الشركة</a><a href="#services">خدماتنا</a><a class="btn red" href="{{ route('public.quote') }}">طلب عرض سعر</a><a class="btn" href="{{ route('public.emergency') }}">صيانة طارئة</a><a class="btn" href="{{ route('login') }}">تسجيل الدخول</a></div></header>
<main>
<section class="hero"><div class="wrap hero-grid"><div><strong style="color:var(--red)">UNIFCO · ONE FACILITY SHOP</strong><h1>حلول متكاملة للمرافق والمشاريع والتشغيل والصيانة</h1><p>مؤسسة وحدة المرافق للمقاولات تقدم إدارة المرافق المتكاملة والمشاريع الكهربائية والميكانيكية وأعمال التشغيل والصيانة، مع خبرة في المولدات الكهربائية ولوحات التحويل ATS والاختبارات والتشغيل.</p><div class="actions"><a class="btn red" href="{{ route('public.quote') }}">اطلب عرض سعر</a><a class="btn" href="{{ route('public.emergency') }}">طلب صيانة طارئة</a></div></div><img class="hero-logo" src="{{ route('brand.logo') }}" alt="شعار UNIFCO"></div></section>
<section id="about" class="section"><div class="wrap"><h2>عن UNIFCO</h2><p class="lead">نخدم الجهات والمنشآت عبر تنفيذ وإدارة الأعمال الكهربائية والميكانيكية والتشغيل والصيانة وفق متطلبات الجودة والمواصفات الفنية والممارسات الهندسية المعتمدة.</p></div></section>
<section id="services" class="section alt"><div class="wrap"><h2>خدماتنا</h2><div class="cards"><div class="card"><b>إدارة المرافق المتكاملة</b><p>تشغيل وصيانة المرافق والأنظمة المرتبطة بها.</p></div><div class="card"><b>المشاريع الكهربائية والميكانيكية</b><p>تنفيذ الأعمال والتركيبات والاختبارات والتشغيل.</p></div><div class="card"><b>المولدات الكهربائية وATS</b><p>تشغيل وصيانة وإصلاح أنظمة الطاقة الاحتياطية ولوحات التحويل.</p></div><div class="card"><b>الصيانة الوقائية</b><p>برامج صيانة دورية للحفاظ على الجاهزية.</p></div><div class="card"><b>الصيانة التصحيحية والطوارئ</b><p>معالجة الأعطال واستعادة التشغيل بأسرع مسار ممكن.</p></div><div class="card"><b>الاختبارات والتشغيل النهائي</b><p>التحقق من أداء الأنظمة قبل التسليم والتشغيل.</p></div></div></div></section>
<section class="section"><div class="wrap"><div class="cta"><div><h2 style="color:#fff">هل لديك مشروع أو عطل طارئ؟</h2><p>أرسل طلبك بدون تسجيل. في النهاية نطلب فقط البريد الإلكتروني، الجوال، اسم الشركة والسجل التجاري.</p></div><div class="actions"><a class="btn red" href="{{ route('public.quote') }}">طلب عرض سعر</a><a class="btn" href="{{ route('public.emergency') }}">صيانة طارئة</a></div></div></div></section>
</main>
<footer class="footer"><div class="wrap foot"><div>UNIFCO · مؤسسة وحدة المرافق للمقاولات · C.R 1010823937</div><a href="{{ route('login') }}">بوابة الدخول</a></div></footer>
</body></html>
