@include('customer.partials.portal-shell-open', [
    'activeSection' => 'requests',
    'pageTitle' => $serviceRequest->request_no,
    'pageDescription' => 'Request 360 · Complete customer service record',
])

@push('late-styles')
<style>
    .request-hero{background:linear-gradient(135deg,#102d5c,#183b76);color:#fff;border-radius:14px;padding:20px;display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center}.request-hero small{font-size:9px;color:#b8c8dc;text-transform:uppercase;letter-spacing:.08em}.request-hero h2{font-size:24px;margin:6px 0}.request-hero p{margin:0;color:#dbe5f1;font-size:11px}.request-badges{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.request-badges .portal-pill{background:#ffffff18;color:#fff;border:1px solid #ffffff22}.request-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:12px}.request-stack{display:grid;gap:12px}.request-details{white-space:pre-wrap;line-height:1.75;font-size:11px;color:#34445d}.stage-card{border-inline-start:4px solid var(--red)}.stage-value{font-size:19px;font-weight:900;margin:5px 0 8px}.next-action{padding:11px;border-radius:9px;background:#f3f7fc;font-size:10px;line-height:1.6}.timeline-event{position:relative;padding:0 0 16px 25px}.timeline-event:before{content:"";position:absolute;inset-inline-start:6px;top:5px;width:9px;height:9px;border-radius:50%;background:#1f5b9d}.timeline-event:after{content:"";position:absolute;inset-inline-start:10px;top:14px;bottom:0;width:1px;background:#d9e2ed}.timeline-event:last-child:after{display:none}.timeline-event b{font-size:10px}.timeline-event p{font-size:9px;color:var(--muted);margin:4px 0}.timeline-event time{font-size:8px;color:#8d99aa}.request-attachment{display:flex;justify-content:space-between;gap:10px;padding:10px;border:1px solid #edf1f5;border-radius:8px;font-size:9px}.accept-card{border-color:#f0d79d;background:#fffaf0}.accept-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.accept-grid form{padding:12px;border:1px solid #eadfc8;border-radius:9px;background:#fff}.accept-grid textarea{width:100%;min-height:75px;border:1px solid #d9e1ea;border-radius:7px;padding:9px;margin:8px 0}.relationship-links{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.relationship-link{padding:12px;border:1px solid #e3e9f1;border-radius:9px;background:#f8fafc}.relationship-link small{display:block;font-size:8px;color:var(--muted);margin-bottom:4px}.relationship-link b{font-size:10px;color:var(--blue)}@media(max-width:950px){.request-grid{grid-template-columns:1fr}}@media(max-width:600px){.request-hero{grid-template-columns:1fr}.request-badges{justify-content:flex-start}.accept-grid,.relationship-links{grid-template-columns:1fr}}
</style>
@endpush

@php
    $labels=['OPEN'=>'Open · مفتوح','COMPLETED'=>'Completed · مكتمل','CLOSED'=>'Closed · مغلق','NORMAL'=>'Normal · عادية','HIGH'=>'High · مرتفعة','EMERGENCY'=>'Emergency · طارئة','MAINTENANCE'=>'Maintenance · صيانة','QUOTATION'=>'Quotation · عرض سعر','CONSULTATION'=>'Consultation · استشارة','TRIAGE'=>'Triage · فرز الطلب','SALES_REVIEW'=>'Sales Review · مراجعة المبيعات','TECHNICAL_REVIEW'=>'Technical Review · مراجعة فنية','OPERATIONS_REVIEW'=>'Operations Review · مراجعة العمليات','EMERGENCY_DISPATCH'=>'Emergency Dispatch · توجيه طارئ','IN_PROGRESS'=>'In Progress · جاري التنفيذ','CUSTOMER_ACCEPTANCE'=>'Customer Acceptance · اعتماد العميل'];
    $label=fn($value)=>$labels[strtoupper((string)$value)]??str_replace('_',' ',(string)$value?:'—');
@endphp

<div class="portal-page-head"><div><h2>Request 360</h2><p>Complete request, execution, relationships, attachments and customer actions.</p></div><a class="portal-btn soft" href="{{ route('customer.service-requests.index') }}">← Back to Service Requests</a></div>
<section class="request-hero"><div><small>Customer Request 360</small><h2>{{ $serviceRequest->request_no }}</h2><p>{{ $serviceRequest->subject ?: $serviceRequest->service_category ?: 'Service Request' }}</p></div><div class="request-badges"><span class="portal-pill">{{ $label($serviceRequest->request_type) }}</span><span class="portal-pill {{ $serviceRequest->priority==='EMERGENCY'?'red':'' }}">{{ $label($serviceRequest->priority) }}</span><span class="portal-pill green">{{ $label($serviceRequest->status) }}</span></div></section>

<div class="request-grid"><div class="request-stack">
    <section class="portal-card portal-panel"><h3>Request Summary · ملخص الطلب</h3><div class="portal-kv"><div><small>Request Type</small><strong>{{ $label($serviceRequest->request_type) }}</strong></div><div><small>Service Category</small><strong>{{ $label($serviceRequest->service_category) }}</strong></div><div><small>Created</small><strong>{{ $serviceRequest->created_at?->format('Y-m-d H:i') ?: '—' }}</strong></div><div><small>Last Update</small><strong>{{ $serviceRequest->updated_at?->format('Y-m-d H:i') ?: '—' }}</strong></div><div><small>Assigned Department</small><strong>{{ $label($serviceRequest->assigned_department) }}</strong></div><div><small>Approval State</small><strong>{{ $label($serviceRequest->approval_state) }}</strong></div><div style="grid-column:1/-1"><small>Issue / Request Details</small><div class="request-details">{{ $serviceRequest->details ?: 'No additional details recorded.' }}</div></div></div></section>
    <section class="portal-card portal-panel"><h3>Site, Asset & Contract · الموقع والأصل والعقد</h3><div class="portal-kv"><div><small>Site</small><strong>{{ $site?->name ?: ($serviceRequest->site_city ?: '—') }}</strong></div><div><small>City</small><strong>{{ $serviceRequest->site_city ?: '—' }}</strong></div><div><small>Asset</small><strong>{{ $asset ? (($asset->asset_code ?: '').' · '.$asset->name) : 'Not linked' }}</strong></div><div><small>Contract</small><strong>{{ $contract ? (($contract->contract_no ?: '').' · '.$contract->title) : 'Not linked' }}</strong></div><div><small>Eligibility</small><strong>{{ $label($serviceRequest->eligibility) }}</strong></div><div><small>Work Order</small><strong>{{ $workOrder?->work_order_no ?: 'Not created yet' }}</strong></div></div></section>
    <section class="portal-card portal-panel"><h3>Related Records · السجلات المرتبطة</h3><div class="relationship-links"><a class="relationship-link" href="{{ $asset ? route('customer.asset.show',$asset) : '#' }}"><small>Asset 360</small><b>{{ $asset?->asset_code ?: 'Not linked' }}</b></a><a class="relationship-link" href="{{ $workOrder ? route('customer.work-orders.show',$workOrder) : '#' }}"><small>Service Report</small><b>{{ $workOrder?->work_order_no ?: 'Not created' }}</b></a><a class="relationship-link" href="{{ route('customer.section','contracts') }}"><small>Contract</small><b>{{ $contract?->contract_no ?: 'Not linked' }}</b></a></div></section>
    @if($canAccept)<section class="portal-card portal-panel accept-card"><h3>Action Required · Customer Acceptance</h3><p style="font-size:10px;color:#74654b">Review the completed work and accept it or request rework.</p><div class="accept-grid"><form method="POST" action="{{ route('customer.work-acceptance.decide',$workOrder) }}">@csrf<input type="hidden" name="decision" value="ACCEPT"><b style="font-size:10px">Accept completed work</b><textarea name="notes" placeholder="Optional acceptance notes"></textarea><button class="portal-btn green">Accept Work</button></form><form method="POST" action="{{ route('customer.work-acceptance.decide',$workOrder) }}">@csrf<input type="hidden" name="decision" value="REJECT"><b style="font-size:10px">Reject and request rework</b><textarea name="notes" required placeholder="Describe what needs correction"></textarea><button class="portal-btn red">Request Rework</button></form></div></section>@endif
    <section class="portal-card portal-panel"><h3>Attachments · المرفقات</h3><div style="display:grid;gap:8px">@forelse($attachments as $attachment)<div class="request-attachment"><div><b>{{ $attachment->original_name }}</b><div style="color:var(--muted);margin-top:3px">{{ $label($attachment->attachment_type) }} · {{ number_format(((int)$attachment->size_bytes)/1024,1) }} KB</div></div><a class="portal-btn soft" href="{{ route('customer.attachments.download',$attachment->id) }}">Download</a></div>@empty<div class="portal-empty"><strong>No customer-visible attachments</strong>Evidence and reports will appear here when linked.</div>@endforelse</div></section>
</div><div class="request-stack">
    <section class="portal-card portal-panel stage-card"><h3>Workflow Status · حالة سير العمل</h3><small style="font-size:8px;color:var(--muted)">CURRENT STAGE</small><div class="stage-value">{{ $label($serviceRequest->workflow_stage) }}</div><div class="next-action"><b>Next action · الإجراء التالي</b><br>{{ $label($serviceRequest->next_action ?: 'UNIFCO is processing this request') }}</div>@if($serviceRequest->current_stage_due_at)<div style="margin-top:10px;font-size:9px;color:var(--muted)">Stage due: <b>{{ $serviceRequest->current_stage_due_at->format('Y-m-d H:i') }}</b></div>@endif</section>
    <section class="portal-card portal-panel"><h3>Workflow Timeline · مسار الطلب</h3>@forelse($events as $event)<div class="timeline-event"><b>{{ $event->title ?: $label($event->event_type) }}</b>@if($event->description)<p>{{ $event->description }}</p>@endif<time>{{ $event->created_at?->format('Y-m-d H:i') }}</time></div>@empty<div class="portal-empty"><strong>No timeline events yet</strong>The current stage above remains authoritative.</div>@endforelse</section>
    <section class="portal-card portal-panel"><h3>Request Reference · مرجع الطلب</h3><div class="portal-kv" style="grid-template-columns:1fr"><div><small>Request ID</small><strong>#{{ $serviceRequest->id }}</strong></div><div><small>Workflow Key</small><strong>{{ $label($serviceRequest->workflow_key) }}</strong></div><div><small>Last Updated</small><strong>{{ $serviceRequest->updated_at?->format('Y-m-d H:i:s') ?: '—' }}</strong></div></div></section>
</div></div>

@include('customer.partials.portal-shell-close')
