@extends('layouts.app')
@section('title',$candidate->name.' | Candidate 360')
@section('heading','Candidate 360')
@section('content')
<style>
.c-hero{background:linear-gradient(135deg,#101f38,#1e315b);color:#fff;border-radius:18px;padding:22px;margin-bottom:14px;display:flex;justify-content:space-between;gap:15px;align-items:center}.c-hero h1{margin:4px 0;font-size:23px}.c-hero small{font-size:9px;color:#b9c6d8}.c-hero p{margin:0;color:#dce5f2;font-size:11px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:15px}.card.wide{grid-column:1/-1}.card h3{font-size:13px;margin:0 0 10px}.facts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fact{background:#f7f9fc;border-radius:8px;padding:9px}.fact small{display:block;color:#7c899a;font-size:8px;text-transform:uppercase}.fact b{display:block;margin-top:3px;font-size:10px}.actions{display:flex;gap:6px;flex-wrap:wrap}.formgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.formgrid label{font-size:8px;color:#68768b}.formgrid input,.formgrid select,.formgrid textarea{width:100%}.rowx{display:grid;grid-template-columns:1.2fr .7fr .5fr auto;gap:8px;align-items:center;background:#f7f9fc;border-radius:8px;padding:9px;margin-top:6px;font-size:9px}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#1e315b;font-size:8px;font-weight:800}.ok{background:#17734b}.danger{background:#a51f35}@media(max-width:850px){.grid{grid-template-columns:1fr}.card.wide{grid-column:auto}.formgrid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.c-hero{display:block}.facts,.formgrid{grid-template-columns:1fr}.rowx{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="c-hero"><div><small>{{ $candidate->candidate_no }} · {{ $candidate->stage }}</small><h1>{{ $candidate->name }}</h1><p>{{ $candidate->vacancy?->vacancy_no }} · {{ $candidate->vacancy?->title }}</p></div><div class="actions"><a class="btn secondary" href="{{ route('hr.recruitment.index') }}">Back to Recruitment</a>@if($candidate->employee_id)<a class="btn" href="{{ route('hr.employees.show',$candidate->employee_id) }}">Employee 360</a>@endif</div></section>
<div class="grid">
<section class="card"><h3>Candidate Profile</h3><div class="facts"><div class="fact"><small>Email</small><b>{{ $candidate->email ?: '—' }}</b></div><div class="fact"><small>Mobile</small><b>{{ $candidate->mobile ?: '—' }}</b></div><div class="fact"><small>Nationality</small><b>{{ $candidate->nationality ?: '—' }}</b></div><div class="fact"><small>Source</small><b>{{ $candidate->source ?: '—' }}</b></div><div class="fact"><small>Expected Salary</small><b>{{ number_format((float)$candidate->expected_salary,2) }} SAR</b></div><div class="fact"><small>Job Position</small><b>{{ $candidate->vacancy?->requisition?->position?->title ?: '—' }}</b></div></div><h3 style="margin-top:14px">Pipeline Stage</h3>@if($candidate->stage!=='HIRED')<form method="POST" action="{{ route('hr.recruitment.candidates.stage',$candidate) }}" class="actions">@csrf<select name="stage">@foreach(['APPLIED','SCREENING','SHORTLISTED','INTERVIEW','OFFER','REJECTED','WITHDRAWN'] as $s)<option @selected($candidate->stage===$s)>{{ $s }}</option>@endforeach</select><button class="btn">Update Stage</button></form>@endif</section>
<section class="card"><h3>Employment Offer</h3>@if($candidate->offer)<div class="facts"><div class="fact"><small>Offer</small><b>{{ $candidate->offer->offer_no }}</b></div><div class="fact"><small>Status</small><b>{{ $candidate->offer->status }}</b></div><div class="fact"><small>Basic</small><b>{{ number_format((float)$candidate->offer->basic_salary,2) }}</b></div><div class="fact"><small>Housing</small><b>{{ number_format((float)$candidate->offer->housing_allowance,2) }}</b></div><div class="fact"><small>Start Date</small><b>{{ $candidate->offer->proposed_start_date?->format('d M Y') }}</b></div><div class="fact"><small>Probation</small><b>{{ $candidate->offer->probation_days }} days</b></div></div>@if(in_array($candidate->offer->status,['ISSUED','DRAFT']))<div class="actions" style="margin-top:10px"><form method="POST" action="{{ route('hr.recruitment.offers.decide',$candidate) }}">@csrf<input type="hidden" name="decision" value="ACCEPTED"><button class="btn ok">Accept Offer</button></form><form method="POST" action="{{ route('hr.recruitment.offers.decide',$candidate) }}">@csrf<input type="hidden" name="decision" value="DECLINED"><button class="btn danger">Decline</button></form></div>@endif @if($candidate->offer->status==='ACCEPTED' && !$candidate->employee_id)<form method="POST" action="{{ route('hr.recruitment.hire',$candidate) }}" style="margin-top:10px">@csrf<button class="btn">Hire & Create Employee</button></form>@endif @else<form method="POST" action="{{ route('hr.recruitment.offers.store',$candidate) }}">@csrf<div class="formgrid"><label>Basic Salary<input type="number" step="0.01" name="basic_salary" required></label><label>Housing<input type="number" step="0.01" name="housing_allowance"></label><label>Transport<input type="number" step="0.01" name="transport_allowance"></label><label>Other Allowances<input type="number" step="0.01" name="other_allowances"></label><label>Start Date<input type="date" name="proposed_start_date" required></label><label>Probation Days<input type="number" name="probation_days" value="90" min="0" max="180"></label></div><button class="btn" style="margin-top:8px">Issue Offer</button></form>@endif</section>
<section class="card wide"><h3>Interviews</h3>@if(!in_array($candidate->stage,['REJECTED','WITHDRAWN','HIRED']))<form method="POST" action="{{ route('hr.recruitment.interviews.store',$candidate) }}">@csrf<div class="formgrid"><label>Interview Type<select name="interview_type"><option>HR</option><option>TECHNICAL</option><option>MANAGER</option><option>FINAL</option></select></label><label>Scheduled At<input type="datetime-local" name="scheduled_at" required></label><label>Interviewer User ID<input type="number" name="interviewer_user_id"></label></div><button class="btn" style="margin-top:8px">Schedule Interview</button></form>@endif @forelse($candidate->interviews as $i)<div class="rowx"><span><b>{{ $i->interview_type }}</b><small>{{ $i->scheduled_at?->format('d M Y H:i') }} · {{ $i->interviewer?->name ?: 'Unassigned' }}</small></span><span class="pill">{{ $i->decision }}</span><span>{{ $i->score!==null?$i->score.'/100':'—' }}</span>@if($i->decision==='PENDING')<form method="POST" action="{{ route('hr.recruitment.interviews.decide',[$candidate,$i]) }}" class="actions">@csrf<input type="number" name="score" min="0" max="100" style="width:70px"><select name="decision"><option>PASS</option><option>HOLD</option><option>FAIL</option></select><button class="btn secondary">Record</button></form>@endif</div>@empty<div style="padding:14px;color:#7c899a">No interviews scheduled.</div>@endforelse</section>
@if($candidate->employee_id)<section class="card wide"><h3>Employee Onboarding Checklist</h3>@forelse($tasks as $task)<div class="rowx"><span><b>{{ $task->category }} · {{ $task->task_name }}</b><small>Due {{ $task->due_on?->format('d M Y') ?: '—' }}</small></span><span class="pill">{{ $task->status }}</span><span></span>@if($task->status!=='COMPLETED')<form method="POST" action="{{ route('hr.recruitment.onboarding.complete',$task) }}">@csrf<button class="btn secondary">Complete</button></form>@endif</div>@empty<div style="padding:14px;color:#7c899a">No onboarding tasks.</div>@endforelse</section>@endif
</div>
@endsection
