@extends('layouts.app')
@section('title','Recruitment | UNIFCO Platform')
@section('heading','Recruitment & Onboarding')
@section('content')
<style>
.r-hero{background:linear-gradient(135deg,#101f38,#1e315b 60%,#2b4679);color:#fff;border-radius:18px;padding:22px;margin-bottom:14px;display:flex;justify-content:space-between;align-items:center;gap:16px}.r-hero h1{margin:4px 0;font-size:24px}.r-hero small{font-size:9px;color:#b9c6d8;text-transform:uppercase;letter-spacing:.12em}.r-hero p{margin:0;color:#d8e1ee;font-size:11px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-bottom:14px}.kpi,.card{background:#fff;border:1px solid #e3e8ef;border-radius:13px}.kpi{padding:13px}.kpi small{display:block;color:#7a889c;font-size:8px;text-transform:uppercase;font-weight:800}.kpi b{display:block;font-size:22px;margin-top:4px;color:#16243b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{padding:15px}.card.wide{grid-column:1/-1}.card h3{font-size:13px;margin:0 0 10px}.formgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.formgrid label{font-size:8px;color:#68768b}.formgrid input,.formgrid select,.formgrid textarea{width:100%}.rows{display:grid;gap:6px}.rowx{display:grid;grid-template-columns:1.4fr .8fr .7fr auto;gap:8px;align-items:center;background:#f7f9fc;border-radius:8px;padding:9px;font-size:9px}.rowx b{display:block}.rowx small{color:#7e8a9c}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#1e315b;font-size:8px;font-weight:800}.pipeline{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.stage{background:#f7f9fc;border-radius:9px;padding:10px;text-align:center}.stage b{display:block;font-size:18px}.stage small{font-size:8px;color:#7c899a}@media(max-width:1000px){.kpis{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}.card.wide{grid-column:auto}.formgrid{grid-template-columns:1fr 1fr}.pipeline{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.r-hero{display:block}.kpis,.formgrid,.pipeline{grid-template-columns:1fr}.rowx{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="r-hero"><div><small>People / HR · Talent Acquisition</small><h1>Recruitment Command Center</h1><p>Manpower planning, vacancies, candidates, interviews, offers, hiring and employee onboarding in one workflow.</p></div><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a></section>
<div class="kpis"><div class="kpi"><small>Open Requisitions</small><b>{{ $stats['open_requisitions'] }}</b></div><div class="kpi"><small>Open Vacancies</small><b>{{ $stats['open_vacancies'] }}</b></div><div class="kpi"><small>Active Candidates</small><b>{{ $stats['active_candidates'] }}</b></div><div class="kpi"><small>Offers</small><b>{{ $stats['offers'] }}</b></div><div class="kpi"><small>Pending Onboarding</small><b>{{ $stats['pending_onboarding'] }}</b></div></div>
<div class="grid">
<section class="card"><h3>New Manpower Requisition</h3><form method="POST" action="{{ route('hr.recruitment.requisitions.store') }}">@csrf<div class="formgrid"><label>Title<input name="title" required></label><label>Job Position<select name="job_position_id"><option value="">Unassigned</option>@foreach($positions as $p)<option value="{{ $p->id }}">{{ $p->department }} · {{ $p->title }}</option>@endforeach</select></label><label>Department<input name="department"></label><label>Headcount<input type="number" name="headcount" value="1" min="1" required></label><label>Employment Type<select name="employment_type"><option>FULL_TIME</option><option>PART_TIME</option><option>TEMPORARY</option><option>CONTRACTOR</option></select></label><label>Work Location<input name="work_location"></label><label>Budget Min<input type="number" step="0.01" name="budget_min"></label><label>Budget Max<input type="number" step="0.01" name="budget_max"></label><label>Needed By<input type="date" name="needed_by"></label></div><label style="display:block;margin-top:8px;font-size:8px;color:#68768b">Justification<textarea name="justification" rows="2"></textarea></label><button class="btn" style="margin-top:8px">Submit Requisition</button></form></section>
<section class="card"><h3>Candidate Pipeline</h3>@php($stageCounts=$candidates->groupBy('stage')->map->count())<div class="pipeline">@foreach(['APPLIED','SCREENING','SHORTLISTED','INTERVIEW','OFFER','HIRED'] as $stage)<div class="stage"><b>{{ $stageCounts[$stage]??0 }}</b><small>{{ $stage }}</small></div>@endforeach</div><h3 style="margin-top:14px">Add Candidate</h3><form method="POST" action="{{ route('hr.recruitment.candidates.store') }}">@csrf<div class="formgrid"><label>Vacancy<select name="recruitment_vacancy_id" required><option value="">Select</option>@foreach($vacancies as $v)<option value="{{ $v->id }}">{{ $v->vacancy_no }} · {{ $v->title }}</option>@endforeach</select></label><label>Name<input name="name" required></label><label>Email<input type="email" name="email"></label><label>Mobile<input name="mobile"></label><label>Nationality<input name="nationality"></label><label>Source<input name="source" placeholder="LinkedIn / Referral / Agency"></label><label>Expected Salary<input type="number" step="0.01" name="expected_salary"></label></div><button class="btn" style="margin-top:8px">Add Candidate</button></form></section>
<section class="card wide"><h3>Manpower Requisitions & Vacancies</h3><div class="rows">@forelse($requisitions as $r)<div class="rowx"><span><b>{{ $r->requisition_no }} · {{ $r->title }}</b><small>{{ $r->department ?: 'No department' }} · {{ $r->headcount }} headcount · {{ $r->employment_type }}</small></span><span class="pill">{{ $r->status }}</span><span>{{ $r->vacancies->count() }} vacancy</span><span>@if($r->status==='PENDING_APPROVAL')<form method="POST" action="{{ route('hr.recruitment.requisitions.decide',$r) }}" style="display:inline">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn secondary">Approve</button></form>@endif @if($r->status==='APPROVED')<form method="POST" action="{{ route('hr.recruitment.vacancies.store',$r) }}" style="display:inline">@csrf<button class="btn secondary">Open Vacancy</button></form>@endif</span></div>@empty<div class="empty">No requisitions yet.</div>@endforelse</div></section>
<section class="card"><h3>Active Vacancies</h3><div class="rows">@forelse($vacancies as $v)<div class="rowx" style="grid-template-columns:1.4fr .6fr .5fr"><span><b>{{ $v->vacancy_no }}</b><small>{{ $v->title }}</small></span><span class="pill">{{ $v->status }}</span><b>{{ $v->candidates_count }} candidates</b></div>@empty<div class="empty">No open vacancies.</div>@endforelse</div></section>
<section class="card"><h3>Recent Candidates</h3><div class="rows">@forelse($candidates as $c)<div class="rowx" style="grid-template-columns:1.5fr .6fr auto"><span><b>{{ $c->candidate_no }} · {{ $c->name }}</b><small>{{ $c->vacancy?->title }}</small></span><span class="pill">{{ $c->stage }}</span><a class="btn secondary" href="{{ route('hr.recruitment.candidates.show',$c) }}">Candidate 360</a></div>@empty<div class="empty">No candidates.</div>@endforelse</div></section>
<section class="card wide"><h3>Pending Onboarding</h3><div class="rows">@forelse($onboarding as $t)<div class="rowx"><span><b>{{ $t->employee?->name }} · {{ $t->task_name }}</b><small>{{ $t->category }} · due {{ $t->due_on?->format('d M Y') ?: '—' }}</small></span><span class="pill">{{ $t->status }}</span><span></span><form method="POST" action="{{ route('hr.recruitment.onboarding.complete',$t) }}">@csrf<button class="btn secondary">Complete</button></form></div>@empty<div class="empty">No pending onboarding tasks.</div>@endforelse</div></section>
</div>
@endsection
