@extends('layouts.app')
@section('content')
@php($employeeMap=$employees->keyBy('id'))
@php($policyMap=$policies->keyBy('id'))
<style>
.lv-wrap{display:grid;gap:18px}.lv-hero{padding:24px;border-radius:20px;background:linear-gradient(135deg,#20375f,#325181);color:#fff;display:flex;justify-content:space-between;gap:18px;align-items:center}.lv-hero h1{margin:0 0 6px;font-size:26px}.lv-hero p{margin:0;color:#d2dced}.lv-hero a{color:#fff;text-decoration:none;border:1px solid #ffffff35;padding:9px 12px;border-radius:10px}.lv-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.lv-kpi,.lv-card{background:#fff;border:1px solid #e4e9f0;border-radius:16px;box-shadow:0 5px 18px #18243b0a}.lv-kpi{padding:16px}.lv-kpi small{display:block;color:#738198;text-transform:uppercase;font-size:10px;letter-spacing:.07em}.lv-kpi strong{font-size:26px;color:#20385e}.lv-grid{display:grid;grid-template-columns:1.45fr 1fr;gap:16px}.lv-card{padding:18px}.lv-card h2{font-size:16px;color:#20385e;margin:0 0 13px}.lv-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.lv-form label{font-size:11px;color:#66758d;display:grid;gap:5px}.lv-form input,.lv-form select,.lv-form textarea{border:1px solid #dce3ec;border-radius:9px;padding:9px;background:#fbfcfe}.lv-form .full{grid-column:1/-1}.lv-btn{border:0;background:#20385e;color:#fff;padding:9px 13px;border-radius:9px;font-weight:700}.lv-table{width:100%;border-collapse:collapse}.lv-table th{font-size:10px;text-transform:uppercase;color:#75839a;text-align:left;padding:9px;border-bottom:1px solid #e7ebf1}.lv-table td{padding:10px 9px;border-bottom:1px solid #eef2f6;font-size:12px}.pill{display:inline-block;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:700;background:#edf2f7}.pending{background:#fff4db;color:#916318}.approved{background:#e8f7ef;color:#157247}.rejected{background:#fdecef;color:#a12538}.balance{font-weight:800;color:#1b6f49}@media(max-width:900px){.lv-grid{grid-template-columns:1fr}.lv-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.lv-kpis,.lv-form{grid-template-columns:1fr}}
</style>
<div class="lv-wrap">
<section class="lv-hero"><div><small>PEOPLE / LEAVE</small><h1>Leave Management</h1><p>Policy-led leave balances, monthly accrual, carry-forward controls and approval workflow.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a href="{{ route('hr.dashboard') }}">HR Dashboard</a><a href="{{ route('hr.attendance.index') }}">Attendance & Time</a></div></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<section class="lv-kpis"><div class="lv-kpi"><small>Pending Approvals</small><strong>{{ $pending }}</strong></div><div class="lv-kpi"><small>Approved Days This Month</small><strong>{{ number_format($approvedThisMonth,1) }}</strong></div><div class="lv-kpi"><small>Available Balance Days</small><strong>{{ number_format($availableDays,1) }}</strong></div></section>
<section class="lv-grid">
<div class="lv-card"><h2>Leave Requests</h2><div style="overflow:auto"><table class="lv-table"><thead><tr><th>Employee</th><th>Policy</th><th>Dates</th><th>Days</th><th>Status</th><th>Decision</th></tr></thead><tbody>
@forelse($requests as $l)@php($emp=$employeeMap->get($l->employee_id))@php($policy=$policyMap->get($l->leave_policy_id))<tr><td><strong>{{ $emp?->employee_no ?? '#'.$l->employee_id }}</strong><br>{{ $emp?->name }}</td><td>{{ $policy?->name ?? $l->leave_type }}</td><td>{{ $l->starts_on->toDateString() }} → {{ $l->ends_on->toDateString() }}<br><small>{{ $l->day_portion }}</small></td><td>{{ $l->days }}</td><td><span class="pill {{ strtolower($l->status) }}">{{ $l->status }}</span></td><td>@if($l->status==='PENDING')<form method="POST" action="{{ route('hr.leave.decide',$l) }}" style="display:flex;gap:4px">@csrf<button class="lv-btn" name="decision" value="APPROVED">Approve</button><button class="lv-btn" name="decision" value="REJECTED" style="background:#8b3140">Reject</button></form>@else{{ $l->decision_notes ?: '—' }}@endif</td></tr>@empty<tr><td colspan="6">No leave requests yet.</td></tr>@endforelse
</tbody></table></div></div>
<div class="lv-card"><h2>Submit Leave Request</h2><form class="lv-form" method="POST" action="{{ route('hr.leave.store') }}">@csrf
<label class="full">Employee<select name="employee_id" required>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} — {{ $e->name }}</option>@endforeach</select></label>
<label class="full">Leave Policy<select name="leave_policy_id" required>@foreach($policies as $p)<option value="{{ $p->id }}">{{ $p->code }} — {{ $p->name }}</option>@endforeach</select></label>
<label>Starts<input type="date" name="starts_on" required></label><label>Ends<input type="date" name="ends_on" required></label>
<label>Days<input type="number" step="0.5" name="days" required></label><label>Portion<select name="day_portion"><option>FULL_DAY</option><option>HALF_DAY_AM</option><option>HALF_DAY_PM</option></select></label>
<label class="full">Reason<textarea name="reason" rows="2"></textarea></label><div class="full"><button class="lv-btn">Submit Request</button></div></form></div>
</section>
<section class="lv-grid">
<div class="lv-card"><h2>Employee Leave Balances — {{ $year }}</h2><div style="overflow:auto"><table class="lv-table"><thead><tr><th>Employee</th><th>Policy</th><th>Opening</th><th>Accrued</th><th>Used</th><th>Carry</th><th>Available</th><th>Accrue</th></tr></thead><tbody>
@forelse($balances as $b)@php($emp=$employeeMap->get($b->employee_id))@php($policy=$policyMap->get($b->leave_policy_id))<tr><td>{{ $emp?->employee_no }}<br>{{ $emp?->name }}</td><td>{{ $policy?->code ?? '#'.$b->leave_policy_id }}</td><td>{{ $b->opening_days }}</td><td>{{ $b->accrued_days }}</td><td>{{ $b->used_days }}</td><td>{{ $b->carried_forward_days }}</td><td class="balance">{{ number_format($b->availableDays(),2) }}</td><td>@if($policy?->accrual_method==='MONTHLY')<form method="POST" action="{{ route('hr.leave.balances.accrue',$b) }}">@csrf<input type="hidden" name="months" value="1"><button class="lv-btn">+ 1 month</button></form>@else—@endif</td></tr>@empty<tr><td colspan="8">Initialize employee leave balances below.</td></tr>@endforelse
</tbody></table></div></div>
<div class="lv-card"><h2>Initialize / Carry Forward Balance</h2><form class="lv-form" method="POST" action="{{ route('hr.leave.balances.store') }}">@csrf
<label class="full">Employee<select name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} — {{ $e->name }}</option>@endforeach</select></label>
<label class="full">Policy<select name="leave_policy_id">@foreach($policies as $p)<option value="{{ $p->id }}">{{ $p->code }} — {{ $p->name }}</option>@endforeach</select></label>
<label>Year<input type="number" name="balance_year" value="{{ $year }}"></label><label>Opening Days<input type="number" step="0.5" name="opening_days" value="0"></label><label>Carry Forward<input type="number" step="0.5" name="carried_forward_days" value="0"></label><div class="full"><button class="lv-btn">Save Balance</button></div></form></div>
</section>
<section class="lv-grid">
<div class="lv-card"><h2>Leave Policies</h2><table class="lv-table"><thead><tr><th>Code</th><th>Policy</th><th>Entitlement</th><th>Accrual</th><th>Carry Limit</th><th>Paid</th></tr></thead><tbody>@forelse($policies as $p)<tr><td>{{ $p->code }}</td><td><strong>{{ $p->name }}</strong><br>{{ $p->leave_type }}</td><td>{{ $p->annual_entitlement_days }} days</td><td>{{ $p->accrual_method }}</td><td>{{ $p->carry_forward_limit_days }}</td><td>{{ $p->paid?'Yes':'No' }}</td></tr>@empty<tr><td colspan="6">Create your first leave policy.</td></tr>@endforelse</tbody></table></div>
<div class="lv-card"><h2>Create Leave Policy</h2><form class="lv-form" method="POST" action="{{ route('hr.leave.policies.store') }}">@csrf
<label>Code<input name="code" placeholder="ANNUAL" required></label><label>Name<input name="name" placeholder="Annual Leave" required></label><label>Type<input name="leave_type" value="ANNUAL" required></label><label>Entitlement / Year<input type="number" step="0.5" name="annual_entitlement_days" value="21" required></label><label>Accrual<select name="accrual_method"><option>MONTHLY</option><option>ANNUAL</option><option>MANUAL</option></select></label><label>Carry Limit<input type="number" step="0.5" name="carry_forward_limit_days" value="0"></label><label><span><input type="checkbox" name="requires_approval" value="1" checked> Requires approval</span></label><label><span><input type="checkbox" name="paid" value="1" checked> Paid leave</span></label><div class="full"><button class="lv-btn">Create Policy</button></div></form></div>
</section>
</div>
@endsection
