@extends('layouts.app')
@section('title','Customer Asset Governance')
@section('heading','Customer Asset Governance')
@section('content')
<style>.card{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:16px;margin-bottom:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form{display:grid;grid-template-columns:1fr 1fr;gap:7px}.form input,.form select,.form textarea{padding:8px;border:1px solid #d7e0eb;border-radius:6px}.wide{grid-column:1/-1}.btn{border:0;border-radius:7px;background:#06275c;color:#fff;padding:8px 10px;font-weight:800}.row{padding:9px 0;border-bottom:1px solid #edf1f5}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#edf3fb;color:#285f99;font-size:10px;font-weight:800}.notice{background:#e9f7ef;color:#176940;padding:10px;border-radius:8px;margin-bottom:12px}.flow{font-family:ui-monospace,monospace;background:#f6f8fb;padding:12px;border-radius:8px}@media(max-width:800px){.grid,.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="card"><h3>Creation ≠ Approval</h3><p>Customer Admin: <b>New Asset → PENDING_VERIFICATION</b>. The asset never becomes ACTIVE directly. UNIFCO Maintenance Engineer creates/enriches assets; Maintenance Manager performs <b>Verify & Activate</b>.</p><p>Initial registration requires only <b>Customer + Site + Category + Asset Name</b>. Minimum Verification Data is enforced before ACTIVE.</p></div>
<div class="grid">
@if($isCustomer)
<section class="card"><h3>Add Customer Asset</h3><form class="form" method="POST" action="{{ route('customer-assets.submissions.store') }}">@csrf
<input name="customer_site_id" type="number" required placeholder="Customer Site ID"><input name="name" required placeholder="Asset name"><input name="asset_category" required placeholder="Category"><input name="customer_asset_code" placeholder="Customer asset code"><input name="serial_no" placeholder="Serial number"><input name="asset_type" placeholder="Type"><input name="manufacturer" placeholder="Manufacturer"><input name="model_no" placeholder="Model"><select name="criticality"><option value="">Criticality later</option><option>MEDIUM</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select><select name="maintenance_strategy"><option value="">PM Strategy later</option><option>PREVENTIVE</option><option>PREDICTIVE</option><option>CONDITION_BASED</option><option>CORRECTIVE</option><option>RUN_TO_FAILURE</option></select><input type="date" name="installation_date"><input class="wide" name="physical_location" placeholder="Physical location"><textarea class="wide" name="technical_specifications" placeholder='{"capacity":"1000 kVA"}'></textarea><input type="hidden" name="ownership_type" value="CUSTOMER_OWNED"><button class="btn wide">Create → Pending Verification</button></form></section>
<section class="card"><h3>Bulk Import · up to 5,000 assets</h3><div class="flow">Imported → Validation Queue → Duplicate Check → Approved</div><p>Excel/CSV may start with the registration minimum: name, asset_category, customer_site_id. Optional enrichment: serial_no, manufacturer, model_no, customer_asset_code, type, location, PM strategy, installation date.</p><p><b>Duplicate Check:</b> Customer + Site + Serial Number + Manufacturer + Model + Customer Asset Code. Strong matches are flagged as <b>Possible Duplicate Asset</b>.</p><form method="POST" enctype="multipart/form-data" action="{{ route('customer-assets.import') }}">@csrf<input type="file" name="file" accept=".csv,.xlsx" required><button class="btn">Import Excel</button></form></section>
@endif
<section class="card wide"><h3>Verification & Approval Queue</h3>@forelse($submissions as $s)<div class="row"><span class="pill">{{ $s->status }}</span> <b>{{ $s->name }}</b> · {{ $s->serial_no ?: 'Serial pending' }} · {{ $s->ownership_type }} · {{ $s->source }}
@if(!$isCustomer && $s->status==='PENDING_VERIFICATION')<form method="POST" action="{{ route('customer-assets.submissions.review',$s->id) }}" style="display:inline">@csrf<input name="notes" placeholder="Review notes"><button class="btn" name="decision" value="APPROVE">Approve into Asset Master</button><button class="btn" name="decision" value="REJECT">Reject</button></form>@endif
<a href="{{ route('customer-assets.submissions.audit',$s->id) }}">Audit trail</a></div>@empty<p>No submissions.</p>@endforelse</section>
</div>
@endsection
