<!doctype html>
<html lang="{{ $home['lang'] }}" dir="{{ $home['dir'] }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#132137">
<meta name="description" content="{{ $home['hero_text'] }}">
<title>UNIFCO | One Facility Shop</title>
<style>
:root{--navy:#1e315b;--navy-deep:#071f4d;--dark:#132137;--red:#ce122d;--light:#f5f7fa;--muted:#68758a;--line:#e1e6ed;--white:#fff;--shadow:0 12px 32px rgba(10,31,62,.1);--soft-shadow:0 5px 18px rgba(10,31,62,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:82px}body{margin:0;color:var(--dark);background:#fff;font-family:"Cairo",Tahoma,Arial,sans-serif;-webkit-font-smoothing:antialiased}body[dir=ltr]{font-family:Inter,Arial,sans-serif}a{text-decoration:none;color:inherit}button,input{font:inherit}img{display:block;max-width:100%}.wrap{width:min(1280px,94%);margin-inline:auto}.section{padding:54px 0}.section.alt{background:var(--light)}.proof-icon svg,.line-icon svg,.mini-icon svg,.process-icon svg,.why-icon svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:1.75;stroke-linecap:round;stroke-linejoin:round}
.top{position:sticky;top:0;z-index:60;background:rgba(255,255,255,.97);border-bottom:1px solid #e7ebf0;backdrop-filter:blur(14px)}.nav{min-height:76px;display:flex;align-items:center;gap:20px;direction:ltr}.brand-link{display:flex;align-items:center;gap:9px;margin-right:auto;direction:ltr}.site-logo-frame{width:42px;height:50px;overflow:hidden;flex:0 0 42px}.site-logo{width:42px;height:65px;object-fit:cover;object-position:center top}.brand-copy{display:flex;flex-direction:column;line-height:.88}.brand-copy strong{font-family:Inter,Arial,sans-serif;font-size:24px;letter-spacing:.03em;color:var(--navy-deep)}.brand-copy small{margin-top:5px;font-family:Inter,Arial,sans-serif;font-size:6px;font-weight:900;letter-spacing:.16em;color:var(--red)}.nav-links{display:flex;align-items:center;gap:23px;direction:{{ $home['dir'] }}}.nav-links a{position:relative;font-size:12px;font-weight:800;color:#25354d;white-space:nowrap}.nav-links a:first-child:after,.nav-links a:hover:after{content:"";position:absolute;inset-inline:0;bottom:-12px;height:2px;background:var(--red)}.nav-actions{display:flex;align-items:center;gap:9px;direction:ltr}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:42px;padding:10px 18px;border:1px solid transparent;border-radius:6px;background:var(--navy-deep);color:#fff;font-size:11px;font-weight:900;transition:.18s;cursor:pointer}.btn:hover{transform:translateY(-1px);box-shadow:0 7px 18px rgba(7,31,77,.18)}.btn.red{background:var(--red)}.btn.outline{background:transparent;border-color:rgba(255,255,255,.72);color:#fff}.btn.white{background:#fff;border-color:#d9e0e9;color:var(--navy-deep)}.lang{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:9px 13px;border:1px solid #ccd4df;border-radius:6px;font-size:10px;font-weight:900;color:var(--navy-deep);background:#fff}.menu-toggle{display:none;border:0;background:var(--navy-deep);color:#fff;width:42px;height:42px;border-radius:7px;font-size:20px;cursor:pointer}.mobile-menu{display:none;padding:0 0 14px;direction:{{ $home['dir'] }}}.mobile-menu.open{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mobile-menu a{padding:10px 12px;background:#f5f7fa;border-radius:7px;color:var(--navy-deep);font-size:11px;font-weight:800}
.hero{min-height:500px;display:flex;align-items:center;position:relative;overflow:hidden;color:#fff;background-image:linear-gradient(90deg,rgba(3,22,48,.98) 0%,rgba(5,30,62,.91) 30%,rgba(5,30,62,.54) 50%,rgba(5,30,62,.06) 74%),url('/images/unifco-hero-approved-v15.webp');background-position:center;background-size:cover}.hero:after{content:"";position:absolute;inset:auto 0 0;height:4px;background:linear-gradient(90deg,var(--red),#e53b50 32%,transparent 74%)}.hero-inner{position:relative;z-index:2;display:flex;direction:ltr}.hero-copy{width:min(540px,47%);padding:58px 0 50px;text-align:{{ $home['dir']==='rtl' ? 'right' : 'left' }};direction:{{ $home['dir'] }}}.hero-eyebrow{font-family:Inter,Arial,sans-serif;font-size:16px;font-weight:900;letter-spacing:.04em}.hero h1{font-size:clamp(38px,4.3vw,58px);line-height:1.25;margin:9px 0 14px;color:#fff;max-width:540px;letter-spacing:-.02em}.hero p{font-size:14px;line-height:2;color:#e1e8f2;max-width:520px;margin:0}.hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:24px}.hero-proof{display:flex;gap:0;margin-top:34px}.proof{display:flex;align-items:center;gap:10px;min-width:145px;padding-inline:18px;border-inline-end:1px solid rgba(255,255,255,.28)}.proof:first-child{padding-inline-start:0}.proof:last-child{border:0}.proof-icon{width:38px;height:38px;border:1px solid rgba(255,255,255,.38);border-radius:50%;display:grid;place-items:center}.proof-icon svg{width:18px;height:18px}.proof b,.proof small{display:block}.proof b{font-size:11px}.proof small{font-size:9px;color:#ced9e7}
.capability-bar{background:#fff;border-bottom:1px solid var(--line)}.capabilities{display:grid;grid-template-columns:repeat(4,1fr);direction:ltr}.capability{min-height:92px;padding:17px 24px;display:flex;align-items:center;justify-content:center;gap:14px;border-right:1px solid var(--line);direction:{{ $home['dir'] }}}.capability:last-child{border:0}.line-icon{width:48px;height:48px;flex:0 0 48px;display:grid;place-items:center;color:var(--navy-deep)}.line-icon svg{width:28px;height:28px}.capability b,.capability small{display:block}.capability b{font-family:Inter,Arial,sans-serif;font-size:11px;color:var(--navy-deep);margin-bottom:2px}.capability small{font-size:9.5px;color:var(--muted)}
.section-head{text-align:center;margin:0 auto 25px;max-width:760px}.kicker{color:var(--red);font-size:11px;font-weight:900;margin-bottom:4px}.section-head h2,.about-copy h2,.operation-card h2,.final-cta h2{font-size:clamp(26px,3vw,38px);line-height:1.35;color:var(--navy-deep);margin:0 0 7px}.section-head p{font-size:12px;color:var(--muted);margin:0;line-height:1.8}.about-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:52px;align-items:center;direction:ltr}.about-media,.about-copy{direction:{{ $home['dir'] }}}.about-media{position:relative;min-height:370px}.about-media img{width:100%;height:370px;object-fit:cover;object-position:center 34%;border-radius:10px;box-shadow:var(--shadow)}.about-stamp{position:absolute;right:-18px;bottom:-18px;width:122px;height:122px;border-radius:7px;background:linear-gradient(145deg,#db1532,#bd0e26);color:#fff;display:grid;place-items:center;text-align:center;font-family:Inter,Arial,sans-serif;font-size:19px;line-height:1.08;font-weight:900;box-shadow:0 12px 24px rgba(206,18,45,.24)}.about-copy>p{font-size:13px;line-height:1.95;color:#5e6c81;margin:0}.about-points{display:grid;grid-template-columns:1fr 1fr;margin:20px 0 18px}.about-point{display:flex;align-items:center;gap:11px;padding:12px 0;border-bottom:1px solid var(--line)}.about-point:nth-child(odd){padding-inline-end:20px;border-inline-end:1px solid var(--line)}.about-point:nth-child(even){padding-inline-start:20px}.about-point .mini-icon{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;color:var(--navy-deep);background:#f1f5f9}.about-point b,.about-point small{display:block}.about-point b{font-size:12px;color:var(--navy-deep)}.about-point small{font-size:10px;color:var(--muted)}.stats{position:relative;z-index:3;margin-top:29px;display:grid;grid-template-columns:repeat(4,1fr);direction:{{ $home['dir'] }};border-radius:8px;overflow:hidden;background:linear-gradient(100deg,#052252,#0a376b);color:#fff;box-shadow:0 12px 26px rgba(7,31,77,.18)}.stat{text-align:center;padding:18px 12px;position:relative}.stat:not(:last-child):after{content:"";position:absolute;inset-inline-end:0;top:25%;height:50%;width:1px;background:rgba(255,255,255,.28)}.stat strong{display:block;font-size:27px;line-height:1.1}.stat span{font-size:10px;color:#d7e2f0}
.service-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;direction:ltr}.service-card{background:#fff;border:1px solid #dde3eb;border-radius:8px;overflow:hidden;box-shadow:0 3px 12px rgba(7,31,77,.05);transition:.18s;direction:{{ $home['dir'] }}}.service-card:hover{transform:translateY(-4px);box-shadow:var(--shadow)}.service-image{height:136px;position:relative;background:#e9eef3;overflow:hidden}.service-image img{width:100%;height:100%;object-fit:cover}.service-number{position:absolute;left:7px;top:7px;background:#fff;color:var(--red);border-radius:4px;padding:4px 7px;font-family:Inter,Arial,sans-serif;font-size:11px;font-weight:900;box-shadow:0 3px 10px #0002}.service-body{padding:12px}.service-body b{display:block;min-height:35px;font-family:Inter,Arial,sans-serif;font-size:10.5px;line-height:1.25;color:var(--navy-deep)}.service-body p{font-size:9.5px;line-height:1.7;color:var(--muted);min-height:60px;margin:5px 0}.more{color:var(--red);font-size:9px;font-weight:900}.center-action{text-align:center;margin-top:14px}.center-action .btn{min-width:170px}
.process-wrap{padding-top:46px;padding-bottom:44px}.process{display:grid;grid-template-columns:repeat(4,1fr);gap:36px;direction:ltr}.process-step{text-align:center;position:relative;direction:{{ $home['dir'] }}}.process-step:not(:last-child):after{content:"→";position:absolute;right:-27px;top:23px;color:#8491a2;font-size:18px}.process-icon{width:56px;height:56px;margin:0 auto 8px;border-radius:50%;display:grid;place-items:center;background:var(--navy-deep);color:#fff;box-shadow:0 7px 16px rgba(7,31,77,.16)}.process-icon svg{width:23px;height:23px}.process-step strong{display:inline-block;font-family:Inter,Arial,sans-serif;color:var(--red);font-size:10px;margin-inline-end:5px}.process-step b{font-size:12px;color:var(--navy-deep)}.process-step p{font-size:10px;line-height:1.65;color:var(--muted);margin:4px auto 0;max-width:210px}
.industry-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:10px;direction:ltr}.industry{height:142px;position:relative;overflow:hidden;border-radius:6px;background:#dfe6ed;box-shadow:var(--soft-shadow);direction:{{ $home['dir'] }}}.industry img{width:100%;height:100%;object-fit:cover}.industry:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(6,28,59,.9),rgba(6,28,59,.02) 76%)}.industry span{position:absolute;z-index:2;inset-inline:7px;bottom:10px;color:#fff;text-align:center;font-size:10px;font-weight:900}.industry-grid+.center-action{margin-top:13px}
.operations{padding:0 0 48px}.operation-split{display:grid;grid-template-columns:1fr 1fr;border-radius:10px;overflow:hidden;box-shadow:var(--shadow);direction:ltr}.operation-card{min-height:365px;position:relative;direction:{{ $home['dir'] }}}.operation-card h2{font-size:24px}.maintenance-card{color:#fff;background:#072657;display:grid;grid-template-columns:35% 1fr;padding:0;direction:ltr}.maintenance-photo{min-height:365px;overflow:hidden}.maintenance-photo img{width:100%;height:100%;object-fit:cover;object-position:45% center}.operation-content{padding:34px 28px;direction:{{ $home['dir'] }}}.maintenance-card h2,.maintenance-card p{color:#fff}.maintenance-card p{opacity:.82}.portal-card{padding:32px 34px 0;background:linear-gradient(145deg,#fff,#f6f8fb);overflow:hidden}.operation-card p{font-size:11px;line-height:1.8;color:var(--muted);max-width:500px}.check-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px 16px;margin:16px 0}.check{font-size:9.5px;font-weight:750}.check:before{content:"✓";display:inline-grid;place-items:center;width:16px;height:16px;margin-inline-end:6px;border-radius:50%;background:var(--red);color:#fff;font-size:8px}.portal-device{width:90%;height:190px;margin:10px auto -8px;object-fit:contain;object-position:center bottom;filter:drop-shadow(0 14px 15px rgba(9,29,58,.17))}
.why-grid{display:grid;grid-template-columns:repeat(6,1fr);border:1px solid var(--line);border-radius:8px;background:#fff;direction:ltr}.why-card{text-align:center;padding:22px 14px;position:relative;direction:{{ $home['dir'] }}}.why-card:not(:last-child):after{content:"";position:absolute;right:0;top:20%;height:60%;width:1px;background:var(--line)}.why-icon{width:44px;height:44px;margin:auto;border:1px solid #d5dde8;border-radius:50%;display:grid;place-items:center;color:var(--navy-deep);background:#f8fafc}.why-card b{display:block;color:var(--navy-deep);font-size:11px;margin:8px 0 3px}.why-card p{font-size:9px;line-height:1.65;color:var(--muted);margin:0}
.projects-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;align-items:stretch;direction:ltr}.project-panel,.emergency-panel{background:#fff;border:1px solid var(--line);border-radius:8px;padding:18px;direction:{{ $home['dir'] }}}.project-panel h2{font-size:20px;color:var(--navy-deep);margin:0 0 12px}.project-gallery{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;direction:ltr}.project-gallery img{height:132px;width:100%;object-fit:cover;border-radius:5px;background:#e9eef3}.project-panel .center-action{text-align:start;margin-top:10px}.emergency-panel{border-color:#e7aebb;display:flex;flex-direction:column;justify-content:center;text-align:center}.emergency-panel h2{font-size:24px;color:var(--red);margin:0 0 5px}.emergency-panel p{font-size:11px;line-height:1.8;color:var(--muted);margin:0 auto 17px;max-width:420px}.emergency-contact{margin:16px auto 0;padding:10px 14px;width:min(100%,390px);border-top:1px solid var(--line);color:var(--navy-deep);font-size:10px;font-weight:800}
.final{position:relative;overflow:hidden;color:#fff;background:linear-gradient(90deg,rgba(5,28,62,.98),rgba(6,40,79,.88)),url('/images/unifco-hero-workers-v7.jpg?v=20260823-14') center/cover}.final-cta{min-height:200px;display:flex;align-items:center;justify-content:center;text-align:center;gap:45px}.final-cta h2{color:#fff;font-size:30px;margin-bottom:4px}.final-cta p{font-size:12px;color:#dce5f1;margin:0}.final-actions{display:flex;gap:10px;flex-wrap:wrap;justify-content:center}.footer{background:#062653;color:#c9d4e2;padding:34px 0 19px}.footer-grid{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:34px;direction:ltr}.footer-grid>div{direction:{{ $home['dir'] }}}.footer-brand{display:flex;align-items:center;gap:10px;direction:ltr;margin-bottom:8px}.footer-brand .site-logo-frame{background:#fff;border-radius:5px}.footer-brand strong{display:block;color:#fff;font-family:Inter,Arial,sans-serif;font-size:24px;line-height:1}.footer-brand small{display:block;color:#f18a99;font-size:6px;font-weight:900;letter-spacing:.14em;margin-top:4px}.footer p,.footer a,.footer-contact span{font-size:10px;line-height:1.9}.footer h4{color:#fff;font-size:12px;margin:0 0 8px}.footer-contact span{display:block}.socials{display:flex;gap:7px;margin-top:10px}.socials span{width:27px;height:27px;border:1px solid #ffffff55;border-radius:50%;display:grid;place-items:center;font-size:8px}.copyright{border-top:1px solid rgba(255,255,255,.12);margin-top:20px;padding-top:13px;text-align:center;font-size:8px;color:#93a6bf}
@media(max-width:1080px){.nav-links{display:none}.menu-toggle{display:grid;place-items:center}.service-grid{grid-template-columns:repeat(3,1fr)}.industry-grid{grid-template-columns:repeat(4,1fr)}.why-grid{grid-template-columns:repeat(3,1fr)}.why-card:nth-child(3):after{display:none}.footer-grid{grid-template-columns:1.3fr repeat(3,1fr)}}
@media(max-width:850px){.nav-actions .btn{display:none}.hero{min-height:520px;background-position:62% center}.hero-copy{width:min(620px,72%)}.capabilities{grid-template-columns:1fr 1fr}.capability:nth-child(2){border-right:0}.capability:nth-child(-n+2){border-bottom:1px solid var(--line)}.about-grid{grid-template-columns:1fr;gap:30px}.about-media{order:2}.operation-split,.projects-layout{grid-template-columns:1fr}.operation-card{min-height:320px}.final-cta{flex-direction:column;gap:20px;padding:36px 0}.footer-grid{grid-template-columns:1fr 1fr}}
@media(max-width:700px){html{scroll-padding-top:70px}.nav{min-height:70px}.site-logo-frame{width:38px;height:46px;flex-basis:38px}.site-logo{width:38px;height:59px}.brand-copy strong{font-size:21px}.nav-actions .lang{display:none}.mobile-menu.open{display:grid}.hero{min-height:585px;background-position:67% center}.hero:before{content:"";position:absolute;inset:0;background:rgba(3,22,48,.26)}.hero-copy{width:100%;padding:58px 0 42px}.hero h1{font-size:37px;max-width:520px}.hero p{font-size:12px;max-width:500px}.hero-proof{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.proof{min-width:0;padding-inline:7px;gap:6px}.proof-icon{width:30px;height:30px}.proof b{font-size:9px}.proof small{font-size:8px}.section{padding:47px 0}.service-grid{grid-template-columns:1fr 1fr}.service-image{height:145px}.process{grid-template-columns:1fr 1fr;gap:27px}.process-step:nth-child(2):after{display:none}.process-step:not(:last-child):after{right:-20px}.industry-grid{grid-template-columns:1fr 1fr}.industry{height:145px}.stats{grid-template-columns:1fr 1fr}.stat:nth-child(2):after{display:none}.why-grid{grid-template-columns:1fr 1fr}.why-card:nth-child(3):after{display:block}.why-card:nth-child(even):after{display:none}.project-gallery{grid-template-columns:1fr 1fr}.footer-grid{grid-template-columns:1fr 1fr}.about-stamp{right:10px}.maintenance-card{grid-template-columns:1fr}.maintenance-photo{height:235px;min-height:235px}.operation-content{padding:28px 24px}.portal-device{height:auto;margin-bottom:-8px}}
@media(max-width:450px){.wrap{width:min(100% - 28px,1280px)}.nav-actions{display:none}.hero{min-height:620px;background-position:70% center}.hero h1{font-size:32px}.hero-actions{display:grid}.hero-actions .btn{width:100%}.capabilities,.service-grid,.process,.stats,.why-grid,.footer-grid{grid-template-columns:1fr}.capability{border-right:0;border-bottom:1px solid var(--line);justify-content:flex-start}.service-image{height:178px}.process-step:after{display:none!important}.stat:after,.why-card:after{display:none!important}.industry{height:145px}.about-points,.check-grid{grid-template-columns:1fr}.about-point{padding-inline:0!important;border-inline-end:0!important}.operation-card{padding:26px 21px}.maintenance-card{padding:0}.project-gallery{grid-template-columns:1fr 1fr}.project-gallery img{height:105px}.footer-grid{gap:20px}}
</style>
</head>
<body dir="{{ $home['dir'] }}">
<header class="top">
<div class="wrap nav">
<a class="brand-link" href="{{ route('public.home',['lang'=>$home['lang']]) }}" aria-label="UNIFCO home"><span class="site-logo-frame"><img class="site-logo" src="{{ route('brand.logo') }}" alt=""></span><span class="brand-copy"><strong>UNIFCO</strong><small>ONE FACILITY SHOP</small></span></a>
<nav class="nav-links">
<a href="#home">{{ $home['nav'][0] }}</a><a href="#about">{{ $home['nav'][1] }}</a><a href="#services">{{ $home['nav'][2] }}</a><a href="#industries">{{ $home['nav'][3] }}</a><a href="#process">{{ $home['nav'][4] }}</a><a href="#projects">{{ $home['nav'][5] }}</a><a href="#contact">{{ $home['nav'][6] }}</a>
</nav>
<div class="nav-actions"><a class="btn" href="{{ route('login') }}">♙ {{ $home['login'] }}</a><a class="btn red" href="{{ route('public.request-service') }}">♙ {{ $home['request'] }}</a><a class="lang" href="{{ route('public.home',['lang'=>$home['lang']==='ar'?'en':'ar']) }}">{{ $home['language'] }}</a></div>
<button class="menu-toggle" id="menu-toggle" type="button" aria-label="Menu">☰</button>
</div>
<nav class="wrap mobile-menu" id="mobile-menu"><a href="#about">{{ $home['nav'][1] }}</a><a href="#services">{{ $home['nav'][2] }}</a><a href="#industries">{{ $home['nav'][3] }}</a><a href="#process">{{ $home['nav'][4] }}</a><a href="#projects">{{ $home['nav'][5] }}</a><a href="{{ route('login') }}">{{ $home['login'] }}</a><a href="{{ route('public.request-service') }}">{{ $home['request'] }}</a><a href="{{ route('public.home',['lang'=>$home['lang']==='ar'?'en':'ar']) }}">{{ $home['language'] }}</a></nav>
</header>
<main>
<section class="hero" id="home"><div class="wrap hero-inner"><div class="hero-copy"><div class="hero-eyebrow">{{ $home['hero_eyebrow'] }}</div><h1>{{ $home['hero_title'] }}</h1><p>{{ $home['hero_text'] }}</p><div class="hero-actions"><a class="btn red" href="{{ route('public.request-service') }}">{{ $home['request'] }} ↗</a><a class="btn outline" href="#services">{{ $home['explore'] }} ←</a></div><div class="hero-proof">@foreach($home['hero_proofs'] as $proof)<div class="proof"><span class="proof-icon">@include('public.partials.home-icon',['name'=>$proof[0]])</span><span><b>{{ $proof[1] }}</b><small>{{ $proof[2] }}</small></span></div>@endforeach</div></div></div></section>
<section class="capability-bar"><div class="wrap capabilities">@foreach($home['capabilities'] as $item)<div class="capability"><span class="line-icon">@include('public.partials.home-icon',['name'=>$item[0]])</span><span><b>{{ $item[1] }}</b><small>{{ $item[2] }}</small></span></div>@endforeach</div></section>
<section class="section" id="about"><div class="wrap"><div class="about-grid"><div class="about-media"><img src="/images/home/about-technician-v14.webp" alt="{{ $home['about_title'] }}"><div class="about-stamp">ONE<br>FACILITY<br>SHOP</div></div><div class="about-copy"><div class="kicker">{{ $home['about_kicker'] }}</div><h2>{{ $home['about_title'] }}</h2><p>{{ $home['about_text'] }}</p><div class="about-points">@foreach($home['about_points'] as $point)<div class="about-point"><span class="mini-icon">@include('public.partials.home-icon',['name'=>$point[0]])</span><span><b>{{ $point[1] }}</b><small>{{ $point[2] }}</small></span></div>@endforeach</div><a class="btn" href="#services">{{ $home['about_button'] }} ←</a></div></div><div class="stats">@foreach($home['stats'] as $stat)<div class="stat"><strong>{{ $stat[0] }}</strong><span>{{ $stat[1] }}</span></div>@endforeach</div></div></section>
<section class="section alt" id="services"><div class="wrap"><div class="section-head"><div class="kicker">{{ $home['services_kicker'] }}</div><h2>{{ $home['services_title'] }}</h2><p>{{ $home['services_text'] }}</p></div><div class="service-grid">@foreach($home['services'] as $service)<article class="service-card"><div class="service-image"><img src="{{ $service[1] }}" alt="{{ $service[2] }}"><span class="service-number">{{ $service[0] }}</span></div><div class="service-body"><b>{{ $service[2] }}</b><p>{{ $service[3] }}</p><a class="more" href="{{ route('public.request-service') }}">{{ $home['more'] }} ←</a></div></article>@endforeach</div><div class="center-action"><a class="btn red" href="{{ route('public.request-service') }}">{{ $home['all_services'] }}</a></div></div></section>
<section class="section process-wrap" id="process"><div class="wrap"><div class="section-head"><div class="kicker">{{ $home['process_kicker'] }}</div><h2>{{ $home['process_title'] }}</h2></div><div class="process">@foreach($home['process'] as $index=>$step)<article class="process-step"><div class="process-icon">@include('public.partials.home-icon',['name'=>['search','clipboard','settings','chart'][$index]])</div><div><strong>{{ $step[0] }}</strong><b>{{ $step[1] }}</b></div><p>{{ $step[2] }}</p></article>@endforeach</div></div></section>
<section class="section alt" id="industries"><div class="wrap"><div class="section-head"><h2>{{ $home['industries_title'] }}</h2></div><div class="industry-grid">@foreach($home['industries'] as $industry)<article class="industry"><img src="{{ $industry[0] }}" alt="{{ $industry[1] }}"><span>{{ $industry[1] }}</span></article>@endforeach</div><div class="center-action"><a class="btn" href="#contact">{{ $home['all_industries'] }}</a></div></div></section>
<section class="operations"><div class="wrap operation-split"><article class="operation-card maintenance-card"><div class="maintenance-photo"><img src="/images/home/about-technician-v14.webp" alt="{{ $home['maintenance_title'] }}"></div><div class="operation-content"><h2>{{ $home['maintenance_title'] }}</h2><p>{{ $home['maintenance_text'] }}</p><div class="check-grid">@foreach($home['maintenance_checks'] as $check)<span class="check">{{ $check }}</span>@endforeach</div><a class="btn red" href="{{ route('public.request-service') }}">{{ $home['maintenance_button'] }}</a></div></article><article class="operation-card portal-card"><h2>{{ $home['portal_title'] }}</h2><p>{{ $home['portal_text'] }}</p><div class="check-grid">@foreach($home['portal_checks'] as $check)<span class="check">{{ $check }}</span>@endforeach</div><a class="btn" href="{{ route('login') }}">{{ $home['portal_button'] }}</a><img class="portal-device" src="/images/home/client-portal-v14.webp" alt="{{ $home['portal_title'] }}"></article></div></section>
<section class="section"><div class="wrap"><div class="section-head"><h2>{{ $home['why_title'] }}</h2></div><div class="why-grid">@foreach($home['why'] as $reason)<article class="why-card"><span class="why-icon">@include('public.partials.home-icon',['name'=>$reason[0]])</span><b>{{ $reason[1] }}</b><p>{{ $reason[2] }}</p></article>@endforeach</div></div></section>
<section class="section alt" id="projects"><div class="wrap projects-layout"><article class="project-panel"><h2>{{ $home['projects_title'] }}</h2><div class="project-gallery"><img src="/images/home/service-photo-v14-01.webp" alt="Facility project"><img src="/images/home/industry-photo-v14-00.webp" alt="Commercial project"><img src="/images/home/service-photo-v14-02.webp" alt="MEP project"><img src="/images/home/service-photo-v14-04.webp" alt="Electrical project"></div><div class="center-action"><a class="btn" href="{{ route('public.request-service') }}">{{ $home['projects_button'] }}</a></div></article><article class="emergency-panel"><h2>{{ $home['emergency_title'] }}</h2><p>{{ $home['emergency_text'] }}</p><div><a class="btn red" href="{{ route('public.emergency') }}">{{ $home['emergency_button'] }}</a></div><div class="emergency-contact">◴ {{ $home['emergency_contact'] }}</div></article></div></section>
<section class="final"><div class="wrap final-cta"><div><h2>{{ $home['final_title'] }}</h2><p>{{ $home['final_text'] }}</p></div><div class="final-actions"><a class="btn red" href="{{ route('public.quote') }}">{{ $home['quote'] }} ↗</a><a class="btn outline" href="#contact">{{ $home['contact'] }}</a></div></div></section>
</main>
<footer class="footer" id="contact"><div class="wrap footer-grid"><div><div class="footer-brand"><span class="site-logo-frame"><img class="site-logo" src="{{ route('brand.logo') }}" alt=""></span><span><strong>UNIFCO</strong><small>ONE FACILITY SHOP</small></span></div><p>{{ $home['footer_about'] }}</p><div class="socials"><span>in</span><span>f</span><span>𝕏</span><span>▶</span></div></div><div><h4>{{ $home['company'] }}</h4><p><a href="#about">{{ $home['nav'][1] }}</a><br><a href="#process">{{ $home['nav'][4] }}</a><br><a href="#projects">{{ $home['nav'][5] }}</a><br><a href="#contact">{{ $home['nav'][6] }}</a></p></div><div><h4>{{ $home['services_label'] }}</h4><p>Facility Management<br>Maintenance<br>MEP Services<br>HVAC Systems<br>Electrical Services<br>Asset Management</p></div><div><h4>{{ $home['contact_label'] }}</h4><div class="footer-contact">@foreach($home['footer_contact'] as $line)<span>{{ $line }}</span>@endforeach</div><p><a href="{{ route('public.request-service') }}">{{ $home['request'] }}</a><br><a href="{{ route('public.emergency') }}">{{ $home['emergency_button'] }}</a><br><a href="{{ route('login') }}">{{ $home['login'] }}</a></p></div></div><div class="wrap copyright">© {{ date('Y') }} UNIFCO — ONE FACILITY SHOP</div></footer>
<script>const toggle=document.getElementById('menu-toggle'),menu=document.getElementById('mobile-menu');toggle?.addEventListener('click',()=>menu.classList.toggle('open'));menu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>menu.classList.remove('open')));</script>
</body>
</html>
