@extends('layouts.app')
@section('title',($employee->exists?'Edit Employee':'New Employee').' | UNIFCO Platform')
@section('heading',$employee->exists?'Edit Employee':'New Employee')
@section('content')
<style>
.emp-form-shell{max-width:1280px}.form-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:14px;display:flex;justify-content:space-between;align-items:center;gap:14px}.form-hero small{display:block;color:#afbdd1;font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.form-hero h1{font-size:22px;margin:5px 0}.form-hero p{font-size:11px;color:#d9e2ef;margin:0}.form-sections{display:grid;gap:12px}.form-card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:17px}.form-card h3{font-size:13px;color:#17243c;margin:0 0 4px}.form-card>small{display:block;color:#8390a2;font-size:8px;margin-bottom:12px}.fields{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:11px 12px;align-items:start}.fields label{font-size:9px;color:#617086;font-weight:700;grid-column:span 3;min-width:0}.fields input,.fields select,.fields textarea{width:100%;box-sizing:border-box;min-height:40px}.fields textarea{min-height:88px}.w-2{grid-column:span 2!important}.w-3{grid-column:span 3!important}.w-4{grid-column:span 4!important}.w-5{grid-column:span 5!important}.w-6,.span-2{grid-column:span 6!important}.span-4{grid-column:1/-1!important}.readonly{background:#f3f6fa!important;color:#42536b!important;font-weight:800}.phone-group{display:flex;border:1px solid #d5dce5;border-radius:7px;overflow:hidden;background:#fff;min-height:40px}.phone-group select{width:116px!important;flex:0 0 116px;border:0!important;border-right:1px solid #e1e6ed!important;border-radius:0!important;background:#f8fafc;font-size:9px;min-height:38px}.phone-group input{border:0!important;border-radius:0!important;min-width:0;min-height:38px}.doc-field{display:grid!important;grid-template-columns:1fr;gap:5px}.doc-upload{display:flex;align-items:center;gap:6px}.doc-upload input[type=file]{font-size:8px;padding:5px;background:#f8fafc;min-height:36px}.doc-upload span{font-size:8px;color:#758399}.manager-email{background:#f5f8fb;color:#596b82}.auto-note{display:block;color:#77869a;font-size:8px;margin-top:4px}.form-actions{display:flex;gap:8px;position:sticky;bottom:12px;background:rgba(248,249,251,.94);backdrop-filter:blur(8px);padding:10px;border:1px solid #e3e8ef;border-radius:12px;margin-top:12px;z-index:5}.hint{font-size:8px;color:#8895a6;font-weight:400}@media(max-width:1050px){.fields label,.w-2,.w-3,.w-4,.w-5{grid-column:span 6!important}.w-6,.span-2{grid-column:span 6!important}.span-4{grid-column:1/-1!important}}@media(max-width:650px){.fields{grid-template-columns:1fr}.fields label,.w-2,.w-3,.w-4,.w-5,.w-6,.span-2,.span-4{grid-column:auto!important}.form-hero{display:block}.form-hero .btn{margin-top:12px}.phone-group select{width:112px!important;flex-basis:112px}}
</style>
<div class="emp-form-shell">@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="form-hero"><div><small>People / HR · Employee Core</small><h1>{{ $employee->exists?'Edit '.$employee->name:'Create Employee' }}</h1><p>Structured employee identity, contact, reporting, statutory evidence and compensation in one governed master record.</p></div>@if($employee->exists)<a class="btn secondary" href="{{ route('hr.employees.show',$employee) }}">Employee 360</a>@endif</section>
<form method="POST" enctype="multipart/form-data" action="{{ $employee->exists?route('hr.employees.update',$employee):route('hr.employees.store') }}">@csrf @if($employee->exists)@method('PUT')@endif<div class="form-sections">
<section class="form-card"><h3>Personal & Contact</h3><small>Employee number is generated automatically. Name is stored as structured first, middle and last name.</small><div class="fields">
<label class="w-2">Employee No<input class="readonly" value="{{ $nextEmployeeNo }}" readonly><span class="auto-note">Auto-generated: UN-00001, UN-00002…</span></label>
<label class="w-3">First Name<input name="first_name" value="{{ old('first_name',$employee->first_name) }}" required></label>
<label class="w-3">Middle Name<input name="middle_name" value="{{ old('middle_name',$employee->middle_name) }}"></label>
<label class="w-4">Last Name<input name="last_name" value="{{ old('last_name',$employee->last_name) }}" required></label>
<label class="w-4">Personal Email<input type="email" name="email" value="{{ old('email',$employee->email) }}"></label>
<label class="w-5">Mobile<div class="phone-group"><select name="mobile_country_code" aria-label="Mobile country code">@foreach($phoneCountries as $country)<option value="{{ $country['code'] }}" @selected(old('mobile_country_code',$employee->mobile_country_code ?: '+966')===$country['code'])>{{ $country['flag'] }} {{ $country['code'] }}</option>@endforeach</select><input name="mobile" value="{{ old('mobile',$employee->mobile) }}" placeholder="5XXXXXXXX"></div></label>
<label class="w-3">Date of Birth<input type="date" name="date_of_birth" value="{{ old('date_of_birth',$employee->date_of_birth?->format('Y-m-d')) }}"></label>
<label class="w-3">Gender<select name="gender"><option value="">Not specified</option>@foreach(['MALE'=>'Male','FEMALE'=>'Female'] as $k=>$v)<option value="{{ $k }}" @selected(old('gender',$employee->gender)===$k)>{{ $v }}</option>@endforeach</select></label>
<label class="w-3">Nationality<select name="nationality" required><option value="">Select nationality</option>@foreach($nationalities as $nationality)<option value="{{ $nationality }}" @selected(old('nationality',$employee->nationality)===$nationality)>{{ $nationality }}</option>@endforeach</select></label>
<label class="w-3">Marital Status<select name="marital_status"><option value="">Not specified</option>@foreach(['SINGLE','MARRIED','DIVORCED','WIDOWED'] as $v)<option value="{{ $v }}" @selected(old('marital_status',$employee->marital_status)===$v)>{{ $v }}</option>@endforeach</select></label>
<label class="w-6">Address in Birth Country<input name="address_line" value="{{ old('address_line',$employee->address_line) }}"></label>
<label class="w-3">City in Birth Country<input name="city" value="{{ old('city',$employee->city) }}"></label>
<label class="w-3">Emergency Contact Name<input name="emergency_contact_name" value="{{ old('emergency_contact_name',$employee->emergency_contact_name) }}"></label>
<label class="w-5">Emergency Contact Mobile<div class="phone-group"><select name="emergency_mobile_country_code" aria-label="Emergency mobile country code">@foreach($phoneCountries as $country)<option value="{{ $country['code'] }}" @selected(old('emergency_mobile_country_code',$employee->emergency_mobile_country_code ?: '+966')===$country['code'])>{{ $country['flag'] }} {{ $country['code'] }}</option>@endforeach</select><input name="emergency_contact_mobile" value="{{ old('emergency_contact_mobile',$employee->emergency_contact_mobile) }}" placeholder="5XXXXXXXX"></div></label>
</div></section>

<section class="form-card"><h3>Employment & Organization</h3><small>Position, official communication channel, reporting line and contract context.</small><div class="fields">
<label class="w-3">Hire Date<input type="date" name="hire_date" value="{{ old('hire_date',$employee->hire_date?->format('Y-m-d')) }}"></label>
<label class="w-2">Status<select name="status" required>@foreach(['ACTIVE','INACTIVE','ON_LEAVE','TERMINATED'] as $v)<option value="{{ $v }}" @selected(old('status',$employee->status ?: 'ACTIVE')===$v)>{{ $v }}</option>@endforeach</select></label>
<label class="w-3">Position<select name="job_position_id"><option value="">Unassigned</option>@foreach($positions as $position)<option value="{{ $position->id }}" @selected((string)old('job_position_id',$employee->job_position_id)===(string)$position->id)>{{ $position->department ?: 'General' }} · {{ $position->title }}</option>@endforeach</select></label>
<label class="w-4">Official Employee Email<input type="email" name="official_email" value="{{ old('official_email',$employee->official_email) }}" placeholder="name@unifco.com"></label>
<label class="w-3">Manager<select name="manager_employee_id" id="manager-select"><option value="" data-email="">No manager</option>@foreach($managers as $manager)<option value="{{ $manager->id }}" data-email="{{ $manager->official_email ?: $manager->email }}" @selected((string)old('manager_employee_id',$employee->manager_employee_id)===(string)$manager->id)>{{ $manager->employee_no }} · {{ $manager->name }}</option>@endforeach</select></label>
<label class="w-4">Manager Email<input class="manager-email" id="manager-email" value="" readonly placeholder="Shown automatically after manager selection"></label>
<label class="w-3">Employment Type<select name="employment_type"><option value="">Not specified</option>@foreach(['FULL_TIME','PART_TIME','TEMPORARY','CONTRACTOR'] as $v)<option value="{{ $v }}" @selected(old('employment_type',$employee->employment_type)===$v)>{{ str_replace('_',' ',$v) }}</option>@endforeach</select></label>
<label class="w-2">Contract Type<select name="contract_type"><option value="">Not specified</option>@foreach(['FIXED_TERM','INDEFINITE'] as $v)<option value="{{ $v }}" @selected(old('contract_type',$employee->contract_type)===$v)>{{ str_replace('_',' ',$v) }}</option>@endforeach</select></label>
<label class="w-3">Probation End<input type="date" name="probation_end_date" value="{{ old('probation_end_date',$employee->probation_end_date?->format('Y-m-d')) }}"></label>
<label class="w-3">Contract End<input type="date" name="contract_end_date" value="{{ old('contract_end_date',$employee->contract_end_date?->format('Y-m-d')) }}"></label>
<label class="w-6">Employment Contract Attachment<input type="file" name="contract_document" accept=".pdf,.jpg,.jpeg,.png"><span class="auto-note">PDF/JPG/PNG · up to 15 MB</span></label>
<label class="w-6">Work Location<input name="work_location" value="{{ old('work_location',$employee->work_location) }}"></label>
</div></section>

<section class="form-card"><h3>Saudi Identity & Statutory References</h3><small>Attach the evidence beside its related statutory data. Uploads are stored as employee documents.</small><div class="fields">
<label class="doc-field w-3">National ID<input name="national_id" value="{{ old('national_id',$employee->national_id) }}"><div class="doc-upload"><input type="file" name="national_id_document" accept=".pdf,.jpg,.jpeg,.png"></div></label>
<label class="doc-field w-3">Iqama No<input name="iqama_no" value="{{ old('iqama_no',$employee->iqama_no) }}"><div class="doc-upload"><input type="file" name="iqama_document" accept=".pdf,.jpg,.jpeg,.png"></div></label>
<label class="w-3">Iqama Expiry<input type="date" name="iqama_expiry" value="{{ old('iqama_expiry',$employee->iqama_expiry?->format('Y-m-d')) }}"></label>
<label class="w-3">GOSI No<input name="gosi_no" value="{{ old('gosi_no',$employee->gosi_no) }}"></label>
<label class="doc-field w-6">Passport No<input name="passport_no" value="{{ old('passport_no',$employee->passport_no) }}"><div class="doc-upload"><input type="file" name="passport_document" accept=".pdf,.jpg,.jpeg,.png"></div></label>
<label class="w-3">Passport Expiry<input type="date" name="passport_expiry" value="{{ old('passport_expiry',$employee->passport_expiry?->format('Y-m-d')) }}"></label>
</div></section>

<section class="form-card"><h3>Compensation & Banking</h3><small>Employee master compensation in SAR with IBAN evidence stored beside banking data.</small><div class="fields">
<label class="w-3">Basic Salary<input type="number" step="0.01" min="0" name="basic_salary" value="{{ old('basic_salary',$employee->basic_salary ?: 0) }}"></label>
<label class="w-3">Housing Allowance<input type="number" step="0.01" min="0" name="housing_allowance" value="{{ old('housing_allowance',$employee->housing_allowance ?: 0) }}"></label>
<label class="w-3">Transport Allowance<input type="number" step="0.01" min="0" name="transport_allowance" value="{{ old('transport_allowance',$employee->transport_allowance ?: 0) }}"></label>
<label class="w-3">Other Allowances<input type="number" step="0.01" min="0" name="other_allowances" value="{{ old('other_allowances',$employee->other_allowances ?: 0) }}"></label>
<label class="w-3">Bank Name<input name="bank_name" value="{{ old('bank_name',$employee->bank_name) }}"></label>
<label class="w-6">IBAN<input name="iban" value="{{ old('iban',$employee->iban) }}" placeholder="SA..."><span class="hint">Saudi IBAN / employee salary account.</span></label>
<label class="w-3">IBAN Attachment<input type="file" name="iban_document" accept=".pdf,.jpg,.jpeg,.png"><span class="auto-note">Bank certificate or IBAN proof</span></label>
</div></section>

<section class="form-card"><h3>HR Notes</h3><div class="fields"><label class="span-4">Notes<textarea name="notes" rows="4">{{ old('notes',$employee->notes) }}</textarea></label></div></section>
</div><div class="form-actions"><button class="btn">{{ $employee->exists?'Save Employee':'Create Employee' }}</button><a class="btn secondary" href="{{ $employee->exists?route('hr.employees.show',$employee):route('hr.employees.index') }}">Cancel</a></div></form></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const manager=document.getElementById('manager-select'),email=document.getElementById('manager-email');const sync=()=>{const option=manager?.options[manager.selectedIndex];if(email)email.value=option?.dataset.email||''};manager?.addEventListener('change',sync);sync()});</script>
@endsection
