@extends('layouts.app')
@section('title','Employees | UNIFCO Platform')
@section('heading','Employees')
@section('content')
<style>
.emp-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:14px;display:flex;justify-content:space-between;gap:16px;align-items:center}.emp-hero small{display:block;color:#aebbd0;font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.emp-hero h1{font-size:23px;margin:5px 0}.emp-hero p{margin:0;color:#d9e2ef;font-size:11px}.emp-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}.emp-kpi{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:14px}.emp-kpi small{font-size:8px;color:#7d8a9d;text-transform:uppercase;font-weight:800}.emp-kpi b{display:block;font-size:24px;color:#132137;margin-top:5px}.emp-toolbar{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:11px;margin-bottom:12px}.emp-filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:8px;align-items:end}.emp-filters label{font-size:9px;color:#68778b;font-weight:700}.emp-filters input,.emp-filters select{width:100%}.emp-table-wrap{background:#fff;border:1px solid #e3e8ef;border-radius:12px;overflow:hidden}.emp-table{display:table;margin:0;border-radius:0}.emp-table th{font-size:9px;text-transform:uppercase;background:#f7f9fc;color:#68768a}.emp-table td{font-size:11px;vertical-align:middle}.emp-user{display:flex;align-items:center;gap:9px}.emp-avatar{width:34px;height:34px;border-radius:50%;background:#eaf0f7;color:#1e315b;display:flex;align-items:center;justify-content:center;font-weight:900}.emp-user b,.emp-user small{display:block}.emp-user small{color:#7e8b9d;margin-top:2px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eaf6ef;color:#17734b;font-size:8px;font-weight:800}.state.off{background:#f5eeee;color:#924657}.row-actions{display:flex;gap:5px;flex-wrap:wrap}.row-actions a,.row-actions button{font-size:9px;padding:6px 8px}.comp{font-weight:800;color:#1e315b}.directory-footer{padding:10px 12px}@media(max-width:900px){.emp-filters{grid-template-columns:1fr 1fr}.emp-table{display:block;overflow-x:auto}}@media(max-width:600px){.emp-hero{display:block}.emp-hero .btn{margin-top:12px}.emp-kpis,.emp-filters{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="emp-hero"><div><small>People / HR · Employee Core</small><h1>Employee Directory</h1><p>Master employee records with direct access to Employee 360, employment and compensation data.</p></div><div style="display:flex;gap:7px;flex-wrap:wrap"><a class="btn" href="{{ route('hr.employees.create') }}">+ New Employee</a><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a></div></section>
<div class="emp-kpis"><div class="emp-kpi"><small>Total Employees</small><b>{{ $stats['total'] }}</b></div><div class="emp-kpi"><small>Active</small><b>{{ $stats['active'] }}</b></div><div class="emp-kpi"><small>Inactive / Other</small><b>{{ $stats['inactive'] }}</b></div></div>
<section class="emp-toolbar"><form class="emp-filters" method="GET"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Employee no, name, email or mobile"></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['ACTIVE','INACTIVE','ON_LEAVE','TERMINATED'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select></label><label>Department<select name="department"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department }}" @selected(request('department')===$department)>{{ $department }}</option>@endforeach</select></label><div style="display:flex;gap:6px"><button class="btn">Apply</button><a class="btn secondary" href="{{ route('hr.employees.index') }}">Reset</a></div></form></section>
<section class="emp-table-wrap"><table class="emp-table"><thead><tr><th>Employee</th><th>Position</th><th>Department</th><th>Hire Date</th><th>Monthly Compensation</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($employees as $e)<tr><td><div class="emp-user"><span class="emp-avatar">{{ strtoupper(substr($e->name,0,1)) }}</span><span><b>{{ $e->employee_no }} · {{ $e->name }}</b><small>{{ $e->email ?: 'No email' }} @if($e->mobile) · {{ $e->mobile }} @endif</small></span></div></td><td>{{ $e->position?->title ?? 'Unassigned' }}</td><td>{{ $e->position?->department ?? '—' }}</td><td>{{ $e->hire_date?->format('d M Y') ?? '—' }}</td><td><span class="comp">{{ number_format($e->grossMonthlyCompensation(),2) }} SAR</span></td><td><span class="state {{ $e->status==='ACTIVE'?'':'off' }}">{{ $e->status }}</span></td><td><div class="row-actions"><a class="btn secondary" href="{{ route('hr.employees.show',$e) }}">Employee 360</a><a class="btn secondary" href="{{ route('hr.employees.edit',$e) }}">Edit</a>@if($e->status==='ACTIVE')<form method="POST" action="{{ route('hr.employees.deactivate',$e) }}">@csrf<button class="btn secondary">Deactivate</button></form>@else<form method="POST" action="{{ route('hr.employees.activate',$e) }}">@csrf<button class="btn">Activate</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" style="padding:30px;text-align:center;color:#7d8999">No employees match the selected filters.</td></tr>@endforelse</tbody></table><div class="directory-footer">{{ $employees->links() }}</div></section>
@endsection
