@php($partAuthz=app(\App\Services\AuthorizationService::class))
<style>
.request-queue{margin-top:14px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:15px}.request-queue-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.request-queue h3{margin:0;color:#071f4d;font-size:13px}.request-queue-head small{font-size:8px;color:#748297}.rq-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.rq-kpi{background:#f7f9fc;border-radius:9px;padding:9px}.rq-kpi span{display:block;font-size:7px;color:#758399}.rq-kpi b{font-size:17px;color:#071f4d}.rq-list{display:grid;gap:8px}.rq-card{border:1px solid #e5eaf1;border-radius:10px;padding:11px}.rq-card.urgent{border-left:4px solid #d21d37}.rq-top{display:flex;justify-content:space-between;gap:10px}.rq-top b{font-size:10px}.rq-meta{font-size:8px;color:#718096;margin-top:2px}.rq-status{padding:4px 7px;border-radius:999px;background:#edf2f7;font-size:7px;font-weight:900;height:max-content}.rq-status.APPROVED{background:#e5f5eb;color:#176a43}.rq-status.PICKED{background:#e9f2fd;color:#1d5e9e}.rq-status.ISSUED{background:#fff0df;color:#965b00}.rq-status.RECEIVED{background:#daf4e5;color:#12643e}.rq-status.REJECTED{background:#fdebed;color:#b42239}.rq-lines{font-size:8px;color:#334155;padding:7px 0}.rq-actions{display:flex;gap:6px;flex-wrap:wrap}.rq-actions form{display:inline-flex;gap:5px}.rq-actions input{font-size:8px;padding:6px;min-width:160px}.rq-btn{border:0;border-radius:7px;padding:6px 8px;font-size:8px;font-weight:800;color:#fff;background:#071f4d;cursor:pointer}.rq-btn.green{background:#188554}.rq-btn.amber{background:#a96800}.rq-btn.red{background:#bf243b}.approval-note{font-size:7px;color:#b42239;font-weight:800;margin:5px 0}@media(max-width:650px){.rq-kpis{grid-template-columns:1fr}.rq-top{flex-direction:column}}
</style>
<section class="request-queue"><div class="request-queue-head"><span><h3>Technician Part Requests · طلبات قطع الفنيين</h3><small>Request → Approval & Reservation → Pick → Issue → Technician Receipt</small></span></div><div class="rq-kpis"><div class="rq-kpi"><span>WAITING APPROVAL</span><b>{{ $metrics['part_requests_pending'] }}</b></div><div class="rq-kpi"><span>APPROVED / PICKING</span><b>{{ $metrics['part_requests_ready'] }}</b></div><div class="rq-kpi"><span>AWAITING RECEIPT</span><b>{{ $metrics['part_requests_issued'] }}</b></div></div><div class="rq-list">
@forelse($partRequests as $partRequest)<div class="rq-card {{ in_array($partRequest->priority,['CRITICAL','EMERGENCY'])?'urgent':'' }}"><div class="rq-top"><span><b>{{ $partRequest->request_no }} · {{ $partRequest->workOrder?->work_order_no }} · {{ $partRequest->workOrder?->asset?->asset_code }}</b><div class="rq-meta">{{ $partRequest->priority }} · {{ $partRequest->sourceWarehouse?->code }} → {{ $partRequest->destinationWarehouse?->code }} · Requested by {{ $partRequest->requestedBy?->name }} · {{ optional($partRequest->created_at)->diffForHumans() }}</div></span><i class="rq-status {{ $partRequest->status }}">{{ str_replace('_',' ',$partRequest->status) }}</i></div><div class="rq-lines">@foreach($partRequest->lines as $line)<strong>{{ $line->item?->item_code }}</strong> · {{ $line->item?->name }} · Requested {{ (float)$line->requested_quantity }} · Reserved {{ (float)$line->reserved_quantity }} · Issued {{ (float)$line->issued_quantity }}@if(!$loop->last)<br>@endif @endforeach</div>@if(in_array($partRequest->priority,['CRITICAL','EMERGENCY']) && $partRequest->status==='REQUESTED')<div class="approval-note">Supervisor / Manager approval required before reservation.</div>@endif<div class="rq-actions">
@if($partRequest->status==='REQUESTED' && $partAuthz->allows(auth()->user(),'parts.request.approve'))<form method="POST" action="{{ route('inventory.part-requests.approve',$partRequest) }}">@csrf<input name="decision_note" placeholder="Approval note (optional)"><button class="rq-btn green">Approve & Reserve</button></form><form method="POST" action="{{ route('inventory.part-requests.reject',$partRequest) }}">@csrf<input name="decision_note" required placeholder="Rejection reason"><button class="rq-btn red">Reject</button></form>@endif
@if($partRequest->status==='APPROVED' && $partAuthz->allows(auth()->user(),'parts.request.pick'))<form method="POST" action="{{ route('inventory.part-requests.pick',$partRequest) }}">@csrf<button class="rq-btn amber">Mark Picked</button></form>@endif
@if($partRequest->status==='PICKED' && $partAuthz->allows(auth()->user(),'parts.request.issue'))<form method="POST" action="{{ route('inventory.part-requests.issue',$partRequest) }}">@csrf<button class="rq-btn">Issue / Hand Over</button></form>@endif
@if($partRequest->status==='ISSUED')<span class="rq-meta">Awaiting technician confirmation at {{ $partRequest->destinationWarehouse?->code }}.</span>@endif
</div>@if($partRequest->decision_note)<div class="rq-meta" style="margin-top:6px">Decision note: {{ $partRequest->decision_note }}</div>@endif</div>@empty<div class="empty">No technician part requests yet.</div>@endforelse
</div></section>
