@extends('layouts.app')
@section('title','Business Trips & Missions | UNIFCO Platform')
@section('heading','Business Trips / Missions')
@section('content')
<style>
.m-hero{background:linear-gradient(135deg,#101f38,#1e315b 62%,#294576);color:#fff;border-radius:16px;padding:21px 23px;margin-bottom:13px;display:flex;justify-content:space-between;align-items:center;gap:15px}.m-hero small{font-size:9px;text-transform:uppercase;letter-spacing:.13em;color:#aebbd0;font-weight:800}.m-hero h1{margin:5px 0;font-size:23px}.m-hero p{margin:0;font-size:11px;color:#d9e2ee}.m-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:12px}.m-kpi,.m-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px}.m-kpi{padding:13px}.m-kpi small{display:block;color:#7b889a;font-size:8px;text-transform:uppercase;font-weight:800}.m-kpi b{display:block;font-size:22px;margin-top:4px;color:#15233b}.m-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:11px}.m-card{padding:14px}.m-card h3{margin:0 0 9px;font-size:13px;color:#17243c}.m-form{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.m-form label{font-size:9px;color:#66758a;font-weight:700}.m-form input,.m-form select,.m-form textarea{width:100%}.m-form textarea{min-height:64px}.span2{grid-column:span 2}.m-table-wrap{margin-top:12px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.m-table{display:table;margin:0}.m-table th{font-size:8px;text-transform:uppercase;background:#f7f9fc;color:#65758c}.m-table td{font-size:10px;vertical-align:middle}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf3fa;color:#1e315b;font-size:8px;font-weight:800}.pill.ok{background:#e9f7ef;color:#17734b}.pill.warn{background:#fff4df;color:#9a5c00}.pill.bad{background:#fdebed;color:#a62838}.filters{display:flex;gap:7px;align-items:end;flex-wrap:wrap}.filters label{font-size:8px;color:#68768b}.filters input,.filters select{min-width:180px}.policy-note{font-size:9px;color:#728096;background:#f7f9fc;border-radius:8px;padding:9px;margin-top:9px}@media(max-width:980px){.m-grid{grid-template-columns:1fr}.m-kpis{grid-template-columns:1fr 1fr}.m-form{grid-template-columns:1fr 1fr}}@media(max-width:620px){.m-hero{display:block}.m-kpis,.m-form{grid-template-columns:1fr}.span2{grid-column:auto}.m-table{display:block;overflow-x:auto}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="m-hero"><div><small>People / HR · Travel & Field Mobility</small><h1>Business Trips & Missions</h1><p>Request, approve, fund and settle employee missions with project/customer context and auditable expenses.</p></div><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a></section>
<div class="m-kpis"><div class="m-kpi"><small>Pending Approval</small><b>{{ $stats['pending'] }}</b></div><div class="m-kpi"><small>Approved / Active</small><b>{{ $stats['active'] }}</b></div><div class="m-kpi"><small>Settlement Pending</small><b>{{ $stats['unsettled'] }}</b></div><div class="m-kpi"><small>Approved / Paid Advances</small><b>{{ number_format($stats['advances'],2) }}</b><span style="font-size:8px;color:#8290a4">SAR</span></div></div>
<div class="m-grid"><section class="m-card"><h3>New Mission Request</h3><form class="m-form" method="POST" action="{{ route('hr.missions.store') }}">@csrf
<label>Employee<select name="employee_id" required><option value="">Select employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} · {{ $e->name }}</option>@endforeach</select></label>
<label>Mission Type<select name="trip_type"><option value="LOCAL">Local</option><option value="INTERNATIONAL">International</option><option value="FIELD_MISSION">Field Mission</option></select></label>
<label>Travel Method<select name="travel_method"><option value="">Not specified</option><option>AIR</option><option>COMPANY_CAR</option><option>PRIVATE_CAR</option><option>TRAIN</option><option>OTHER</option></select></label>
<label class="span2">Purpose<input name="purpose" required placeholder="Business purpose / work scope"></label><label>Destination City<input name="destination_city" required></label>
<label>Country<input name="destination_country" value="SA" required></label><label>Start<input type="date" name="starts_on" required></label><label>End<input type="date" name="ends_on" required></label>
<label>Project<select name="project_id"><option value="">None</option>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->project_no }} · {{ $p->name }}</option>@endforeach</select></label>
<label>Customer<select name="customer_id"><option value="">None</option>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->customer_code }} · {{ $c->name }}</option>@endforeach</select></label>
<label>Per Diem / Day (SAR)<input type="number" step="0.01" min="0" name="per_diem_rate" value="0" required></label><label>Requested Advance (SAR)<input type="number" step="0.01" min="0" name="requested_advance" value="0"></label>
<label><input type="checkbox" name="hotel_required" value="1"> Hotel required</label><label><input type="checkbox" name="transport_required" value="1"> Transport required</label><div><button class="btn">Submit Mission</button></div></form><div class="policy-note">Per diem is a configurable company amount on each mission; no universal statutory daily rate is assumed by the system.</div></section>
<section class="m-card"><h3>Find Missions</h3><form class="filters" method="GET"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Trip no, city or purpose"></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['PENDING','APPROVED','IN_PROGRESS','SETTLEMENT_PENDING','SETTLED','REJECTED','CANCELLED'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select></label><button class="btn">Apply</button><a class="btn secondary" href="{{ route('hr.missions.index') }}">Reset</a></form></section></div>
<section class="m-table-wrap"><table class="m-table"><thead><tr><th>Mission</th><th>Employee</th><th>Destination</th><th>Dates</th><th>Per Diem</th><th>Advance</th><th>Status</th><th></th></tr></thead><tbody>@forelse($trips as $trip)<tr><td><b>{{ $trip->trip_no }}</b><br><small>{{ $trip->trip_type }}</small></td><td>{{ $trip->employee?->name ?? '—' }}</td><td>{{ $trip->destination_city }}, {{ $trip->destination_country }}</td><td>{{ $trip->starts_on?->format('d M') }} → {{ $trip->ends_on?->format('d M Y') }}</td><td>{{ number_format((float)$trip->per_diem_total,2) }} SAR</td><td>{{ number_format((float)$trip->approved_advance ?: (float)$trip->requested_advance,2) }}<br><small>{{ $trip->advance_status }}</small></td><td><span class="pill {{ in_array($trip->status,['APPROVED','SETTLED'])?'ok':($trip->status==='PENDING'?'warn':(in_array($trip->status,['REJECTED','CANCELLED'])?'bad':'')) }}">{{ $trip->status }}</span></td><td><a class="btn secondary" href="{{ route('hr.missions.show',$trip) }}">Mission 360</a></td></tr>@empty<tr><td colspan="8" style="text-align:center;padding:26px;color:#7d899b">No missions recorded yet.</td></tr>@endforelse</tbody></table><div style="padding:10px">{{ $trips->links() }}</div></section>
@endsection
