@extends('layouts.app')
@section('title',$mission->trip_no.' | Mission 360')
@section('heading','Mission 360')
@section('content')
<style>
.m360-hero{background:linear-gradient(135deg,#101f38,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:14px}.m360-hero small{font-size:9px;color:#aebbd0;text-transform:uppercase}.m360-hero h1{margin:4px 0;font-size:22px}.m360-hero p{margin:0;color:#dbe4f0;font-size:11px}.m360-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.m360-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:14px}.m360-card.wide{grid-column:1/-1}.m360-card h3{margin:0 0 10px;font-size:13px;color:#17243c}.facts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fact{background:#f7f9fc;border-radius:8px;padding:9px}.fact small{display:block;color:#7d899b;font-size:8px;text-transform:uppercase}.fact b{display:block;margin-top:3px;font-size:10px}.actions{display:flex;align-items:end;gap:6px;flex-wrap:wrap;margin-top:10px}.expense-form{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.expense-form label{font-size:8px;color:#68768b}.expense-form input,.expense-form select{width:100%}.expense-row{display:grid;grid-template-columns:1.5fr .6fr .5fr auto;gap:8px;align-items:center;padding:9px;background:#f7f9fc;border-radius:8px;margin-top:6px;font-size:9px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#1e315b;font-size:8px;font-weight:800}.settlement{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.settlement div{background:#f7f9fc;border-radius:9px;padding:11px}.settlement small{display:block;color:#7d899b;font-size:8px;text-transform:uppercase}.settlement b{display:block;margin-top:3px;font-size:15px}.danger{background:#a51f35}.success{background:#17734b}@media(max-width:850px){.m360-grid{grid-template-columns:1fr}.m360-card.wide{grid-column:auto}.expense-form{grid-template-columns:1fr 1fr}.settlement{grid-template-columns:1fr 1fr}}@media(max-width:600px){.m360-hero{display:block}.facts,.expense-form,.settlement{grid-template-columns:1fr}.expense-row{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="m360-hero">
  <div><small>{{ $mission->trip_type }} · {{ $mission->status }}</small><h1>{{ $mission->trip_no }} · {{ $mission->employee ? $mission->employee->name : 'Employee' }}</h1><p>{{ $mission->destination_city }}, {{ $mission->destination_country }} · {{ $mission->starts_on->format('d M Y') }} → {{ $mission->ends_on->format('d M Y') }}</p></div>
  <div class="actions"><a class="btn secondary" href="{{ route('hr.employees.show',$mission->employee_id) }}">Employee 360</a><a class="btn secondary" href="{{ route('hr.missions.index') }}">Back to Missions</a></div>
</section>
<div class="m360-grid">
<section class="m360-card"><h3>Mission Details</h3><div class="facts">
<div class="fact"><small>Employee</small><b>{{ $mission->employee ? $mission->employee->employee_no.' · '.$mission->employee->name : '—' }}</b></div>
<div class="fact"><small>Purpose</small><b>{{ $mission->purpose }}</b></div>
<div class="fact"><small>Project</small><b>{{ $mission->project ? $mission->project->project_no.' · '.$mission->project->name : '—' }}</b></div>
<div class="fact"><small>Customer</small><b>{{ $mission->customer ? $mission->customer->name : '—' }}</b></div>
<div class="fact"><small>Travel Method</small><b>{{ $mission->travel_method ?: '—' }}</b></div>
<div class="fact"><small>Logistics</small><b>Hotel: {{ $mission->hotel_required ? 'YES' : 'NO' }} · Transport: {{ $mission->transport_required ? 'YES' : 'NO' }}</b></div>
</div>
@if($mission->status==='PENDING')<div class="actions"><form method="POST" action="{{ route('hr.missions.decide',$mission->id) }}">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn success">Approve</button></form><form method="POST" action="{{ route('hr.missions.decide',$mission->id) }}">@csrf<input type="hidden" name="decision" value="REJECTED"><button class="btn danger">Reject</button></form></div>@endif
</section>
<section class="m360-card"><h3>Per Diem & Advance</h3><div class="facts"><div class="fact"><small>Per Diem</small><b>{{ number_format((float)$mission->per_diem_rate,2) }} × {{ number_format((float)$mission->per_diem_days,2) }} days</b></div><div class="fact"><small>Per Diem Total</small><b>{{ number_format((float)$mission->per_diem_total,2) }} SAR</b></div><div class="fact"><small>Requested Advance</small><b>{{ number_format((float)$mission->requested_advance,2) }} SAR</b></div><div class="fact"><small>Advance Status</small><b>{{ $mission->advance_status }}</b></div></div>
@if(in_array($mission->status,['APPROVED','IN_PROGRESS','SETTLEMENT_PENDING'],true))<div class="actions"><form method="POST" action="{{ route('hr.missions.advance',$mission->id) }}">@csrf<input type="hidden" name="action" value="APPROVE"><label style="font-size:8px">Approved Amount<input type="number" step="0.01" min="0" name="amount" value="{{ $mission->requested_advance }}"></label><button class="btn">Approve Advance</button></form>@if($mission->advance_status==='APPROVED')<form method="POST" action="{{ route('hr.missions.advance',$mission->id) }}">@csrf<input type="hidden" name="action" value="MARK_PAID"><button class="btn success">Mark Paid</button></form>@endif</div>@endif
</section>
<section class="m360-card wide"><h3>Expenses</h3>
@if(in_array($mission->status,['APPROVED','IN_PROGRESS','SETTLEMENT_PENDING'],true))<form class="expense-form" method="POST" action="{{ route('hr.missions.expenses.store',$mission->id) }}">@csrf<label>Date<input type="date" name="expense_date" required></label><label>Category<select name="category">@foreach(['HOTEL','TRANSPORT','MEALS','FUEL','TICKET','VISA','OTHER'] as $category)<option value="{{ $category }}">{{ $category }}</option>@endforeach</select></label><label>Amount<input type="number" step="0.01" min="0.01" name="amount" required></label><label>Description<input name="description" required></label><label>Currency<input name="currency" value="SAR" maxlength="3" required></label><label>Receipt Ref<input name="receipt_ref"></label><div><button class="btn">Submit Expense</button></div></form>@endif
@forelse($mission->expenses as $expense)<div class="expense-row"><span><b>{{ $expense->category }} · {{ $expense->description }}</b><br><small>{{ $expense->expense_date->format('d M Y') }} · {{ $expense->receipt_ref ?: 'No receipt reference' }}</small></span><b>{{ number_format((float)$expense->amount,2) }} {{ $expense->currency }}</b><span class="state">{{ $expense->status }}</span><span>@if($expense->status==='SUBMITTED')<form style="display:inline" method="POST" action="{{ route('hr.missions.expenses.decide',[$mission->id,$expense->id]) }}">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn secondary">Approve</button></form><form style="display:inline" method="POST" action="{{ route('hr.missions.expenses.decide',[$mission->id,$expense->id]) }}">@csrf<input type="hidden" name="decision" value="REJECTED"><button class="btn secondary">Reject</button></form>@endif</span></div>@empty<div style="padding:16px;text-align:center;color:#7d899b">No expenses submitted.</div>@endforelse
</section>
<section class="m360-card wide"><h3>Settlement</h3><div class="settlement"><div><small>Per Diem</small><b>{{ number_format((float)$mission->per_diem_total,2) }}</b></div><div><small>Approved Expenses</small><b>{{ number_format((float)$approvedExpenses,2) }}</b></div><div><small>Company Payable</small><b>{{ number_format((float)$mission->company_payable,2) }}</b></div><div><small>Employee Refund Due</small><b>{{ number_format((float)$mission->employee_refund_due,2) }}</b></div></div>
@if(in_array($mission->status,['APPROVED','IN_PROGRESS'],true))<form class="actions" method="POST" action="{{ route('hr.missions.complete',$mission->id) }}">@csrf<input name="completion_notes" placeholder="Completion notes" style="min-width:280px"><button class="btn">Complete & Send to Settlement</button></form>@endif
@if($mission->status==='SETTLEMENT_PENDING')<form class="actions" method="POST" action="{{ route('hr.missions.settle',$mission->id) }}">@csrf<button class="btn success">Calculate & Close Settlement</button></form>@endif
@if($mission->status==='SETTLED')<p style="font-size:9px;color:#68768b">HR settlement is closed. Cash disbursement and accounting posting are not implied until Finance integration is explicitly executed.</p>@endif
</section></div>
@endsection
