@extends('layouts.app')
@section('title','Customer Portal · UNIFCO')
@section('heading','Customer Portal Administration')
@section('content')
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<div class="page-head"><div><h2 style="margin:0">{{ $customer->name }}</h2><p class="muted">Provision login access, contracts, covered assets and customer invoices.</p></div><a class="btn secondary" href="{{ route('crm.customers.index') }}">Back to customers</a></div>
<div class="grid" style="margin-top:16px">
<div class="card"><h3>Portal user</h3><form method="POST" action="{{ route('crm.customers.portal.users.store',$customer) }}">@csrf<div class="stack"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" value="{{ $customer->email }}" required></label><label>Temporary password<input type="password" name="password" required></label><label>Confirm password<input type="password" name="password_confirmation" required></label><button class="btn">Create customer login</button></div></form></div>
<div class="card"><h3>Service contract</h3><form method="POST" action="{{ route('crm.customers.portal.contracts.store',$customer) }}">@csrf<div class="stack"><label>Contract no<input name="contract_no" required></label><label>Title<input name="title" required></label><div class="form-grid"><label>Starts<input type="date" name="starts_on" required></label><label>Ends<input type="date" name="ends_on" required></label></div><div class="form-grid"><label>Value<input type="number" step="0.01" name="contract_value" value="0" required></label><label>Currency<input name="currency" value="SAR" maxlength="3" required></label><label>Billing cycle<select name="billing_cycle"><option>MONTHLY</option><option>QUARTERLY</option><option>ANNUAL</option><option>MILESTONE</option></select></label></div><label>Scope<textarea name="scope"></textarea></label><label>SLA summary<textarea name="sla_summary"></textarea></label><button class="btn">Create contract</button></div></form></div>
<div class="card"><h3>Assign covered asset</h3><form method="POST" action="{{ route('crm.customers.portal.assets.store',$customer) }}">@csrf<label>Asset<select name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} · {{ $asset->name }} {{ $asset->customer_id==$customer->id?'(assigned)':'' }}</option>@endforeach</select></label><button class="btn" style="margin-top:10px">Assign asset</button></form></div>
<div class="card"><h3>Link AR invoice</h3><form method="POST" action="{{ route('crm.customers.portal.invoices.store',$customer) }}">@csrf<label>Invoice<select name="financial_document_id" required>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->document_no }} · {{ $invoice->amount }} {{ $invoice->currency }} {{ $invoice->customer_id==$customer->id?'(linked)':'' }}</option>@endforeach</select></label><button class="btn" style="margin-top:10px">Link invoice</button></form></div>
</div>
<div class="card" style="margin-top:16px"><h3>Portal users</h3><table><thead><tr><th>Name</th><th>Email</th><th>Status</th></tr></thead><tbody>@forelse($portalUsers as $u)<tr><td>{{ $u->name }}</td><td>{{ $u->email }}</td><td>{{ $u->status }}</td></tr>@empty<tr><td colspan="3">No customer portal users yet.</td></tr>@endforelse</tbody></table></div>
<div class="card" style="margin-top:16px"><h3>Contracts</h3><table><thead><tr><th>No</th><th>Title</th><th>Dates</th><th>Value</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td>{{ $c->contract_no }}</td><td>{{ $c->title }}</td><td>{{ $c->starts_on?->format('Y-m-d') }} — {{ $c->ends_on?->format('Y-m-d') }}</td><td>{{ number_format((float)$c->contract_value,2) }} {{ $c->currency }}</td><td>{{ $c->status }}</td></tr>@empty<tr><td colspan="5">No contracts yet.</td></tr>@endforelse</tbody></table></div>
@endsection