@extends('layouts.app')
@section('title','Customer Onboarding · UNIFCO')
@section('heading','Customer Onboarding Center')
@section('content')
<style>
.onboard-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:24px;display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center}.onboard-hero h2{margin:0 0 5px;font-size:25px}.onboard-hero p{margin:0;color:#cbd9e9;font-size:12px}.status-chip{display:inline-flex;padding:6px 10px;border-radius:999px;background:#ffffff18;font-size:10px;font-weight:800;margin-top:10px}.progress-wrap{min-width:240px}.progress-label{display:flex;justify-content:space-between;font-size:11px;margin-bottom:7px}.progress{height:10px;background:#ffffff20;border-radius:20px;overflow:hidden}.progress span{display:block;height:100%;background:#e20b24;border-radius:20px}.steps{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:16px 0}.step-card{padding:13px;border:1px solid #dfe6ef;border-radius:11px;background:#fff;text-align:center}.step-card.done{border-color:#bfe5d0;background:#f1fbf5}.step-icon{width:28px;height:28px;border-radius:50%;margin:0 auto 6px;display:grid;place-items:center;background:#eef3f9;color:#06275c;font-weight:900}.step-card.done .step-icon{background:#16945f;color:#fff}.step-card b{display:block;font-size:10px}.onboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.onboard-card{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:18px}.onboard-card h3{margin:0 0 5px;color:#06275c}.onboard-card .muted{font-size:10px}.mini-list{display:grid;gap:7px;margin-top:12px}.mini-row{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #edf1f5;padding-top:8px;font-size:11px}.action-row{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.activate{background:#16945f!important}.role{font-size:9px;background:#edf4fd;color:#3268a5;padding:3px 7px;border-radius:6px}.section-title{margin:22px 0 10px;font-size:15px;color:#06275c}@media(max-width:1050px){.steps{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.onboard-hero{grid-template-columns:1fr}.progress-wrap{min-width:0}.steps,.onboard-grid{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<div class="onboard-hero"><div><h2>{{ $customer->name }}</h2><p>{{ $customer->customer_code }} · {{ $customer->industry ?: 'Customer onboarding' }} · {{ $customer->city ?: 'No city set' }}</p><span class="status-chip">{{ $customer->onboarding_status ?: 'ONBOARDING' }}</span></div><div class="progress-wrap"><div class="progress-label"><span>Onboarding progress</span><strong>{{ $progress }}%</strong></div><div class="progress"><span style="width:{{ $progress }}%"></span></div><div class="action-row"><a class="btn secondary" href="{{ route('crm.customers.edit',$customer) }}">Edit company data</a>@if($customer->onboarding_status!=='ACTIVE')<form method="POST" action="{{ route('crm.customers.portal.activate',$customer) }}">@csrf<button class="btn activate">Activate Customer</button></form>@endif</div></div></div>
<div class="steps">@foreach(['company'=>'Company','contacts'=>'Contacts','sites'=>'Sites','assets'=>'Assets','contracts'=>'Contracts','portal_users'=>'Portal Users'] as $key=>$label)<div class="step-card {{ $steps[$key]?'done':'' }}"><div class="step-icon">{{ $steps[$key]?'✓':'•' }}</div><b>{{ $label }}</b></div>@endforeach</div>
<div class="onboard-grid">
<div class="onboard-card"><h3>1 · Customer Contacts</h3><p class="muted">Add facility, maintenance, finance and emergency contacts.</p><form method="POST" action="{{ route('crm.customers.portal.contacts.store',$customer) }}">@csrf<div class="form-grid"><label>Name<input name="name" required></label><label>Job title<input name="job_title"></label><label>Type<select name="contact_type"><option>PRIMARY</option><option>FACILITY</option><option>MAINTENANCE</option><option>FINANCE</option><option>EMERGENCY</option><option>APPROVER</option></select></label><label>Email<input type="email" name="email"></label><label>Mobile<input name="mobile"></label><label><span>Primary contact</span><select name="is_primary"><option value="0">No</option><option value="1">Yes</option></select></label></div><button class="btn" style="margin-top:10px">Add Contact</button></form><div class="mini-list">@forelse($contacts as $c)<div class="mini-row"><span><strong>{{ $c->name }}</strong><br><small>{{ $c->job_title }} · {{ $c->contact_type }}</small></span><span>{{ $c->mobile ?: $c->email }}</span></div>@empty<p class="muted">No contacts added yet.</p>@endforelse</div></div>
<div class="onboard-card"><h3>2 · Customer Sites</h3><p class="muted">Create all operating locations before assigning equipment.</p><form method="POST" action="{{ route('crm.customers.portal.sites.store',$customer) }}">@csrf<div class="form-grid"><label>Site code<input name="site_code" required placeholder="RUH-HQ"></label><label>Site name<input name="name" required></label><label>City<input name="city"></label><label>Contact name<input name="contact_name"></label><label>Contact mobile<input name="contact_mobile"></label><label>Latitude<input type="number" step="0.0000001" name="latitude"></label><label>Longitude<input type="number" step="0.0000001" name="longitude"></label><label style="grid-column:1/-1">Address<textarea name="address"></textarea></label></div><button class="btn" style="margin-top:10px">Add Site</button></form><div class="mini-list">@forelse($sites as $s)<div class="mini-row"><span><strong>{{ $s->site_code }} · {{ $s->name }}</strong><br><small>{{ $s->city }} · {{ $s->address }}</small></span><span>{{ $s->status }}</span></div>@empty<p class="muted">No sites added yet.</p>@endforelse</div></div>
<div class="onboard-card"><h3>3 · Portal Users & Roles</h3><p class="muted">Create customer users with a specific portal responsibility.</p><form method="POST" action="{{ route('crm.customers.portal.users.store',$customer) }}">@csrf<div class="form-grid"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" value="{{ $customer->email }}" required></label><label>Portal Role<select name="customer_portal_role"><option>CUSTOMER_ADMIN</option><option>FACILITY_MANAGER</option><option>FINANCE</option><option>REQUESTER</option><option>VIEWER</option></select></label><label>Temporary password<input type="password" name="password" required></label><label>Confirm password<input type="password" name="password_confirmation" required></label></div><button class="btn" style="margin-top:10px">Create Portal User</button></form><div class="mini-list">@forelse($portalUsers as $u)<div class="mini-row"><span><strong>{{ $u->name }}</strong><br><small>{{ $u->email }}</small></span><span class="role">{{ $u->customer_portal_role ?: 'CUSTOMER' }}</span></div>@empty<p class="muted">No portal users yet.</p>@endforelse</div></div>
<div class="onboard-card"><h3>4 · Covered Assets</h3><p class="muted">Assign equipment to the customer. Site-level assignment will be expanded in the next batch.</p><form method="POST" action="{{ route('crm.customers.portal.assets.store',$customer) }}">@csrf<label>Asset<select name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} · {{ $asset->name }} {{ $asset->customer_id==$customer->id?'(assigned)':'' }}</option>@endforeach</select></label><button class="btn" style="margin-top:10px">Assign Asset</button></form><div class="action-row"><span class="role">{{ $assignedAssets }} assigned assets</span></div></div>
</div>
<h3 class="section-title">5 · Service Contract</h3><div class="card"><form method="POST" action="{{ route('crm.customers.portal.contracts.store',$customer) }}">@csrf<div class="form-grid"><label>Contract no<input name="contract_no" required></label><label>Title<input name="title" required></label><label>Starts<input type="date" name="starts_on" required></label><label>Ends<input type="date" name="ends_on" required></label><label>Value<input type="number" step="0.01" name="contract_value" value="0" required></label><label>Currency<input name="currency" value="SAR" maxlength="3" required></label><label>Billing cycle<select name="billing_cycle"><option>MONTHLY</option><option>QUARTERLY</option><option>ANNUAL</option><option>MILESTONE</option></select></label><label style="grid-column:1/-1">Scope<textarea name="scope"></textarea></label><label style="grid-column:1/-1">SLA summary<textarea name="sla_summary"></textarea></label></div><button class="btn" style="margin-top:10px">Create Contract</button></form></div>
<div class="card" style="margin-top:14px"><h3>Contracts</h3><table><thead><tr><th>No</th><th>Title</th><th>Dates</th><th>Value</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td>{{ $c->contract_no }}</td><td>{{ $c->title }}</td><td>{{ $c->starts_on?->format('Y-m-d') }} — {{ $c->ends_on?->format('Y-m-d') }}</td><td>{{ number_format((float)$c->contract_value,2) }} {{ $c->currency }}</td><td>{{ $c->status }}</td></tr>@empty<tr><td colspan="5">No contracts yet.</td></tr>@endforelse</tbody></table></div>
@endsection
