@extends('layouts.app')
@section('title','Field Operations · UNIFCO')
@section('heading','Field Operations')
@section('content')
<style>.ops-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.ops-card{background:#fff;border:1px solid #e3e8ef;border-radius:14px;padding:18px}.ops-table{overflow:auto}.ops-table table{min-width:720px}.ops-form{display:grid;gap:10px}.ops-form .row2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ops-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.ops-kpi{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:15px}.ops-kpi strong{display:block;color:#1e315b;font-size:25px}@media(max-width:900px){.ops-grid{grid-template-columns:1fr}.ops-kpis{grid-template-columns:1fr 1fr}}@media(max-width:520px){.ops-kpis,.ops-form .row2{grid-template-columns:1fr}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="ops-kpis"><div class="ops-kpi">Work orders<strong>{{ $workOrders->count() }}</strong></div><div class="ops-kpi">Assignments<strong>{{ $assignments->count() }}</strong></div><div class="ops-kpi">Inspections<strong>{{ $inspections->count() }}</strong></div><div class="ops-kpi">Templates<strong>{{ $templates->count() }}</strong></div></div>
<div class="ops-grid">
<section class="ops-card"><h2>Scheduling & Dispatch</h2><form class="ops-form" method="POST" action="{{ route('field.assign') }}">@csrf<div class="row2"><label>Work order<select name="work_order_id" required>@foreach($workOrders as $w)<option value="{{ $w->id }}">{{ $w->work_order_no }} · {{ $w->priority }}</option>@endforeach</select></label><label>Technician<select name="employee_id" required>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} · {{ $e->name }}</option>@endforeach</select></label></div><div class="row2"><label>Start<input type="datetime-local" name="scheduled_start" required></label><label>End<input type="datetime-local" name="scheduled_end"></label></div><label>Dispatch notes<textarea name="dispatcher_notes"></textarea></label><button class="btn">Dispatch work order</button></form></section>
<section class="ops-card"><h2>Inspection Template</h2><form class="ops-form" method="POST" action="{{ route('field.templates.store') }}">@csrf<div class="row2"><label>Template No<input name="template_no" required></label><label>Name<input name="name" required></label></div><label>Checklist — one item per line<textarea name="checklist" required></textarea></label><button class="btn">Create template</button></form></section>
</div>
<section class="ops-card" style="margin-top:16px"><h2>Dispatch Board</h2><div class="ops-table"><table><thead><tr><th>Work Order</th><th>Technician</th><th>Scheduled</th><th>Status</th><th>Notes</th></tr></thead><tbody>@forelse($assignments as $a)<tr><td>{{ optional($workOrders->firstWhere('id',$a->work_order_id))->work_order_no }}</td><td>{{ optional($employees->firstWhere('id',$a->employee_id))->name }}</td><td>{{ $a->scheduled_start?->format('Y-m-d H:i') }}</td><td><span class="pill">{{ $a->dispatch_status }}</span></td><td>{{ $a->dispatcher_notes }}</td></tr>@empty<tr><td colspan="5">No assignments yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="ops-card" style="margin-top:16px"><h2>Inspection History</h2><div class="ops-table"><table><thead><tr><th>No</th><th>Work Order</th><th>Status</th><th>Findings</th><th>Recommendations</th></tr></thead><tbody>@forelse($inspections as $i)<tr><td>{{ $i->inspection_no }}</td><td>{{ optional($workOrders->firstWhere('id',$i->work_order_id))->work_order_no }}</td><td>{{ $i->status }}</td><td>{{ $i->findings }}</td><td>{{ $i->recommendations }}</td></tr>@empty<tr><td colspan="5">No inspections yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
