@extends('layouts.app')
@section('title','Performance & Career | UNIFCO Platform')
@section('heading','Performance & Career')
@section('content')
<style>
.p7-hero{background:linear-gradient(135deg,#111f38,#1e315b 60%,#34517f);color:#fff;border-radius:18px;padding:24px;display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:14px}.p7-hero small{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#aebbd0;font-weight:800}.p7-hero h1{margin:5px 0;font-size:25px}.p7-hero p{margin:0;color:#dce4ef;font-size:11px;max-width:760px}.p7-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-bottom:14px}.p7-kpi,.p7-card{background:#fff;border:1px solid #e2e8f0;border-radius:13px}.p7-kpi{padding:13px}.p7-kpi small{display:block;font-size:8px;color:#7e8ca0;text-transform:uppercase;font-weight:800}.p7-kpi b{display:block;font-size:21px;margin-top:5px;color:#15233a}.p7-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.p7-card{padding:16px}.p7-card h3{margin:0 0 4px;font-size:13px}.p7-card>small{font-size:8px;color:#8491a2}.p7-list{display:grid;gap:6px;margin-top:10px}.p7-row{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#f7f9fc;padding:9px 10px;border-radius:9px;font-size:10px}.p7-row b{display:block}.p7-row small{display:block;color:#7d8a9b;margin-top:2px}.p7-pill{font-size:8px;font-weight:800;border-radius:999px;padding:4px 7px;background:#e9f4ef;color:#17734b}.p7-warn{background:#fff3df;color:#995d00}.p7-empty{padding:14px;text-align:center;color:#8290a2;background:#f8fafc;border-radius:9px;margin-top:10px;font-size:10px}.p7-form{margin-top:14px;background:#fff;border:1px solid #e2e8f0;border-radius:13px;padding:16px}.p7-actions{display:flex;gap:7px;flex-wrap:wrap}.p7-wide{grid-column:1/-1}@media(max-width:1200px){.p7-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:820px){.p7-grid{grid-template-columns:1fr}.p7-kpis{grid-template-columns:1fr 1fr}.p7-hero{display:block}.p7-actions{margin-top:12px}}@media(max-width:520px){.p7-kpis{grid-template-columns:1fr}}
</style>
<section class="p7-hero"><div><small>People / HR · Phase 7</small><h1>Performance & Career Command Center</h1><p>Goals, reviews, probation, skills, certifications, development plans, promotions and salary reviews in one employee-lifecycle workspace.</p></div><div class="p7-actions"><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a><a class="btn secondary" href="{{ route('hr.employees.index') }}">Employees</a></div></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="p7-kpis"><div class="p7-kpi"><small>Open Cycles</small><b>{{ $stats['open_cycles'] }}</b></div><div class="p7-kpi"><small>Open Goals</small><b>{{ $stats['open_goals'] }}</b></div><div class="p7-kpi"><small>Pending Reviews</small><b>{{ $stats['pending_reviews'] }}</b></div><div class="p7-kpi"><small>Probation Due</small><b>{{ $stats['probation_due'] }}</b></div><div class="p7-kpi"><small>Expiring Certs</small><b>{{ $stats['expiring_certifications'] }}</b></div><div class="p7-kpi"><small>Career Approvals</small><b>{{ $stats['career_actions'] }}</b></div></div>
<div class="p7-grid">
<section class="p7-card"><h3>Probation Reviews Due</h3><small>Employees whose probation ends in the next 30 days.</small><div class="p7-list">@forelse($probationDue as $e)<div class="p7-row"><span><b>{{ $e->employee_no }} · {{ $e->name }}</b><small>Ends {{ $e->probation_end_date?->format('d M Y') }}</small></span><a class="btn secondary" href="{{ route('hr.performance.employees.show',$e) }}">Review</a></div>@empty<div class="p7-empty">No probation reviews due.</div>@endforelse</div></section>
<section class="p7-card"><h3>Certification Expiry Watch</h3><small>Certifications expiring within 90 days.</small><div class="p7-list">@forelse($expiringSkills as $s)<div class="p7-row"><span><b>{{ $s->employee?->name }} · {{ $s->skill_name }}</b><small>{{ $s->issuer ?: 'Issuer not recorded' }}</small></span><span class="p7-pill p7-warn">{{ $s->expires_on?->format('d M Y') }}</span></div>@empty<div class="p7-empty">No certifications approaching expiry.</div>@endforelse</div></section>
<section class="p7-card"><h3>Recent Performance Reviews</h3><small>Latest manager evaluations and approval states.</small><div class="p7-list">@forelse($reviews as $r)<div class="p7-row"><span><b>{{ $r->employee?->name }} · {{ $r->review_type }}</b><small>{{ number_format((float)$r->overall_score,1) }}% · {{ str_replace('_',' ',$r->rating ?: 'UNRATED') }}</small></span><span class="p7-pill">{{ $r->status }}</span></div>@empty<div class="p7-empty">No reviews yet.</div>@endforelse</div></section>
<section class="p7-card"><h3>Career Actions</h3><small>Promotion, transfer and salary review approvals.</small><div class="p7-list">@forelse($career as $a)<div class="p7-row"><span><b>{{ $a->employee?->name }} · {{ str_replace('_',' ',$a->action_type) }}</b><small>{{ $a->toPosition?->title ?: 'Position unchanged' }} · {{ $a->effective_on?->format('d M Y') }}</small></span><span class="p7-pill {{ $a->status==='PENDING_APPROVAL'?'p7-warn':'' }}">{{ $a->status }}</span></div>@empty<div class="p7-empty">No career actions waiting.</div>@endforelse</div></section>
<section class="p7-card p7-wide"><h3>Performance Cycles</h3><small>Formal periods used for goals and reviews.</small><div class="p7-list">@forelse($cycles as $c)<div class="p7-row"><span><b>{{ $c->code }} · {{ $c->name }}</b><small>{{ $c->starts_on?->format('d M Y') }} → {{ $c->ends_on?->format('d M Y') }}</small></span><span class="p7-pill">{{ $c->status }}</span></div>@empty<div class="p7-empty">No performance cycles configured.</div>@endforelse</div></section>
</div>
<section class="p7-form"><h3>Create Performance Cycle</h3><form method="POST" action="{{ route('hr.performance.cycles.store') }}">@csrf<div class="form-grid"><label>Code<input name="code" required placeholder="PERF-2026"></label><label>Name<input name="name" required placeholder="2026 Annual Performance Cycle"></label><label>Starts on<input type="date" name="starts_on" required></label><label>Ends on<input type="date" name="ends_on" required></label></div><button class="btn">Create Cycle</button></form></section>
<section class="p7-form"><h3>Open Employee Performance 360</h3><div class="form-grid">@foreach($employees as $e)<a class="btn secondary" href="{{ route('hr.performance.employees.show',$e) }}">{{ $e->employee_no }} · {{ $e->name }}</a>@endforeach</div></section>
@endsection
