@extends('layouts.app')
@section('title',($mode==='create'?'New User':'Edit User').' | UNIFCO Platform')
@section('heading',$mode==='create'?'New User':'Edit User')
@section('content')
<style>
.wizard{max-width:980px}.wizard-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:12px}.wizard-hero h1{margin:0 0 5px;font-size:22px}.wizard-hero p{margin:0;color:#dce5f2;font-size:11px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.step-tab{border:1px solid #dfe6ef;background:#fff;color:#637189;border-radius:10px;padding:11px;text-align:left;font-size:10px;font-weight:800;cursor:pointer}.step-tab.active{background:#1e315b;color:#fff;border-color:#1e315b}.step-tab b{display:inline-grid;place-items:center;width:21px;height:21px;border-radius:50%;background:#edf2f8;color:#1e315b;margin-right:6px}.step-tab.active b{background:#fff}.step-panel{display:none;background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:18px}.step-panel.active{display:block}.step-panel h3{margin:0 0 5px;color:#132137;font-size:15px}.step-panel>p{margin:0 0 15px;color:#77869a;font-size:10px}.form-grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.step-panel label{font-size:10px;font-weight:700;color:#607086}.step-panel input,.step-panel select{width:100%}.multi{min-height:150px}.help{font-size:9px;color:#8190a4}.wizard-actions{display:flex;justify-content:space-between;gap:8px;margin-top:14px}.check{display:flex!important;align-items:center;gap:8px;padding:11px;border:1px solid #e5eaf1;border-radius:10px}.check input{width:auto}.security-note{padding:10px;background:#f5f8fc;border-radius:9px;color:#607086;font-size:9px}@media(max-width:700px){.form-grid2{grid-template-columns:1fr}.steps{grid-template-columns:1fr}.step-tab{display:none}.step-tab.active{display:block}}
</style>
@php($selectedRoleCodes=old('roles',$selectedRoleCodes??[])) @php($selectedPrimaryRole=old('primary_role',$selectedPrimaryRole??($selectedRoleCodes[0]??null))) @php($selectedScopeIds=old('scope_ids',$selectedScopeIds??[]))
<div class="wizard"><section class="wizard-hero"><h1>{{ $mode==='create'?'Create New User':'Edit '.$managedUser->name }}</h1><p>Identity → Access → Security. Roles and scopes remain separate and fully auditable.</p></section>
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $mode==='create'?route('admin.users.store'):route('admin.users.update',$managedUser) }}">@csrf @if($mode==='edit')@method('PUT')@endif
<div class="steps"><button type="button" class="step-tab active" data-step="1"><b>1</b>Identity</button><button type="button" class="step-tab" data-step="2"><b>2</b>Access</button><button type="button" class="step-tab" data-step="3"><b>3</b>Security</button></div>
<section class="step-panel active" data-panel="1"><h3>Identity</h3><p>Core account and organization information.</p><div class="form-grid2"><label>Name AR / الاسم<input name="name_ar" value="{{ old('name_ar',$managedUser->name_ar ?: $managedUser->name) }}" required></label><label>Name EN<input name="name_en" value="{{ old('name_en',$managedUser->name_en) }}"></label><input type="hidden" name="name" value="{{ old('name',$managedUser->name) }}"><label>Email<input type="email" name="email" value="{{ old('email',$managedUser->email) }}" required></label><label>Mobile<input name="mobile" value="{{ old('mobile',$managedUser->mobile) }}" placeholder="Optional"></label><label>Organization<select name="organization_id"><option value="">None</option>@foreach($organizations as $org)<option value="{{ $org->id }}" @selected((string)old('organization_id',$managedUser->organization_id)===(string)$org->id)>{{ $org->name }}</option>@endforeach</select></label><label>Employee / Job identity<select name="employee_id"><option value="">Not linked</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string)old('employee_id',$managedUser->employee_id)===(string)$employee->id)>{{ $employee->employee_no }} · {{ $employee->name }}</option>@endforeach</select></label></div><div class="wizard-actions"><a class="btn secondary" href="{{ route('workspace.show','users') }}">Cancel</a><button type="button" class="btn" data-next="2">Next: Access</button></div></section>
<section class="step-panel" data-panel="2"><h3>Access</h3><p>Assign one or more master roles, then constrain visible data with one or more scopes.</p><div class="form-grid2"><label>Role / Roles<select class="multi" id="role-select" name="roles[]" multiple required>@foreach($roles as $role)<option value="{{ $role->code }}" @selected(in_array($role->code,$selectedRoleCodes,true))>{{ $role->name_ar ?: $role->name_en }} · {{ $role->code }} · {{ $role->grants_business_authority?'Business':'System' }}</option>@endforeach</select><span class="help">Use Ctrl/Cmd to select multiple roles. Additional business authority must be a separate role.</span></label><div><label>Primary Role<select id="primary-role" name="primary_role">@foreach($roles as $role)<option value="{{ $role->code }}" @selected($selectedPrimaryRole===$role->code)>{{ $role->name_ar ?: $role->name_en }} · {{ $role->code }}</option>@endforeach</select><span class="help">Primary Role controls the default workspace only; permissions still merge from every assigned role.</span></label><label style="margin-top:12px">Scopes<select class="multi" name="scope_ids[]" multiple>@foreach($scopes as $scope)<option value="{{ $scope->id }}" @selected(in_array($scope->id,array_map('intval',$selectedScopeIds),true))>{{ $scope->scope_type }} · {{ $scope->name ?: '#'.$scope->scope_id }}</option>@endforeach</select><span class="help">Scope limits data visibility; it never grants a missing permission.</span></label></div></div><div class="security-note">Explicit Deny overrides every Allow across multiple roles. System Administrator grants system authority only; assign a separate business role when required.</div><div class="wizard-actions"><button type="button" class="btn secondary" data-next="1">Back</button><button type="button" class="btn" data-next="3">Next: Security</button></div></section>
<section class="step-panel" data-panel="3"><h3>Security</h3><p>Invite-based setup avoids sending or displaying reusable credentials.</p><div class="form-grid2"><label>Status<select name="status" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status',$managedUser->status ?: 'ACTIVE')===$status)>{{ $status }}</option>@endforeach</select></label>@if($mode==='create')<label class="check"><input type="checkbox" name="send_invitation" value="1" @checked(old('send_invitation',true))><span>Send secure invitation (72 hours)</span></label><input type="hidden" name="password" value=""><input type="hidden" name="password_confirmation" value="">@endif<label class="check"><input type="checkbox" checked disabled><span>Require password change at first setup</span></label><label class="check"><input type="checkbox" disabled><span>MFA enrollment (architecture ready; provider pending)</span></label></div><div class="security-note">Passwords are hashed and cannot be viewed or recovered. Reset Password creates an audited reset action and revokes existing sessions.</div><div class="wizard-actions"><button type="button" class="btn secondary" data-next="2">Back</button><button class="btn">{{ $mode==='create'?'Create & Send Invitation':'Save Changes' }}</button></div></section>
</form></div>
<script>(()=>{const show=n=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===String(n)));document.querySelectorAll('[data-step]').forEach(x=>x.classList.toggle('active',x.dataset.step===String(n)));};document.querySelectorAll('[data-step],[data-next]').forEach(x=>x.addEventListener('click',()=>show(x.dataset.step||x.dataset.next)));const roles=document.getElementById('role-select'),primary=document.getElementById('primary-role');const sync=()=>{const selected=[...roles.selectedOptions].map(x=>x.value);[...primary.options].forEach(x=>x.hidden=!selected.includes(x.value));if(!selected.includes(primary.value))primary.value=selected[0]||''};roles?.addEventListener('change',sync);sync();})();</script>
@endsection
