@extends('layouts.app')
@section('title','Users | UNIFCO Platform')
@section('heading','Users')
@section('content')
<style>
.users-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:14px;display:flex;justify-content:space-between;align-items:center;gap:16px}.users-hero small{color:#aebbd0;text-transform:uppercase;letter-spacing:.12em;font-size:9px;font-weight:800}.users-hero h1{margin:5px 0;font-size:23px}.users-hero p{margin:0;color:#dce5f2;font-size:12px}.users-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.users-kpi{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:14px}.users-kpi span{display:block;color:#77859a;font-size:9px;text-transform:uppercase;font-weight:800;letter-spacing:.05em}.users-kpi b{display:block;color:#132137;font-size:25px;margin-top:5px}.users-toolbar{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:12px;margin-bottom:12px}.users-filters{display:grid;grid-template-columns:minmax(220px,2fr) repeat(3,minmax(130px,1fr)) auto;gap:8px;align-items:end}.users-filters label{font-size:9px;color:#66758a;font-weight:700}.users-filters input,.users-filters select{width:100%;background:#fff}.users-table-wrap{background:#fff;border:1px solid #e3e8ef;border-radius:12px;overflow:hidden}.users-table{margin:0;display:table;border-radius:0}.users-table th{background:#f7f9fc;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:.05em}.users-table td{font-size:11px;vertical-align:middle}.user-cell{display:flex;align-items:center;gap:9px}.user-avatar{width:32px;height:32px;border-radius:50%;background:#e9eef6;color:#1e315b;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:10px}.user-cell b{display:block;color:#17243c}.user-cell small{color:#7c899b}.status{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border-radius:999px;background:#edf8f2;color:#17734b;font-size:9px;font-weight:800}.status.off{background:#f5f1f2;color:#8a4a55}.role{padding:4px 7px;border-radius:7px;background:#eef3fa;color:#1e315b;font-size:9px;font-weight:800}.actions{display:flex;gap:5px;flex-wrap:wrap}.actions a{font-size:9px;padding:6px 8px}.users-footer{padding:10px 12px}.empty-users{padding:32px;text-align:center;color:#718096}.security-links{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:900px){.users-kpis{grid-template-columns:1fr 1fr}.users-filters{grid-template-columns:1fr 1fr}.users-table{display:block;overflow-x:auto}}@media(max-width:600px){.users-hero{display:block}.security-links{margin-top:12px}.users-kpis,.users-filters{grid-template-columns:1fr}}
</style>
<section class="users-hero"><div><small>Administration · Access & Security</small><h1>User Management</h1><p>Manage platform identities, access roles, organization assignment and account status.</p></div><div class="security-links"><a class="btn secondary" href="{{ route('admin.permissions.index') }}">Roles & Permissions</a><a class="btn secondary" href="{{ route('admin.audit.index') }}">Audit Trail</a></div></section>
<div class="users-kpis"><div class="users-kpi"><span>Total Users</span><b>{{ $stats['total'] }}</b></div><div class="users-kpi"><span>Active</span><b>{{ $stats['active'] }}</b></div><div class="users-kpi"><span>Inactive / Suspended</span><b>{{ $stats['inactive'] }}</b></div><div class="users-kpi"><span>Administrators</span><b>{{ $stats['admins'] }}</b></div></div>
<section class="users-toolbar"><form class="users-filters" method="GET"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Name or email"></label><label>Role<select name="role"><option value="">All Roles</option>@foreach($roles as $role)<option value="{{ $role }}" @selected(request('role')===$role)>{{ $role }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All Statuses</option><option value="ACTIVE" @selected(request('status')==='ACTIVE')>ACTIVE</option><option value="INACTIVE" @selected(request('status')==='INACTIVE')>INACTIVE</option><option value="SUSPENDED" @selected(request('status')==='SUSPENDED')>SUSPENDED</option></select></label><label>Organization<select name="organization_id"><option value="">All Organizations</option>@foreach($organizationNames as $id=>$name)<option value="{{ $id }}" @selected((string)request('organization_id')===(string)$id)>{{ $name }}</option>@endforeach</select></label><div style="display:flex;gap:6px"><button class="btn" type="submit">Apply</button><a class="btn secondary" href="{{ route('workspace.show','users') }}">Reset</a></div></form></section>
<section class="users-table-wrap"><table class="users-table"><thead><tr><th>User</th><th>Role</th><th>Organization</th><th>Employee</th><th>Status</th><th>Security</th><th>Actions</th></tr></thead><tbody>@forelse($users as $user)<tr><td><div class="user-cell"><span class="user-avatar">{{ strtoupper(substr($user->name,0,1).(str_contains($user->name,' ')?substr(strrchr($user->name,' '),1,1):'')) }}</span><span><b>{{ $user->name }}</b><small>{{ $user->email }}</small></span></div></td><td><span class="role">{{ $user->role }}</span></td><td>{{ $organizationNames[$user->organization_id] ?? '—' }}</td><td>{{ $user->employee_id ? '#'.$user->employee_id : '—' }}</td><td><span class="status {{ $user->status==='ACTIVE'?'':'off' }}">● {{ $user->status }}</span></td><td>{{ $user->id===auth()->id() ? 'Current session' : 'Protected account' }}</td><td><div class="actions"><a class="btn secondary" href="{{ route('admin.permissions.index') }}">Permissions</a><a class="btn secondary" href="{{ route('admin.audit.index') }}">Audit</a></div></td></tr>@empty<tr><td colspan="7" class="empty-users">No users match the selected filters.</td></tr>@endforelse</tbody></table><div class="users-footer">{{ $users->links() }}</div></section>
@endsection
