@extends('layouts.app')
@section('title',$managedUser->name.' | User Profile')
@section('heading','User Profile')
@section('content')
<style>
.profile-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:14px;display:flex;justify-content:space-between;gap:16px;align-items:center}.profile-id{display:flex;gap:12px;align-items:center}.profile-avatar{width:54px;height:54px;border-radius:50%;background:#fff;color:#1e315b;display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:900}.profile-hero h1{margin:0 0 3px;font-size:22px}.profile-hero p{margin:0;color:#cbd6e5;font-size:11px}.profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.panel{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:16px}.panel.wide{grid-column:1/-1}.panel h3{margin:0 0 11px;color:#17243c;font-size:13px}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.detail{background:#f8fafc;border-radius:9px;padding:10px}.detail small{display:block;color:#8491a3;font-size:8px;text-transform:uppercase}.detail b{display:block;margin-top:4px;font-size:11px}.inline-actions{display:flex;gap:6px;flex-wrap:wrap}.inline-actions form{display:inline}.danger{background:#9e1b32}.warn{background:#b26b12}.success{background:#17734b}.password-form,.permission-form{display:grid;grid-template-columns:1fr 1fr auto;gap:7px;align-items:end}.permission-list,.timeline,.token-list{display:grid;gap:5px;margin-top:10px}.permission-row,.timeline-row,.token-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:8px 9px;background:#f7f9fc;border-radius:8px;font-size:10px}.timeline-row{align-items:flex-start}.timeline-row small,.token-row small{color:#7a889b}.badge{padding:3px 6px;border-radius:999px;background:#eaf0f8;color:#1e315b;font-size:8px;font-weight:800}.badge.allow{background:#e8f7ee;color:#17734b}.badge.deny{background:#fdecec;color:#9f1f1f}.badge.warn{background:#fff5e8;color:#9a5b00}.badge.bad{background:#fdecec;color:#9f1f1f}.security-note{padding:10px;background:#f8fafc;border-radius:9px;color:#68758a;font-size:10px;margin-top:10px}.security-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.security-card{padding:10px;background:#f8fafc;border-radius:9px}.security-card small{display:block;font-size:8px;color:#8491a3;text-transform:uppercase}.security-card b{display:block;margin-top:4px;font-size:11px}.security-actions{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px}.security-actions form,.security-actions button{width:100%}.token-row form{margin:0}@media(max-width:950px){.profile-grid{grid-template-columns:1fr}.panel.wide{grid-column:auto}.security-grid{grid-template-columns:1fr 1fr}.security-actions{grid-template-columns:1fr 1fr}.profile-hero{display:block}.inline-actions{margin-top:12px}.password-form,.permission-form{grid-template-columns:1fr}}@media(max-width:560px){.detail-grid,.security-grid,.security-actions{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="profile-hero"><div class="profile-id"><span class="profile-avatar">{{ strtoupper(substr($managedUser->name,0,1)) }}</span><div><h1>{{ $managedUser->name }}</h1><p>{{ $managedUser->email }} · {{ $managedUser->role }} · {{ $managedUser->status }}</p></div></div><div class="inline-actions"><a class="btn secondary" href="{{ route('admin.users.edit',$managedUser) }}">Edit User</a><a class="btn secondary" href="{{ route('workspace.show','users') }}">Back to Users</a></div></section>
<div class="profile-grid">
<section class="panel"><h3>Identity & Assignment</h3><div class="detail-grid"><div class="detail"><small>Role</small><b>{{ $managedUser->role }}</b></div><div class="detail"><small>Status</small><b>{{ $managedUser->status }}</b></div><div class="detail"><small>Organization</small><b>{{ optional($organizations->firstWhere('id',$managedUser->organization_id))->name ?? '—' }}</b></div><div class="detail"><small>Employee</small><b>{{ optional($employees->firstWhere('id',$managedUser->employee_id))->name ?? 'Not linked' }}</b></div></div><h3 style="margin-top:15px">Account Status</h3><div class="inline-actions">@foreach(['ACTIVE'=>'Activate','INACTIVE'=>'Deactivate','SUSPENDED'=>'Suspend'] as $value=>$label)<form method="POST" action="{{ route('admin.users.status',$managedUser) }}">@csrf<input type="hidden" name="status" value="{{ $value }}"><button class="btn {{ $value==='ACTIVE'?'success':($value==='SUSPENDED'?'danger':'warn') }}" @disabled($managedUser->status===$value)>{{ $label }}</button></form>@endforeach</div></section>
<section class="panel"><h3>Security Summary</h3><div class="security-grid"><div class="security-card"><small>Last Login</small><b>{{ $managedUser->last_login_at?->format('d M Y H:i') ?? 'Never' }}</b></div><div class="security-card"><small>MFA</small><b>{{ str_replace('_',' ',$managedUser->mfa_status ?? 'NOT_CONFIGURED') }}</b></div><div class="security-card"><small>Account Lock</small><b>{{ $managedUser->locked_at ? 'LOCKED' : 'UNLOCKED' }}</b></div><div class="security-card"><small>Password Change</small><b>{{ $managedUser->force_password_change ? 'REQUIRED' : 'NORMAL' }}</b></div></div><div class="security-actions">@foreach(['LOCK'=>'Lock','UNLOCK'=>'Unlock','REQUIRE_PASSWORD_CHANGE'=>'Require Password Change','CLEAR_PASSWORD_CHANGE'=>'Clear Password Flag','REVOKE_SESSIONS'=>'Revoke Sessions'] as $action=>$label)<form method="POST" action="{{ route('admin.users.security',$managedUser) }}">@csrf<input type="hidden" name="action" value="{{ $action }}"><button class="btn {{ in_array($action,['LOCK','REVOKE_SESSIONS'])?'danger':'secondary' }}">{{ $label }}</button></form>@endforeach</div><div class="security-note">Session revocation is enforced through a server-side account session version. MFA is reported truthfully as not configured until real enrollment/TOTP support is added.</div></section>
<section class="panel" id="password"><h3>Reset Password</h3><form class="password-form" method="POST" action="{{ route('admin.users.reset-password',$managedUser) }}">@csrf<label>New Password<input type="password" name="password" minlength="8" required></label><label>Confirm<input type="password" name="password_confirmation" minlength="8" required></label><button class="btn">Reset Password</button></form><div class="security-note">A password reset revokes existing sessions and marks the account for password change.</div></section>
<section class="panel"><h3>API Tokens</h3><div class="token-list">@forelse($apiTokens as $token)<div class="token-row"><span><b>{{ $token->name }}</b><small>{{ $token->isActive()?'Active':'Revoked / Expired' }} · Last used {{ $token->last_used_at?->format('d M Y H:i') ?? 'Never' }}</small></span>@if($token->isActive())<form method="POST" action="{{ route('admin.users.api-tokens.revoke',[$managedUser,$token]) }}">@csrf<button class="btn danger">Revoke</button></form>@endif</div>@empty<div class="security-note">No API tokens issued to this user.</div>@endforelse</div></section>
<section class="panel wide" id="permissions"><h3>User-specific Permission Overrides</h3>@if($managedUser->role==='ADMIN')<div class="security-note">Administrators have implicit full access. User-specific overrides are disabled for ADMIN accounts.</div>@else<form class="permission-form" method="POST" action="{{ route('admin.users.permission',$managedUser) }}">@csrf<label>Permission Code<input name="permission_code" placeholder="e.g. inventory.stock.move" required></label><label>Effect<select name="effect"><option value="ALLOW">Allow</option><option value="DENY">Deny</option><option value="INHERIT">Remove override / inherit role</option></select></label><button class="btn">Apply Override</button></form><div class="permission-list">@forelse($overrides as $override)<div class="permission-row"><span>{{ $override->permission_code }}</span><span class="badge {{ $override->allowed?'allow':'deny' }}">{{ $override->allowed?'ALLOW':'DENY' }}</span></div>@empty<div class="security-note">No user-specific overrides. Access follows the assigned role.</div>@endforelse</div>@endif<h3 style="margin-top:18px">Role Permissions</h3><div class="permission-list">@forelse($permissions as $permission)<div class="permission-row"><span>{{ $permission }}</span><span class="badge">Inherited</span></div>@empty<div class="security-note">No role permissions configured for this role.</div>@endforelse</div></section>
<section class="panel wide"><h3>Recent Audit Timeline</h3><div class="timeline">@forelse($auditTimeline as $event)<div class="timeline-row"><span><b>{{ $event->action }}</b><small>{{ $event->created_at }}</small></span><span class="badge">#{{ $event->id }}</span></div>@empty<div class="security-note">No recorded user-administration events yet.</div>@endforelse</div></section>
</div>
@endsection
