@extends('layouts.app')
@section('title','System Administration | UNIFCO Platform')
@section('heading','System Administration')
@section('content')
@php($integrationSummary=app(\App\Services\IntegrationHealthService::class)->summary(auth()->user()->tenant_id))
<style>
.sys-page{max-width:1500px;margin:0 auto}.sys-eyebrow{font-size:8px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:#aebbd0}.sys-hero{background:linear-gradient(135deg,#111f35 0%,#1e315b 72%,#263e6b 100%);color:#fff;border-radius:14px;padding:18px 20px;display:flex;justify-content:space-between;align-items:center;gap:18px;box-shadow:0 12px 30px rgba(19,33,55,.11)}.sys-hero h1{font-size:22px;margin:4px 0 5px;letter-spacing:-.015em}.sys-hero p{font-size:10.5px;line-height:1.55;color:#dce5f2;margin:0;max-width:720px}.system-state{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#ffffff14;border:1px solid #ffffff1f;font-size:9px;font-weight:900;white-space:nowrap}.system-state:before{content:'';width:8px;height:8px;border-radius:50%;background:#41d18b;box-shadow:0 0 0 4px rgba(65,209,139,.12)}.system-state.WARNING:before{background:#f3b64c}.system-state.DEGRADED:before{background:#f0833f}.system-state.CRITICAL:before{background:#f04b5f}
.sys-health-strip{display:flex;gap:7px;flex-wrap:wrap;padding:10px 12px;background:#fff;border:1px solid #e4e9f0;border-radius:11px;margin-top:10px;box-shadow:0 3px 12px rgba(19,33,55,.03)}.health-chip{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;background:#f7f9fb;border-radius:999px;font-size:8.5px;color:#4f5d71;font-weight:750}.health-chip:before{content:'';width:7px;height:7px;border-radius:50%;background:#8b98aa}.health-chip.ok:before{background:#168453}.health-chip.warn:before{background:#d98b10}.health-chip.bad:before{background:#b42318}
.sys-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px;margin:10px 0}.sys-kpi{background:#fff;border:1px solid #e4e9f0;border-radius:11px;padding:12px;position:relative;overflow:hidden;box-shadow:0 3px 12px rgba(19,33,55,.025)}.sys-kpi:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:#dce3ec}.sys-kpi.alert:before{background:#ce122d}.sys-kpi.good:before{background:#168453}.sys-kpi small{font-size:7.8px;color:#748297;font-weight:850;text-transform:uppercase;letter-spacing:.04em}.sys-kpi b{display:block;color:#132137;font-size:22px;margin-top:4px;line-height:1}.sys-kpi span{display:block;color:#93a0b1;font-size:7.5px;margin-top:5px}
.sys-actions{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0 12px}.sys-actions .btn{font-size:9px;padding:7px 10px;border-radius:8px}.sys-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:11px}.sys-panel{background:#fff;border:1px solid #e4e9f0;border-radius:12px;padding:14px;box-shadow:0 4px 14px rgba(19,33,55,.035)}.sys-panel-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:6px}.sys-panel h3{font-size:11.5px;color:#132137;margin:0}.sys-panel-head small{font-size:8px;color:#8693a5}.sys-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 5px;border-bottom:1px solid #edf0f5;font-size:9.5px;text-decoration:none;color:#172033;transition:background .14s ease}.sys-row:hover{background:#f8fafc}.sys-row:last-child{border:0}.sys-row small{color:#7b899c;display:block;margin-top:2px;line-height:1.35}.sys-row b{font-size:9.5px}.sys-empty{padding:24px 12px;text-align:center;color:#8592a4;font-size:9px;background:#fafbfd;border-radius:9px}.sys-timeline{position:relative}.sys-timeline .sys-row{padding-left:22px}.sys-timeline .sys-row:before{content:'';position:absolute;left:7px;width:7px;height:7px;border-radius:50%;background:#1e315b;box-shadow:0 0 0 3px #edf2f8}.severity{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3f8;color:#526277;font-size:8px;font-weight:850}.severity.HIGH,.severity.CRITICAL{background:#fdecec;color:#a52424}.severity.WARNING,.severity.MEDIUM{background:#fff5e5;color:#996000}.severity.LOW,.severity.INFO{background:#eaf7f0;color:#16744b}
@media(max-width:1100px){.sys-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.sys-hero{align-items:flex-start;flex-direction:column}.sys-grid{grid-template-columns:1fr}.sys-kpis{grid-template-columns:repeat(2,1fr)}.sys-health-strip{overflow:auto;flex-wrap:nowrap}.health-chip{white-space:nowrap}.sys-actions{overflow:auto;flex-wrap:nowrap;padding-bottom:3px}.sys-actions .btn{white-space:nowrap}}
</style>
<div class="sys-page">
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="sys-hero"><div><div class="sys-eyebrow">SYSTEM AUTHORITY · IT GOVERNANCE</div><h1>System Administrator</h1><p>Central control for identity, access, security, integrations and immutable audit. Operational, financial and contractual execution remains intentionally outside this role.</p></div><span class="system-state {{ $status }}">{{ $status }}</span></section>
<div class="sys-health-strip" aria-label="System health">
@foreach($integrationSummary['rows'] as $row)<span class="health-chip {{ in_array($row->status,['OPERATIONAL','READY'])?'ok':(in_array($row->status,['PENDING','DEGRADED'])?'warn':'bad') }}">{{ $row->name }} · {{ $row->status }}</span>@endforeach
@if($integrationSummary['rows']->isEmpty())<span class="health-chip warn">Integration health not initialized</span>@endif
</div>
<div class="sys-kpis">
<div class="sys-kpi good"><small>Active Users</small><b>{{ $kpis['active_users'] }}</b><span>Internal platform users</span></div>
<div class="sys-kpi"><small>Portal Users</small><b>{{ $kpis['customer_users'] }}</b><span>Customer access accounts</span></div>
<div class="sys-kpi"><small>Active Sessions</small><b>{{ $kpis['active_sessions'] }}</b><span>Live authenticated sessions</span></div>
<div class="sys-kpi {{ $kpis['failed_logins']?'alert':'' }}"><small>Failed Logins · 24h</small><b>{{ $kpis['failed_logins'] }}</b><span>Security monitoring</span></div>
<div class="sys-kpi {{ $kpis['system_alerts']?'alert':'' }}"><small>System Alerts</small><b>{{ $kpis['system_alerts'] }}</b><span>Items needing attention</span></div>
<div class="sys-kpi {{ $kpis['integrations']===$kpis['integration_total']?'good':'' }}"><small>Integration Health</small><b>{{ $kpis['integrations'] }}/{{ $kpis['integration_total'] }}</b><span>Healthy registered services</span></div>
</div>
<div class="sys-actions"><a class="btn" href="{{ route('workspace.show','users') }}">Users & Access</a><a class="btn secondary" href="{{ route('admin.permissions.index') }}">Roles & Permissions</a><a class="btn secondary" href="{{ route('admin.system.login-activity') }}">Login Activity</a><a class="btn secondary" href="{{ route('admin.system.sessions') }}">Active Sessions</a><a class="btn secondary" href="{{ route('admin.system.security-events') }}">Security Events</a><a class="btn secondary" href="{{ route('admin.system.integrations') }}">Integrations & Health</a><a class="btn secondary" href="{{ route('admin.system.scope-audit') }}">Scope Audit</a><a class="btn secondary" href="{{ route('admin.audit.index') }}">Audit Trail</a></div>
<div class="sys-grid">
<section class="sys-panel"><div class="sys-panel-head"><h3>Users & Access</h3><small>Recent access activity</small></div>@forelse($recentUsers as $user)<a class="sys-row" href="{{ route('admin.users.show',$user) }}"><span><b>{{ $user->name }}</b><small>{{ $user->employee?->position?->department ?? ($user->customer_id?'External':'No department') }} · {{ $user->accessScopes->pluck('name')->filter()->join(', ') ?: 'No scope' }}</small></span><span style="text-align:right"><b>{{ $user->activeRoles->pluck('code')->join(' + ') ?: $user->role }}</b><small>{{ $user->status }} · {{ $user->last_login_at?->diffForHumans() ?? 'Never logged in' }}</small></span></a>@empty<div class="sys-empty">No users available.</div>@endforelse</section>
<section class="sys-panel"><div class="sys-panel-head"><h3>System Alerts</h3><small>{{ $kpis['system_alerts'] }} active</small></div>@if($failedJobs)<div class="sys-row"><span><b>Background job failure</b><small>{{ $failedJobs }} failed in the last 24 hours</small></span><span class="severity HIGH">HIGH</span></div>@endif @forelse($events as $event)<div class="sys-row"><span><b>{{ str_replace('_',' ',$event->event_type) }}</b><small>{{ $event->occurred_at }}</small></span><span class="severity {{ $event->severity }}">{{ $event->severity }}</span></div>@empty @if(!$failedJobs)<div class="sys-empty">No active security alerts.</div>@endif @endforelse</section>
</div>
<section class="sys-panel" style="margin-top:11px"><div class="sys-panel-head"><h3>Recent System Activity</h3><small>Immutable audit stream</small></div><div class="sys-timeline">@forelse($activity as $event)<div class="sys-row"><span><b>{{ $event->action }}</b><small>{{ $event->created_at }} · {{ $event->ip_address ?? 'IP not recorded' }}</small></span><span class="severity">{{ $event->entity_type ? class_basename($event->entity_type).' #'.$event->entity_id : 'SYSTEM' }}</span></div>@empty<div class="sys-empty">No audit activity recorded.</div>@endforelse</div></section>
</div>
@endsection
