@extends('layouts.app')
@section('title','System Administration | UNIFCO Platform')
@section('heading','System Administration')
@section('content')
<style>
.sys-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;display:flex;justify-content:space-between;align-items:center;gap:18px}.sys-hero h1{font-size:23px;margin:3px 0}.sys-hero p{font-size:11px;color:#dce5f2;margin:0}.system-state{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;background:#ffffff18;font-size:10px;font-weight:900}.system-state:before{content:'';width:8px;height:8px;border-radius:50%;background:#41d18b}.system-state.WARNING:before{background:#f3b64c}.system-state.DEGRADED:before{background:#f0833f}.system-state.CRITICAL:before{background:#f04b5f}.sys-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin:13px 0}.sys-kpi,.sys-panel{background:#fff;border:1px solid #e3e8ef;border-radius:12px}.sys-kpi{padding:13px}.sys-kpi small{font-size:8px;color:#748297;font-weight:800;text-transform:uppercase}.sys-kpi b{display:block;color:#132137;font-size:22px;margin-top:4px}.sys-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:12px;margin-top:12px}.sys-panel{padding:15px}.sys-panel h3{font-size:12px;color:#132137;margin:0 0 10px}.sys-row{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #edf0f5;font-size:10px}.sys-row:last-child{border:0}.sys-row small{color:#7b899c;display:block;margin-top:2px}.sys-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}@media(max-width:1100px){.sys-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.sys-grid{grid-template-columns:1fr}.sys-kpis{grid-template-columns:repeat(2,1fr)}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="sys-hero"><div><small>SYSTEM AUTHORITY · IT GOVERNANCE</small><h1>System Administrator</h1><p>Users, access, security, integrations and audit — operational transactions are intentionally excluded.</p></div><span class="system-state {{ $status }}">{{ $status }}</span></section>
<div class="sys-kpis"><div class="sys-kpi"><small>Active Users</small><b>{{ $kpis['active_users'] }}</b></div><div class="sys-kpi"><small>Customer Portal Users</small><b>{{ $kpis['customer_users'] }}</b></div><div class="sys-kpi"><small>Active Sessions</small><b>{{ $kpis['active_sessions'] }}</b></div><div class="sys-kpi"><small>Failed Logins · 24h</small><b>{{ $kpis['failed_logins'] }}</b></div><div class="sys-kpi"><small>System Alerts</small><b>{{ $kpis['system_alerts'] }}</b></div><div class="sys-kpi"><small>Active Integrations</small><b>{{ $kpis['integrations'] }}</b></div></div>
<div class="sys-actions"><a class="btn" href="{{ route('workspace.show','users') }}">Users & Access</a><a class="btn secondary" href="{{ route('admin.permissions.index') }}">Roles & Permissions</a><a class="btn secondary" href="{{ route('admin.system.sessions') }}">Active Sessions</a><a class="btn secondary" href="{{ route('admin.system.security-events') }}">Security Events</a><a class="btn secondary" href="{{ route('admin.system.scheduled-jobs') }}">Scheduled Jobs</a><a class="btn secondary" href="{{ route('admin.audit.index') }}">Immutable Audit Trail</a></div>
<div class="sys-grid"><section class="sys-panel"><h3>Users & Access</h3>@forelse($recentUsers as $user)<a class="sys-row" href="{{ route('admin.users.show',$user) }}"><span><b>{{ $user->name }}</b><small>{{ $user->employee?->position?->department ?? ($user->customer_id?'External':'No department') }} · {{ $user->accessScopes->pluck('name')->filter()->join(', ') ?: 'No scope' }}</small></span><span><b>{{ $user->activeRoles->pluck('code')->join(' + ') ?: $user->role }}</b><small>{{ $user->status }} · {{ $user->last_login_at?->diffForHumans() ?? 'Never logged in' }}</small></span></a>@empty<div class="muted">No users.</div>@endforelse</section><section class="sys-panel"><h3>System Alerts</h3>@if($failedJobs)<div class="sys-row"><span><b>Background job failure</b><small>{{ $failedJobs }} failed in the last 24 hours · inspect Scheduled Jobs</small></span><span class="pill">HIGH</span></div>@endif @forelse($events as $event)<div class="sys-row"><span><b>{{ str_replace('_',' ',$event->event_type) }}</b><small>{{ $event->occurred_at }}</small></span><span class="pill">{{ $event->severity }}</span></div>@empty @if(!$failedJobs)<div class="muted">No security alerts.</div>@endif @endforelse</section></div>
<section class="sys-panel" style="margin-top:12px"><h3>System Activity & Audit</h3>@forelse($activity as $event)<div class="sys-row"><span><b>{{ $event->action }}</b><small>{{ $event->created_at }} · {{ $event->ip_address ?? 'IP not recorded' }}</small></span><span class="pill">{{ $event->entity_type ? class_basename($event->entity_type).' #'.$event->entity_id : 'SYSTEM' }}</span></div>@empty<div class="muted">No audit activity.</div>@endforelse</section>
@endsection
