@extends('layouts.app')
@section('title','Integrations & Health | UNIFCO Platform')
@section('heading','Integrations & Health')
@section('content')
@include('admin.system.operations-styles')
@php($health=app(\App\Services\IntegrationHealthService::class))
@php($summary=request()->boolean('refresh')?$health->refresh(auth()->user()->tenant_id):$health->summary(auth()->user()->tenant_id))
<style>
.health-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0}.health-card{background:#fff;border:1px solid #e4e9f0;border-radius:11px;padding:13px;box-shadow:0 3px 12px rgba(19,33,55,.025)}.health-card small{font-size:8px;text-transform:uppercase;letter-spacing:.04em;color:#78869a;font-weight:800}.health-card b{font-size:23px;color:#132137;display:block;margin-top:4px}.health-card .sub{font-size:8px;color:#8a97a8;margin-top:4px}.integration-row{display:grid;grid-template-columns:1.35fr .75fr .75fr .8fr 1.15fr;gap:10px;align-items:center;padding:11px 6px;border-bottom:1px solid #edf0f5;font-size:9.5px;transition:background .15s ease}.integration-row:not(.head):hover{background:#fafbfd}.integration-row:last-child{border-bottom:0}.integration-row.head{font-weight:800;color:#66758a;text-transform:uppercase;font-size:8px;letter-spacing:.04em;background:#fafbfd;border-radius:8px;padding:9px 6px}.integration-row small{display:block;color:#8693a5;margin-top:3px;line-height:1.4}.state{display:inline-flex;align-items:center;gap:6px;font-weight:850}.state:before{content:'';width:7px;height:7px;border-radius:50%;background:#8b98aa}.state.OPERATIONAL,.state.READY{color:#168453}.state.OPERATIONAL:before,.state.READY:before{background:#168453}.state.PENDING,.state.DEGRADED{color:#ad6a00}.state.PENDING:before,.state.DEGRADED:before{background:#d98b10}.state.ERROR{color:#b42318}.state.ERROR:before{background:#b42318}.state.DISABLED{color:#7d8795}@media(max-width:900px){.health-grid{grid-template-columns:repeat(2,1fr)}.integration-row{grid-template-columns:1fr 1fr}.integration-row span:last-child{grid-column:1/-1}.integration-row.head{display:none}}@media(max-width:520px){.health-grid{grid-template-columns:1fr 1fr}}
</style>
<section class="ops-hero"><div><h1>Integration Registry & Health</h1><p>Operational health for platform dependencies, providers, API access and background services.</p></div><span class="ops-status {{ $summary['all_healthy']?'success':'warning' }}">{{ $summary['all_healthy']?'Operational':'Check required' }}</span></section>
<div class="health-grid"><div class="health-card"><small>Enabled Integrations</small><b>{{ $summary['total'] }}</b><div class="sub">Registered services</div></div><div class="health-card"><small>Healthy / Ready</small><b>{{ $summary['healthy'] }}</b><div class="sub">Passing health checks</div></div><div class="health-card"><small>Needs Attention</small><b>{{ $summary['degraded'] }}</b><div class="sub">Degraded or pending</div></div><div class="health-card"><small>Overall State</small><b style="font-size:16px">{{ $summary['all_healthy']?'OPERATIONAL':'CHECK REQUIRED' }}</b><div class="sub">Current platform status</div></div></div>
<section class="ops-card"><div class="ops-toolbar"><div><h3>Registered Components</h3><small style="color:#8693a5;font-size:8px">Last known state for each system dependency</small></div><a class="btn" href="{{ route('admin.system.integrations',['refresh'=>1]) }}">Refresh Health</a></div><div style="margin-top:10px"><div class="integration-row head"><span>Integration</span><span>Category</span><span>Provider</span><span>Status</span><span>Last Check</span></div>@forelse($summary['rows'] as $row)<div class="integration-row"><span><b>{{ $row->name }}</b><small>{{ $row->code }}</small></span><span>{{ $row->category }}</span><span>{{ $row->provider ?: 'Auto-detect' }}</span><span class="state {{ $row->status }}">{{ $row->status }}</span><span>{{ $row->last_checked_at?->format('d M Y H:i') ?? 'Not checked yet' }}<small>{{ $row->response_ms!==null?$row->response_ms.' ms':'' }}</small>@if($row->last_error)<small>{{ $row->last_error }}</small>@elseif(data_get($row->metadata,'detail'))<small>{{ data_get($row->metadata,'detail') }}</small>@endif</span></div>@empty<div class="ops-empty">No integrations are registered yet.</div>@endforelse</div></section>
@endsection
