@extends('layouts.app')
@section('title','Integrations & Health | UNIFCO Platform')
@section('heading','Integrations & Health')
@section('content')
@include('admin.system.operations-styles')
@php($health=app(\App\Services\IntegrationHealthService::class))
@php($summary=request()->boolean('refresh')?$health->refresh(auth()->user()->tenant_id):$health->summary(auth()->user()->tenant_id))
<style>.health-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.health-card{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:14px}.health-card b{font-size:24px;color:#132137;display:block}.integration-row{display:grid;grid-template-columns:1.3fr .8fr .7fr .8fr 1.2fr;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #edf0f5;font-size:10px}.integration-row:last-child{border-bottom:0}.state{font-weight:850}.state.OPERATIONAL,.state.READY{color:#168453}.state.PENDING,.state.DEGRADED{color:#ad6a00}.state.ERROR{color:#b42318}.state.DISABLED{color:#7d8795}@media(max-width:900px){.health-grid{grid-template-columns:repeat(2,1fr)}.integration-row{grid-template-columns:1fr 1fr}.integration-row span:last-child{grid-column:1/-1}}</style>
<section class="ops-hero"><h1>Integration Registry & Health</h1><p>Operational registry for platform dependencies, providers, API access and live health state.</p></section>
<div class="health-grid"><div class="health-card"><small>Enabled Integrations</small><b>{{ $summary['total'] }}</b></div><div class="health-card"><small>Healthy / Ready</small><b>{{ $summary['healthy'] }}</b></div><div class="health-card"><small>Needs Attention</small><b>{{ $summary['degraded'] }}</b></div><div class="health-card"><small>Overall State</small><b style="font-size:16px">{{ $summary['all_healthy']?'OPERATIONAL':'CHECK REQUIRED' }}</b></div></div>
<section class="ops-card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><h3 style="margin:0">Registered Components</h3><a class="btn" href="{{ route('admin.system.integrations',['refresh'=>1]) }}">Refresh Health</a></div><div style="margin-top:10px"><div class="integration-row" style="font-weight:800;color:#66758a"><span>Integration</span><span>Category</span><span>Provider</span><span>Status</span><span>Last Check</span></div>@forelse($summary['rows'] as $row)<div class="integration-row"><span><b>{{ $row->name }}</b><small>{{ $row->code }}</small></span><span>{{ $row->category }}</span><span>{{ $row->provider ?: 'Auto-detect' }}</span><span class="state {{ $row->status }}">{{ $row->status }}</span><span>{{ $row->last_checked_at?->format('d M Y H:i') ?? 'Not checked yet' }}<small>{{ $row->response_ms!==null?$row->response_ms.' ms':'' }}</small>@if($row->last_error)<small>{{ $row->last_error }}</small>@elseif(data_get($row->metadata,'detail'))<small>{{ data_get($row->metadata,'detail') }}</small>@endif</span></div>@empty<div class="ops-empty">No integrations are registered yet.</div>@endforelse</div></section>
@endsection
