@extends('layouts.app')
@section('title','Master Data | UNIFCO Platform')
@section('heading','Master Data')
@section('content')
@include('admin.system.operations-styles')
<section class="ops-hero"><h1>Administrative Master Data</h1><p>Controlled service classifications and labels. Master data cannot bypass workflow, scope or approval policies.</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="ops-card"><form class="ops-filter" method="POST" action="{{ route('admin.system.master-data.store') }}">@csrf<label>Type<select name="type">@foreach(\App\Models\MasterDataEntry::TYPES as $type)<option>{{ $type }}</option>@endforeach</select></label><label>Code<input name="code" required></label><label>Name AR<input name="name_ar"></label><label>Name EN<input name="name_en" required></label><label>Description<input name="description"></label><button class="btn">Create Entry</button></form></section>
<section class="ops-card"><form method="GET" class="ops-filter"><label>Type<select name="type"><option value="">All types</option>@foreach(\App\Models\MasterDataEntry::TYPES as $type)<option @selected(request('type')===$type)>{{ $type }}</option>@endforeach</select></label><button class="btn">Filter</button></form><table class="ops-table"><thead><tr><th>Type</th><th>Code</th><th>Arabic</th><th>English</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->type }}</td><td>{{ $entry->code }}</td><td>{{ $entry->name_ar ?: '—' }}</td><td>{{ $entry->name_en }}</td><td>{{ $entry->is_active?'ACTIVE':'INACTIVE' }}</td><td><form method="POST" action="{{ route('admin.system.master-data.status',$entry) }}">@csrf<input type="hidden" name="is_active" value="{{ $entry->is_active?0:1 }}"><input type="hidden" name="reason" value="Administrator changed master data availability"><button class="btn secondary">{{ $entry->is_active?'Deactivate':'Activate' }}</button></form></td></tr>@empty<tr><td colspan="6" class="ops-empty">No master data entries.</td></tr>@endforelse</tbody></table>{{ $entries->links() }}</section>
@endsection
