<style>
:root{--sys-navy:#132137;--sys-blue:#1e315b;--sys-red:#ce122d;--sys-line:#e4e9f0;--sys-soft:#f6f8fb;--sys-muted:#718096;--sys-success:#168453;--sys-warning:#a96600;--sys-danger:#b42318}
.ops-hero{background:linear-gradient(135deg,var(--sys-navy),var(--sys-blue));color:#fff;border-radius:14px;padding:18px 20px;margin-bottom:14px;display:flex;justify-content:space-between;align-items:center;gap:16px;box-shadow:0 10px 28px rgba(19,33,55,.10)}
.ops-hero h1{margin:0 0 5px;font-size:21px;letter-spacing:-.01em}.ops-hero p{margin:0;color:#dce5f2;font-size:10.5px;line-height:1.6;max-width:760px}
.ops-card{background:#fff;border:1px solid var(--sys-line);border-radius:12px;padding:16px;margin-top:12px;box-shadow:0 4px 14px rgba(19,33,55,.035)}
.ops-card h3{margin:0;color:var(--sys-navy);font-size:12px}.ops-filter{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:9px;align-items:end;background:var(--sys-soft);border:1px solid #edf1f5;border-radius:10px;padding:11px}.ops-filter label{font-size:8.5px;color:#66758a;font-weight:700;text-transform:uppercase;letter-spacing:.04em}
.ops-filter input,.ops-filter select{background:#fff;min-height:36px}.ops-table{width:100%;border-collapse:collapse;margin-top:12px}.ops-table th,.ops-table td{padding:10px 9px;border-bottom:1px solid #edf0f5;text-align:left;font-size:10px;vertical-align:top}.ops-table th{position:sticky;top:0;background:#fafbfd;color:#77869a;font-size:8px;text-transform:uppercase;letter-spacing:.05em;z-index:1}.ops-table tbody tr{transition:background .15s ease}.ops-table tbody tr:hover{background:#fafbfd}.ops-table small{display:block;color:#7b899c;margin-top:3px;line-height:1.45}.ops-empty{padding:30px 18px;text-align:center;color:#7b899c;background:#fafbfd;border-radius:9px}
.ops-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.ops-metric{background:#fff;border:1px solid var(--sys-line);border-radius:11px;padding:13px;box-shadow:0 3px 12px rgba(19,33,55,.025)}.ops-metric small{font-size:8px;color:#78869a;text-transform:uppercase;letter-spacing:.04em}.ops-metric b{display:block;font-size:21px;color:var(--sys-navy);margin-top:4px}.ops-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.ops-toolbar .btn{min-height:36px}.ops-status{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:5px 9px;font-size:8.5px;font-weight:850;background:#f0f3f7;color:#5d6b7e}.ops-status:before{content:'';width:7px;height:7px;border-radius:50%;background:#8794a7}.ops-status.success{background:#eaf7f0;color:var(--sys-success)}.ops-status.success:before{background:var(--sys-success)}.ops-status.warning{background:#fff6e6;color:var(--sys-warning)}.ops-status.warning:before{background:#d98b10}.ops-status.danger{background:#fdeeee;color:var(--sys-danger)}.ops-status.danger:before{background:var(--sys-danger)}
@media(max-width:760px){.ops-hero{align-items:flex-start;flex-direction:column;padding:16px}.ops-summary{grid-template-columns:1fr}.ops-card{padding:12px}.ops-filter{grid-template-columns:1fr}.ops-table{display:block;overflow:auto}.ops-table th,.ops-table td{white-space:nowrap}}
</style>
