@extends('layouts.app')
@section('title','Organization | UNIFCO Platform')
@section('heading','Organization')
@section('content')
@include('admin.system.operations-styles')
<section class="ops-hero"><h1>Organization Structure</h1><p>Administrative structure is separate from security scope. Department membership never grants project or site access.</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="ops-summary"><div class="ops-metric"><small>Organizations</small><b>{{ $organizations->count() }}</b></div><div class="ops-metric"><small>Departments</small><b>{{ $positions->pluck('department')->filter()->unique()->count() }}</b></div><div class="ops-metric"><small>Job Titles</small><b>{{ $positions->count() }}</b></div></div>
<section class="ops-card"><h3>Organization Units</h3><form class="ops-filter" method="POST" action="{{ route('admin.system.organizations.store') }}">@csrf<label>Code<input name="code" required></label><label>Name<input name="name" required></label><button class="btn">Create Organization</button></form><table class="ops-table"><thead><tr><th>Code</th><th>Name</th><th>Status</th></tr></thead><tbody>@foreach($organizations as $organization)<tr><td>{{ $organization->code }}</td><td>{{ $organization->name }}</td><td>{{ $organization->status }}</td></tr>@endforeach</tbody></table></section>
<section class="ops-card"><h3>Departments & Job Titles</h3><form class="ops-filter" method="POST" action="{{ route('admin.system.job-positions.store') }}">@csrf<label>Organization<select name="organization_id"><option value="">No organization</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}">{{ $organization->name }}</option>@endforeach</select></label><label>Code<input name="code" required></label><label>Department<input name="department" required></label><label>Job Title<input name="title" required></label><button class="btn">Create Job Title</button></form><table class="ops-table"><thead><tr><th>Code</th><th>Department</th><th>Job Title</th><th>Status</th></tr></thead><tbody>@forelse($positions as $position)<tr><td>{{ $position->code }}</td><td>{{ $position->department }}</td><td>{{ $position->title }}</td><td>{{ $position->status }}</td></tr>@empty<tr><td colspan="4" class="ops-empty">No job titles.</td></tr>@endforelse</tbody></table></section>
@endsection
