@extends('layouts.app')
@section('title','Organization | UNIFCO Platform')
@section('heading','Organization')
@section('content')
@include('admin.system.operations-styles')
<style>
.org-note{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.org-note div{background:#fff;border:1px solid #e4e9f0;border-radius:10px;padding:10px}.org-note b{display:block;color:#132137;font-size:9px}.org-note small{display:block;color:#7d8999;font-size:8px;margin-top:3px;line-height:1.45}.org-columns{display:grid;grid-template-columns:1fr 1.2fr;gap:12px}.org-title{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;margin-bottom:10px}.org-title small{display:block;color:#7b899c;font-size:8px;margin-top:3px}.status-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border-radius:999px;background:#eaf7f0;color:#168453;font-size:8px;font-weight:850}.status-chip:before{content:'';width:6px;height:6px;border-radius:50%;background:#168453}@media(max-width:900px){.org-columns,.org-note{grid-template-columns:1fr}}
</style>
<section class="ops-hero"><div><h1>Organization Structure</h1><p>Manage companies, departments and job titles without mixing organizational membership with security scope.</p></div><span class="ops-status success">Structured</span></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="ops-summary"><div class="ops-metric"><small>Organizations</small><b>{{ $organizations->count() }}</b></div><div class="ops-metric"><small>Departments</small><b>{{ $positions->pluck('department')->filter()->unique()->count() }}</b></div><div class="ops-metric"><small>Job Titles</small><b>{{ $positions->count() }}</b></div></div>
<div class="org-note"><div><b>Organization ≠ Access Scope</b><small>Department membership never grants project or site access.</small></div><div><b>Job Title ≠ Permission</b><small>Authority is derived only from assigned roles and permissions.</small></div><div><b>Scope Remains Explicit</b><small>Project, Site, Customer and other scopes are managed in Access Control.</small></div></div>
<div class="org-columns">
<section class="ops-card"><div class="org-title"><div><h3>Organization Units</h3><small>Create and maintain tenant organizational entities.</small></div><span class="ops-status">{{ $organizations->count() }} units</span></div><form class="ops-filter" method="POST" action="{{ route('admin.system.organizations.store') }}">@csrf<label>Code<input name="code" required></label><label>Name<input name="name" required></label><button class="btn">Create Organization</button></form><table class="ops-table"><thead><tr><th>Code</th><th>Name</th><th>Status</th></tr></thead><tbody>@forelse($organizations as $organization)<tr><td><b>{{ $organization->code }}</b></td><td>{{ $organization->name }}</td><td><span class="status-chip">{{ $organization->status }}</span></td></tr>@empty<tr><td colspan="3" class="ops-empty">No organization units.</td></tr>@endforelse</tbody></table></section>
<section class="ops-card"><div class="org-title"><div><h3>Departments & Job Titles</h3><small>Maintain reporting structure and employee job identity.</small></div><span class="ops-status">{{ $positions->count() }} titles</span></div><form class="ops-filter" method="POST" action="{{ route('admin.system.job-positions.store') }}">@csrf<label>Organization<select name="organization_id"><option value="">No organization</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}">{{ $organization->name }}</option>@endforeach</select></label><label>Code<input name="code" required></label><label>Department<input name="department" required></label><label>Job Title<input name="title" required></label><button class="btn">Create Job Title</button></form><table class="ops-table"><thead><tr><th>Code</th><th>Department</th><th>Job Title</th><th>Status</th></tr></thead><tbody>@forelse($positions as $position)<tr><td><b>{{ $position->code }}</b></td><td>{{ $position->department }}</td><td>{{ $position->title }}</td><td><span class="status-chip">{{ $position->status }}</span></td></tr>@empty<tr><td colspan="4" class="ops-empty">No job titles.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
