@extends('layouts.app')
@section('title','Security Events | UNIFCO Platform')
@section('heading','Security Events')
@section('content')
@include('admin.system.operations-styles')
<section class="ops-hero"><h1>Security Events</h1><p>Authentication, account-lock and suspicious-access signals that require technical or security review.</p></section>
<section class="ops-card"><form class="ops-filter" method="GET"><label>Event<select name="event_type"><option value="">All events</option>@foreach($eventTypes as $type)<option @selected(request('event_type')===$type)>{{ $type }}</option>@endforeach</select></label><label>Severity<select name="severity"><option value="">All severities</option>@foreach(['INFO','WARNING','HIGH','CRITICAL'] as $value)<option @selected(request('severity')===$value)>{{ $value }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['OPEN','RESOLVED'] as $value)<option @selected(request('status')===$value)>{{ $value }}</option>@endforeach</select></label><label>User<select name="user_id"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></label><label>From<input type="date" name="from" value="{{ request('from') }}"></label><label>To<input type="date" name="to" value="{{ request('to') }}"></label><label>IP Address<input name="ip" value="{{ request('ip') }}"></label><button class="btn">Filter</button></form>
<table class="ops-table"><thead><tr><th>Severity</th><th>Event</th><th>User / Service</th><th>Time</th><th>IP / Session</th><th>Status</th></tr></thead><tbody>@forelse($events as $event)<tr><td><span class="pill">{{ $event->severity }}</span></td><td><b>{{ str_replace('_',' ',$event->event_type) }}</b><small>{{ collect($event->context)->map(fn($v,$k)=>$k.': '.(is_scalar($v)?$v:'…'))->take(3)->join(' · ') }}</small></td><td>{{ $event->user?->name ?: 'System / Unknown' }}<small>{{ $event->user?->email }}</small></td><td>{{ $event->occurred_at?->format('d M Y H:i:s') }}</td><td>{{ $event->ip_address ?: 'Unavailable' }}<small>{{ str($event->session_id)->limit(24) }}</small></td><td>{{ $event->status }}</td></tr>@empty<tr><td colspan="6" class="ops-empty">No security events.</td></tr>@endforelse</tbody></table>{{ $events->links() }}</section>
@endsection
