@extends('layouts.app')
@php($loginActivity=request()->routeIs('admin.system.login-activity'))
@section('title',($loginActivity?'Login Activity':'Active Sessions').' | UNIFCO Platform')
@section('heading',$loginActivity?'Login Activity':'Active Sessions')
@section('content')
@include('admin.system.operations-styles')
<section class="ops-hero"><h1>{{ $loginActivity?'Login Activity':'Active Sessions' }}</h1><p>{{ $loginActivity?'Review successful sign-in history, login time, recent activity, device, browser and IP.':'Review active sessions and force logout when required. Administrative actions are fully audited.' }}</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="ops-card"><form class="ops-filter" method="GET"><label>User<select name="user_id"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user_id')===(string)$user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['ACTIVE','LOGGED_OUT','REVOKED'] as $value)<option @selected(request('status')===$value)>{{ $value }}</option>@endforeach</select></label><label>IP Address<input name="ip" value="{{ request('ip') }}"></label><button class="btn">Filter</button></form>
<table class="ops-table"><thead><tr><th>User</th><th>Login / Activity</th><th>Device</th><th>IP / Session</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($sessions as $session)<tr><td><b>{{ $session->user?->name ?: 'Unknown user' }}</b><small>{{ $session->user?->email }}</small></td><td>{{ $session->login_at?->format('d M Y H:i') }}<small>{{ $session->last_activity_at?->diffForHumans() }}</small></td><td>{{ $session->device ?: 'Unknown' }}<small>{{ $session->browser ?: 'Unknown browser' }}</small></td><td>{{ $session->ip_address ?: 'Unavailable' }}<small>{{ str($session->session_id)->limit(24) }}</small></td><td><span class="pill">{{ $session->status }}</span></td><td>@if($session->status==='ACTIVE' && $session->session_id!==request()->session()->getId())<form method="POST" action="{{ route('admin.system.sessions.revoke',$session) }}" onsubmit="return confirm('Force logout this session?')">@csrf<button class="btn danger">Force Logout</button></form>@else—@endif</td></tr>@empty<tr><td colspan="6" class="ops-empty">No recorded sessions.</td></tr>@endforelse</tbody></table>{{ $sessions->links() }}</section>
@endsection
