@extends('layouts.app')
@section('title','Payroll | UNIFCO Platform')
@section('heading','Payroll')
@section('content')
<style>
.pay-hero{background:linear-gradient(135deg,#101f38,#1e315b 62%,#294579);color:#fff;border-radius:16px;padding:22px 24px;display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:14px}.pay-hero small{display:block;font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#aebbd0;font-weight:800}.pay-hero h1{margin:5px 0;font-size:24px}.pay-hero p{margin:0;color:#dce5f2;font-size:11px}.pay-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.panel{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:16px}.panel h3{margin:0 0 4px;font-size:13px}.panel>small{font-size:8px;color:#8190a4}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.form-grid label{font-size:9px;color:#65748a;font-weight:700}.form-grid input,.form-grid select{width:100%}.full{grid-column:1/-1}.runs{grid-column:1/-1}.runs table{display:table;margin:10px 0 0}.badge{padding:4px 7px;border-radius:999px;background:#edf3fa;color:#1e315b;font-size:8px;font-weight:800}.status-posted{background:#e8f7ee;color:#17734b}.policy-note{padding:10px;background:#f7f9fc;border-radius:9px;font-size:9px;color:#66758a;margin-top:10px}@media(max-width:900px){.pay-grid{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.runs{grid-column:auto}.runs table{display:block}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="pay-hero"><div><small>People / HR · Saudi Payroll</small><h1>Payroll Command Center</h1><p>Generate payroll from employee compensation, attendance overtime, unpaid leave and versioned GOSI policies.</p></div><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a></section>
<div class="pay-grid">
<section class="panel"><h3>Generate Payroll Run</h3><small>Calculates all active employees in the current organization.</small><form method="POST" action="{{ route('hr.payroll.runs.store') }}" class="form-grid">@csrf<label>Payroll No<input name="payroll_no" value="PAY-{{ now()->format('Y-m') }}" required></label><label>Currency<input name="currency" value="SAR" required maxlength="3"></label><label>Period Start<input type="date" name="period_start" value="{{ now()->startOfMonth()->toDateString() }}" required></label><label>Period End<input type="date" name="period_end" value="{{ now()->endOfMonth()->toDateString() }}" required></label><label>Posting Date<input type="date" name="posting_date" value="{{ now()->toDateString() }}" required></label><div style="display:flex;align-items:end"><button class="btn">Calculate Payroll</button></div></form></section>
<section class="panel"><h3>Saudi Payroll Policy</h3><small>Versioned statutory parameters; create a new effective version instead of editing historical calculations.</small><form method="POST" action="{{ route('hr.payroll.policies.store') }}" class="form-grid">@csrf<label>Code<input name="code" value="KSA-GOSI" required></label><label>Name<input name="name" value="Saudi GOSI Standard" required></label><label>Effective From<input type="date" name="effective_from" value="{{ now()->startOfYear()->toDateString() }}" required></label><label>Effective To<input type="date" name="effective_to"></label><label>Pension Employee<input type="number" step="0.0001" name="pension_employee_rate" value="0.09" required></label><label>Pension Employer<input type="number" step="0.0001" name="pension_employer_rate" value="0.09" required></label><label>SANED Employee<input type="number" step="0.0001" name="saned_employee_rate" value="0.01" required></label><label>SANED Employer<input type="number" step="0.0001" name="saned_employer_rate" value="0.01" required></label><label>Occupational Hazard Employer<input type="number" step="0.0001" name="occupational_hazard_employer_rate" value="0.02" required></label><label>OT Basic Premium<input type="number" step="0.0001" name="overtime_basic_premium_rate" value="0.50" required></label><label>Standard Month Days<input type="number" step="0.01" name="standard_month_days" value="30" required></label><div style="display:flex;align-items:end"><button class="btn">Add Policy Version</button></div></form><div class="policy-note">Current implementation treats Saudi nationals as pension + SANED eligible and applies occupational-hazard employer contribution to all employees. Contributory wage is Basic + Housing.</div></section>
<section class="panel runs"><h3>Payroll Runs</h3><small>Calculated, reviewable and Finance-postable payroll periods.</small><table><thead><tr><th>Payroll</th><th>Period</th><th>Employees</th><th>Gross</th><th>Employee Deductions</th><th>Employer Contributions</th><th>Net</th><th>Status</th><th></th></tr></thead><tbody>@forelse($runs as $run)<tr><td><b>{{ $run->payroll_no }}</b></td><td>{{ $run->period_start?->format('d M') }} → {{ $run->period_end?->format('d M Y') }}</td><td>{{ $run->lines->count() }}</td><td>{{ number_format((float)$run->gross_total,2) }} {{ $run->currency }}</td><td>{{ number_format((float)$run->employee_deductions_total,2) }}</td><td>{{ number_format((float)$run->employer_contributions_total,2) }}</td><td><b>{{ number_format((float)$run->net_total,2) }}</b></td><td><span class="badge {{ $run->status==='POSTED'?'status-posted':'' }}">{{ $run->status }}</span></td><td><a class="btn secondary" href="{{ route('hr.payroll.show',$run) }}">Review</a></td></tr>@empty<tr><td colspan="9">No dedicated payroll runs yet.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
