@extends('layouts.app')
@section('title',$payroll->payroll_no.' | Payroll')
@section('heading','Payroll Review')
@section('content')
<style>.hero{background:linear-gradient(135deg,#101f38,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;display:flex;justify-content:space-between;gap:14px;align-items:center}.hero h1{margin:0 0 4px;font-size:23px}.hero p{margin:0;color:#cfdaea;font-size:10px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.kpi{background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:14px}.kpi small{font-size:8px;color:#79879a;text-transform:uppercase;font-weight:800}.kpi b{display:block;font-size:20px;margin-top:4px}.panel{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:15px;margin-top:12px}.panel h3{margin:0 0 8px;font-size:13px}.policy{padding:9px;background:#f7f9fc;border-radius:8px;font-size:9px;color:#65748a}.pay-table{display:table;margin:10px 0 0}.pay-table th{font-size:8px}.pay-table td{font-size:9px}.post-form{display:grid;grid-template-columns:repeat(3,1fr) auto;gap:8px;align-items:end}.post-form label{font-size:9px}.post-form input{width:100%}@media(max-width:950px){.kpis{grid-template-columns:1fr 1fr}.pay-table{display:block}.post-form{grid-template-columns:1fr}}@media(max-width:520px){.kpis{grid-template-columns:1fr}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="hero"><div><h1>{{ $payroll->payroll_no }}</h1><p>{{ $payroll->period_start?->format('d M Y') }} → {{ $payroll->period_end?->format('d M Y') }} · {{ $payroll->status }} · Policy {{ $policy?->code ?? 'Legacy' }}</p></div><div style="display:flex;gap:7px"><a class="btn secondary" href="{{ route('hr.payroll.index') }}">Back to Payroll</a>@if($payroll->status==='DRAFT')<form method="POST" action="{{ route('hr.payroll.recalculate',$payroll) }}">@csrf<button class="btn">Recalculate</button></form>@endif</div></section>
<div class="kpis"><div class="kpi"><small>Gross Payroll</small><b>{{ number_format((float)$payroll->gross_total,2) }} {{ $payroll->currency }}</b></div><div class="kpi"><small>Employee Deductions</small><b>{{ number_format((float)$payroll->employee_deductions_total,2) }}</b></div><div class="kpi"><small>Employer Contributions</small><b>{{ number_format((float)$payroll->employer_contributions_total,2) }}</b></div><div class="kpi"><small>Net Payroll</small><b>{{ number_format((float)$payroll->net_total,2) }}</b></div></div>
<section class="panel"><h3>Employee Payroll Lines</h3><div class="policy">Overtime includes actual hourly wage + policy premium on basic hourly wage. Saudi GOSI employee deductions and employer contributions are separated so net pay and employer cost remain auditable.</div><table class="pay-table"><thead><tr><th>Employee</th><th>Basic</th><th>Housing</th><th>Transport/Other</th><th>OT Hours</th><th>OT Pay</th><th>Unpaid Leave</th><th>GOSI Wage</th><th>Employee GOSI</th><th>Employer GOSI</th><th>Net Pay</th></tr></thead><tbody>@foreach($payroll->lines as $line)<tr><td><b>{{ $employees[$line->employee_id]->name ?? '#'.$line->employee_id }}</b><br>{{ $employees[$line->employee_id]->employee_no ?? '' }}</td><td>{{ number_format((float)$line->basic_pay,2) }}</td><td>{{ number_format((float)$line->housing_allowance,2) }}</td><td>{{ number_format((float)$line->transport_allowance+(float)$line->other_allowances,2) }}</td><td>{{ $line->overtime_hours }}</td><td>{{ number_format((float)$line->overtime_pay,2) }}</td><td>{{ $line->unpaid_leave_days }} d<br>-{{ number_format((float)$line->unpaid_leave_deduction,2) }}</td><td>{{ number_format((float)$line->gosi_contributory_wage,2) }}</td><td>{{ number_format((float)$line->gosi_pension_employee+(float)$line->gosi_saned_employee,2) }}</td><td>{{ number_format((float)$line->gosi_pension_employer+(float)$line->gosi_saned_employer+(float)$line->gosi_hazard_employer,2) }}</td><td><b>{{ number_format((float)$line->net_pay,2) }}</b></td></tr>@endforeach</tbody></table></section>
@if($payroll->status==='DRAFT')<section class="panel"><h3>Post to Finance</h3><form method="POST" action="{{ route('hr.payroll.post',$payroll) }}" class="post-form">@csrf<label>Payroll Expense Account<input name="expense_account_code" placeholder="e.g. 5100" required></label><label>Net Payroll Payable<input name="payable_account_code" placeholder="e.g. 2100" required></label><label>Deductions Payable<input name="deductions_account_code" placeholder="e.g. 2200" required></label><button class="btn">Post Payroll</button></form></section>@endif
@endsection
