@extends('layouts.app')
@section('title',($order->exists?'Edit':'New').' Work Order · UNIFCO')
@section('heading',$order->exists?'Edit Work Order':'New Work Order')
@section('content')
<style>.wo-form{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.wo-form label{font-size:10px;font-weight:800}.wo-form input,.wo-form select{width:100%}.intro{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:14px;padding:20px;margin-bottom:14px}.intro h2{margin:0 0 4px}.intro p{margin:0;color:#cbd9ea;font-size:11px}@media(max-width:750px){.wo-form{grid-template-columns:1fr}}</style>
<div class="intro"><h2>{{ $order->exists?'Update Work Order':'Create Maintenance Work Order' }}</h2><p>Corrective, preventive, predictive and inspection work can all be executed later in the same workspace with evidence and cost capture.</p></div>
@if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<div class="card"><form method="POST" action="{{ $order->exists?route('maintenance.work-orders.update',$order):route('maintenance.work-orders.store') }}">@csrf @if($order->exists)@method('PUT')@endif<div class="wo-form"><label>Work Order No<input name="work_order_no" value="{{ old('work_order_no',$order->work_order_no) }}" required placeholder="WO-2026-0001"></label><label>Asset<select name="asset_id" required><option value="">Select asset</option>@foreach($assets as $a)<option value="{{ $a->id }}" @selected(old('asset_id',$order->asset_id)==$a->id)>{{ $a->asset_code }} · {{ $a->name }}</option>@endforeach</select></label><label>Type<select name="maintenance_type">@foreach(['PREVENTIVE','CORRECTIVE','PREDICTIVE','INSPECTION'] as $type)<option @selected(old('maintenance_type',$order->maintenance_type ?: 'CORRECTIVE')===$type)>{{ $type }}</option>@endforeach</select></label><label>Priority<select name="priority">@foreach(['LOW','NORMAL','HIGH','CRITICAL'] as $p)<option @selected(old('priority',$order->priority ?: 'NORMAL')===$p)>{{ $p }}</option>@endforeach</select></label><label>Planned Start<input type="datetime-local" name="planned_start" value="{{ old('planned_start',$order->planned_start?->format('Y-m-d\TH:i')) }}"></label></div><button class="btn" style="margin-top:12px">{{ $order->exists?'Save Changes':'Create Work Order' }}</button> <a class="btn secondary" href="{{ route('maintenance.work-orders.index') }}">Cancel</a></form></div>
@endsection
