@extends('layouts.app')
@section('title','Maintenance Work Orders · UNIFCO')
@section('heading','Maintenance Work Orders')
@section('content')
<style>.wo-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:22px;margin-bottom:14px}.wo-hero h2{margin:0 0 5px}.wo-hero p{margin:0;color:#cbd9ea;font-size:11px}.status{font-size:9px;font-weight:800;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#405a78}.status.IN_PROGRESS{background:#dcecff;color:#0b4b87}.status.COMPLETED{background:#def4e8;color:#176a43}.priority.CRITICAL{color:#b51530;font-weight:900}.priority.HIGH{color:#9a5d00;font-weight:800}.row-actions{display:flex;gap:6px;flex-wrap:wrap}</style>
<div class="wo-hero"><h2>Maintenance Execution Center</h2><p>Plan → Work Order → Checklist → Evidence → Spare Parts → Failure Analysis → Cost → Closeout</p><div style="margin-top:12px"><a class="btn" href="{{ route('maintenance.work-orders.create') }}">+ New Work Order</a></div></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<div class="card"><div class="table-wrap"><table><thead><tr><th>Work Order</th><th>Asset</th><th>Plan / Contract</th><th>Type</th><th>Priority</th><th>Planned</th><th>Status</th><th>Cost</th><th></th></tr></thead><tbody>@forelse($orders as $o)<tr><td><strong>{{ $o->work_order_no }}</strong><br><small>#{{ $o->id }}</small></td><td>{{ $o->asset?->asset_code }}<br><small>{{ $o->asset?->name }}</small></td><td>{{ $o->plan?->plan_no ?: '—' }}<br><small>{{ $o->contract?->contract_no ?: 'No contract' }}</small></td><td>{{ $o->maintenance_type }}</td><td><span class="priority {{ $o->priority }}">{{ $o->priority }}</span></td><td>{{ optional($o->planned_start)->format('Y-m-d H:i') ?: '—' }}</td><td><span class="status {{ $o->status }}">{{ $o->status }}</span></td><td>{{ number_format((float)$o->total_cost,2) }} SAR</td><td><div class="row-actions"><a class="btn secondary" href="{{ route('maintenance.work-orders.show',$o) }}">Execution Workspace</a>@if($o->status==='OPEN')<a class="btn secondary" href="{{ route('maintenance.work-orders.edit',$o) }}">Edit</a>@endif</div></td></tr>@empty<tr><td colspan="9">No work orders found.</td></tr>@endforelse</tbody></table></div></div>{{ $orders->links() }}
@endsection
