@extends('layouts.app')
@section('title',$workOrder->work_order_no.' · Work Order · UNIFCO')
@section('heading','Work Order Execution')
@section('content')
@php
$required=$tasks->where('required',1); $done=$required->whereNotNull('completed_at'); $completion=$required->count()?round($done->count()/$required->count()*100):100;
$fmtMinutes=function($m){ if($m===null)return '—'; if($m>=1440)return round($m/1440,1).' d'; if($m>=60)return round($m/60,1).' h'; return round($m,1).' min'; };
@endphp
<style>
.wo-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;padding:22px;border-radius:16px}.wo-hero h2{margin:4px 0}.wo-hero p{margin:0;color:#cbd9ea;font-size:11px}.status{display:inline-flex;padding:5px 8px;border-radius:999px;background:#ffffff19;font-size:9px;font-weight:800}.status.IN_PROGRESS{background:#dcecff;color:#0b4b87}.status.COMPLETED{background:#dff5e9;color:#12643e}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:14px 0}.kpi{background:#fff;border:1px solid #e2e8f0;border-radius:11px;padding:13px}.kpi b{font-size:18px;color:#071f4d;display:block}.kpi span{font-size:9px;color:#748297}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.box{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:17px}.box h3{margin:0 0 12px;color:#071f4d;font-size:14px}.forms{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.forms label{font-size:9px;font-weight:700}.forms input,.forms select,.forms textarea{width:100%}.wide{grid-column:1/-1}.progress{height:8px;background:#e6ebf1;border-radius:99px;overflow:hidden}.progress i{display:block;height:100%;background:#168a55}.task{border:1px solid #e4eaf1;border-radius:10px;padding:12px;margin-top:8px}.task-head{display:flex;justify-content:space-between;gap:10px}.task-title{font-size:11px;font-weight:800;color:#071f4d}.task-meta{font-size:8px;color:#708095}.task-result{display:grid;grid-template-columns:130px 1fr 1fr;gap:8px;margin-top:8px}.pass{color:#12643e}.fail{color:#b21f36}.evidence{padding:8px 0;border-bottom:1px solid #edf1f5;font-size:10px}.part-critical{color:#b21f36;font-weight:800}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.cost-row{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #edf1f5;font-size:10px}.cost-row.total{font-weight:900;color:#071f4d;font-size:12px}@media(max-width:1100px){.kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.grid2{grid-template-columns:1fr}.forms,.task-result{grid-template-columns:1fr 1fr}}@media(max-width:600px){.kpis,.forms,.task-result{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ implode(' | ',$errors->all()) }}</div>@endif
<section class="wo-hero"><span class="status {{ $workOrder->status }}">{{ $workOrder->status }}</span><h2>{{ $workOrder->work_order_no }} · {{ $workOrder->asset?->asset_code }}</h2><p>{{ $workOrder->asset?->name }} · {{ $workOrder->asset?->customer?->name }} · {{ $workOrder->asset?->site?->name ?: 'No site' }} · {{ $workOrder->maintenance_type }} · {{ $workOrder->priority }}</p><div class="actions"><a class="btn secondary" href="{{ route('maintenance.work-orders.index') }}">Work Orders</a><a class="btn secondary" href="{{ route('eam.assets.show',$workOrder->asset) }}">Asset 360</a>@if($workOrder->status==='OPEN')<a class="btn secondary" href="{{ route('maintenance.work-orders.edit',$workOrder) }}">Edit</a>@endif</div></section>
<section class="kpis"><div class="kpi"><b>{{ $completion }}%</b><span>Required Checklist</span></div><div class="kpi"><b>{{ $fmtMinutes($metrics['mtbf_minutes']) }}</b><span>Asset MTBF</span></div><div class="kpi"><b>{{ $fmtMinutes($metrics['mttr_minutes']) }}</b><span>Asset MTTR</span></div><div class="kpi"><b>{{ $metrics['failure_count'] }}</b><span>Recorded Failures</span></div><div class="kpi"><b>{{ number_format((float)$workOrder->material_cost,2) }}</b><span>Material Cost SAR</span></div><div class="kpi"><b>{{ number_format((float)$workOrder->total_cost,2) }}</b><span>Total Cost SAR</span></div></section>

@if($workOrder->status==='OPEN')<section class="box"><h3>Start Work</h3><form method="POST" action="{{ route('maintenance.work-orders.start',$workOrder) }}">@csrf<div class="forms"><label class="wide">Execution / Safety Notes<textarea name="execution_notes" placeholder="Isolation, LOTO, permit, access conditions, initial observations..."></textarea></label></div><button class="btn">Start Work Order</button></form></section>@endif

<div class="grid2"><section class="box"><h3>Maintenance Checklist</h3>@if($workOrder->plan)<p class="muted">{{ $workOrder->plan->plan_no }} · {{ $workOrder->plan->name }}</p><div class="progress"><i style="width:{{ $completion }}%"></i></div>@endif
@if($tasks->count())<form method="POST" action="{{ route('maintenance.work-orders.checklist',$workOrder) }}">@csrf @foreach($tasks as $task)<div class="task"><div class="task-head"><div><div class="task-title">{{ $task->sort_order }}. {{ $task->task_title }} @if($task->required)<span style="color:#e20b24">*</span>@endif</div><div class="task-meta">{{ $task->response_type }} @if($task->unit) · {{ $task->unit }} @endif @if($task->min_value!==null||$task->max_value!==null) · Range {{ $task->min_value ?? '—' }} to {{ $task->max_value ?? '—' }} @endif @if($task->photo_required) · Photo required @endif</div>@if($task->instructions)<div class="task-meta" style="margin-top:3px">{{ $task->instructions }}</div>@endif</div><span class="{{ $task->result_status==='FAIL'?'fail':'pass' }}">{{ $task->result_status ?: 'PENDING' }}</span></div><div class="task-result">@if($task->response_type==='PASS_FAIL')<select name="results[{{ $task->id }}][result_status]"><option value="">Pending</option><option @selected($task->result_status==='PASS')>PASS</option><option @selected($task->result_status==='FAIL')>FAIL</option><option @selected($task->result_status==='NA')>NA</option></select>@elseif($task->response_type==='NUMBER')<input type="number" step="any" name="results[{{ $task->id }}][numeric_value]" value="{{ $task->numeric_value }}" placeholder="Reading">@else<input name="results[{{ $task->id }}][text_value]" value="{{ $task->text_value }}" placeholder="Result / observation">@endif<input name="results[{{ $task->id }}][technician_notes]" value="{{ $task->technician_notes }}" placeholder="Technician notes"><span class="task-meta">{{ $task->completed_at ?: 'Not completed' }}</span></div></div>@endforeach<button class="btn" style="margin-top:10px">Save Checklist</button></form>@else<p class="muted">No checklist is attached to this work order.</p>@endif</section>
<section class="box"><h3>Photo & Document Evidence</h3><form method="POST" enctype="multipart/form-data" action="{{ route('maintenance.work-orders.attachments.store',$workOrder) }}">@csrf<div class="forms"><label>Type<select name="attachment_type"><option>PHOTO</option><option>BEFORE_PHOTO</option><option>AFTER_PHOTO</option><option>THERMAL_IMAGE</option><option>DOCUMENT</option><option>OTHER</option></select></label><label>Checklist Task<select name="maintenance_plan_task_id"><option value="">General evidence</option>@foreach($tasks as $task)<option value="{{ $task->id }}">{{ $task->sort_order }} · {{ $task->task_title }}</option>@endforeach</select></label><label>Title<input name="title"></label><label class="wide">File<input type="file" name="file" required></label></div><button class="btn" style="margin-top:8px">Upload Evidence</button></form><div style="margin-top:12px">@forelse($attachments as $a)<div class="evidence"><strong>{{ $a->attachment_type }}</strong> · {{ $a->title ?: $a->original_name }} @if($a->maintenance_plan_task_id) · Task #{{ $a->maintenance_plan_task_id }} @endif <a href="{{ route('maintenance.work-orders.attachments.download',[$workOrder,$a->id]) }}">Download</a></div>@empty<p class="muted">No evidence uploaded.</p>@endforelse</div></section></div>

<div class="grid2"><section class="box"><h3>Spare Parts / Inventory Issue</h3><form method="POST" action="{{ route('maintenance.work-orders.materials.store',$workOrder) }}">@csrf<div class="forms"><label>Part<select name="item_id" required><option value="">Select inventory item</option>@if($compatibleParts->count())<optgroup label="Compatible with this asset">@foreach($compatibleParts as $p)<option value="{{ $p->id }}">{{ $p->critical_spare?'★ ':'' }}{{ $p->item_code }} · {{ $p->name }} @if($p->manufacturer_part_no)· {{ $p->manufacturer_part_no }}@endif</option>@endforeach</optgroup>@endif<optgroup label="All active inventory items">@foreach($allItems as $item)<option value="{{ $item->id }}">{{ $item->item_code }} · {{ $item->name }}</option>@endforeach</optgroup></select></label><label>Warehouse<input name="warehouse_code" required placeholder="MAIN"></label><label>Quantity<input type="number" step="any" min="0.0001" name="quantity" required></label><label>Unit Cost SAR<input type="number" step="0.01" min="0" name="unit_cost"></label></div><button class="btn" style="margin-top:8px">Issue to Work Order</button></form><div style="margin-top:12px">@forelse($materials as $m)<div class="cost-row"><span>{{ $m->item_code }} · {{ $m->item_name }}<br><small>{{ $m->warehouse_code }} · {{ $m->quantity }} {{ $m->uom }}</small></span><strong>{{ number_format((float)$m->total_cost,2) }} SAR</strong></div>@empty<p class="muted">No materials issued.</p>@endforelse<div class="cost-row total"><span>Material Cost</span><span>{{ number_format((float)$workOrder->material_cost,2) }} SAR</span></div></div></section>
<section class="box"><h3>Failure / Root Cause Record</h3><form method="POST" action="{{ route('maintenance.work-orders.failures.store',$workOrder) }}">@csrf<div class="forms"><label>Failure Code<input name="failure_code"></label><label>Failure Mode<input name="failure_mode" required placeholder="No output / breaker trip / battery failure"></label><label>Severity<select name="severity"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Failed At<input type="datetime-local" name="failed_at" required></label><label>Restored At<input type="datetime-local" name="restored_at"></label><label>Downtime Minutes<input type="number" min="0" name="downtime_minutes"></label><label>Failure Effect<input name="failure_effect"></label><label>Failure Cause<input name="failure_cause"></label><label class="wide">Root Cause<textarea name="root_cause"></textarea></label><label class="wide">Corrective Action<textarea name="corrective_action"></textarea></label></div><button class="btn" style="margin-top:8px">Record Failure</button></form>@foreach($failures as $f)<div class="evidence"><strong>{{ $f->failure_mode }}</strong> · {{ $f->severity }} · {{ $f->failed_at }} → {{ $f->restored_at ?: 'Open' }} · {{ $f->downtime_minutes }} min<br><small>{{ $f->root_cause }}</small></div>@endforeach</section></div>

@if($workOrder->status!=='COMPLETED')<section class="box" style="margin-top:14px"><h3>Complete Work Order</h3><p class="muted">Required checklist items and required photo evidence must be complete before closure.</p><form method="POST" action="{{ route('maintenance.work-orders.complete',$workOrder) }}">@csrf<div class="forms"><label>Labor Hours<input type="number" step="0.01" min="0" name="labor_hours" value="{{ $workOrder->labor_hours }}"></label><label>Labor Cost SAR<input type="number" step="0.01" min="0" name="labor_cost" value="{{ $workOrder->labor_cost }}"></label><label>External Cost SAR<input type="number" step="0.01" min="0" name="external_cost" value="{{ $workOrder->external_cost }}"></label><label class="wide">Completion Notes<textarea name="completion_notes" required placeholder="Work performed, final condition, recommendations, follow-up requirements..."></textarea></label></div><button class="btn" style="margin-top:8px">Complete & Close Work Order</button></form></section>@else<section class="box" style="margin-top:14px"><h3>Completion Summary</h3><div class="cost-row"><span>Labor</span><strong>{{ number_format((float)$workOrder->labor_cost,2) }} SAR</strong></div><div class="cost-row"><span>Materials</span><strong>{{ number_format((float)$workOrder->material_cost,2) }} SAR</strong></div><div class="cost-row"><span>External</span><strong>{{ number_format((float)$workOrder->external_cost,2) }} SAR</strong></div><div class="cost-row total"><span>Total</span><strong>{{ number_format((float)$workOrder->total_cost,2) }} SAR</strong></div><p>{{ $workOrder->completion_notes }}</p></section>@endif
@endsection
