@extends('layouts.app')
@section('title','Inventory Operations')
@section('heading','Inventory Operations')
@section('content')
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="grid">
<div class="card"><h3>Warehouse</h3><form method="POST" action="{{ route('inventory.operations.warehouses.store') }}">@csrf<div class="form-grid"><label>Code<input name="code" required></label><label>Name<input name="name" required></label></div><button class="btn">Create Warehouse</button></form></div>
<div class="card"><h3>Warehouse Transfer</h3><form method="POST" action="{{ route('inventory.operations.transfers.store') }}">@csrf<div class="form-grid"><label>Transfer No<input name="transfer_no" required></label><label>Item<select name="item_id">@foreach($items as $i)<option value="{{ $i->id }}">{{ $i->item_code }}</option>@endforeach</select></label><label>From<select name="from_warehouse_code">@foreach($warehouses as $w)<option value="{{ $w->code }}">{{ $w->code }}</option>@endforeach</select></label><label>To<select name="to_warehouse_code">@foreach($warehouses as $w)<option value="{{ $w->code }}">{{ $w->code }}</option>@endforeach</select></label><label>Qty<input type="number" step="0.0001" name="quantity" required></label></div><button class="btn">Post Transfer</button></form></div>
<div class="card"><h3>Physical Count</h3><form method="POST" action="{{ route('inventory.operations.counts.store') }}">@csrf<div class="form-grid"><label>Count No<input name="count_no" required></label><label>Item<select name="item_id">@foreach($items as $i)<option value="{{ $i->id }}">{{ $i->item_code }}</option>@endforeach</select></label><label>Warehouse<select name="warehouse_code">@foreach($warehouses as $w)<option value="{{ $w->code }}">{{ $w->code }}</option>@endforeach</select></label><label>Counted Qty<input type="number" step="0.0001" name="counted_quantity" min="0" required></label></div><button class="btn">Post Count</button></form></div>
</div>
<div class="grid"><div class="card"><h3>Recent Transfers</h3><table class="table"><tr><th>No</th><th>From</th><th>To</th><th>Qty</th></tr>@foreach($transfers as $t)<tr><td>{{ $t->transfer_no }}</td><td>{{ $t->from_warehouse_code }}</td><td>{{ $t->to_warehouse_code }}</td><td>{{ $t->quantity }}</td></tr>@endforeach</table></div><div class="card"><h3>Recent Counts</h3><table class="table"><tr><th>No</th><th>Warehouse</th><th>System</th><th>Counted</th><th>Variance</th></tr>@foreach($counts as $c)<tr><td>{{ $c->count_no }}</td><td>{{ $c->warehouse_code }}</td><td>{{ $c->system_quantity }}</td><td>{{ $c->counted_quantity }}</td><td>{{ $c->variance }}</td></tr>@endforeach</table></div></div>
@endsection
