@extends('layouts.app')
@section('title','Customer Portal Users | UNIFCO Platform')
@section('heading','Customer Portal Users')
@section('content')
@include('admin.system.operations-styles')
<style>
.cp-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:14px;padding:18px 20px;margin-bottom:13px;display:flex;justify-content:space-between;align-items:center;gap:16px}.cp-hero small{color:#aebbd0;text-transform:uppercase;letter-spacing:.14em;font-size:8px;font-weight:900}.cp-hero h1{margin:4px 0;font-size:21px}.cp-hero p{margin:0;color:#dce5f2;font-size:10.5px}.cp-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:12px}.cp-kpi{background:#fff;border:1px solid #e3e8ef;border-radius:11px;padding:13px}.cp-kpi span{display:block;color:#77859a;font-size:8px;text-transform:uppercase;font-weight:800}.cp-kpi b{display:block;color:#132137;font-size:23px;margin-top:4px}.cp-toolbar{background:#fff;border:1px solid #e3e8ef;border-radius:11px;padding:11px;margin-bottom:9px}.cp-filters{display:grid;grid-template-columns:minmax(220px,2fr) repeat(3,minmax(150px,1fr)) auto;gap:8px;align-items:end}.cp-filters label{font-size:8px;color:#66758a;font-weight:800;text-transform:uppercase}.cp-wrap{background:#fff;border:1px solid #e3e8ef;border-radius:11px;overflow:hidden}.cp-table{display:table;margin:0;border-radius:0}.cp-table th{background:#fafbfd;color:#64748b;font-size:8px;text-transform:uppercase}.cp-table td{font-size:10px;vertical-align:middle}.role{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#1e315b;font-size:8px;font-weight:850}.status{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf8f2;color:#17734b;font-size:8px;font-weight:850}.status.off{background:#f5f1f2;color:#8a4a55}.scope{display:inline-flex;margin:2px;padding:3px 6px;border-radius:999px;background:#f5f7fa;color:#526176;font-size:8px}.hero-actions{display:flex;gap:6px;flex-wrap:wrap}@media(max-width:850px){.cp-kpis,.cp-filters{grid-template-columns:1fr 1fr}.cp-hero{align-items:flex-start;flex-direction:column}.cp-table{display:block;overflow-x:auto}}@media(max-width:600px){.cp-kpis,.cp-filters{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="cp-hero"><div><small>CUSTOMER ACCESS · PORTAL GOVERNANCE</small><h1>Customer Portal Users</h1><p>Manage customer-linked identities, portal roles and allowed sites separately from internal users.</p></div><div class="hero-actions"><a class="btn" href="{{ route('admin.users.create',['portal'=>1]) }}">+ New Portal User</a><a class="btn secondary" href="{{ route('workspace.show','users') }}">All Users</a></div></section>
<div class="cp-kpis"><div class="cp-kpi"><span>Portal Users</span><b>{{ $stats['total'] }}</b></div><div class="cp-kpi"><span>Active</span><b>{{ $stats['active'] }}</b></div><div class="cp-kpi"><span>Customer Admins</span><b>{{ $stats['admins'] }}</b></div><div class="cp-kpi"><span>Customers Represented</span><b>{{ $stats['customers'] }}</b></div></div>
<section class="cp-toolbar"><form class="cp-filters" method="GET"><label>Search<input name="q" value="{{ request('q') }}" placeholder="Name or email"></label><label>Customer<select name="customer_id"><option value="">All Customers</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)request('customer_id')===(string)$customer->id)>#{{ $customer->id }} · {{ $customer->customer_code }} · {{ $customer->name }}</option>@endforeach</select></label><label>Portal Role<select name="portal_role"><option value="">All Roles</option>@foreach($portalRoles as $code=>$label)<option value="{{ $code }}" @selected(request('portal_role')===$code)>{{ $label }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All Statuses</option>@foreach(['ACTIVE','INACTIVE','SUSPENDED'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select></label><div style="display:flex;gap:6px"><button class="btn">Apply</button><a class="btn secondary" href="{{ route('admin.customer-portal-users.index') }}">Reset</a></div></form></section>
<section class="cp-wrap"><table class="cp-table"><thead><tr><th>User</th><th>Customer</th><th>Portal Role</th><th>Allowed Sites</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>@forelse($users as $user)<tr><td><b>{{ $user->name }}</b><br><span class="muted">{{ $user->email }}</span></td><td>#{{ $user->customer_id }} · {{ $customerNames[$user->customer_id] ?? 'Unknown Customer' }}</td><td><span class="role">{{ $portalRoles[$user->customer_portal_role] ?? $user->customer_portal_role }}</span></td><td>@if($user->customer_portal_role==='CUSTOMER_ADMIN')<span class="scope">All customer sites</span>@else @forelse($scopes->get($user->id,collect()) as $scope)<span class="scope">{{ $siteNames[$scope->scope_id] ?? 'Site #'.$scope->scope_id }}</span>@empty<span class="muted">No site scope</span>@endforelse @endif</td><td><span class="status {{ $user->status==='ACTIVE'?'':'off' }}">{{ $user->status }}</span></td><td>{{ $user->last_login_at?->format('d M Y H:i') ?? 'Never recorded' }}</td><td><a class="btn secondary" href="{{ route('admin.users.show',$user) }}">User 360</a></td></tr>@empty<tr><td colspan="7">No Customer Portal users match the selected filters.</td></tr>@endforelse</tbody></table><div style="padding:10px">{{ $users->links() }}</div></section>
@endsection
