@extends('layouts.app')
@section('title','HR Analytics | UNIFCO Platform')
@section('heading','HR Analytics & Workforce Planning')
@section('content')
<style>
.a-hero{background:linear-gradient(135deg,#0f1f38,#213a68);color:#fff;border-radius:18px;padding:23px;display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:12px}.a-hero h1{font-size:24px;margin:4px 0}.a-hero p{font-size:10px;color:#d7e1ef;margin:0;max-width:850px}.kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;margin-bottom:12px}.kpi,.card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:13px}.kpi small,.card>small{font-size:8px;color:#7b899a;text-transform:uppercase;font-weight:800}.kpi b{display:block;font-size:19px;color:#17243b;margin:4px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wide{grid-column:1/-1}.card h3{font-size:13px;margin:0 0 4px}.bar-row{display:grid;grid-template-columns:140px 1fr 70px;gap:8px;align-items:center;margin:8px 0;font-size:9px}.bar{height:8px;background:#edf1f6;border-radius:999px;overflow:hidden}.bar i{height:100%;display:block;background:#1e315b}.table-wrap{overflow:auto}.table-wrap table{min-width:760px}.table-wrap th{font-size:8px;text-transform:uppercase}.table-wrap td{font-size:9px}.plan-form{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin:10px 0}.plan-form label{font-size:8px;font-weight:800;color:#68778a}.plan-form input,.plan-form select{width:100%;font-size:9px}.plan-form .notes{grid-column:1/-2}.trend{display:grid;grid-template-columns:repeat(auto-fit,minmax(70px,1fr));gap:7px;align-items:end;min-height:170px;margin-top:12px}.trend-col{display:grid;grid-template-rows:1fr auto;gap:5px;height:150px;text-align:center;font-size:8px;color:#6e7d91}.trend-bar{align-self:end;background:#1e315b;border-radius:6px 6px 2px 2px;min-height:3px}.risk{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef2f7;font-size:8px;font-weight:800}.risk.bad{background:#fbe7eb;color:#a20d2d}.risk.good{background:#e7f6ed;color:#17734b}.forecast{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin-top:10px}.forecast div{background:#f8fafc;border-radius:9px;padding:10px;text-align:center}.forecast b{display:block;font-size:16px}.forecast small{font-size:7px;color:#78869a}@media(max-width:1150px){.kpis{grid-template-columns:repeat(3,1fr)}.plan-form{grid-template-columns:1fr 1fr}.plan-form .notes{grid-column:1/-1}.forecast{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.a-hero{display:block}.a-hero form{margin-top:10px}.kpis{grid-template-columns:1fr 1fr}.forecast{grid-template-columns:1fr 1fr}}@media(max-width:500px){.kpis,.plan-form,.forecast{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="a-hero"><div><small>PEOPLE / HR · EXECUTIVE INTELLIGENCE</small><h1>Workforce Intelligence Command Center</h1><p>Executive workforce metrics generated from HR master data, payroll, attendance, leave, recruitment, performance and compliance. Saudi headcount ratios shown here are internal planning indicators, not official Nitaqat classifications.</p></div><form method="GET"><select name="year" onchange="this.form.submit()">@for($y=now()->year+1;$y>=now()->year-4;$y--)<option value="{{ $y }}" @selected($year===$y)>{{ $y }}</option>@endfor</select></form></section>
<div class="kpis"><div class="kpi"><small>Active Headcount</small><b>{{ $active->count() }}</b></div><div class="kpi"><small>Saudi Workforce</small><b>{{ $active->count()?round($saudis->count()/$active->count()*100,1):0 }}%</b><span>{{ $saudis->count() }} employees</span></div><div class="kpi"><small>Monthly Workforce Cost</small><b>SAR {{ number_format($monthlyCost,0) }}</b></div><div class="kpi"><small>Turnover {{ $year }}</small><b>{{ $turnoverRate }}%</b><span>{{ $separations }} separations</span></div><div class="kpi"><small>Absence Rate</small><b>{{ $absenceRate }}%</b><span>{{ $absences }} absence records</span></div><div class="kpi"><small>Compliance Risk</small><b>{{ $complianceRisk }}</b><span>{{ $criticalCompliance }} critical/high</span></div></div>
<div class="grid">
<section class="card"><h3>Cost & Capacity</h3><small>Annualized estimates based on current active employee compensation.</small><div class="bar-row"><span>Annualized workforce cost</span><div class="bar"><i style="width:100%"></i></div><b>SAR {{ number_format($annualizedCost,0) }}</b></div><div class="bar-row"><span>Paid leave liability</span><div class="bar"><i style="width:{{ $annualizedCost?min(100,$leaveLiability/$annualizedCost*100):0 }}%"></i></div><b>SAR {{ number_format($leaveLiability,0) }}</b></div><div class="bar-row"><span>Overtime hours</span><div class="bar"><i style="width:{{ min(100,$overtimeHours/100) }}%"></i></div><b>{{ number_format($overtimeHours,1) }}</b></div><div class="bar-row"><span>Late minutes</span><div class="bar"><i style="width:{{ min(100,$lateMinutes/1000) }}%"></i></div><b>{{ number_format($lateMinutes) }}</b></div><div class="bar-row"><span>Paid leave days</span><div class="bar"><i style="width:{{ min(100,$leaveDays/100) }}%"></i></div><b>{{ number_format($leaveDays,1) }}</b></div></section>
<section class="card"><h3>Talent & Hiring Signals</h3><small>Pipeline and performance readiness.</small><div class="bar-row"><span>Open vacancies</span><div class="bar"><i style="width:{{ min(100,$openVacancies*10) }}%"></i></div><b>{{ $openVacancies }}</b></div><div class="bar-row"><span>Approved headcount</span><div class="bar"><i style="width:{{ min(100,$approvedHeadcount*10) }}%"></i></div><b>{{ $approvedHeadcount }}</b></div><div class="bar-row"><span>Average performance</span><div class="bar"><i style="width:{{ min(100,(float)($averagePerformance??0)) }}%"></i></div><b>{{ $averagePerformance===null?'—':$averagePerformance }}</b></div><div class="bar-row"><span>Official Nitaqat evidence</span><div class="bar"><i style="width:{{ $profile && $profile->nitaqat_reported_band!=='NOT_REVIEWED'?100:10 }}%"></i></div><b>{{ $profile?str_replace('_',' ',$profile->nitaqat_reported_band):'Not reviewed' }}</b></div></section>
<section class="card"><h3>Department Workforce</h3><small>Headcount, Saudi mix and current monthly compensation.</small>@php($maxDept=max(1,(int)$departmentRows->max('headcount')))@foreach($departmentRows as $r)<div class="bar-row"><span>{{ $r['department'] }}</span><div class="bar"><i style="width:{{ $r['headcount']/$maxDept*100 }}%"></i></div><b>{{ $r['headcount'] }} · {{ $r['saudi_pct'] }}%</b></div>@endforeach</section>
<section class="card"><h3>Location Distribution</h3><small>Current active workforce footprint.</small>@php($maxLoc=max(1,(int)$locationRows->max('headcount')))@foreach($locationRows as $r)<div class="bar-row"><span>{{ $r['location'] }}</span><div class="bar"><i style="width:{{ $r['headcount']/$maxLoc*100 }}%"></i></div><b>{{ $r['headcount'] }}</b></div>@endforeach</section>
<section class="card"><h3>Nationality Mix</h3><small>Top recorded nationalities.</small>@php($maxNat=max(1,(int)$nationalityRows->max('count')))@foreach($nationalityRows as $r)<div class="bar-row"><span>{{ $r['name'] }}</span><div class="bar"><i style="width:{{ $r['count']/$maxNat*100 }}%"></i></div><b>{{ $r['count'] }}</b></div>@endforeach</section>
<section class="card"><h3>Contract Mix</h3><small>Employment contract profile.</small>@php($maxCon=max(1,(int)$contractRows->max('count')))@foreach($contractRows as $r)<div class="bar-row"><span>{{ str_replace('_',' ',$r['name']) }}</span><div class="bar"><i style="width:{{ $r['count']/$maxCon*100 }}%"></i></div><b>{{ $r['count'] }}</b></div>@endforeach</section>
<section class="card wide"><h3>Payroll Trend</h3><small>Gross payroll by payroll period during {{ $year }}.</small>@php($maxPayroll=max(1,(float)$payrollTrend->max('gross')))@if($payrollTrend->count())<div class="trend">@foreach($payrollTrend as $p)<div class="trend-col"><div class="trend-bar" title="SAR {{ number_format($p['gross'],2) }}" style="height:{{ max(3,$p['gross']/$maxPayroll*100) }}%"></div><span>{{ $p['month'] }}</span></div>@endforeach</div>@else<div class="muted" style="padding:20px 0">No payroll runs for this year.</div>@endif</section>
<section class="card wide"><h3>6-Month Headcount Forecast</h3><small>Planning forecast based on current headcount, recorded separations and approved recruitment pipeline. It is a planning model, not a prediction guarantee.</small><div class="forecast">@foreach($forecast as $f)<div><small>{{ $f['month'] }}</small><b>{{ $f['projected_headcount'] }}</b><small>Hires {{ $f['planned_hires_to_date'] }} · Attrition {{ $f['attrition_to_date'] }}</small></div>@endforeach</div></section>
<section class="card wide"><h3>Workforce Plan</h3><small>Set annual headcount, monthly cost and internal Saudi workforce targets by department or ALL.</small><form class="plan-form" method="POST" action="{{ route('hr.analytics.plans.store') }}">@csrf<label>Year<input type="number" name="plan_year" value="{{ $year }}" min="2020" max="{{ now()->year+3 }}"></label><label>Department<select name="department"><option value="ALL">ALL</option>@foreach($departmentRows as $r)<option value="{{ $r['department'] }}">{{ $r['department'] }}</option>@endforeach</select></label><label>Target Headcount<input type="number" name="target_headcount" min="0" required></label><label>Monthly Budget SAR<input type="number" step="0.01" name="budgeted_monthly_cost" min="0" required></label><label>Saudi Target %<input type="number" step="0.01" name="target_saudi_pct" min="0" max="100"></label><label class="notes">Notes<input name="notes"></label><div><button class="btn">Save Plan</button></div></form><div class="table-wrap"><table><thead><tr><th>Scope</th><th>Target HC</th><th>Actual HC</th><th>HC Gap</th><th>Monthly Budget</th><th>Actual Cost</th><th>Budget Gap</th><th>Saudi Target</th><th>Actual Saudi</th></tr></thead><tbody>@forelse($planAnalysis as $r)<tr><td>{{ $r['plan']->department }}</td><td>{{ $r['plan']->target_headcount }}</td><td>{{ $r['actual_headcount'] }}</td><td><span class="risk {{ $r['headcount_gap']<0?'bad':'good' }}">{{ $r['headcount_gap'] }}</span></td><td>SAR {{ number_format($r['plan']->budgeted_monthly_cost,0) }}</td><td>SAR {{ number_format($r['actual_monthly_cost'],0) }}</td><td>SAR {{ number_format($r['budget_gap'],0) }}</td><td>{{ $r['plan']->target_saudi_pct===null?'—':$r['plan']->target_saudi_pct.'%' }}</td><td>{{ $r['actual_saudi_pct'] }}%</td></tr>@empty<tr><td colspan="9">No workforce plan saved for {{ $year }}.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
