@include('customer.partials.portal-shell-open',[
    'customer'=>$customer,
    'activeSection'=>'assets',
    'pageTitle'=>'صحة الأصول · Asset Health',
    'pageDescription'=>'حالة جميع أصول الشركة واحتياجات الصيانة والإحلال',
])

<div class="portal-page-head"><div><h2>صحة محفظة الأصول</h2><p>مؤشرات الاعتمادية والصيانة وقطع الغيار لكل أصول الشركة.</p></div><a class="portal-btn soft" href="{{ route('customer.section','assets') }}">عرض جميع الأصول</a></div>
<form class="portal-card health-filters" method="GET"><label>الموقع<select name="site_id"><option value="">جميع المواقع</option>@foreach($sites as $site)<option value="{{ $site->id }}" @selected($siteId==$site->id)>{{ $site->site_code }} · {{ $site->name }}</option>@endforeach</select></label><label>العقد<select name="contract_id"><option value="">جميع العقود</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" @selected($contractId==$contract->id)>{{ $contract->contract_no }} · {{ $contract->title }}</option>@endforeach</select></label><button class="portal-btn">تطبيق</button></form>

<section class="health-kpis">
    @foreach([
        ['إجمالي الأصول',$metrics['total'],''],['متوسط الصحة',$metrics['average']===null?'لا توجد بيانات':$metrics['average'].'/100',''],['الجاهزية',$metrics['availability'].'%','green'],['تحتاج متابعة',$metrics['critical'],'red'],
        ['صيانة وقائية متأخرة',$metrics['overduePm'],'amber'],['أعطال خلال 30 يومًا',$metrics['failures30'],'red'],['تخطيط إحلال',$metrics['replacement'],'amber'],['تنبيهات قطع الغيار',$reorderAlerts->count(),'amber']
    ] as [$label,$value,$tone])<article class="portal-card health-kpi"><span>{{ $label }}</span><strong class="{{ $tone }}">{{ $value }}</strong></article>@endforeach
</section>

<div class="portal-grid-2">
    <section class="portal-card portal-panel"><h3>توصيات دورة الحياة · Lifecycle Recommendations</h3>@forelse($recommendations as $recommendation)<div class="health-item"><div><a href="{{ route('customer.asset.show',$recommendation->id) }}"><strong>{{ $recommendation->asset_code }} · {{ $recommendation->name }}</strong></a><small>{{ $recommendation->site ?: 'بدون موقع' }} · {{ $recommendation->reason }}</small></div><span class="portal-pill {{ in_array($recommendation->health_band,['ATTENTION','CRITICAL'])?'red':'amber' }}">{{ $recommendation->health_score ?? '—' }} · {{ str_replace('_',' ',$recommendation->recommendation) }}</span></div>@empty<div class="portal-empty"><strong>لا توجد إجراءات إحلال مطلوبة</strong>المحفظة لا تحتاج إجراء دورة حياة حاليًا.</div>@endforelse</section>
    <section class="portal-card portal-panel"><h3>توفر قطع الغيار · Parts Availability</h3>@forelse($reorderAlerts as $alert)<div class="health-item"><div><strong>{{ $alert->asset_code }} · {{ $alert->asset_name }}</strong><small>{{ $alert->item_code }} · {{ $alert->item_name }} · المتاح {{ number_format($alert->available_quantity,2) }} {{ $alert->uom }}</small></div><span class="portal-pill {{ $alert->computed_alert_status==='OUT_OF_STOCK'?'red':'amber' }}">{{ str_replace('_',' ',$alert->computed_alert_status) }}</span></div>@empty<div class="portal-empty"><strong>لا توجد تنبيهات توفر</strong>لا توجد قطع غيار تتطلب المتابعة حاليًا.</div>@endforelse</section>
</div>

<section class="portal-card portal-panel health-gap"><h3>استهلاك قطع الغيار خلال 12 شهرًا</h3><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>القطعة</th><th>الوصف</th><th>الكمية المستهلكة</th><th>أوامر العمل</th></tr></thead><tbody>@forelse($consumption as $item)<tr><td>{{ $item->item_code }}</td><td>{{ $item->item_name }}</td><td>{{ number_format((float)$item->total_quantity,2) }} {{ $item->uom }}</td><td>{{ $item->work_order_count }}</td></tr>@empty<tr><td colspan="4" class="portal-empty">لا توجد بيانات استهلاك خلال الفترة.</td></tr>@endforelse</tbody></table></div></section>

<section class="portal-card portal-panel health-gap"><h3>جميع الأصول · Full Portfolio</h3><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>الأصل</th><th>الموقع</th><th>الحالة التشغيلية</th><th>الصحة</th><th>العمر المتبقي</th><th></th></tr></thead><tbody>@forelse($assets as $asset)<tr><td><strong>{{ $asset->asset_code }}</strong><br>{{ $asset->name }}</td><td>{{ $asset->site?->name ?: '—' }}</td><td>{{ str_replace('_',' ',$asset->operational_status ?: '—') }}</td><td><span class="portal-pill {{ in_array($asset->health_band,['ATTENTION','CRITICAL'])?'red':($asset->health_band==='HEALTHY'?'green':'amber') }}">{{ $asset->health_score ?? '—' }} · {{ $asset->health_band ?: 'PENDING' }}</span></td><td>{{ $asset->remaining_life_months===null?'—':$asset->remaining_life_months.' شهر' }}</td><td><a class="portal-btn soft" href="{{ route('customer.asset.show',$asset) }}">Asset 360</a></td></tr>@empty<tr><td colspan="6" class="portal-empty">لا توجد أصول ضمن الفلاتر المحددة.</td></tr>@endforelse</tbody></table></div></section>

@push('late-styles')<style>
.health-filters{padding:12px;display:grid;grid-template-columns:1fr 1fr auto;gap:9px;align-items:end;margin-bottom:12px}.health-filters label{font-size:9px;font-weight:750}.health-filters select{display:block;width:100%;margin-top:5px;border:1px solid #d8e1eb;border-radius:8px;padding:9px;background:#fff}.health-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.health-kpi{padding:14px}.health-kpi span{display:block;color:var(--muted);font-size:9px}.health-kpi strong{display:block;font-size:20px;margin-top:7px}.health-kpi .green{color:var(--green)}.health-kpi .red{color:var(--red)}.health-kpi .amber{color:var(--amber)}.health-item{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #edf1f5}.health-item:last-child{border-bottom:0}.health-item strong,.health-item small{display:block;font-size:9px}.health-item small{color:var(--muted);margin-top:4px;line-height:1.6}.health-gap{margin-top:12px}@media(max-width:980px){.health-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.health-filters,.health-kpis{grid-template-columns:1fr}}
</style>@endpush
@include('customer.partials.portal-shell-close')
