<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $asset->asset_code }} · Asset 360 · UNIFCO</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
:root{font-family:'Cairo',sans-serif;--navy:#06275c;--navy2:#071f4d;--red:#e20b24;--green:#168a55;--bg:#f5f7fa;--line:#dfe6ee;--muted:#708095}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--navy2)}a{text-decoration:none;color:inherit}.top{height:70px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 28px;gap:12px;position:sticky;top:0;z-index:10}.brand{font-weight:900;color:var(--navy);font-size:20px}.spacer{flex:1}.btn{display:inline-flex;align-items:center;padding:9px 13px;border-radius:8px;background:var(--navy);color:#fff;font-size:11px;font-weight:800}.btn.secondary{background:#eef3f8;color:var(--navy)}.wrap{max-width:1380px;margin:auto;padding:22px}.hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:23px}.hero h1{margin:4px 0;font-size:25px}.hero p{margin:0;color:#cbd8e9;font-size:11px}.badge{display:inline-flex;padding:4px 8px;border-radius:999px;background:#ffffff18;font-size:9px}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:14px 0}.kpi,.box{background:#fff;border:1px solid var(--line);border-radius:12px}.kpi{padding:14px}.kpi b{display:block;font-size:20px;color:var(--navy)}.kpi span{font-size:9px;color:var(--muted)}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.box{padding:17px}.box h3{margin:0 0 12px;font-size:14px;color:var(--navy)}.mini{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mini div{background:#f7f9fc;padding:9px;border-radius:8px}.mini span{display:block;font-size:8px;color:var(--muted)}.mini strong{font-size:10px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:10px}.table th,.table td{padding:9px;border-bottom:1px solid #edf1f5;text-align:left;white-space:nowrap}.table th{font-size:9px;color:var(--muted)}.gallery{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.photo{border:1px solid var(--line);border-radius:8px;padding:10px;background:#fafbfd;font-size:9px}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eaf6ef;color:#176a43;font-size:8px}.pill.bad{background:#fdebed;color:#b42239}.specs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.spec{padding:8px;background:#f7f9fc;border-radius:7px}.spec span{font-size:8px;color:var(--muted);display:block}.spec b{font-size:10px}@media(max-width:1000px){.kpis{grid-template-columns:repeat(3,1fr)}.gallery{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.wrap{padding:12px}.grid2,.kpis,.mini,.specs{grid-template-columns:1fr 1fr}.top{padding:0 12px}.gallery{grid-template-columns:1fr}}@media(max-width:480px){.kpis,.mini,.specs{grid-template-columns:1fr}}
</style></head><body>
<header class="top"><div class="brand">UNIFCO</div><div class="spacer"></div><a class="btn secondary" href="{{ route('customer.section','assets') }}">← Assets · الأصول</a><a class="btn secondary" href="{{ route('customer.portal') }}">Dashboard</a></header>
<main class="wrap"><section class="hero"><span class="badge">READ ONLY · للعرض فقط</span><h1>{{ $asset->asset_code }} · {{ $asset->name }}</h1><p>{{ $asset->customer?->name }} · {{ $asset->site?->name ?: 'No site assigned' }} · {{ $asset->asset_category }} {{ $asset->asset_subcategory ? ' / '.$asset->asset_subcategory : '' }}</p></section>
<section class="kpis"><div class="kpi"><b>{{ $asset->operational_status ?: '—' }}</b><span>Operational Status · الحالة التشغيلية</span></div><div class="kpi"><b>{{ $metrics['pmCompliance'] }}%</b><span>PM Completion · الالتزام بالصيانة</span></div><div class="kpi"><b>{{ $metrics['failureCount'] }}</b><span>Failures · الأعطال</span></div><div class="kpi"><b>{{ $metrics['mtbf']===null?'—':round($metrics['mtbf']/60,1).' h' }}</b><span>MTBF</span></div><div class="kpi"><b>{{ $metrics['mttr']===null?'—':round($metrics['mttr']/60,1).' h' }}</b><span>MTTR</span></div><div class="kpi"><b>{{ $workOrders->where('status','COMPLETED')->count() }}</b><span>Completed WOs · أوامر مكتملة</span></div></section>
<div class="grid2"><section class="box"><h3>Asset Profile · بيانات الأصل</h3><div class="mini"><div><span>Manufacturer</span><strong>{{ $asset->manufacturer ?: '—' }}</strong></div><div><span>Model</span><strong>{{ $asset->model_no ?: '—' }}</strong></div><div><span>Serial Number</span><strong>{{ $asset->serial_no ?: '—' }}</strong></div><div><span>Criticality</span><strong>{{ $asset->criticality ?: '—' }}</strong></div><div><span>Lifecycle</span><strong>{{ $asset->lifecycle_status ?: '—' }}</strong></div><div><span>Warranty</span><strong>{{ $asset->warranty_expiry?->format('Y-m-d') ?: '—' }}</strong></div><div><span>Installation Date</span><strong>{{ $asset->installation_date?->format('Y-m-d') ?: '—' }}</strong></div><div><span>Commission Date</span><strong>{{ $asset->commission_date?->format('Y-m-d') ?: '—' }}</strong></div></div></section><section class="box"><h3>Technical Specifications · المواصفات الفنية</h3><div class="specs">@forelse($specifications as $s)<div class="spec"><span>{{ $s->spec_label }}</span><b>{{ $s->spec_value ?: '—' }} {{ $s->unit }}</b></div>@empty<p>No specifications available.</p>@endforelse</div></section></div>
<div class="grid2"><section class="box"><h3>Maintenance Plans · جداول الصيانة</h3><div class="table-wrap"><table class="table"><thead><tr><th>Plan</th><th>Strategy</th><th>Frequency</th><th>Next Due</th><th>Priority</th><th>Status</th></tr></thead><tbody>@forelse($plans as $p)<tr><td>{{ $p->plan_no }}<br><small>{{ $p->name }}</small></td><td>{{ $p->maintenance_strategy }}</td><td>{{ $p->frequency_value }} {{ $p->frequency_type }}</td><td>{{ $p->next_due_date ?: $p->next_due_meter ?: '—' }}</td><td>{{ $p->priority }}</td><td>{{ $p->status }}</td></tr>@empty<tr><td colspan="6">No maintenance plans.</td></tr>@endforelse</tbody></table></div></section><section class="box"><h3>Failure History · سجل الأعطال</h3><div class="table-wrap"><table class="table"><thead><tr><th>Failure</th><th>Severity</th><th>Date</th><th>Downtime</th><th>Status</th></tr></thead><tbody>@forelse($failures as $f)<tr><td>{{ $f->failure_mode }}</td><td>{{ $f->severity }}</td><td>{{ $f->failed_at }}</td><td>{{ $f->downtime_minutes }} min</td><td><span class="pill {{ $f->status==='OPEN'?'bad':'' }}">{{ $f->status }}</span></td></tr>@empty<tr><td colspan="5">No failures recorded.</td></tr>@endforelse</tbody></table></div></section></div>
<section class="box" style="margin-top:14px"><h3>Work Order History · سجل أوامر العمل</h3><div class="table-wrap"><table class="table"><thead><tr><th>WO</th><th>Type</th><th>Priority</th><th>Planned</th><th>Status</th><th>Details</th></tr></thead><tbody>@forelse($workOrders as $wo)<tr><td>{{ $wo->work_order_no }}</td><td>{{ $wo->maintenance_type }}</td><td>{{ $wo->priority }}</td><td>{{ $wo->planned_start?->format('Y-m-d H:i') ?: '—' }}</td><td>{{ $wo->status }}</td><td><a class="btn secondary" href="{{ route('customer.work-orders.show',$wo) }}">View Report</a></td></tr>@empty<tr><td colspan="6">No work orders.</td></tr>@endforelse</tbody></table></div></section>
<div class="grid2"><section class="box"><h3>Documents · المستندات</h3>@forelse($documents as $d)<div style="padding:8px 0;border-bottom:1px solid #edf1f5;font-size:10px"><strong>{{ $d->document_type }}</strong> · {{ $d->title }}</div>@empty<p>No customer-visible documents.</p>@endforelse</section><section class="box"><h3>Maintenance Evidence · صور وتقارير داعمة</h3><div class="gallery">@forelse($attachments as $a)<a class="photo" href="{{ route('customer.work-orders.attachments.download',[$a->work_order_id,$a->id]) }}"><strong>{{ $a->attachment_type }}</strong><br>{{ $a->title ?: $a->original_name }}</a>@empty<p>No customer-visible evidence.</p>@endforelse</div></section></div>
</main></body></html>
