@include('customer.partials.portal-shell-open', ['activeSection'=>'search','pageTitle'=>'Customer Search','pageDescription'=>'Search all customer requests, assets, work orders, contracts and invoices.'])
@push('late-styles')<style>.search-form{display:flex;gap:8px;padding:12px;margin-bottom:12px}.search-form input{flex:1;min-width:0;border:1px solid var(--line);border-radius:8px;padding:10px}.search-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.search-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #edf1f5}.search-item:last-child{border-bottom:0}.search-item b{font-size:10px}.search-item small{display:block;color:var(--muted);font-size:8px;margin-top:3px}@media(max-width:780px){.search-grid{grid-template-columns:1fr}}</style>@endpush
<div class="portal-page-head"><div><h2>Customer Search</h2><p>One search across the complete customer account.</p></div>@if($query!=='')<span class="portal-pill">{{ $total }} results</span>@endif</div>
<form class="portal-card search-form" method="GET"><input name="q" value="{{ $query }}" required placeholder="Request, work order, asset, invoice or contract"><button class="portal-btn">Search</button></form>
@if($query==='')<div class="portal-card portal-empty"><strong>Search the complete customer account</strong>Enter a reference number, asset, serial number, subject or title.</div>@else<div class="search-grid">
<section class="portal-card portal-panel"><h3>Service Requests ({{ $requests->count() }})</h3>@forelse($requests as $item)<a class="search-item" href="{{ route('customer.service-requests.show',$item) }}"><div><b>{{ $item->request_no }}</b><small>{{ $item->subject }}</small></div><span class="portal-pill">{{ str_replace('_',' ',$item->status) }}</span></a>@empty<div class="portal-empty">No service requests found.</div>@endforelse</section>
<section class="portal-card portal-panel"><h3>Work Orders ({{ $workOrders->count() }})</h3>@forelse($workOrders as $item)<a class="search-item" href="{{ route('customer.work-orders.show',$item) }}"><div><b>{{ $item->work_order_no }}</b><small>{{ $item->asset?->asset_code }} · {{ $item->asset?->name }}</small></div><span class="portal-pill">{{ str_replace('_',' ',$item->status) }}</span></a>@empty<div class="portal-empty">No work orders found.</div>@endforelse</section>
<section class="portal-card portal-panel"><h3>Assets ({{ $assets->count() }})</h3>@forelse($assets as $item)<a class="search-item" href="{{ route('customer.asset.show',$item) }}"><div><b>{{ $item->asset_code }}</b><small>{{ $item->name }} · {{ $item->serial_no ?: 'No serial' }}</small></div><span class="portal-pill">Asset 360</span></a>@empty<div class="portal-empty">No assets found.</div>@endforelse</section>
<section class="portal-card portal-panel"><h3>Contracts & Invoices ({{ $contracts->count()+$invoices->count() }})</h3>@foreach($contracts as $item)<a class="search-item" href="{{ route('customer.section','contracts') }}"><div><b>{{ $item->contract_no }}</b><small>{{ $item->title }}</small></div><span class="portal-pill">Contract</span></a>@endforeach @foreach($invoices as $item)<a class="search-item" href="{{ route('customer.section','invoices') }}"><div><b>{{ $item->document_no }}</b><small>{{ number_format((float)$item->amount,2) }} {{ $item->currency }}</small></div><span class="portal-pill">Invoice</span></a>@endforeach @if($contracts->isEmpty()&&$invoices->isEmpty())<div class="portal-empty">No contracts or invoices found.</div>@endif</section>
</div>@endif
@include('customer.partials.portal-shell-close')
