@include('customer.partials.portal-shell-open', [
    'activeSection' => 'work-orders',
    'pageTitle' => $workOrder->work_order_no,
    'pageDescription' => 'Customer service report · تقرير خدمة العميل',
])

@push('late-styles')
<style>
    .report-actions{display:flex;gap:7px;flex-wrap:wrap}.report-hero{background:linear-gradient(135deg,#071f4d,#123d72);color:#fff;border-radius:16px;padding:22px}.report-hero h2{margin:6px 0;font-size:25px}.report-hero p{margin:0;color:#ccd9e9;font-size:10px}.report-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}.report-kpi{padding:14px}.report-kpi b{display:block;font-size:17px}.report-kpi span{font-size:8px;color:var(--muted)}.report-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.report-summary{white-space:pre-wrap;font-size:10px;line-height:1.8}.report-evidence{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.report-file{padding:10px;background:#f7f9fc;border-radius:8px;border:1px solid #e4eaf0;font-size:9px}.report-footer{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.report-sign{min-height:110px;border:1px dashed #cfd9e6;border-radius:9px;padding:13px}.report-sign small{color:var(--muted);font-size:9px}.report-qr{display:flex;align-items:center;gap:12px}.report-qr-mark{width:68px;height:68px;background:repeating-linear-gradient(45deg,var(--navy) 0 4px,#fff 4px 8px);border:8px solid #fff;outline:1px solid var(--line)}@media(max-width:900px){.report-kpis{grid-template-columns:repeat(2,1fr)}.report-grid,.report-footer{grid-template-columns:1fr}.report-evidence{grid-template-columns:1fr 1fr}}@media(max-width:500px){.report-kpis,.report-evidence{grid-template-columns:1fr}}@media print{.report-actions{display:none}.report-hero{break-inside:avoid}.portal-card{box-shadow:none}.report-grid{break-inside:avoid}}
</style>
@endpush

@php
    $statusLabels=['OPEN'=>'Open · مفتوح','IN_PROGRESS'=>'In Progress · جاري التنفيذ','COMPLETED'=>'Completed · مكتمل','CLOSED'=>'Closed · مغلق','NORMAL'=>'Normal · عادية','HIGH'=>'High · مرتفعة','EMERGENCY'=>'Emergency · طارئة','CORRECTIVE'=>'Corrective · تصحيحية','PREVENTIVE'=>'Preventive · وقائية'];
    $label=fn($value)=>$statusLabels[strtoupper((string)$value)]??str_replace('_',' ',(string)$value?:'—');
    $isComplete=in_array(strtoupper((string)$workOrder->status),['COMPLETED','CLOSED'],true);
@endphp

<div class="portal-page-head"><div><h2>Service Report · تقرير الخدمة</h2><p>Verified customer-visible execution record. Internal UNIFCO costs are excluded.</p></div><div class="report-actions no-print"><a class="portal-btn soft" href="{{ route('customer.section','work-orders') }}">← Work Orders</a><a class="portal-btn soft" href="{{ route('customer.asset.show',$workOrder->asset) }}">Asset 360</a><button class="portal-btn" type="button" onclick="window.print()">Print / PDF</button></div></div>

<section class="report-hero"><span class="portal-pill">CUSTOMER SERVICE REPORT · تقرير خدمة العميل</span><h2>{{ $workOrder->work_order_no }}</h2><p>{{ $workOrder->asset?->asset_code }} · {{ $workOrder->asset?->name }} · {{ $workOrder->asset?->site?->name ?: 'No site' }} · {{ $label($workOrder->maintenance_type) }} · {{ $label($workOrder->priority) }}</p></section>
<section class="report-kpis"><div class="portal-card report-kpi"><b>{{ $label($workOrder->status) }}</b><span>Status · الحالة</span></div><div class="portal-card report-kpi"><b>{{ $workOrder->planned_start?->format('Y-m-d H:i') ?: '—' }}</b><span>Planned · الموعد المخطط</span></div><div class="portal-card report-kpi"><b>{{ $workOrder->started_at?->format('Y-m-d H:i') ?: '—' }}</b><span>Started · بدأ التنفيذ</span></div><div class="portal-card report-kpi"><b>{{ $workOrder->completed_at?->format('Y-m-d H:i') ?: '—' }}</b><span>Completed · اكتمل</span></div><div class="portal-card report-kpi"><b>{{ $workOrder->downtime_minutes ?: 0 }} min</b><span>Downtime · التوقف</span></div></section>

@unless($isComplete)<section class="portal-card portal-panel" style="border-inline-start:4px solid var(--amber)"><h3>Work is still in progress · العمل ما زال جاريًا</h3><p style="font-size:10px;color:var(--muted);margin:0">This is a live interim report. Final customer acceptance becomes available after UNIFCO completes the work order.</p></section>@endunless

<div class="report-grid"><section class="portal-card portal-panel"><h3>Maintenance Checklist · قائمة الفحص</h3><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Task</th><th>Result</th><th>Reading</th><th>Completed</th></tr></thead><tbody>@forelse($tasks as $task)<tr><td>{{ $task->task_title }}</td><td><span class="portal-pill {{ $task->result_status==='FAIL'?'red':'green' }}">{{ $label($task->result_status ?: 'PENDING') }}</span></td><td>{{ $task->numeric_value ?? $task->text_value ?? '—' }} {{ $task->unit }}</td><td>{{ $task->completed_at ?: '—' }}</td></tr>@empty<tr><td colspan="4">No checklist attached.</td></tr>@endforelse</tbody></table></div></section>
<section class="portal-card portal-panel"><h3>Spare Parts Used · قطع الغيار المستخدمة</h3><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Part</th><th>Description</th><th>Quantity</th></tr></thead><tbody>@forelse($materials as $material)<tr><td>{{ $material->item_code }}</td><td>{{ $material->item_name }}</td><td>{{ $material->quantity }} {{ $material->uom }}</td></tr>@empty<tr><td colspan="3">No parts used.</td></tr>@endforelse</tbody></table></div><p style="font-size:9px;color:var(--muted);margin-top:10px">Internal purchasing and labor costs are not displayed in the customer portal.</p></section></div>

<div class="report-grid"><section class="portal-card portal-panel"><h3>Failure / Corrective Action · العطل والإجراء التصحيحي</h3>@forelse($failures as $failure)<div style="padding:9px 0;border-bottom:1px solid #edf1f5"><strong style="font-size:10px">{{ $failure->failure_mode }} · {{ $label($failure->severity) }}</strong><div style="font-size:9px;color:var(--muted)">{{ $failure->failed_at }} → {{ $failure->restored_at ?: 'Open' }} · {{ $failure->downtime_minutes }} min</div><div class="report-summary">{{ $failure->failure_effect }}
{{ $failure->corrective_action }}</div></div>@empty<p class="report-summary">No failure event linked to this work order.</p>@endforelse</section><section class="portal-card portal-panel"><h3>Completion Summary · ملخص التنفيذ</h3><div class="report-summary">{{ $workOrder->completion_notes ?: $workOrder->execution_notes ?: 'Work is still in progress.' }}</div></section></div>

<section class="portal-card portal-panel" style="margin-top:14px"><h3>Maintenance Evidence · الصور قبل وبعد</h3><div class="report-evidence">@forelse($attachments as $attachment)<a class="report-file" href="{{ route('customer.work-orders.attachments.download',[$workOrder,$attachment->id]) }}"><strong>{{ $label($attachment->attachment_type) }}</strong><br>{{ $attachment->title ?: $attachment->original_name }}</a>@empty<div class="portal-empty"><strong>No customer-visible evidence</strong>Before/after photos will appear here once uploaded.</div>@endforelse</div></section>

<section class="report-footer"><div class="portal-card portal-panel"><h3>Customer Acceptance · اعتماد العميل</h3><div class="report-sign">@if($workOrder->customer_accepted_at)<strong>Accepted · تم الاعتماد</strong><br><small>{{ $workOrder->customer_accepted_at }}<br>{{ $workOrder->customer_acceptance_notes }}</small>@elseif($workOrder->customer_rejected_at)<strong style="color:var(--red)">Rework requested · مطلوب إعادة العمل</strong><br><small>{{ $workOrder->customer_rejected_at }}<br>{{ $workOrder->customer_acceptance_notes }}</small>@else<small>{{ $isComplete ? 'Awaiting customer acceptance.' : 'Available after work completion.' }}</small>@endif</div></div><div class="portal-card portal-panel"><h3>Report Verification · التحقق من التقرير</h3><div class="report-qr"><div class="report-qr-mark" aria-hidden="true"></div><div><strong>{{ $workOrder->work_order_no }}</strong><p style="font-size:9px;color:var(--muted)">Generated from the live UNIFCO record.<br>{{ now()->format('Y-m-d H:i') }}</p></div></div></div></section>

@include('customer.partials.portal-shell-close')
