@extends('layouts.app')
@section('title','Procurement Operations')
@section('heading','Procurement Operations')
@section('content')
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="grid">
<div class="card"><h3>Supplier</h3><form method="POST" action="{{ route('procurement.operations.suppliers.store') }}">@csrf<div class="form-grid"><label>Code<input name="supplier_code" required></label><label>Name<input name="name" required></label><label>Email<input name="email"></label><label>Tax No<input name="tax_no"></label></div><button class="btn">Create Supplier</button></form></div>
<div class="card"><h3>Purchase Requisition</h3><form method="POST" action="{{ route('procurement.operations.requisitions.store') }}">@csrf<div class="form-grid"><label>No<input name="requisition_no" required></label><label>Date<input type="date" name="requested_date" required></label><label>Purpose<input name="purpose"></label><label>Item<select name="lines[0][item_id]">@foreach($items as $i)<option value="{{ $i->id }}">{{ $i->item_code }} — {{ $i->name }}</option>@endforeach</select></label><label>Qty<input type="number" step="0.0001" name="lines[0][quantity]" required></label><label>Est. Price<input type="number" step="0.01" name="lines[0][estimated_unit_price]" required></label></div><button class="btn">Create Requisition</button></form></div>
</div>
<div class="card"><h3>Requisitions</h3><table class="table"><tr><th>No</th><th>Status</th><th>Lines</th><th>Actions</th></tr>@foreach($requisitions as $r)<tr><td>{{ $r->requisition_no }}</td><td>{{ $r->status }}</td><td>{{ $r->lines->count() }}</td><td>@if($r->status==='DRAFT')<form method="POST" action="{{ route('procurement.operations.requisitions.approve',$r) }}">@csrf<button class="btn">Approve</button></form>@elseif($r->status==='APPROVED')<form method="POST" action="{{ route('procurement.operations.requisitions.convert',$r) }}">@csrf<select name="supplier_id">@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select><input name="po_number" placeholder="PO number" required><button class="btn">Create PO</button></form>@endif</td></tr>@endforeach</table></div>
<div class="card"><h3>3-Way Match / AP Handoff</h3><table class="table"><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Invoice Match</th></tr>@foreach($orders as $po)<tr><td>{{ $po->po_number }}</td><td>{{ $po->supplier_name }}</td><td>{{ $po->status }}</td><td>@if($po->status==='APPROVED')<form method="POST" action="{{ route('procurement.operations.purchase-orders.match',$po) }}">@csrf<select name="supplier_id">@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select><input name="invoice_no" placeholder="Invoice #" required><input type="date" name="invoice_date" required><input type="number" step="0.01" name="amount" placeholder="Amount" required><input name="currency" value="USD" required><input name="control_account_code" value="2000" required><input name="offset_account_code" value="5000" required><button class="btn">Match + Create AP</button></form>@endif</td></tr>@endforeach</table></div>
@endsection
