@extends('layouts.app')
@section('title','HR Operations | UNIFCO Platform')
@section('heading','HR Operations')
@section('content')
<style>
.ops-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:16px;padding:20px 22px;margin-bottom:13px;display:flex;justify-content:space-between;align-items:center;gap:14px}.ops-hero small{display:block;color:#aab9cd;font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.ops-hero h1{font-size:22px;margin:5px 0}.ops-hero p{margin:0;color:#d9e2ef;font-size:10px}.ops-links{display:flex;gap:6px;flex-wrap:wrap}.ops-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ops-card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:16px;scroll-margin-top:95px}.ops-card.wide{grid-column:1/-1}.ops-card h3{font-size:13px;margin:0 0 4px;color:#17243c}.ops-card>small{display:block;font-size:8px;color:#8290a2;margin-bottom:11px}.ops-form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;align-items:end;padding:10px;background:#f8fafc;border-radius:9px;margin-bottom:10px}.ops-form label{font-size:8px;color:#66758a;font-weight:700}.ops-form input,.ops-form select{width:100%;font-size:9px}.ops-table{display:table;width:100%;margin:0}.ops-table th{font-size:8px;text-transform:uppercase;background:#f7f9fc;color:#69778b}.ops-table td{font-size:9px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eaf6ef;color:#17734b;font-size:8px;font-weight:800}.state.pending{background:#fff4e3;color:#945900}.state.reject{background:#fbecef;color:#9d2439}.decision{display:flex;gap:4px}.payroll-card{padding:10px;background:#f8fafc;border-radius:9px;margin-top:7px;display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.payroll-card b,.payroll-card small{display:block}.payroll-card small{color:#7c899b;font-size:8px;margin-top:3px}.post-form{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px}.post-form input{font-size:8px}.legacy-note{padding:10px;background:#fff7e8;border-left:3px solid #d18a17;border-radius:8px;color:#765308;font-size:9px;margin-bottom:12px}@media(max-width:900px){.ops-grid{grid-template-columns:1fr}.ops-card.wide{grid-column:auto}.ops-form{grid-template-columns:1fr 1fr}.post-form{grid-template-columns:1fr 1fr}.ops-hero{display:block}.ops-links{margin-top:12px}}@media(max-width:550px){.ops-form,.post-form{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="ops-hero"><div><small>People / HR · Transitional Operations</small><h1>HR Operations</h1><p>Existing operational engine preserved while Attendance, Leave and Payroll become dedicated HR workspaces.</p></div><div class="ops-links"><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a><a class="btn secondary" href="{{ route('hr.employees.index') }}">Employees</a></div></section>
<div class="legacy-note">This page remains operational during the HR modernization. Transactions are not being discarded; they are being separated into dedicated modules in subsequent HR phases.</div>
<div class="ops-grid">
<section class="ops-card" id="positions"><h3>Job Positions</h3><small>Position and department structure used by Employee 360.</small><form class="ops-form" method="POST" action="{{ route('hr.operations.positions.store') }}">@csrf<label>Code<input name="code" required></label><label>Title<input name="title" required></label><label>Department<input name="department"></label><div><button class="btn">Create Position</button></div></form><table class="ops-table"><thead><tr><th>Code</th><th>Title</th><th>Department</th></tr></thead><tbody>@foreach($positions as $p)<tr><td>{{ $p->code }}</td><td>{{ $p->title }}</td><td>{{ $p->department ?: '—' }}</td></tr>@endforeach</tbody></table></section>
<section class="ops-card" id="attendance"><h3>Attendance & Time</h3><small>Current attendance recorder. Shift, punch and Saudi time-policy engine will be introduced in HR Phase 2.</small><form class="ops-form" method="POST" action="{{ route('hr.operations.attendance.store') }}">@csrf<label>Employee<select name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} · {{ $e->name }}</option>@endforeach</select></label><label>Work Date<input type="date" name="work_date" required></label><label>Worked Hours<input type="number" step="0.25" name="worked_hours" value="8" required></label><label>Overtime<input type="number" step="0.25" name="overtime_hours" value="0" required></label><div><button class="btn">Record Attendance</button></div></form>@if($attendance->isNotEmpty())<table class="ops-table"><thead><tr><th>Employee</th><th>Date</th><th>Worked</th><th>Overtime</th><th>Status</th></tr></thead><tbody>@foreach($attendance->take(12) as $a)<tr><td>#{{ $a->employee_id }}</td><td>{{ $a->work_date?->format('d M Y') }}</td><td>{{ $a->worked_hours }} h</td><td>{{ $a->overtime_hours }} h</td><td>{{ $a->status }}</td></tr>@endforeach</tbody></table>@endif</section>
<section class="ops-card wide" id="leave"><h3>Leave Management</h3><small>Leave requests and approvals. Leave balances, accrual and statutory policy types are scheduled for HR Phase 2.</small><form class="ops-form" method="POST" action="{{ route('hr.operations.leave.store') }}">@csrf<label>Employee<select name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} · {{ $e->name }}</option>@endforeach</select></label><label>Leave Type<select name="leave_type"><option>ANNUAL</option><option>SICK</option><option>UNPAID</option><option>OTHER</option></select></label><label>Starts<input type="date" name="starts_on" required></label><label>Ends<input type="date" name="ends_on" required></label><label>Days<input type="number" step="0.5" name="days" required></label><label style="grid-column:span 2">Reason<input name="reason"></label><div><button class="btn">Submit Leave</button></div></form><table class="ops-table"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th>Decision</th></tr></thead><tbody>@foreach($leaves as $l)<tr><td>#{{ $l->employee_id }}</td><td>{{ $l->leave_type }}</td><td>{{ $l->starts_on->toDateString() }} → {{ $l->ends_on->toDateString() }}</td><td>{{ $l->days }}</td><td><span class="state {{ $l->status==='PENDING'?'pending':($l->status==='REJECTED'?'reject':'') }}">{{ $l->status }}</span></td><td>@if($l->status==='PENDING')<form class="decision" method="POST" action="{{ route('hr.operations.leave.decide',$l) }}">@csrf<button class="btn" name="decision" value="APPROVED">Approve</button><button class="btn secondary" name="decision" value="REJECTED">Reject</button></form>@endif</td></tr>@endforeach</tbody></table></section>
<section class="ops-card wide" id="payroll"><h3>Payroll Runs</h3><small>Current payroll transaction engine. Dedicated Saudi payroll, compensation and statutory deduction workspaces will replace this entry form in HR Phase 4.</small><form class="ops-form" method="POST" action="{{ route('hr.operations.payroll.store') }}">@csrf<label>Payroll No<input name="payroll_no" placeholder="PAY-2026-08" required></label><label>Period Start<input type="date" name="period_start" required></label><label>Period End<input type="date" name="period_end" required></label><label>Posting Date<input type="date" name="posting_date" required></label><label>Currency<input name="currency" value="SAR" maxlength="3" required></label><label>Employee<select name="lines[0][employee_id]">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }} · {{ $e->name }}</option>@endforeach</select></label><label>Basic Pay<input type="number" step="0.01" name="lines[0][basic_pay]" required></label><label>Allowances<input type="number" step="0.01" name="lines[0][allowances]" value="0" required></label><label>Deductions<input type="number" step="0.01" name="lines[0][deductions]" value="0" required></label><div><button class="btn">Create Payroll</button></div></form>@forelse($payrolls as $run)<div class="payroll-card"><span><b>{{ $run->payroll_no }} · {{ $run->status }}</b><small>{{ $run->period_start }} → {{ $run->period_end }} · {{ number_format($run->lines->sum('net_pay'),2) }} {{ $run->currency }}</small></span>@if($run->status==='DRAFT')<form class="post-form" method="POST" action="{{ route('hr.operations.payroll.post',$run) }}">@csrf<input name="expense_account_code" placeholder="Payroll expense" required><input name="payable_account_code" placeholder="Net payroll payable" required><input name="deductions_account_code" placeholder="Deductions payable" required><button class="btn">Post to Finance</button></form>@endif</div>@empty<div style="padding:14px;color:#8390a2;font-size:9px">No payroll runs yet.</div>@endforelse</section>
</div>
@endsection
