@extends('layouts.app')
@section('title','HR Dashboard | UNIFCO Platform')
@section('heading','HR Command Center')
@section('content')
<style>
.hr-hero{background:linear-gradient(135deg,#101f38,#1e315b 58%,#273f70);color:#fff;border-radius:18px;padding:24px;display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:14px}.hr-hero small{display:block;font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#aab8ce;font-weight:800}.hr-hero h1{font-size:25px;margin:5px 0}.hr-hero p{margin:0;color:#d7e0ed;font-size:11px;max-width:760px}.hr-actions{display:flex;gap:7px;flex-wrap:wrap}.hr-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:14px}.hr-kpi{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:14px}.hr-kpi small{display:block;color:#77869a;font-size:8px;font-weight:800;text-transform:uppercase}.hr-kpi b{display:block;font-size:23px;color:#132137;margin-top:5px}.hr-kpi span{font-size:8px;color:#8190a4}.hr-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.hr-card{background:#fff;border:1px solid #e3e8ef;border-radius:14px;padding:16px}.hr-card h3{font-size:13px;margin:0 0 4px;color:#17243c}.hr-card>small{font-size:8px;color:#8190a4}.hr-list{display:grid;gap:6px;margin-top:11px}.hr-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:9px 10px;background:#f7f9fc;border-radius:8px;font-size:10px}.hr-row b{display:block}.hr-row small{display:block;color:#7d899a;margin-top:2px}.pill-state{font-size:8px;font-weight:800;padding:4px 7px;border-radius:999px;background:#eaf4ef;color:#17734b}.pill-warn{background:#fff3e1;color:#9a5c00}.dept-row{display:grid;grid-template-columns:120px 1fr 30px;gap:8px;align-items:center;margin:9px 0;font-size:9px}.dept-track{height:7px;background:#eef2f7;border-radius:999px;overflow:hidden}.dept-track i{display:block;height:100%;background:#1e315b;border-radius:999px}.empty{padding:16px;text-align:center;color:#8390a2;font-size:10px;background:#f8fafc;border-radius:9px;margin-top:10px}.section-links{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:14px}.section-link{display:block;text-decoration:none;background:#fff;border:1px solid #e3e8ef;border-radius:12px;padding:13px;color:#17243c}.section-link b{display:block;font-size:11px}.section-link small{font-size:8px;color:#7b899c}.section-link.live{border-color:#bccae0;background:linear-gradient(180deg,#fff,#f7faff)}.section-link.live b:after{content:' LIVE';font-size:7px;color:#17734b;margin-left:5px}.section-link:hover{border-color:#9aabc2;box-shadow:0 5px 14px rgba(19,33,55,.05)}@media(max-width:1150px){.hr-kpis{grid-template-columns:repeat(3,1fr)}.section-links{grid-template-columns:repeat(2,1fr)}}@media(max-width:820px){.hr-grid{grid-template-columns:1fr}.hr-hero{display:block}.hr-actions{margin-top:13px}.hr-kpis{grid-template-columns:1fr 1fr}}@media(max-width:520px){.hr-kpis,.section-links{grid-template-columns:1fr}.dept-row{grid-template-columns:90px 1fr 25px}}
</style>
<section class="hr-hero"><div><small>People / HR · Saudi HR operations</small><h1>HR Command Center</h1><p>Employee lifecycle, attendance intelligence, leave balances, payroll readiness and compliance signals from one operational view.</p></div><div class="hr-actions"><a class="btn" href="{{ route('hr.employees.create') }}">+ New Employee</a><a class="btn secondary" href="{{ route('hr.attendance.index') }}">Attendance & Time</a><a class="btn secondary" href="{{ route('hr.leave.index') }}">Leave Management</a></div></section>
<div class="hr-kpis"><div class="hr-kpi"><small>Total Employees</small><b>{{ $stats['total'] }}</b><span>Company workforce</span></div><div class="hr-kpi"><small>Active</small><b>{{ $stats['active'] }}</b><span>Currently employed</span></div><div class="hr-kpi"><small>On Leave Today</small><b>{{ $stats['on_leave'] }}</b><span>Approved leave</span></div><div class="hr-kpi"><small>Attendance Today</small><b>{{ $stats['present_today'] }}</b><span>Recorded employees</span></div><div class="hr-kpi"><small>Pending Leave</small><b>{{ $stats['pending_leave'] }}</b><span>Needs decision</span></div><div class="hr-kpi"><small>Monthly Compensation</small><b>{{ number_format($stats['monthly_compensation'],0) }}</b><span>SAR employee master estimate</span></div></div>
<div class="hr-grid">
<section class="hr-card"><h3>Workforce by Department</h3><small>Current employee distribution by assigned job position.</small>@php($deptMax=max(1,$departments->max()??1))@forelse($departments as $department=>$count)<div class="dept-row"><span>{{ $department }}</span><div class="dept-track"><i style="width:{{ ($count/$deptMax)*100 }}%"></i></div><b>{{ $count }}</b></div>@empty<div class="empty">No department assignments yet.</div>@endforelse</section>
<section class="hr-card"><h3>Latest Payroll</h3><small>Most recent payroll run status.</small>@if($latestPayroll)<div class="hr-list"><div class="hr-row"><span><b>{{ $latestPayroll->payroll_no }}</b><small>{{ $latestPayroll->period_start }} → {{ $latestPayroll->period_end }}</small></span><span class="pill-state">{{ $latestPayroll->status }}</span></div><div class="hr-row"><span>Employees</span><b>{{ $latestPayroll->lines->count() }}</b></div><div class="hr-row"><span>Net payroll</span><b>{{ number_format($latestPayroll->lines->sum('net_pay'),2) }} {{ $latestPayroll->currency }}</b></div></div>@else<div class="empty">No payroll run recorded.</div>@endif</section>
<section class="hr-card"><h3>Pending Leave Requests</h3><small>Requests waiting for HR or workflow decision.</small><div class="hr-list">@forelse($pendingLeaves as $leave)<div class="hr-row"><span><b>Employee #{{ $leave->employee_id }} · {{ $leave->leave_type }}</b><small>{{ $leave->starts_on }} → {{ $leave->ends_on }} · {{ $leave->days }} days</small></span><span class="pill-state pill-warn">PENDING</span></div>@empty<div class="empty">No pending leave requests.</div>@endforelse</div></section>
<section class="hr-card"><h3>Upcoming Expiries</h3><small>Contracts and employee documents expiring within 90 days.</small><div class="hr-list">@foreach($expiringContracts as $contract)<div class="hr-row"><span><b>{{ $contract->employee?->name }} · Contract</b><small>{{ $contract->contract_no }}</small></span><span class="pill-state pill-warn">{{ $contract->ends_on?->format('d M Y') }}</span></div>@endforeach @foreach($expiringDocuments as $document)<div class="hr-row"><span><b>{{ $document->employee?->name }} · {{ $document->document_type }}</b><small>{{ $document->document_no ?: 'No document number' }}</small></span><span class="pill-state pill-warn">{{ $document->expires_on?->format('d M Y') }}</span></div>@endforeach @if($expiringContracts->isEmpty() && $expiringDocuments->isEmpty())<div class="empty">No expiries in the next 90 days.</div>@endif</div></section>
</div>
<div class="section-links"><a class="section-link live" href="{{ route('hr.employees.index') }}"><b>Employees / Employee 360</b><small>Personal, employment, compensation and HR history.</small></a><a class="section-link live" href="{{ route('hr.attendance.index') }}"><b>Attendance & Time</b><small>Shifts, lateness, overtime, attendance types and Ramadan working hours.</small></a><a class="section-link live" href="{{ route('hr.leave.index') }}"><b>Leave Management</b><small>Policies, balances, accrual, carry-forward and approvals.</small></a><a class="section-link" href="{{ route('hr.operations.index') }}#payroll"><b>Payroll</b><small>Existing payroll engine pending dedicated payroll workspace.</small></a></div>
@endsection
