@extends('layouts.app')
@section('content')
<h1>CRM & Projects Operations</h1>
<p>Lead-to-opportunity-to-project execution, WBS, resource planning and project costing.</p>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif

<div class="grid">
<section><h2>Customer Acquisition</h2><p>All field marketing, phone, WhatsApp, email and referral leads now enter through the controlled acquisition workflow with duplicate matching and source tracking.</p><a href="{{ route('crm.acquisition.index') }}"><button type="button">Open Customer Acquisition</button></a></section>
<section><h2>New Opportunity</h2><form method="post" action="{{ route('crm.operations.opportunities.store') }}">@csrf
<input name="opportunity_no" placeholder="Opportunity No" required><input name="name" placeholder="Opportunity" required><select name="stage"><option>QUALIFICATION</option><option>PROPOSAL</option><option>NEGOTIATION</option></select><input name="expected_value" type="number" step="0.01" min="0" placeholder="Expected value" required><input name="probability" type="number" min="0" max="99" value="25" required><input name="expected_close" type="date"><button>Create Opportunity</button></form></section>
<section><h2>Issue Quotation</h2><form method="post" action="{{ route('crm.operations.quotations.store') }}">@csrf
<select name="opportunity_id" required>@foreach($opportunities as $o)<option value="{{ $o->id }}">{{ $o->opportunity_no }} - {{ $o->name }}</option>@endforeach</select><input name="quotation_no" placeholder="Quotation No" required><input name="quotation_date" type="date" required><input name="currency" value="USD" maxlength="3" required><input name="amount" type="number" step="0.01" min="0.01" required><button>Issue</button></form></section>
</div>

<h2>Open Opportunities</h2><table><thead><tr><th>No</th><th>Name</th><th>Stage</th><th>Value</th><th>Win / Create Project</th></tr></thead><tbody>@foreach($opportunities as $o)<tr><td>{{ $o->opportunity_no }}</td><td>{{ $o->name }}</td><td>{{ $o->stage }}</td><td>{{ $o->expected_value }}</td><td>@if($o->status==='OPEN')<form method="post" action="{{ route('crm.operations.opportunities.win',$o) }}">@csrf<select name="customer_id" required>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->customer_code }} - {{ $c->name }}</option>@endforeach</select><input name="project_no" placeholder="Project No" required><input name="project_name" placeholder="Project Name" required><input name="budget" type="number" step="0.01" min="0"><button>Mark Won</button></form>@else{{ $o->status }}@endif</td></tr>@endforeach</tbody></table>

<h2>Project WBS & Costing</h2>
<div class="grid"><section><h3>Add WBS Task</h3><form method="post" action="{{ route('projects.operations.tasks.store') }}">@csrf<select name="project_id">@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->project_no }}</option>@endforeach</select><input name="wbs_code" placeholder="WBS" required><input name="name" placeholder="Task" required><input name="budget" type="number" step="0.01" min="0" value="0" required><button>Add Task</button></form></section></div>
<table><thead><tr><th>Project</th><th>Status</th><th>Budget</th><th>Actual Cost</th><th>Resource / Timesheet</th></tr></thead><tbody>@foreach($projects as $p)<tr><td>{{ $p->project_no }} - {{ $p->name }}</td><td>{{ $p->status }}</td><td>{{ $p->budget }}</td><td>{{ $p->actual_cost }}</td><td><form method="post" action="{{ route('projects.operations.resources.store',$p) }}">@csrf<select name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }}</option>@endforeach</select><input name="role" placeholder="Role"><input name="planned_hours" type="number" step="0.5" min="0" value="0"><button>Assign</button></form><form method="post" action="{{ route('projects.operations.timesheets.store',$p) }}">@csrf<select name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_no }}</option>@endforeach</select><select name="project_task_id"><option value="">No task</option>@foreach($tasks->where('project_id',$p->id) as $t)<option value="{{ $t->id }}">{{ $t->wbs_code }}</option>@endforeach</select><input name="work_date" type="date" required><input name="hours" type="number" step="0.25" min="0.25" max="24" required><input name="hourly_cost" type="number" step="0.01" min="0" required><button>Post Time</button></form></td></tr>@endforeach</tbody></table>
@endsection