@extends('layouts.app')
@section('title','My HR Documents | UNIFCO Platform')
@section('heading','My HR Documents')
@section('content')
<style>
.doc-hero{background:linear-gradient(135deg,#10203a,#223a68);color:#fff;border-radius:16px;padding:22px;display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:13px}.doc-hero h1{margin:4px 0;font-size:24px}.doc-hero p{margin:0;color:#d7e1ef;font-size:10px}.doc-grid{display:grid;grid-template-columns:1fr 1.25fr;gap:12px}.doc-card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:16px}.doc-card h3{margin:0 0 4px;font-size:13px}.doc-card>small{display:block;color:#8190a4;font-size:8px;margin-bottom:12px}.doc-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.doc-form label{font-size:8px;font-weight:800;color:#6f7d90}.doc-form input,.doc-form select,.doc-form textarea{width:100%;font-size:10px}.doc-form .wide{grid-column:1/-1}.req{display:grid;grid-template-columns:110px 1fr auto;gap:10px;padding:10px;border-bottom:1px solid #edf0f4;align-items:center;font-size:9px}.pill{padding:4px 7px;border-radius:999px;font-size:8px;font-weight:800;background:#eef2f7}.pill.ISSUED{background:#e7f6ed;color:#17734b}.pill.PENDING{background:#fff3e2;color:#935900}.pill.REJECTED{background:#fbecef;color:#9b2840}.change-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:10px;background:#f8fafc;border-radius:9px}.empty{padding:20px;text-align:center;background:#f8fafc;border-radius:9px;color:#8190a4;font-size:9px}@media(max-width:900px){.doc-grid{grid-template-columns:1fr}}@media(max-width:600px){.doc-form,.change-grid{grid-template-columns:1fr}.doc-form .wide{grid-column:auto}.req{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="doc-hero"><div><small>EMPLOYEE SELF-SERVICE · DIGITAL HR SERVICES</small><h1>My HR Documents & Requests</h1><p>Request official letters, certificates, profile changes and general HR services without access to other employee records.</p></div><a class="btn secondary" href="{{ route('hr.self-service.index') }}">← My HR</a></section>
<div class="doc-grid">
<section class="doc-card"><h3>New HR Request</h3><small>Formal letters require approval before HR can issue the final document.</small><form class="doc-form" method="POST" action="{{ route('hr.self-service.documents.store') }}">@csrf
<label>Request Type<select name="request_type" id="request_type" required><option value="SALARY_CERTIFICATE">Salary Certificate</option><option value="SERVICE_CERTIFICATE">Service Certificate</option><option value="BANK_LETTER">Bank Letter</option><option value="NOC">No Objection Certificate</option><option value="PROFILE_UPDATE">Profile Update</option><option value="GENERAL">General HR Request</option></select></label>
<label>Language<select name="language"><option value="EN">English</option><option value="AR">العربية</option></select></label>
<label>Recipient / Organization<input name="recipient_name" placeholder="Bank / Embassy / To whom it may concern"></label><label>Purpose<input name="purpose" placeholder="Visa, bank account, official use..."></label>
<label class="wide">Notes<textarea name="notes" rows="3"></textarea></label>
<div class="wide" id="profile-fields"><small style="display:block;margin-bottom:7px;color:#6d7b8e">Profile update fields — only changed values are submitted.</small><div class="change-grid"><label>Email<input type="email" name="email" value="{{ $employee->email }}"></label><label>Mobile<input name="mobile" value="{{ $employee->mobile }}"></label><label>Address<input name="address_line" value="{{ $employee->address_line }}"></label><label>City<input name="city" value="{{ $employee->city }}"></label><label>Emergency Contact<input name="emergency_contact_name" value="{{ $employee->emergency_contact_name }}"></label><label>Emergency Mobile<input name="emergency_contact_mobile" value="{{ $employee->emergency_contact_mobile }}"></label><label>Bank<input name="bank_name" value="{{ $employee->bank_name }}"></label><label>IBAN<input name="iban" value="{{ $employee->iban }}"></label></div></div>
<div class="wide"><button class="btn">Submit Request</button></div></form></section>
<section class="doc-card"><h3>My Requests</h3><small>Issued letters are immutable snapshots of the approved employee data at issuance time.</small>@forelse($requests as $r)<div class="req"><div><b>{{ $r->request_no }}</b><br><small>{{ $r->created_at?->format('d M Y') }}</small></div><div><b>{{ str_replace('_',' ',$r->request_type) }}</b><br><small>{{ $r->purpose ?: $r->notes ?: '—' }}</small></div><div style="text-align:right"><span class="pill {{ $r->status }}">{{ $r->status }}</span>@if($r->status==='ISSUED')<br><a style="display:inline-block;margin-top:6px" href="{{ route('hr.documents.show',$r) }}">Open Letter</a>@endif</div></div>@empty<div class="empty">No HR service requests yet.</div>@endforelse</section>
</div>
<script>const s=document.getElementById('request_type'),p=document.getElementById('profile-fields');function sync(){p.style.display=s.value==='PROFILE_UPDATE'?'block':'none'}s.addEventListener('change',sync);sync();</script>
@endsection
