@extends('layouts.app')
@section('title','HR Documents | UNIFCO Platform')
@section('heading','HR Documents & Requests')
@section('content')
<style>
.hrd-hero{background:linear-gradient(135deg,#101f38,#213a68);color:#fff;border-radius:17px;padding:22px;display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:12px}.hrd-hero h1{font-size:24px;margin:4px 0}.hrd-hero p{font-size:10px;color:#d7e1ee;margin:0}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:12px}.kpi{background:#fff;border:1px solid #e3e8ef;border-radius:11px;padding:12px}.kpi small{display:block;font-size:8px;color:#7b899a;text-transform:uppercase}.kpi b{display:block;font-size:20px;color:#17243b;margin-top:4px}.grid{display:grid;grid-template-columns:1.35fr .65fr;gap:12px}.card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:15px}.card h3{font-size:13px;margin:0 0 4px}.card>small{font-size:8px;color:#7c899a}.filters{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.filters select{font-size:9px;min-width:150px}.table-wrap{overflow:auto}.table-wrap table{min-width:850px}.table-wrap th{font-size:8px;text-transform:uppercase}.table-wrap td{font-size:9px}.pill{padding:4px 7px;border-radius:999px;font-size:8px;font-weight:800;background:#eef2f7}.PENDING{background:#fff3e2;color:#945900}.APPROVED{background:#eaf3ff;color:#235a9a}.ISSUED{background:#e8f6ee;color:#17734b}.REJECTED{background:#fbecef;color:#9b2840}.actions{display:flex;gap:5px;flex-wrap:wrap}.actions form{display:inline}.template{padding:9px;background:#f8fafc;border-radius:8px;margin-top:7px;font-size:9px}.template b{display:block}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.form-grid label{font-size:8px;font-weight:800;color:#68778a}.form-grid input,.form-grid select,.form-grid textarea{width:100%;font-size:9px}.form-grid .wide{grid-column:1/-1}@media(max-width:1000px){.grid{grid-template-columns:1fr}.kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.kpis,.form-grid{grid-template-columns:1fr}.form-grid .wide{grid-column:auto}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="hrd-hero"><div><small>PEOPLE / HR · DOCUMENT SERVICES</small><h1>HR Documents Command Center</h1><p>Approve employee requests, issue controlled digital letters and maintain Arabic / English templates with immutable issuance snapshots.</p></div><div><a class="btn secondary" href="{{ route('hr.dashboard') }}">HR Dashboard</a></div></section>
<div class="kpis"><div class="kpi"><small>Pending Requests</small><b>{{ $stats['pending'] }}</b></div><div class="kpi"><small>Approved / Ready</small><b>{{ $stats['approved'] }}</b></div><div class="kpi"><small>Issued Letters</small><b>{{ $stats['issued'] }}</b></div><div class="kpi"><small>Profile Updates</small><b>{{ $stats['profile_updates'] }}</b></div></div>
<div class="grid"><section class="card"><h3>HR Service Queue</h3><small>Profile changes are applied only after an independent approval. Formal letters require approval then issuance.</small><form class="filters" method="GET"><select name="status"><option value="">All statuses</option>@foreach(['PENDING','APPROVED','ISSUED','REJECTED'] as $s)<option @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select><select name="type"><option value="">All request types</option>@foreach($types as $t)<option value="{{ $t }}" @selected(request('type')===$t)>{{ str_replace('_',' ',$t) }}</option>@endforeach</select><button class="btn secondary">Filter</button></form><div class="table-wrap"><table><thead><tr><th>Request</th><th>Employee</th><th>Type</th><th>Language</th><th>Status</th><th>Requested</th><th>Action</th></tr></thead><tbody>@forelse($requests as $r)<tr><td><b>{{ $r->request_no }}</b></td><td>{{ $r->employee?->name }}<br><small>{{ $r->employee?->employee_no }}</small></td><td>{{ str_replace('_',' ',$r->request_type) }}</td><td>{{ $r->language }}</td><td><span class="pill {{ $r->status }}">{{ $r->status }}</span></td><td>{{ $r->created_at?->format('d M Y H:i') }}</td><td><div class="actions"><a class="btn secondary" href="{{ route('hr.documents.show',$r) }}">Open</a>@if($r->status==='PENDING')<form method="POST" action="{{ route('hr.documents.decide',$r) }}">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn">Approve</button></form><form method="POST" action="{{ route('hr.documents.decide',$r) }}">@csrf<input type="hidden" name="decision" value="REJECTED"><button class="btn secondary">Reject</button></form>@elseif($r->status==='APPROVED' && !in_array($r->request_type,['PROFILE_UPDATE','GENERAL']))<form method="POST" action="{{ route('hr.documents.issue',$r) }}">@csrf<button class="btn">Issue Letter</button></form>@endif</div></td></tr>@empty<tr><td colspan="7">No requests found.</td></tr>@endforelse</tbody></table></div>{{ $requests->links() }}</section>
<section class="card"><h3>Letter Templates</h3><small>System templates are provisioned per tenant and can be supplemented with organization-specific versions.</small>@foreach($templates as $t)<div class="template"><b>{{ $t->name }} · {{ $t->language }}</b><span>{{ str_replace('_',' ',$t->document_type) }} · {{ $t->code }}</span></div>@endforeach<form class="form-grid" method="POST" action="{{ route('hr.documents.templates.store') }}">@csrf<label>Code<input name="code" required></label><label>Name<input name="name" required></label><label>Type<select name="document_type">@foreach(['SALARY_CERTIFICATE','SERVICE_CERTIFICATE','BANK_LETTER','NOC'] as $t)<option value="{{ $t }}">{{ str_replace('_',' ',$t) }}</option>@endforeach</select></label><label>Language<select name="language"><option>EN</option><option>AR</option></select></label><label class="wide">Subject<input name="subject" required></label><label class="wide">Body Template<textarea name="body_template" rows="7" required placeholder="Use placeholders such as @{{employee_name}}, @{{employee_no}}, @{{position}}, @{{hire_date}}, @{{gross_salary}}, @{{recipient}}, @{{purpose}}"></textarea></label><label><input type="checkbox" name="include_salary" value="1"> Include salary</label><div><button class="btn">Create Template</button></div></form></section></div>
@endsection
