@extends('layouts.app')
@section('title',$service->request_no.' | HR Document')
@section('heading','HR Request 360')
@section('content')
<style>.hero{background:linear-gradient(135deg,#10203a,#203a68);color:#fff;border-radius:16px;padding:20px;display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:12px}.hero h1{font-size:22px;margin:3px 0}.hero p{margin:0;color:#d8e2ef;font-size:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{background:#fff;border:1px solid #e3e8ef;border-radius:13px;padding:15px}.card h3{font-size:13px;margin:0 0 8px}.details{display:grid;grid-template-columns:1fr 1fr;gap:7px}.detail{background:#f8fafc;border-radius:8px;padding:9px}.detail small{display:block;font-size:8px;color:#7d899a;text-transform:uppercase}.detail b{display:block;font-size:10px;margin-top:3px}.pill{padding:5px 8px;border-radius:999px;background:#eef2f7;font-size:8px;font-weight:800}.ISSUED{background:#e8f6ee;color:#17734b}.PENDING{background:#fff3e2;color:#955a00}.APPROVED{background:#eaf3ff;color:#245b98}.REJECTED{background:#fbecef;color:#9b2840}.snapshot{white-space:pre-wrap;line-height:1.9;font-size:11px;background:#fbfcfe;border:1px solid #edf0f4;border-radius:10px;padding:18px}.actions{display:flex;gap:7px;flex-wrap:wrap}.changes{display:grid;gap:6px}.change{display:grid;grid-template-columns:140px 1fr;gap:8px;padding:8px;background:#f8fafc;border-radius:8px;font-size:9px}@media(max-width:800px){.grid,.details{grid-template-columns:1fr}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="hero"><div><small>{{ str_replace('_',' ',$service->request_type) }} · {{ $service->language }}</small><h1>{{ $service->request_no }}</h1><p>{{ $service->employee?->name }} · {{ $service->employee?->employee_no }}</p></div><div class="actions"><span class="pill {{ $service->status }}">{{ $service->status }}</span>@if($service->status==='ISSUED')<a class="btn" href="{{ route('hr.documents.print',$service) }}" target="_blank">Print / Save PDF</a>@endif @if($isHr)<a class="btn secondary" href="{{ route('hr.documents.index') }}">Documents Queue</a>@else<a class="btn secondary" href="{{ route('hr.self-service.documents.index') }}">My Requests</a>@endif</div></section>
<div class="grid"><section class="card"><h3>Request Details</h3><div class="details"><div class="detail"><small>Employee</small><b>{{ $service->employee?->name }}</b></div><div class="detail"><small>Requested</small><b>{{ $service->created_at?->format('d M Y H:i') }}</b></div><div class="detail"><small>Recipient</small><b>{{ $service->recipient_name ?: '—' }}</b></div><div class="detail"><small>Purpose</small><b>{{ $service->purpose ?: '—' }}</b></div><div class="detail"><small>Decision</small><b>{{ $service->decided_at?->format('d M Y H:i') ?: 'Pending' }}</b></div><div class="detail"><small>Document No</small><b>{{ $service->document_no ?: 'Not issued' }}</b></div></div>@if($service->notes)<p style="font-size:10px;margin-top:10px">{{ $service->notes }}</p>@endif</section>
<section class="card"><h3>Approval & Control</h3><p style="font-size:9px;color:#718094">Requests are employee-scoped. Issued letters are immutable snapshots; later employee changes do not alter an issued document.</p>@if($service->decision_notes)<div class="detail"><small>Decision Notes</small><b>{{ $service->decision_notes }}</b></div>@endif @if($isHr && $service->status==='PENDING')<div class="actions" style="margin-top:10px"><form method="POST" action="{{ route('hr.documents.decide',$service) }}">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn">Approve</button></form><form method="POST" action="{{ route('hr.documents.decide',$service) }}">@csrf<input type="hidden" name="decision" value="REJECTED"><button class="btn secondary">Reject</button></form></div>@elseif($isHr && $service->status==='APPROVED' && !in_array($service->request_type,['PROFILE_UPDATE','GENERAL']))<form method="POST" action="{{ route('hr.documents.issue',$service) }}">@csrf<button class="btn">Issue Official Letter</button></form>@endif</section>
@if($service->request_type==='PROFILE_UPDATE')<section class="card" style="grid-column:1/-1"><h3>Requested Profile Changes</h3><div class="changes">@forelse($service->requested_changes??[] as $field=>$value)<div class="change"><b>{{ str_replace('_',' ',ucfirst($field)) }}</b><span>{{ $value }}</span></div>@empty<p>No changes.</p>@endforelse</div></section>@endif
@if($service->status==='ISSUED' && $service->snapshot)<section class="card" style="grid-column:1/-1"><h3>{{ $service->snapshot['subject'] ?? 'Issued Letter' }}</h3><div class="snapshot" dir="{{ $service->language==='AR'?'rtl':'ltr' }}">{{ $service->snapshot['body'] ?? '' }}</div><div class="details" style="margin-top:10px"><div class="detail"><small>Issued At</small><b>{{ $service->issued_at?->format('d M Y H:i') }}</b></div><div class="detail"><small>Verification</small><b>{{ substr($service->verification_token,0,12) }}…</b></div></div></section>@endif</div>
@endsection
