@extends('layouts.app')
@section('title','Final Settlements | UNIFCO Platform')
@section('heading','End of Service & Final Settlement')
@section('content')
<style>
.fs-hero{background:linear-gradient(135deg,#101f38,#1e315b);color:#fff;border-radius:16px;padding:22px;margin-bottom:13px}.fs-hero small{font-size:9px;color:#aebbd0;text-transform:uppercase;letter-spacing:.12em}.fs-hero h1{margin:5px 0;font-size:23px}.fs-hero p{margin:0;color:#dce5f1;font-size:10px;max-width:850px}.fs-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:12px}.fs-kpi,.fs-card{background:#fff;border:1px solid #e2e8ef;border-radius:12px;padding:14px}.fs-kpi small{display:block;color:#7d899b;font-size:8px;text-transform:uppercase}.fs-kpi b{display:block;margin-top:4px;font-size:21px;color:#17243c}.fs-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:12px}.fs-card h3{font-size:13px;margin:0 0 4px}.fs-card>small{font-size:8px;color:#8290a3}.fs-form{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:11px}.fs-form label{font-size:8px;color:#657389}.fs-form .wide{grid-column:1/-1}.fs-table td,.fs-table th{font-size:9px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef3fa;color:#1e315b;font-size:8px;font-weight:800}.note{margin-top:10px;padding:10px;background:#f7f9fc;border-radius:8px;color:#657389;font-size:8px}@media(max-width:900px){.fs-grid{grid-template-columns:1fr}.fs-kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.fs-kpis,.fs-form{grid-template-columns:1fr}.fs-form .wide{grid-column:auto}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="fs-hero"><small>People / HR · Saudi End of Service</small><h1>End of Service & Final Settlement</h1><p>Calculate and approve auditable employee exit settlements with Saudi EOS award logic, unused annual leave wage, pending earnings, deductions and segregation of duties.</p></section>
<div class="fs-kpis"><div class="fs-kpi"><small>Draft</small><b>{{ $stats['draft'] }}</b></div><div class="fs-kpi"><small>Pending Approval</small><b>{{ $stats['pending'] }}</b></div><div class="fs-kpi"><small>Approved</small><b>{{ $stats['approved'] }}</b></div><div class="fs-kpi"><small>Approved / Paid Net</small><b>{{ number_format($stats['netApproved'],0) }} SAR</b></div></div>
<div class="fs-grid">
<section class="fs-card"><h3>Prepare Final Settlement</h3><small>The calculation is saved as a versioned snapshot before approval.</small><form class="fs-form" method="POST" action="{{ route('hr.settlements.store') }}">@csrf
<label>Employee<select name="employee_id" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no }} · {{ $employee->name }}</option>@endforeach</select></label>
<label>Termination Reason<select name="termination_reason" required>@foreach($reasons as $reason)<option value="{{ $reason }}">{{ str_replace('_',' ',$reason) }}</option>@endforeach</select></label>
<label>Service Start Date<input type="date" name="service_start_date"><small>Leave blank to use hire date.</small></label><label>Last Working Day<input type="date" name="last_working_day" required></label>
<label>Unused Leave Days<input type="number" step="0.01" min="0" name="unused_leave_days"><small>Leave blank to derive paid annual balances.</small></label><label>Unpaid Salary<input type="number" step="0.01" min="0" name="unpaid_salary" value="0"></label>
<label>Other Earnings<input type="number" step="0.01" min="0" name="other_earnings" value="0"></label><label>Notice Compensation<input type="number" step="0.01" min="0" name="notice_compensation" value="0"></label>
<label>Employee Debt<input type="number" step="0.01" min="0" name="employee_debt" value="0"></label><label>Advance Recovery<input type="number" step="0.01" min="0" name="advance_recovery" value="0"></label>
<label>Other Deductions<input type="number" step="0.01" min="0" name="other_deductions" value="0"></label><label class="wide">Notes<textarea name="notes" rows="3"></textarea></label>
<div class="wide"><button class="btn">Calculate Draft Settlement</button></div></form><div class="note">Saudi baseline: Article 84 EOS formula; Article 85 resignation tiers; Article 87 full-award exceptions; Article 111 unused annual leave wage. Article 80 termination is modeled as zero EOS award. HR must validate the selected reason and evidence before approval.</div></section>
<section class="fs-card"><h3>Settlement Register</h3><small>Search, review and continue the approval lifecycle.</small><form class="row" method="GET" style="margin-top:10px"><input name="q" value="{{ request('q') }}" placeholder="Settlement / employee"><select name="status"><option value="">All statuses</option>@foreach(['DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','PAID'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select><button class="btn secondary">Filter</button></form>
<table class="fs-table"><thead><tr><th>Settlement</th><th>Employee</th><th>Reason</th><th>EOS</th><th>Net</th><th>Status</th></tr></thead><tbody>@forelse($settlements as $settlement)<tr><td><a href="{{ route('hr.settlements.show',$settlement) }}"><b>{{ $settlement->settlement_no }}</b></a></td><td>{{ $settlement->employee?->employee_no }} · {{ $settlement->employee?->name }}</td><td>{{ str_replace('_',' ',$settlement->termination_reason) }}</td><td>{{ number_format((float)$settlement->eos_award,2) }}</td><td><b>{{ number_format((float)$settlement->net_settlement,2) }}</b></td><td><span class="state">{{ $settlement->status }}</span></td></tr>@empty<tr><td colspan="6">No final settlements yet.</td></tr>@endforelse</tbody></table>{{ $settlements->links() }}</section>
</div>
@endsection
