@extends('layouts.app')
@section('title',$settlement->settlement_no.' | Final Settlement')
@section('heading','Final Settlement 360')
@section('content')
<style>
.s-hero{background:linear-gradient(135deg,#101f38,#1e315b);color:#fff;border-radius:16px;padding:21px;margin-bottom:12px;display:flex;justify-content:space-between;gap:14px;align-items:center}.s-hero small{font-size:9px;color:#aebbd0;text-transform:uppercase}.s-hero h1{font-size:22px;margin:4px 0}.s-hero p{font-size:10px;color:#dce5f1;margin:0}.s-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.s-card{background:#fff;border:1px solid #e2e8ef;border-radius:12px;padding:14px}.s-card.wide{grid-column:1/-1}.s-card h3{font-size:13px;margin:0 0 9px}.facts{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.fact{background:#f7f9fc;border-radius:8px;padding:9px}.fact small{display:block;color:#7d899b;font-size:8px;text-transform:uppercase}.fact b{display:block;margin-top:3px;font-size:11px}.sum{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sum div{background:#f7f9fc;border-radius:9px;padding:11px}.sum small{display:block;color:#7d899b;font-size:8px;text-transform:uppercase}.sum b{display:block;font-size:17px;margin-top:3px}.sum .net{background:#eef3fa}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.mini-form{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.mini-form label{font-size:8px;color:#68758a}.danger{background:#a51f35}.success{background:#17734b}.legal{font-size:8px;color:#647287;line-height:1.55;background:#f8fafc;border-radius:8px;padding:10px;margin-top:10px}@media(max-width:850px){.s-grid{grid-template-columns:1fr}.s-card.wide{grid-column:auto}.sum,.mini-form{grid-template-columns:1fr 1fr}}@media(max-width:560px){.s-hero{display:block}.sum,.facts,.mini-form{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="s-hero"><div><small>{{ $settlement->termination_reason }} · {{ $settlement->status }}</small><h1>{{ $settlement->settlement_no }} · {{ $settlement->employee?->name }}</h1><p>{{ $settlement->employee?->employee_no }} · Service {{ number_format((float)$settlement->service_years,2) }} years · Last working day {{ $settlement->last_working_day?->format('d M Y') }}</p></div><a class="btn secondary" href="{{ route('hr.settlements.index') }}">Back to Settlements</a></section>
<div class="s-grid">
<section class="s-card"><h3>Employment & EOS Basis</h3><div class="facts"><div class="fact"><small>Service Start</small><b>{{ $settlement->service_start_date?->format('d M Y') }}</b></div><div class="fact"><small>Last Working Day</small><b>{{ $settlement->last_working_day?->format('d M Y') }}</b></div><div class="fact"><small>Last Wage Basis</small><b>{{ number_format((float)$settlement->last_wage_basis,2) }} SAR</b></div><div class="fact"><small>EOS Base Award</small><b>{{ number_format((float)$settlement->eos_base_award,2) }} SAR</b></div><div class="fact"><small>Entitlement Multiplier</small><b>{{ number_format((float)$settlement->eos_multiplier*100,2) }}%</b></div><div class="fact"><small>EOS Award</small><b>{{ number_format((float)$settlement->eos_award,2) }} SAR</b></div></div></section>
<section class="s-card"><h3>Leave & Other Entitlements</h3><div class="facts"><div class="fact"><small>Unused Leave</small><b>{{ number_format((float)$settlement->unused_leave_days,2) }} days</b></div><div class="fact"><small>Leave Daily Rate</small><b>{{ number_format((float)$settlement->leave_daily_rate,2) }} SAR</b></div><div class="fact"><small>Leave Encashment</small><b>{{ number_format((float)$settlement->leave_encashment,2) }} SAR</b></div><div class="fact"><small>Unpaid Salary</small><b>{{ number_format((float)$settlement->unpaid_salary,2) }} SAR</b></div><div class="fact"><small>Other Earnings</small><b>{{ number_format((float)$settlement->other_earnings,2) }} SAR</b></div><div class="fact"><small>Notice Compensation</small><b>{{ number_format((float)$settlement->notice_compensation,2) }} SAR</b></div></div></section>
<section class="s-card wide"><h3>Settlement Summary</h3><div class="sum"><div><small>EOS Award</small><b>{{ number_format((float)$settlement->eos_award,2) }}</b></div><div><small>Leave Encashment</small><b>{{ number_format((float)$settlement->leave_encashment,2) }}</b></div><div><small>Total Deductions</small><b>{{ number_format((float)$settlement->total_deductions,2) }}</b></div><div class="net"><small>Net Settlement</small><b>{{ number_format((float)$settlement->net_settlement,2) }} SAR</b></div></div>
@if($settlement->status==='DRAFT')<form class="mini-form" method="POST" action="{{ route('hr.settlements.recalculate',$settlement) }}">@csrf<label>Unused Leave Days<input type="number" step="0.01" min="0" name="unused_leave_days" value="{{ $settlement->unused_leave_days }}"></label><label>Unpaid Salary<input type="number" step="0.01" min="0" name="unpaid_salary" value="{{ $settlement->unpaid_salary }}"></label><label>Other Earnings<input type="number" step="0.01" min="0" name="other_earnings" value="{{ $settlement->other_earnings }}"></label><label>Notice Compensation<input type="number" step="0.01" min="0" name="notice_compensation" value="{{ $settlement->notice_compensation }}"></label><label>Employee Debt<input type="number" step="0.01" min="0" name="employee_debt" value="{{ $settlement->employee_debt }}"></label><label>Advance Recovery<input type="number" step="0.01" min="0" name="advance_recovery" value="{{ $settlement->advance_recovery }}"></label><label>Other Deductions<input type="number" step="0.01" min="0" name="other_deductions" value="{{ $settlement->other_deductions }}"></label><div><button class="btn secondary">Recalculate Draft</button></div></form><form class="actions" method="POST" action="{{ route('hr.settlements.submit',$settlement) }}">@csrf<button class="btn">Submit for Approval</button></form>@endif
@if($settlement->status==='PENDING_APPROVAL')<div class="actions"><form method="POST" action="{{ route('hr.settlements.decide',$settlement) }}">@csrf<input type="hidden" name="decision" value="APPROVED"><button class="btn success">Approve Settlement</button></form><form method="POST" action="{{ route('hr.settlements.decide',$settlement) }}">@csrf<input type="hidden" name="decision" value="REJECTED"><button class="btn danger">Reject</button></form></div>@endif
@if($settlement->status==='APPROVED')<form class="actions" method="POST" action="{{ route('hr.settlements.paid',$settlement) }}">@csrf<button class="btn success">Mark Paid</button></form>@endif
<div class="legal">Calculation snapshot preserves the policy, salary components, service fractions and legal rule path used at calculation time. Payment status does not imply Finance GL posting; Finance integration remains a separate controlled action.</div></section>
</div>
@endsection
