@extends('layouts.app')
@section('title','Customer Acquisition · UNIFCO')
@section('heading','Customer Acquisition')
@section('content')
<style>.acq-grid{display:grid;grid-template-columns:1fr 1.4fr;gap:14px}.acq-box{background:#fff;border:1px solid #e1e6ee;border-radius:12px;padding:16px}.acq-box h3{margin:0 0 12px;font-size:14px;color:#071f4d}.funnel{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:14px}.metric{background:#fff;border:1px solid #e1e6ee;border-radius:10px;padding:12px}.metric small{font-size:8px;color:#76849a}.metric b{display:block;font-size:22px;margin-top:5px;color:#06275c}.metric.attn b{color:#9d5a00}.form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.field{display:grid;gap:5px;font-size:9px;font-weight:800;color:#4d5d73}.field input,.field select,.field textarea{border:1px solid #d8e0ea;border-radius:7px;padding:8px;background:#fff;font-size:10px}.field textarea{min-height:72px}.wide{grid-column:1/-1}.btn{border:0;border-radius:7px;background:#06275c;color:#fff;padding:8px 10px;font-size:9px;font-weight:850;cursor:pointer}.btn.green{background:#137346}.btn.amber{background:#9d5a00}.btn.red{background:#a93434}.notice{padding:11px 13px;background:#e9f7ef;color:#176940;border-radius:9px;margin-bottom:12px;font-size:10px}.errors{padding:11px 13px;background:#fff0f0;color:#9c2f2f;border-radius:9px;margin-bottom:12px;font-size:10px}.lead{border:1px solid #e7ebf1;border-radius:10px;padding:12px;margin-bottom:9px}.lead-head{display:flex;justify-content:space-between;gap:10px}.lead b{font-size:11px}.lead small{display:block;color:#758297;font-size:9px;margin-top:4px}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf3fb;color:#275f9c;font-size:8px;font-weight:850}.pill.pending{background:#fff4dc;color:#8c5d00}.pill.ok{background:#e7f6ec;color:#176940}.pill.bad{background:#fdeaea;color:#9d3535}.lead-actions{display:flex;gap:6px;align-items:end;flex-wrap:wrap;margin-top:9px}.lead-actions form{display:flex;gap:5px;flex-wrap:wrap}.lead-actions select,.lead-actions input{font-size:9px;border:1px solid #d8e0ea;border-radius:6px;padding:6px}.customer{padding:11px 0;border-bottom:1px solid #edf1f5}.customer:last-child{border:0}.customer b{font-size:10px}.customer small{display:block;font-size:9px;color:#758297;margin-top:3px}.review{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.review form{display:flex;gap:5px;flex-wrap:wrap}.review input,.review select{font-size:9px;border:1px solid #d8e0ea;border-radius:6px;padding:6px}@media(max-width:1100px){.acq-grid{grid-template-columns:1fr}.funnel{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.funnel,.form{grid-template-columns:1fr 1fr}.wide{grid-column:1/-1}}@media(max-width:430px){.funnel,.form{grid-template-columns:1fr}}</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors">@foreach($errors->all() as $e)<div>{{ $e }}</div>@endforeach</div>@endif
<div class="funnel">
@foreach($stages as $stage=>$count)<div class="metric"><small>{{ str_replace('_',' ',$stage) }}</small><b>{{ $count }}</b></div>@endforeach
<div class="metric attn"><small>OVERDUE FOLLOW-UPS</small><b>{{ $overdueFollowUps }}</b></div><div class="metric attn"><small>PENDING CONVERSIONS</small><b>{{ $pendingConversions }}</b></div><div class="metric attn"><small>PENDING ONBOARDING</small><b>{{ $pendingOnboarding }}</b></div>
</div>
<div class="acq-grid"><section class="acq-box"><h3>Unified Lead / Inquiry Intake</h3><form class="form" method="POST" action="{{ route('crm.acquisition.store') }}">@csrf<div class="field"><label>Contact Name</label><input name="name" required></div><div class="field"><label>Company</label><input name="company"></div><div class="field"><label>Mobile</label><input name="mobile"></div><div class="field"><label>Email</label><input type="email" name="email"></div><div class="field"><label>CR Number</label><input name="commercial_registration"></div><div class="field"><label>City</label><input name="city"></div><div class="field"><label>Acquisition Source</label><select name="source_channel" required>@foreach($sources as $source)<option value="{{ $source }}">{{ str_replace('_',' ',$source) }}</option>@endforeach</select></div><div class="field"><label>Source Detail / Campaign</label><input name="source_detail" placeholder="Campaign, event, WhatsApp line, referral…"></div><div class="field"><label>Lead Owner</label><select name="assigned_to"><option value="">Current user</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}">{{ $assignee->name }} · {{ $assignee->role }}</option>@endforeach</select></div><div class="field"><label>Next Follow-up</label><input type="datetime-local" name="next_follow_up_at"></div><div class="field wide"><label>Service Interest</label><input name="service_interest" placeholder="Maintenance, consultation, projects, spare parts…"></div><div class="field wide"><label>Inquiry / Visit Notes</label><textarea name="inquiry_notes" placeholder="What did the prospect ask for? Channel context, visit outcome, follow-up commitment…"></textarea></div><div class="wide"><button class="btn">Check Identity & Capture Lead</button></div></form><p style="font-size:9px;color:#758297;line-height:1.6;margin:12px 0 0">One intake path now covers field marketing, website, WhatsApp, email, phone and referrals. CR, email, phone and company identity are checked before a lead is created.</p></section>
<section class="acq-box"><h3>Qualification & Conversion Queue</h3>@forelse($recent as $lead)<div class="lead"><div class="lead-head"><div><span class="pill">{{ $lead->lead_no }}</span><b style="display:block;margin-top:7px">{{ $lead->company ?: $lead->name }}</b><small>{{ $lead->name }} · {{ $lead->mobile ?: 'No mobile' }} · {{ $lead->email ?: 'No email' }}</small><small>{{ str_replace('_',' ',$lead->source_channel ?: $lead->source) }}{{ $lead->service_interest?' · '.$lead->service_interest:'' }}</small><small>Owner: {{ optional($assignees->firstWhere('id',$lead->assigned_to))->name ?: 'Unassigned' }} · Follow-up: {{ $lead->next_follow_up_at?->format('Y-m-d H:i') ?: 'Not scheduled' }}</small></div><div><span class="pill">{{ str_replace('_',' ',$lead->lifecycle_stage ?: $lead->status) }}</span>@if($lead->conversion_approval_status && $lead->conversion_approval_status!=='NOT_REQUESTED')<span class="pill {{ $lead->conversion_approval_status==='APPROVED'?'ok':($lead->conversion_approval_status==='PENDING'?'pending':'bad') }}">{{ str_replace('_',' ',$lead->conversion_approval_status) }}</span>@endif</div></div>@if($lead->inquiry_notes)<small style="margin-top:8px">{{ $lead->inquiry_notes }}</small>@endif<div class="lead-actions">@if($lead->lifecycle_stage!=='CONVERTED')<form method="POST" action="{{ route('crm.acquisition.stage',$lead) }}">@csrf<select name="lifecycle_stage">@foreach($allowedStages as $stage)<option value="{{ $stage }}" @selected($lead->lifecycle_stage===$stage)>{{ str_replace('_',' ',$stage) }}</option>@endforeach</select><button class="btn">Update Stage</button></form><form method="POST" action="{{ route('crm.acquisition.follow-up',$lead) }}">@csrf<select name="assigned_to"><option value="">Unassigned</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((int)$lead->assigned_to===(int)$assignee->id)>{{ $assignee->name }}</option>@endforeach</select><input type="datetime-local" name="next_follow_up_at" value="{{ $lead->next_follow_up_at?->format('Y-m-d\TH:i') }}"><button class="btn">Save Follow-up</button></form>@endif
@if(in_array($lead->lifecycle_stage,['QUALIFIED','OPPORTUNITY'],true) && !$lead->converted_customer_id)
@if(in_array($lead->conversion_approval_status,['NOT_REQUESTED','REJECTED'],true))<form method="POST" action="{{ route('crm.acquisition.request-conversion',$lead) }}">@csrf<input name="notes" placeholder="Conversion justification"><button class="btn amber">Request Conversion</button></form>@endif
@if($canReview && $lead->conversion_approval_status==='PENDING')<form method="POST" action="{{ route('crm.acquisition.review-conversion',$lead) }}">@csrf<input name="notes" placeholder="Review note"><button class="btn green" name="decision" value="APPROVE">Approve</button><button class="btn red" name="decision" value="REJECT">Reject</button></form>@endif
@if($lead->conversion_approval_status==='APPROVED')<form method="POST" action="{{ route('crm.acquisition.convert',$lead) }}">@csrf<button class="btn green">Convert to Customer</button></form>@endif
@endif
@if($lead->converted_customer_id)<span class="pill ok">Customer #{{ $lead->converted_customer_id }}</span>@endif</div></div>@empty<div style="padding:20px;text-align:center;color:#758297;font-size:10px">No leads captured yet.</div>@endforelse</section></div>
<section class="acq-box" style="margin-top:14px"><h3>Customer Onboarding Review</h3>@forelse($customers as $customer)<div class="customer"><b>{{ $customer->customer_code }} · {{ $customer->name }}</b><small>{{ str_replace('_',' ',$customer->acquisition_source ?: 'UNKNOWN') }} · {{ $customer->status }} / {{ $customer->onboarding_status }} · Review: {{ str_replace('_',' ',$customer->onboarding_review_status ?: 'PENDING') }}{{ $customer->origin_lead_id?' · Origin Lead #'.$customer->origin_lead_id:'' }}</small>@if($customer->onboarding_review_notes)<small>{{ $customer->onboarding_review_notes }}</small>@endif @if($canReview && $customer->status==='ONBOARDING')<div class="review"><form method="POST" action="{{ route('crm.acquisition.review-onboarding',$customer) }}">@csrf<input name="notes" placeholder="Onboarding review note"><select name="decision"><option value="APPROVED">Approve & Activate</option><option value="NEEDS_INFO">Needs Information</option><option value="REJECTED">Reject</option></select><button class="btn">Update Onboarding</button></form></div>@endif</div>@empty<div style="color:#758297;font-size:10px">No acquisition-linked customers yet.</div>@endforelse</section>
@endsection
