@extends('layouts.app')
@section('title','Permissions Matrix | UNIFCO Platform')
@section('heading','Permissions Matrix')
@section('content')
@include('admin.system.operations-styles')
<style>
.pm-hero{background:linear-gradient(135deg,#132137,#1e315b);color:#fff;border-radius:14px;padding:18px 20px;margin-bottom:14px;display:flex;justify-content:space-between;gap:16px;align-items:center;box-shadow:0 10px 28px rgba(19,33,55,.10)}.pm-hero small{font-size:8px;letter-spacing:.12em;text-transform:uppercase;color:#9fb0c7;font-weight:850}.pm-hero h1{margin:4px 0;font-size:21px}.pm-hero p{margin:0;color:#dce5f2;font-size:10.5px;line-height:1.6}.pm-policy{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.pm-policy div{background:#fff;border:1px solid #e4e9f0;border-radius:11px;padding:11px}.pm-policy b{display:block;color:#132137;font-size:9.5px}.pm-policy small{display:block;color:#7b899c;font-size:8px;margin-top:4px;line-height:1.45}.pm-form{display:grid;grid-template-columns:1fr 1.4fr .8fr 1.4fr auto;gap:9px;align-items:end}.pm-form label{font-size:8.5px;color:#66758a;font-weight:750;text-transform:uppercase;letter-spacing:.04em}.pm-form select,.pm-form input{min-height:38px}.authority{display:inline-flex;padding:4px 7px;border-radius:999px;font-size:8px;font-weight:850}.authority.business{background:#fff0f1;color:#b4233d}.authority.system{background:#eef3fa;color:#1e315b}.effect{display:inline-flex;padding:4px 7px;border-radius:999px;font-size:8px;font-weight:850}.effect.allow{background:#eaf7f0;color:#168453}.effect.deny{background:#fdeeee;color:#b42318}.pm-footnote{margin-top:10px;padding:10px 11px;border-radius:9px;background:#f8fafc;border:1px solid #edf1f5;color:#708096;font-size:8.5px;line-height:1.5}@media(max-width:950px){.pm-form{grid-template-columns:1fr 1fr}.pm-form .btn{grid-column:1/-1}.pm-policy{grid-template-columns:1fr}}@media(max-width:600px){.pm-form{grid-template-columns:1fr}.pm-form .btn{grid-column:auto}.pm-hero{align-items:flex-start;flex-direction:column}}
</style>
<section class="pm-hero"><div><small>Access Control · Effective Authority</small><h1>Roles & Permissions</h1><p>Master Role → Permission → Scope. Explicit Deny always wins, and system authority remains separate from business authority.</p></div><span class="ops-status success">Governed</span></section>
@if(session('status'))<p class="notice">{{ session('status') }}</p>@endif
<div class="pm-policy"><div><b>Role-Based Access</b><small>Actions originate from assigned master roles.</small></div><div><b>Scope-Based Visibility</b><small>Scopes constrain records; they do not create permissions.</small></div><div><b>Separation of Duties</b><small>SYSTEM_ADMIN does not inherit business approvals or execution rights.</small></div></div>
<section class="ops-card"><div class="ops-toolbar"><div><h3>Permission Assignment</h3><small class="muted">Create a tenant override from the master baseline.</small></div><a class="btn secondary" href="{{ route('admin.access-control.index') }}">Access Control</a></div><form class="pm-form" method="POST" action="{{ route('admin.permissions.store') }}" style="margin-top:12px">@csrf <label>Master Role<select name="role_code" required>@foreach($roles as $role)<option value="{{ $role->code }}">{{ $role->code }}{{ $role->is_system_role?' · System':'' }}</option>@endforeach</select></label><label>Permission<select name="permission_code" required>@foreach($permissions as $permission)<option value="{{ $permission->code }}">{{ $permission->code }}{{ $permission->is_business_authority?' · HIGH RISK':'' }}</option>@endforeach</select></label><label>Effect<select name="effect"><option value="ALLOW">Allow</option><option value="DENY">Explicit Deny</option></select></label><label>Reason<input name="reason" required placeholder="Reason for access change"></label><button class="btn">Apply</button></form></section>
<section class="ops-card"><div class="ops-toolbar"><div><h3>Effective Role Matrix</h3><small class="muted">Tenant overrides are clearly separated from immutable master baseline rows.</small></div><span class="ops-status">{{ $rows->count() }} assignments</span></div><table class="ops-table"><thead><tr><th>Role</th><th>Permission</th><th>Effect</th><th>Authority</th><th>Source / Action</th></tr></thead><tbody>@forelse($rows as $row)@php($permission=$permissions->firstWhere('code',$row->permission_code))<tr><td><b>{{ $row->role_code }}</b></td><td>{{ $row->permission_code }}</td><td><span class="effect {{ strtolower($row->effect ?? 'ALLOW') }}">{{ $row->effect ?? 'ALLOW' }}</span></td><td><span class="authority {{ $permission?->is_business_authority?'business':'system' }}">{{ $permission?->is_business_authority?'Business Authority':'System / Standard' }}</span></td><td>@if($row->tenant_id)<form method="POST" action="{{ route('admin.permissions.destroy',$row->id) }}">@csrf @method('DELETE')<button class="btn secondary">Return to Master</button></form>@else<span class="muted">Master baseline</span>@endif</td></tr>@empty<tr><td colspan="5" class="ops-empty">No permission assignments.</td></tr>@endforelse</tbody></table><div class="pm-footnote">Effective access is resolved from all active roles, scopes and user-specific exceptions. Explicit Deny overrides Allow. Hiding UI controls is never treated as authorization; server-side permission checks remain authoritative.</div></section>
@endsection
