@extends('layouts.app')
@section('title','My HR | UNIFCO Platform')
@section('heading','My HR')
@section('content')
<style>
.ess-hero{background:linear-gradient(135deg,#101f38,#1e315b 62%,#29436f);color:#fff;border-radius:18px;padding:23px;display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:13px}.ess-hero small{font-size:8px;letter-spacing:.14em;text-transform:uppercase;color:#aab9cf;font-weight:800}.ess-hero h1{font-size:24px;margin:4px 0}.ess-hero p{margin:0;color:#d5deec;font-size:10px}.ess-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-bottom:13px}.ess-kpi,.ess-card{background:#fff;border:1px solid #e2e8f0;border-radius:13px;padding:14px}.ess-kpi small,.ess-card>small{font-size:8px;color:#7d899b;text-transform:uppercase;font-weight:800}.ess-kpi b{display:block;font-size:19px;margin-top:5px;color:#17243c}.ess-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ess-card h3{font-size:13px;margin:0 0 3px;color:#17243c}.wide{grid-column:1/-1}.quick{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:11px}.quick form{background:#f8fafc;border:1px solid #e8edf3;border-radius:10px;padding:11px}.quick h4{font-size:10px;margin:0 0 8px}.form-row{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.form-row label{font-size:8px;color:#66758b}.form-row .full{grid-column:1/-1}.form-row input,.form-row select,.form-row textarea{width:100%;font-size:9px}.mini{width:100%;display:table;margin-top:10px}.mini th{font-size:8px;text-transform:uppercase;color:#718096;background:#f7f9fc}.mini td{font-size:9px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#e8f6ee;color:#14744a;font-size:8px;font-weight:800}.state.warn{background:#fff3e1;color:#995c00}.state.bad{background:#fbecef;color:#9b263b}.empty{padding:15px;text-align:center;background:#f8fafc;border-radius:8px;color:#8390a2;font-size:9px;margin-top:9px}.balance-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.balance{background:#f8fafc;border-radius:9px;padding:10px}.balance b{display:block;font-size:16px;color:#1e315b}.balance span{font-size:8px;color:#758399}.privacy{padding:9px 11px;background:#edf4ff;border-left:3px solid #315b96;border-radius:8px;font-size:9px;color:#53647d;margin:10px 0}.goalbar{height:6px;border-radius:999px;background:#edf1f6;overflow:hidden;margin-top:5px}.goalbar i{display:block;height:100%;background:#1e315b}.payslip{display:grid;grid-template-columns:110px repeat(4,1fr);gap:7px;align-items:center;padding:9px;background:#f8fafc;border-radius:8px;margin-top:6px;font-size:9px}.payslip strong{font-size:10px}@media(max-width:1000px){.ess-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:780px){.ess-grid,.quick{grid-template-columns:1fr}.wide{grid-column:auto}.ess-hero{display:block}.ess-kpis{grid-template-columns:1fr 1fr}.form-row{grid-template-columns:1fr}.form-row .full{grid-column:auto}.balance-grid{grid-template-columns:1fr 1fr}.payslip{grid-template-columns:1fr 1fr}}@media(max-width:480px){.ess-kpis,.balance-grid{grid-template-columns:1fr}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="ess-hero"><div><small>Employee Self-Service · Private Workspace</small><h1>{{ $employee->name }}</h1><p>{{ $employee->employee_no }} · {{ $employee->position?->title ?? 'No position assigned' }} · {{ $employee->position?->department ?? 'Unassigned department' }}</p></div><div><a class="btn secondary" href="{{ route('hr.performance.employees.show',$employee) }}">My Performance 360</a></div></section>
<div class="ess-kpis"><div class="ess-kpi"><small>Status</small><b>{{ $employee->status }}</b></div><div class="ess-kpi"><small>Today</small><b>{{ $todayAttendance?->status ?? 'NO RECORD' }}</b></div><div class="ess-kpi"><small>Pending Leave</small><b>{{ $leaves->where('status','PENDING')->count() }}</b></div><div class="ess-kpi"><small>Active Goals</small><b>{{ $goals->whereIn('status',['OPEN','IN_PROGRESS'])->count() }}</b></div><div class="ess-kpi"><small>Latest Net Pay</small><b>{{ $payroll->first()?number_format((float)$payroll->first()->net_pay,0).' SAR':'—' }}</b></div></div>
<div class="privacy">This portal is scoped to your linked employee record. Manager and HR workspaces remain separate; employer-side payroll costs and other employees' compensation are not exposed here.</div>
<div class="ess-grid">
<section class="ess-card wide"><h3>Quick Requests</h3><small>Submit personal HR requests without HR master-data privileges.</small><div class="quick"><form method="POST" action="{{ route('hr.self-service.leave.store') }}">@csrf<h4>Request Leave</h4><div class="form-row"><label>Leave Type<select name="leave_policy_id" required><option value="">Select</option>@foreach($policies as $p)<option value="{{ $p->id }}">{{ $p->name }} · {{ $p->paid?'Paid':'Unpaid' }}</option>@endforeach</select></label><label>Portion<select name="day_portion"><option value="FULL_DAY">Full Day</option><option value="HALF_DAY_AM">Half Day AM</option><option value="HALF_DAY_PM">Half Day PM</option></select></label><label>From<input type="date" name="starts_on" required></label><label>To<input type="date" name="ends_on" required></label><label class="full">Reason<textarea name="reason" rows="2"></textarea></label><div><button class="btn">Submit Leave</button></div></div></form><form method="POST" action="{{ route('hr.self-service.missions.store') }}">@csrf<h4>Request Business Mission</h4><div class="form-row"><label>Type<select name="trip_type"><option>LOCAL</option><option>INTERNATIONAL</option><option>FIELD_MISSION</option></select></label><label>Destination City<input name="destination_city" required></label><label>Country<input name="destination_country" value="Saudi Arabia" required></label><label>Travel Method<input name="travel_method" placeholder="Car / Flight"></label><label>From<input type="date" name="starts_on" required></label><label>To<input type="date" name="ends_on" required></label><label>Requested Advance<input type="number" step="0.01" min="0" name="requested_advance" value="0"></label><label><span>Requirements</span><span style="display:flex;gap:10px"><span><input type="checkbox" name="hotel_required" value="1"> Hotel</span><span><input type="checkbox" name="transport_required" value="1"> Transport</span></span></label><label class="full">Purpose<textarea name="purpose" rows="2" required></textarea></label><div><button class="btn">Submit Mission</button></div></div></form></div></section>
<section class="ess-card"><h3>Leave Balances · {{ $year }}</h3><small>Authoritative balance ledger from HR Leave Management.</small><div class="balance-grid">@forelse($balances as $b)<div class="balance"><b>{{ number_format($b->availableDays(),1) }}</b><span>{{ $policies->firstWhere('id',$b->leave_policy_id)?->name ?? 'Leave' }} available days</span></div>@empty<div class="empty">No leave balance initialized for this year.</div>@endforelse</div></section>
<section class="ess-card"><h3>My Leave Requests</h3><small>Latest submitted requests and decisions.</small>@if($leaves->isNotEmpty())<table class="mini"><thead><tr><th>Type</th><th>Dates</th><th>Days</th><th>Status</th></tr></thead><tbody>@foreach($leaves as $l)<tr><td>{{ $l->leave_type }}</td><td>{{ $l->starts_on?->format('d M') }} → {{ $l->ends_on?->format('d M Y') }}</td><td>{{ $l->days }}</td><td><span class="state {{ $l->status==='PENDING'?'warn':($l->status==='REJECTED'?'bad':'') }}">{{ $l->status }}</span></td></tr>@endforeach</tbody></table>@else<div class="empty">No leave requests yet.</div>@endif</section>
<section class="ess-card"><h3>My Goals</h3><small>Update actual achievement and progress only. Scores remain manager/HR controlled.</small>@forelse($goals as $g)<div style="padding:9px 0;border-bottom:1px solid #edf0f4"><div style="display:flex;justify-content:space-between;gap:8px"><b style="font-size:10px">{{ $g->title }}</b><span class="state">{{ $g->status }}</span></div><small style="font-size:8px;color:#7c899a">Target {{ $g->target_value ?? '—' }} {{ $g->unit }} · Actual {{ $g->actual_value ?? '—' }} · Score {{ $g->score ?? '—' }}</small><div class="goalbar"><i style="width:{{ min(100,max(0,(float)($g->score??0))) }}%"></i></div><form method="POST" action="{{ route('hr.self-service.goals.update',$g) }}" style="display:flex;gap:6px;margin-top:7px;align-items:end">@csrf<label style="font-size:8px">Actual<input type="number" step="0.01" name="actual_value" value="{{ $g->actual_value }}"></label><label style="font-size:8px">Status<select name="status"><option @selected($g->status==='OPEN')>OPEN</option><option @selected($g->status==='IN_PROGRESS')>IN_PROGRESS</option><option @selected($g->status==='COMPLETED')>COMPLETED</option></select></label><button class="btn secondary">Update</button></form></div>@empty<div class="empty">No goals assigned.</div>@endforelse</section>
<section class="ess-card"><h3>Approved Performance Reviews</h3><small>Only approved reviews are visible in employee self-service.</small>@if($reviews->isNotEmpty())<table class="mini"><thead><tr><th>Date</th><th>Type</th><th>Score</th><th>Rating</th></tr></thead><tbody>@foreach($reviews as $r)<tr><td>{{ $r->review_date?->format('d M Y') }}</td><td>{{ $r->review_type }}</td><td>{{ $r->overall_score }}</td><td>{{ str_replace('_',' ',$r->rating) }}</td></tr>@endforeach</tbody></table>@else<div class="empty">No approved performance review available.</div>@endif</section>
<section class="ess-card wide"><h3>My Payslips</h3><small>Employee-side payroll results only.</small>@forelse($payroll as $line)@php($run=$runs->get($line->payroll_run_id))<div class="payslip"><strong>{{ $run?->payroll_no ?? 'Payroll' }}</strong><span>{{ $run?->period_start?->format('M Y') ?? '—' }}</span><span>Gross {{ number_format((float)$line->basic_pay+(float)$line->allowances+(float)$line->overtime_pay,2) }}</span><span>Deductions {{ number_format((float)$line->deductions,2) }}</span><span><b>Net {{ number_format((float)$line->net_pay,2) }} SAR</b></span></div>@empty<div class="empty">No payroll lines available.</div>@endforelse</section>
<section class="ess-card wide"><h3>My Missions</h3><small>Requests, approvals and settlement status.</small>@if($missions->isNotEmpty())<table class="mini"><thead><tr><th>No</th><th>Destination</th><th>Dates</th><th>Advance</th><th>Status</th></tr></thead><tbody>@foreach($missions as $m)<tr><td>{{ $m->trip_no }}</td><td>{{ $m->destination_city }}, {{ $m->destination_country }}</td><td>{{ $m->starts_on?->format('d M') }} → {{ $m->ends_on?->format('d M Y') }}</td><td>{{ number_format((float)$m->requested_advance,2) }}</td><td><span class="state {{ $m->status==='PENDING'?'warn':'' }}">{{ $m->status }}</span></td></tr>@endforeach</tbody></table>@else<div class="empty">No mission requests yet.</div>@endif</section>
</div>
@endsection
