@extends('layouts.app')
@section('title','Manager Self-Service | UNIFCO Platform')
@section('heading','Manager Self-Service')
@section('content')
<style>
.mss-hero{background:linear-gradient(135deg,#102038,#1e315b 62%,#29436f);color:#fff;border-radius:18px;padding:22px;display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:13px}.mss-hero small{font-size:8px;letter-spacing:.14em;text-transform:uppercase;color:#aab8cd;font-weight:800}.mss-hero h1{font-size:23px;margin:4px 0}.mss-hero p{margin:0;color:#d7e0ec;font-size:10px}.mss-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:13px}.mss-kpi,.mss-card{background:#fff;border:1px solid #e2e8ef;border-radius:13px;padding:14px}.mss-kpi small,.mss-card>small{font-size:8px;color:#7d899c;text-transform:uppercase;font-weight:800}.mss-kpi b{display:block;font-size:20px;color:#17243c;margin-top:5px}.mss-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wide{grid-column:1/-1}.mss-card h3{font-size:13px;margin:0 0 3px;color:#17243c}.mini{width:100%;display:table;margin-top:10px}.mini th{font-size:8px;text-transform:uppercase;color:#718096;background:#f7f9fc}.mini td{font-size:9px}.state{display:inline-flex;padding:4px 7px;border-radius:999px;background:#e8f6ee;color:#14734a;font-size:8px;font-weight:800}.state.warn{background:#fff3e1;color:#975b00}.decision{display:flex;gap:5px;align-items:center;flex-wrap:wrap}.decision textarea{font-size:8px;min-width:120px;min-height:36px}.decision button{padding:6px 8px;font-size:8px}.danger{background:#a52a40!important}.team-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.person{background:#f8fafc;border:1px solid #edf0f4;border-radius:10px;padding:10px}.person b{display:block;font-size:10px}.person small{font-size:8px;color:#7c899b}.privacy{padding:9px 11px;background:#edf4ff;border-left:3px solid #315b96;border-radius:8px;font-size:9px;color:#53647d;margin-bottom:12px}.empty{padding:15px;text-align:center;background:#f8fafc;border-radius:8px;color:#8390a2;font-size:9px;margin-top:9px}@media(max-width:900px){.mss-kpis{grid-template-columns:1fr 1fr}.mss-grid{grid-template-columns:1fr}.wide{grid-column:auto}.team-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.mss-kpis,.team-grid{grid-template-columns:1fr}.mss-hero{display:block}}
</style>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<section class="mss-hero"><div><small>Manager Self-Service · Direct Reports Only</small><h1>{{ $manager->name }}'s Team</h1><p>Team approvals, goals and performance visibility without company-wide HR administration privileges.</p></div><a class="btn secondary" href="{{ route('hr.self-service.index') }}">My HR</a></section>
<div class="mss-kpis"><div class="mss-kpi"><small>Direct Reports</small><b>{{ $team->count() }}</b></div><div class="mss-kpi"><small>Pending Leave</small><b>{{ $pendingLeaves->count() }}</b></div><div class="mss-kpi"><small>Pending Missions</small><b>{{ $pendingMissions->count() }}</b></div><div class="mss-kpi"><small>Open Goals</small><b>{{ $goals->count() }}</b></div></div>
<div class="privacy">Manager Self-Service is explicitly scoped by <b>manager_employee_id</b>. It does not expose employee bank details, payroll amounts, final settlements or HR records outside your direct-report scope.</div>
<div class="mss-grid">
<section class="mss-card wide"><h3>My Team</h3><small>Direct reporting line from Employee Master.</small><div class="team-grid">@forelse($team as $e)<div class="person"><b>{{ $e->name }}</b><small>{{ $e->employee_no }} · {{ $e->position?->title ?? 'No position' }}</small><div style="margin-top:7px"><a class="btn secondary" href="{{ route('hr.performance.employees.show',$e) }}">Performance</a></div></div>@empty<div class="empty">No direct reports assigned.</div>@endforelse</div></section>
<section class="mss-card"><h3>Leave Approval Queue</h3><small>Only leave requests belonging to direct reports.</small>@if($pendingLeaves->isNotEmpty())<table class="mini"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Decision</th></tr></thead><tbody>@foreach($pendingLeaves as $l)<tr><td>{{ $team->firstWhere('id',$l->employee_id)?->name ?? 'Employee' }}</td><td>{{ $l->leave_type }}<br><small>{{ $l->days }} days</small></td><td>{{ $l->starts_on?->format('d M') }} → {{ $l->ends_on?->format('d M Y') }}</td><td><form class="decision" method="POST" action="{{ route('hr.manager-self-service.leave.decide',$l) }}">@csrf<textarea name="decision_notes" placeholder="Decision note"></textarea><button class="btn" name="decision" value="APPROVED">Approve</button><button class="btn danger" name="decision" value="REJECTED">Reject</button></form></td></tr>@endforeach</tbody></table>@else<div class="empty">No pending team leave requests.</div>@endif</section>
<section class="mss-card"><h3>Mission Approval Queue</h3><small>Direct-report business trips and field missions.</small>@if($pendingMissions->isNotEmpty())<table class="mini"><thead><tr><th>Employee</th><th>Destination</th><th>Dates</th><th>Decision</th></tr></thead><tbody>@foreach($pendingMissions as $m)<tr><td>{{ $m->employee?->name }}</td><td>{{ $m->destination_city }}<br><small>{{ $m->purpose }}</small></td><td>{{ $m->starts_on?->format('d M') }} → {{ $m->ends_on?->format('d M Y') }}</td><td><form class="decision" method="POST" action="{{ route('hr.manager-self-service.missions.decide',$m) }}">@csrf<button class="btn" name="decision" value="APPROVED">Approve</button><button class="btn danger" name="decision" value="REJECTED">Reject</button></form></td></tr>@endforeach</tbody></table>@else<div class="empty">No pending team missions.</div>@endif</section>
<section class="mss-card"><h3>Team Goals</h3><small>Open and in-progress goals for direct reports.</small>@if($goals->isNotEmpty())<table class="mini"><thead><tr><th>Employee</th><th>Goal</th><th>Target</th><th>Actual</th><th>Status</th></tr></thead><tbody>@foreach($goals as $g)<tr><td>{{ $g->employee?->name }}</td><td>{{ $g->title }}</td><td>{{ $g->target_value ?? '—' }} {{ $g->unit }}</td><td>{{ $g->actual_value ?? '—' }}</td><td><span class="state">{{ $g->status }}</span></td></tr>@endforeach</tbody></table>@else<div class="empty">No open goals for the team.</div>@endif</section>
<section class="mss-card"><h3>Performance Review Visibility</h3><small>Review lifecycle for direct reports; no company-wide review access.</small>@if($reviews->isNotEmpty())<table class="mini"><thead><tr><th>Employee</th><th>Date</th><th>Type</th><th>Score</th><th>Status</th></tr></thead><tbody>@foreach($reviews as $r)<tr><td>{{ $r->employee?->name }}</td><td>{{ $r->review_date?->format('d M Y') }}</td><td>{{ $r->review_type }}</td><td>{{ $r->overall_score }}</td><td><span class="state {{ $r->status==='PENDING_APPROVAL'?'warn':'' }}">{{ $r->status }}</span></td></tr>@endforeach</tbody></table>@else<div class="empty">No team performance reviews yet.</div>@endif</section>
</div>
@endsection
